"""The parameter layout table is consistent, without TouchDesigner.

`tools/td_add_pages.py` moves controls onto the pages `appletd/td_pages.py` names.
Every mistake possible in that table is a typo that would only show up as a parameter
in the wrong place, or missing, on a rebuilt component - so it is checked here where a
failure costs a second rather than a build.
"""

from __future__ import annotations

from appletd import td_pages


def test_no_parameter_is_listed_on_two_pages() -> None:
    """A name in two sections silently wins wherever the later move puts it."""
    assert td_pages.duplicates() == []


def test_every_page_in_the_order_has_a_layout() -> None:
    assert set(td_pages.PAGE_ORDER) == set(td_pages.LAYOUT)


def test_section_headers_are_unique_and_valid_parameter_names() -> None:
    """A custom parameter name is unique across the whole COMP, not per page - which
    is why `header_name` mixes the page in. "Output" is a section on four pages."""
    names = [name for _page, name, _label, _above in td_pages.sections()]
    assert len(names) == len(set(names)), "two sections want the same parameter name"
    for name in names:
        assert name[0].isupper() and name[1:].islower(), name
        assert name.isalnum(), name


def test_a_header_never_collides_with_a_real_parameter() -> None:
    assert not set(n for _p, n, _l, _a in td_pages.sections()) & set(
        td_pages.placement())


def test_placement_indexes_are_a_total_order_within_each_page() -> None:
    for page in td_pages.PAGE_ORDER:
        indexes = sorted(index for name, (owner, index)
                         in td_pages.placement().items() if owner == page)
        assert indexes == list(range(len(indexes))), page


def test_unplaced_reports_what_the_table_forgot() -> None:
    """The check that stops the build. It must not be fooled by the dividers it adds
    itself, nor by a parameter on its way out."""
    header = td_pages.sections()[0][1]
    assert td_pages.unplaced(["Active", header, td_pages.RETIRED[0]]) == []
    assert td_pages.unplaced(["Active", "Somethingnew"]) == ["Somethingnew"]


def test_the_depth_pins_are_all_there() -> None:
    """24 pin parameters generated by a comprehension in the table - the one place a
    slip would remove controls rather than move them."""
    depth = dict(td_pages.LAYOUT["Depth"])["Pins"]
    for row in range(1, 9):
        for axis in ("x", "y", "m"):
            assert "Depthpin%d%s" % (row, axis) in depth


def test_every_generated_header_carries_the_prefix_the_cleanup_keys_on() -> None:
    """`tools/td_add_pages.py` destroys orphaned dividers by the `Hdr` prefix, which
    is how a section that MOVES pages does not leave a parameter the table has never
    heard of. If `header_name` ever stopped producing that prefix, the cleanup would
    silently match nothing and the build would fail on the next section move."""
    for _page, name, _label, _above in td_pages.sections():
        assert name.startswith("Hdr"), name


def test_a_moved_section_leaves_no_name_the_table_still_claims() -> None:
    """The specific failure: Output moved General -> Advanced, and the old
    `Hdrgeneraloutput` was left behind as an unknown parameter."""
    assert td_pages.header_name("General", "Output") != td_pages.header_name(
        "Advanced", "Output")
