"""The Install button, its status field, and the module that does the work.

    RUN IT
        run("<repo>/tools/td_add_install.py")

    or through the chain: tools/td_rebuild.py, layer "install". AFTER "embed" -
    the button writes out what that put in.

WHAT IT BUILDS
    Vision page      `Install`      a pulse, greyed out once the probe passes
                     `Installstate` read-only, the one line somebody reads
    Advanced page    `Forceinstall` a pulse that always runs, whatever the probe says
    install_control  a Text DAT module: probe, write, launch, poll
    install_callbacks a Parameter Execute for the two pulses
    install_start    an Execute DAT that probes when the project opens

WHY THE PANEL READS `install` OUT OF THE .toe. It has to probe and render a script
BEFORE any install exists, so it cannot import `appletd.install` from disk - there is
nothing there. `mod()` reads it straight out of the embedded DAT instead, which works
because that module is standard-library only, and there is a test asserting it stays
that way.

WHY THE WORK IS ONE SUBPROCESS. Everything that touches the network is in a generated
shell script (`appletd.install.render_script`), launched with Popen and POLLED from the
main thread with `run(..., delayFrames=n)`. Nothing may touch a TouchDesigner object
from any thread but the main one, so there is no callback thread here at all - the same
shape as the sidecar pid watch.

The 19 modules are written out INLINE, before the subprocess starts. 402 KB of local
writes is a few milliseconds, and it keeps the only step that needs the DATs in the
process that has them.

Ref: docs/BUILD_PLAN.md step 21, appletd/install.py.
"""

import os
import sys

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MASTER_PATH = "/project1/appletd"
CONTROL = "install_control"
CALLBACKS = "install_callbacks"
ON_START = "install_start"
LOG_PATH = "/tmp/appletd_install.log"

# The states, in the order they are reached, with the colour a panel should show.
# Kept here as documentation rather than as code: `Installstate` is a string field, and
# the colour swatch was tried on `Capturestate` in August and removed - real colour,
# and a meaningless label next to a word that already said it.
#
#   Not installed - press Install      nothing has ever been installed
#   Install needed - <what is missing> a stamp, but something is absent
#   Update needed - press Install      complete, and the .toe wants another version
#   Installing - <step>                a subprocess is running; the last STEP line
#   Install failed - <why>             the script said FAIL, or exited non-zero
#   Installed - <interpreter>          everything is there and verified
#
# `Install failed` NAMES THE STEP. "Install failed" on its own is the message that
# makes somebody file an issue instead of fixing their proxy.

CONTROL_SOURCE = '''# Generated by tools/td_add_install.py
"""Install: probe what is on disk, write the package out, run the installer.

THE PANEL'S COPY OF `appletd.install` COMES OUT OF THE .toe, not off disk. It has to
work before an install exists, and before one does there is no `appletd` package to
import. `mod()` on the embedded Text DAT is the whole mechanism, and it works because
that module imports nothing but the standard library.

NOTHING HERE TOUCHES A TOUCHDESIGNER OBJECT FROM ANOTHER THREAD. The installer is a
subprocess; it is polled by `run(..., delayFrames=n)` on the main thread. That rule is
not a preference - a `store()` from a worker thread put up a THREAD CONFLICT dialog
once and TouchDesigner said it may terminate (DESIGN.md 2.8).
"""

import os
import subprocess

COMP_PATH = %(comp)r
SRC_PATH = COMP_PATH + "/src"
LOG_PATH = %(log)r
POLL_FRAMES = 30

# The running installer, and the step it last reported. MODULE globals, not operator
# storage: TouchDesigner PICKLES operator storage into the .toe, and a Popen handle is
# not something to write into a project file.
_process = None
_step = ""


def _install_module():
    """`appletd.install`, read out of the embedded DAT."""
    dat = op(SRC_PATH + "/install")
    if dat is None:
        raise RuntimeError(
            "no %%s/install DAT - run tools/td_embed_package.py. The panel reads "
            "its "
            "own logic out of the .toe, so without that DAT there is nothing to read."
            %% SRC_PATH)
    return mod(dat)


def _comp():
    return op(COMP_PATH)


def _migrate_root(comp):
    """Blank an `Installroot` that belongs to somebody ELSE'S home. Returns it, or None.

    A .tox built before 2026-08-24 carries the BUILDER'S expanded path -
    `/Users/<whoever>/Library/Application Support/appletd` - because the parameter's
    default was `os.path.expanduser(...)` evaluated on the machine that ran the
    builder. On anybody else's Mac that points at a directory they do not have, and
    Install fails on it. Found on a second machine, which is the only place it can be
    found.

    Newly built files ship this BLANK and the install code already reads blank as
    "work it out" - `Installroot.eval() or DEFAULT_INSTALL_ROOT`, expanded here rather
    than at build. This is the same fix for a file that is already out there: it runs
    when the project opens, so the component heals itself rather than needing a
    download.

    CONSERVATIVE ON PURPOSE. Only a path under `/Users/` that is not under THIS home
    is touched - so a deliberate `/Volumes/Work/appletd` or a shared location is left
    exactly as it is, and so is a correct path on the machine that made it.
    """
    par = getattr(comp.par, "Installroot", None)
    if par is None:
        return None
    root = str(par.eval())
    home = os.path.expanduser("~")
    if not root or not root.startswith("/Users/"):
        return None
    if root == home or root.startswith(home + os.sep):
        return None
    par.val = ""
    return root


def state(comp=None):
    """Look at the disk and write `Installstate`. Returns the string it wrote.

    Cheap: stats a few files and reads one small JSON. Called when the project opens
    and after every install, NOT on a timer.
    """
    comp = comp or _comp()
    if comp is None:
        return "no COMP"
    if _process is not None:
        text = "Installing - %%s" %% (_step or "starting")
        comp.par.Installstate = text
        return text

    install = _install_module()
    # BEFORE the path is read, because the whole point is that the stored one may
    # belong to another machine.
    stale = _migrate_root(comp)
    root = str(comp.par.Installroot.eval() or install.DEFAULT_INSTALL_ROOT)
    if stale:
        print("[appletd] Install Folder was %%r, which is not under this home "
              "directory - cleared, so it resolves to %%r" %% (stale, root))
    wanted = str(comp.par.Sourceversion.eval())
    found = install.probe(root, wanted_version=wanted)

    if found.state == "missing":
        text = "Not installed - press Install"
    elif found.state == "incomplete":
        missing = []
        if found.modules_present < found.modules_wanted:
            missing.append("%%d of %%d modules"
                           %% (found.modules_wanted - found.modules_present,
                              found.modules_wanted))
        if not found.packages:
            missing.append("Python packages")
        text = "Install needed - missing %%s" %% ", ".join(missing)
    elif found.state == "stale":
        text = ("Update needed - installed %%s, this file wants %%s"
                %% (found.stamp_version, found.wanted_version))
    else:
        # Only here does it cost a subprocess, and only because "the files are there"
        # is not the same claim as "the interpreter can import them" - which is the
        # distinction the whole install design turns on (BUILD_PLAN 21.1).
        checked = install.find_interpreter(
            root, override=str(comp.par.Sidecarpython.eval()) or None)
        if checked is None:
            text = "Install needed - nothing here can import pyobjc"
        else:
            text = "Installed - %%s" %% os.path.basename(os.path.dirname(
                os.path.dirname(checked.path)))
    comp.par.Installstate = text
    # The button is greyed out when there is nothing to do. `Forceinstall` on Advanced
    # is always live, for the case where somebody knows better than the probe.
    comp.par.Install.enable = not text.startswith("Installed")
    return text


def write_package(root):
    """Write every embedded module to `<root>/appletd/`. Returns how many.

    INLINE rather than in the subprocess, because this is the one step that needs the
    DATs and the subprocess cannot read them. 402 KB of local writes.
    """
    install = _install_module()
    src = op(SRC_PATH)
    if src is None:
        raise RuntimeError("no %%s - run tools/td_embed_package.py" %% SRC_PATH)
    target = os.path.join(root, "appletd")
    os.makedirs(target, exist_ok=True)
    written = 0
    for name in install.EMBEDDED_MODULES:
        dat = src.op(name)
        if dat is None:
            raise RuntimeError(
                "%%s is embedded in EMBEDDED_MODULES but has no DAT. Re-run "
                "tools/td_embed_package.py." %% name)
        with open(os.path.join(target, name + ".py"), "w", encoding="utf-8") as handle:
            handle.write(dat.text)
        written += 1
    return written


def install(force=False):
    """Write the package out and start the installer. Returns a message.

    `force` skips the "already installed" shortcut. It does NOT skip the interpreter
    probe: forcing a reinstall is not a reason to download 26 MB somebody already has.
    """
    global _process, _step
    comp = _comp()
    if comp is None:
        return "no COMP"
    if _process is not None:
        return "an install is already running"

    module = _install_module()
    try:
        module.require_arm64()
    except RuntimeError as refused:
        comp.par.Installstate = "Install failed - %%s" %% refused
        return str(refused)

    root = str(comp.par.Installroot.eval() or module.DEFAULT_INSTALL_ROOT)
    version = str(comp.par.Sourceversion.eval())
    if not force and module.probe(root, wanted_version=version).state == "installed":
        return state(comp)

    # Reuse an interpreter that works before downloading one. `Sidecarpython` first,
    # then the install's own, then the machine's.
    override = str(comp.par.Sidecarpython.eval()) or None
    checked = module.find_interpreter(root, override=override)
    python = checked.path if checked is not None else ""

    _step = "writing %%d modules" %% len(module.EMBEDDED_MODULES)
    comp.par.Installstate = "Installing - " + _step
    written = write_package(root)

    # The requirements travel in the script: an install has no repository behind it.
    # Read from the embedded module's own pins, so the button and the terminal path
    # install the same versions.
    script = module.render_script(
        root=root, version=version,
        requirements=module.REQUIREMENTS,
        python=python,
        want_model=bool(comp.par.Streamdepth.eval()))
    script_path = os.path.join(root, "install.sh")
    with open(script_path, "w", encoding="utf-8") as handle:
        handle.write(script)

    _step = "starting"
    log = open(LOG_PATH, "w", encoding="utf-8")
    _process = subprocess.Popen(["/bin/sh", script_path], stdout=log,
                                stderr=subprocess.STDOUT, cwd=root)
    print("[appletd] install started, pid %%d, %%d modules written, log %%s"
          %% (_process.pid, written, LOG_PATH), flush=True)
    if python:
        print("[appletd]   using %%s - nothing will be downloaded" %% python,
              flush=True)
    else:
        print("[appletd]   no working interpreter found; one will be downloaded",
              flush=True)
    run("op(%%r).module.poll()" %% (COMP_PATH + "/" + %(control)r),
        delayFrames=POLL_FRAMES)
    return "installing"


def poll():
    """Called by a scheduled `run` while the installer is going. Reschedules itself."""
    global _process, _step
    comp = _comp()
    if _process is None or comp is None:
        return
    _step = _last_step()
    code = _process.poll()
    if code is None:
        comp.par.Installstate = "Installing - %%s" %% (_step or "starting")
        run("op(%%r).module.poll()" %% (COMP_PATH + "/" + %(control)r),
            delayFrames=POLL_FRAMES)
        return

    _process = None
    if code == 0:
        print("[appletd] install finished", flush=True)
        state(comp)
    else:
        # The script's own FAIL line if it produced one, because it names WHICH step -
        # "install failed" on its own is what makes somebody file an issue instead of
        # fixing their proxy.
        why = _last_step(prefix="FAIL") or "exit %%d, see %%s" %% (code, LOG_PATH)
        comp.par.Installstate = "Install failed - %%s" %% why
        print("[appletd] install FAILED: %%s" %% why, flush=True)


def _last_step(prefix="STEP"):
    """The last line of the log with `prefix`, or "". Never raises."""
    try:
        with open(LOG_PATH, encoding="utf-8", errors="replace") as handle:
            lines = [l.strip() for l in handle if l.startswith(prefix + " ")]
    except OSError:
        return ""
    return lines[-1][len(prefix) + 1:] if lines else ""
'''

CALLBACK_SOURCE = '''# Generated by tools/td_add_install.py
#
# `Install` and `Forceinstall` are pulses, so this is `onPulse` - `onValueChange`
# never fires for a pulse, which cost an afternoon in August on a different button.


def onPulse(par):
    control = par.owner.op(%(control)r)
    if control is None:
        print("[appletd] no %(control)s DAT - run tools/td_add_install.py")
        return
    control.module.install(force=par.name == "Forceinstall")
'''

START_SOURCE = '''# Generated by tools/td_add_install.py
#
# Probes when the project opens, so somebody who has never installed sees "Not
# installed - press Install" rather than a component that quietly does nothing.
#
# `onStart` and not `onProjectPreSave`: this has to run when the file is OPENED.


def onStart():
    control = op(%(control_path)r)
    if control is not None:
        control.module.state()
'''


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.td_layout import master_xy, placement

    comp = op(MASTER_PATH)
    if comp is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("install: the button, the status and the module that does the work")
    print("=" * 70)

    keep = bool(comp.par.Keeplayout.eval())
    existing = {par.name: par for par in comp.customPars}

    vision = advanced = None
    for page in comp.customPages:
        if page.name == "Vision":
            vision = page
        elif page.name == "Advanced":
            advanced = page
    if vision is None or advanced is None:
        print("FAIL no Vision/Advanced page - run tools/td_build_vision.py first")
        return

    # Append only what is absent. `appendPulse` on an existing parameter resets it,
    # and a reset fires a deferred callback that outlives a restore - which is how
    # `Verbosity` ended up on "Minimal" with every derive group off (DESIGN.md 2.11).
    if "Install" not in existing:
        vision.appendPulse("Install", label="Install")
    if "Installstate" not in existing:
        par = vision.appendStr("Installstate", label="Install Status")[0]
        par.readOnly = True
    else:
        existing["Installstate"].readOnly = True
    if "Forceinstall" not in existing:
        advanced.appendPulse(
            "Forceinstall", label="Force Install  (ignores the probe)")
    print("1. Install and Installstate on Vision, Forceinstall on Advanced")

    # The Vision page order: the install comes FIRST, because nothing else on the page
    # can work until it is done.
    order = ["Install", "Installstate"] + [
        p.name for p in vision.pars if p.name not in ("Install", "Installstate")]
    vision.sort(*order)

    for name, source, subs in (
            (CONTROL, CONTROL_SOURCE, {"comp": MASTER_PATH, "log": LOG_PATH,
                                       "control": CONTROL}),
            (CALLBACKS, CALLBACK_SOURCE, {"control": CONTROL}),
            (ON_START, START_SOURCE,
             {"control_path": MASTER_PATH + "/" + CONTROL})):
        dat = comp.op(name)
        existed = dat is not None
        if dat is None:
            kind = (td.parameterexecuteDAT if name == CALLBACKS
                    else td.executeDAT if name == ON_START else td.textDAT)
            dat = comp.create(kind, name)
        dat.text = source % subs
        where = placement(master_xy(name), keep, existed)
        if where is not None:
            dat.nodeX, dat.nodeY = where
        if name == CALLBACKS:
            dat.par.ops = comp.path
            dat.par.pars = "Install Forceinstall"
            dat.par.custom = True
            dat.par.builtin = False
            dat.par.onpulse = True
            dat.par.valuechange = False
            dat.par.active = True
        elif name == ON_START:
            dat.par.active = True
            dat.par.start = True
        print("   %-18s %s" % (name, "reused" if existed else "created"))

    # -- verification ------------------------------------------------------
    failures = []
    if comp.op("src") is None:
        failures.append("no `src` container - run tools/td_embed_package.py, or the "
                        "panel has nothing to read its own logic out of")
    elif comp.op("src/install") is None:
        failures.append("`src` has no `install` DAT - re-run "
                        "tools/td_embed_package.py")
    for name in ("Install", "Installstate", "Forceinstall", "Installroot",
                 "Sidecarpython", "Sourceversion"):
        if not hasattr(comp.par, name):
            failures.append("parameter %s is missing" % name)

    control = comp.op(CONTROL)
    reported = None
    if control is not None and not failures:
        try:
            reported = control.module.state()
        except Exception as problem:            # noqa: BLE001 - reported, not hidden
            failures.append("state() raised: %r" % problem)

    print()
    if failures:
        print("FAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print("   verified. Installstate reads: %s" % reported)
        print("   Install is %s"
              % ("greyed out - nothing to do"
                 if not comp.par.Install.enable else "live"))
    print()


main()
