#!/usr/bin/env python
"""Add the Attributes page - the group toggles - to the visionhands COMP.

    Paste into a Text DAT, Run Script. Idempotent.

WHAT THE TOGGLES ACTUALLY DO, because it is less than docs/ATTRIBUTES.md's step 3
describes and the difference is deliberate.

**They gate the compute that costs something.** `visionhands/derive.py` takes the
set of enabled groups and computes only those, and `tools/td_add_derive.py`'s
`_groups()` reader has always read these parameters - it just fell back to "all
enabled" because they did not exist. So turning Descriptor off stops 84 channels
being computed in Python, and Contacts off stops 28, inside the one operator in
the whole COMP where per-channel cost is real: main-thread Python measured at
0.210 ms for 171 channels (DESIGN.md 2.7).

**They do NOT yet gate the native groups, and that is a judgement rather than an
omission.** docs/ATTRIBUTES.md specifies `allowCooking` off on a group COMP. That
mechanism works - MEASURED below - but wrapping the latch bank, the temporal
group and the filter in base COMPs is a restructure of about 150 operators, and
what it would save is negligible: those are tiny native CHOPs on 1-sample inputs,
against a Python cook that the toggles above already gate. The compute worth
saving is already saved.

**A disabled DERIVE group's channels genuinely disappear** from the COMP's output,
because `derive()` simply does not emit them - measured, Verbosity = Minimal takes
`derive_chop` from 171 channels to 0 and the COMP output from 561 to 393. Nothing
is left stale there.

**A disabled NATIVE group's channels do NOT disappear**, because nothing gates
them: the latch, trigger and motion channels keep their last value. That is the one
real gap, and closing it needs an exact channel-to-group map - see the note at the
end of this file for why wildcard patterns cannot provide one.

MEASURED, the `allowCooking` question step 3 could not proceed without: a Feedback
counter and a Cook Type = Always Null inside a base COMP, with `allowCooking` set
to False. The counter FROZE at 275 and its cook count stopped, and on re-enabling
it resumed at 276 rather than jumping. So:

  * disabling a group really does stop all of its cost, including its clock;
  * a group with memory PAUSES rather than resetting, so re-enabling one resumes
    with a `prev` from whenever it was switched off. For the latches that means the
    state is stale for one frame - self-correcting, because the recurrence is
    level-driven - and one edge pulse across the gap may be wrong. Bounded and
    acceptable, but it is why the clock must sit OUTSIDE any gated group if the
    native groups are ever wrapped.

Ref: docs/ATTRIBUTES.md (the group table and the budget), docs/BUILD_PLAN.md step
3, DESIGN.md 2.10 (why memory needs a clock).
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
COMP_PATH = "/project1/visionhands"

# The groups, their defaults, and whether this page can actually gate their cost.
#
# `derive` means the group is computed by visionhands/derive.py, so the toggle
# reaches it through the existing `_groups()` reader and genuinely saves work.
# `native` means the group is built from CHOPs, where the toggle is currently
# advisory - it records intent and drives nothing. Said plainly in the label, so
# nobody switches one off expecting a saving that is not there.
GROUPS = (
    # name          default  gated
    ("Landmarks",   True,  "native"),
    ("Coordstx",    True,  "native"),
    ("Coordspx",    False, "native"),
    ("Core",        True,  "derive"),
    ("Presence",    True,  "derive"),
    ("Contacts",    True,  "derive"),
    ("Triggers",    True,  "native"),
    ("Pose",        True,  "derive"),
    ("Motion",      True,  "native"),
    ("Twohands",    True,  "derive"),
    ("Gestures",    True,  "derive"),
    ("Events",      True,  "native"),
    ("Descriptor",  False, "derive"),
)

# The presets from docs/ATTRIBUTES.md. Verbosity sets the toggles in one click; it
# is not a fourth state, and moving a toggle afterwards does not fight it.
PRESETS = {
    "Minimal": ("Landmarks", "Coordstx"),
    "Interaction": tuple(n for n, _d, _g in GROUPS
                         if n not in ("Coordspx", "Descriptor")),
    "Everything": tuple(n for n, _d, _g in GROUPS),
}

CALLBACK_SOURCE = '''# Generated by tools/td_add_groups.py
#
# Verbosity is a preset button, not a fourth state: it writes the toggles once and
# then leaves them alone, so moving one afterwards does not fight it and the
# toggles remain the single source of truth for what is enabled.
PRESETS = %(presets)r


def onValueChange(par, prev):
    if par.name != "Verbosity":
        return
    wanted = PRESETS.get(par.eval())
    if wanted is None:
        return
    comp = par.owner
    for name in %(all_groups)r:
        target = getattr(comp.par, name, None)
        if target is not None:
            target.val = name in wanted
'''


def _page(comp, name="Attributes"):
    """The Attributes page. Created once; a tuned toggle survives a rebuild.

    Traps: `appendCustomPage` with an existing name makes a SECOND page of that
           name. And `appendToggle`/`appendMenu` on an existing parameter reset it,
           so the current values are read first and written back.
    """
    page = None
    for existing in comp.customPages:
        if existing.name == name:
            page = existing
            break
    if page is None:
        page = comp.appendCustomPage(name)

    known = {n for n, _d, _g in GROUPS}
    was = {p.name: p.eval() for p in comp.customPars
           if p.name in known or p.name == "Verbosity"}

    menu = page.appendMenu("Verbosity", label="Verbosity")[0]
    menu.menuNames = list(PRESETS)
    menu.menuLabels = list(PRESETS)
    menu.default = "Interaction"
    if "Verbosity" not in was:
        menu.val = "Interaction"

    for group, default, gated in GROUPS:
        suffix = "" if gated == "derive" else "  (channels only)"
        par = page.appendToggle(group, label=group + suffix)[0]
        par.default = default
        # A toggle has no invalid value, so a stored one always wins - unlike a
        # threshold, where zero had to be treated as untuned.
        par.val = was.get(group, default)
    return page


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    from visionhands.derive import ALL_GROUPS

    comp = op(COMP_PATH)
    if comp is None:
        print("FAIL no COMP at %s - run tools/td_build_comp.py first" % COMP_PATH)
        return

    _page(comp)
    print("1. Attributes page:")
    for group, _default, gated in GROUPS:
        print("   %-12s %-3s  %s" % (group,
                                     "on" if getattr(comp.par, group).eval() else "off",
                                     "gates derive()" if gated == "derive"
                                     else "channels only, gates no cost yet"))
    print("   Verbosity = %s" % comp.par.Verbosity.eval())

    # The preset callback. A Parameter Execute DAT rather than an expression on
    # each toggle: an expression would make the toggles read-only, and the point of
    # a preset is to SET them and then get out of the way.
    callbacks = comp.op("groups_callbacks") or comp.create(td.parameterexecuteDAT,
                                                           "groups_callbacks")
    callbacks.nodeX, callbacks.nodeY = 200, -2100
    callbacks.text = CALLBACK_SOURCE % {
        "presets": {k: list(v) for k, v in PRESETS.items()},
        "all_groups": [n for n, _d, _g in GROUPS],
    }
    callbacks.par.op = comp.path
    callbacks.par.pars = "Verbosity"
    callbacks.par.valuechange = True
    print("2. Verbosity presets wired through %s" % callbacks.name)

    # -- does the toggle actually reach derive()? --------------------------
    # ALL_GROUPS is derive.py's own list, so this catches a toggle whose name does
    # not match the group it is meant to gate - which would fail silently, because
    # `_groups()` treats a missing parameter as "enabled".
    failures = []
    derive_gated = {g for g, _d, kind in GROUPS if kind == "derive"}
    expected = {g.capitalize() for g in ALL_GROUPS}
    if derive_gated != expected:
        failures.append("the derive-gated toggles are %r but derive.ALL_GROUPS "
                        "wants %r" % (sorted(derive_gated), sorted(expected)))

    chop = comp.op("derive_chop")
    if chop is not None:
        before = chop.numChans
        was_descriptor = comp.par.Descriptor.eval()
        comp.par.Descriptor = not was_descriptor
        chop.cook(force=True)
        after = chop.numChans
        comp.par.Descriptor = was_descriptor
        chop.cook(force=True)
        print("3. proof the toggles bite: Descriptor flipped changed derive_chop "
              "from %d channels to %d" % (before, after))
        if before == after:
            failures.append("flipping Descriptor did not change derive_chop's "
                            "channel count - the toggle is not reaching derive()")

    out = comp.op("out1")
    if out is not None:
        out.cook(force=True)
        print("4. COMP output: %d channels" % out.numChans)

    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print("\nverified: every derive group has a toggle, and flipping one "
              "changes what derive() computes.")

    print("\nNOT DONE, deliberately, and what each needs:")
    print("  Trimming the output channel list for the NATIVE groups. A disabled")
    print("  derive group really does vanish from out1; the latch, trigger and")
    print("  motion channels keep their last value, because nothing gates them.")
    print("  docs/ATTRIBUTES.md suggests a Select whose channames is assembled")
    print("  from the enabled groups - but wildcard patterns CANNOT partition")
    print("  these channels: `h?_*_x` matches both the raw `h0_wrist_x` (Landmarks)")
    print("  and the derived `h0_palm_x` (Core), and `h?_e_*` matches both the")
    print("  Events pulses and the Triggers pulses. It needs an exact channel-to-")
    print("  group map, and the sound way to get one is a registry in the package:")
    print("  derive() can already report a group's channels by being called with")
    print("  just that group, and the latch table would move from")
    print("  tools/td_add_latches.py into visionhands/ so both can import it.")
    print("  That refactor is worth doing carefully rather than quickly.")
    print("")
    print("  Gating the NATIVE groups with allowCooking. The mechanism works")
    print("  (measured - see this file's docstring), but it is ~150 operators of")
    print("  restructuring to save native CHOP cost that is already negligible")
    print("  next to the Python cook these toggles do gate. Worth doing when the")
    print("  groups need to be relocatable for another reason, not for the cost.")


main()
