#!/usr/bin/env python
"""An About page: what this is, where it came from, and a button that updates it.

    RUN IT
        run("<repo>/tools/td_add_about.py")

    or through the chain: tools/td_rebuild.py, layer "about".

WHAT IT ADDS. One page, last, holding the version, the repository, and the two pulses
that fetch a newer `.tox` and swap this component for it in place.

WHY THE UPDATER IS HERE AND NOT BESIDE INSTALL. They do different things and confusing
them is expensive. `Install` writes the SIDECAR's files to disk - a Python, pyobjc, the
package, the depth model - and never touches the component. `Update` replaces the
COMPONENT and never touches the install. A user who presses the wrong one after a
failure learns nothing.

THE HAZARD, and the whole reason this file reads the way it does: **the COMP is
replacing itself, from a script that lives inside it.** `loadTox` destroys every child
of the target, and `about_control` is one of those children - so it cannot be the thing
that calls it. Both the download and the swap are handed to `run()`, which executes in
TouchDesigner's own module context rather than in the DAT: the string is compiled before
the DAT dies, and it never refers back to it.

WHAT SURVIVES A SWAP. Every custom parameter value, restored by name from a JSON file
written before the swap and read after it. A file rather than operator storage, because
storage belongs to the COMP that `loadTox` is about to rewrite. Anything the new version
does not have a parameter for is dropped, and the file is left on disk so it can be read.

Ref: docs/BUILD_PLAN.md step 26, tools/td_add_install.py (the same shape, for the other
     half of the problem).
"""

import os
import sys

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER_PATH = "/project1/appletd"

CONTROL = "about_control"
CALLBACKS = "about_callbacks"

# Where the component comes from. A PARAMETER as well as a default, so a fork or a
# branch can be pointed at without editing anything - and so the thing being downloaded
# is visible rather than baked into a script nobody opens.
REPO_URL = "https://github.com/ojrgb/appletd"
TOX_URL = REPO_URL + "/raw/main/appletd.tox"

# A `.tox` starts with these six bytes: a version word and the string "10". Checked
# before anything is swapped in, because `curl -f` still writes a file when a proxy
# answers with an HTML error page, and `loadTox` on 900 bytes of HTML replaces a working
# component with nothing.
TOX_MAGIC = b"\x00\x00\x00\x01" + b"10"
# Smaller than this is not a component. The real file is ~340 KB; anything under 50 KB
# is a truncated download or an error page that happened to start correctly.
TOX_MIN_BYTES = 50_000

CONTROL_SOURCE = '''# Generated by tools/td_add_about.py
#
# The updater. Read the builder's docstring for why the swap is scheduled rather than
# called: this DAT is a child of the COMP that `loadTox` destroys, so it cannot be
# the thing that calls it.
import json
import os
import subprocess
import tempfile

COMP_PATH = %(comp)r
TOX_MAGIC = %(magic)r
TOX_MIN_BYTES = %(min_bytes)d


def _comp():
    return op(COMP_PATH)


def _url(comp):
    par = getattr(comp.par, "Updateurl", None)
    return str(par.eval()).strip() if par is not None else ""


def _say(comp, text):
    if hasattr(comp.par, "Updatestate"):
        comp.par.Updatestate = text
    print("[appletd] " + text)
    return text


def check(comp=None):
    """Ask the server what it has, without downloading it. Returns the state text.

    A HEAD request: ~200 bytes and no body, so this is cheap enough for a button and
    tells us the two things worth knowing - that the URL is reachable at all, and
    whether the file has changed since the last time this component was updated from
    it.

    THE MARKER IS THE ETAG, not a version string. A version we publish is a second
    source of truth that drifts; an ETag is the server's own answer to "is this the
    same bytes", it costs nothing, and it is right even for a change that does not
    move `Sourceversion` - a network edit, a rebuilt page, a re-export.

    A component downloaded by hand has no stored ETag, so the FIRST check always says
    an update is available. That is honest rather than annoying: we genuinely do not
    know which build is in front of us.
    """
    comp = comp or _comp()
    if comp is None:
        return "no COMP"
    url = _url(comp)
    if not url:
        return _say(comp, "No update URL set")
    try:
        # `-L`, because `github.com/.../raw/...` answers 302 to
        # raw.githubusercontent.com and the redirect's own body is zero bytes. Without
        # it the size read as "0.0 MB" and the ETag was the redirect's, not the file's -
        # so the marker would have compared two things that are not the download.
        # The parse below keeps the LAST value of each header, which is the final hop.
        found = subprocess.run(["curl", "-fsSIL", url],
                               capture_output=True, text=True, timeout=20)
    except Exception as problem:                    # noqa: BLE001 - reported, not hidden
        return _say(comp, "Check failed - %%r" %% (problem,))
    if found.returncode != 0:
        return _say(comp, "Check failed - %%s"
                    %% (found.stderr.strip()[:120] or "curl exited %%d"
                       %% found.returncode))

    etag = ""
    size = ""
    for line in found.stdout.splitlines():
        name, _, value = line.partition(":")
        if name.strip().lower() == "etag":
            etag = value.strip().strip('"')
        elif name.strip().lower() == "content-length":
            size = value.strip()
    known = str(getattr(comp.par, "Updateetag", None)
                and comp.par.Updateetag.eval() or "")
    if hasattr(comp.par, "Updatefound"):
        comp.par.Updatefound = etag
    if etag and etag == known:
        return _say(comp, "Up to date")
    if size.isdigit():
        number = int(size)
        megabytes = (" (%%.1f MB)" %% (number / 1e6) if number >= 1e6
                     else " (%%d KB)" %% (number // 1000))
    else:
        megabytes = ""
    if not known:
        return _say(comp, "Update available%%s - this component was not installed "
                    "by the button, so its version is unknown" %% megabytes)
    return _say(comp, "Update available%%s - press Update to fetch and swap"
                %% megabytes)


def update(comp=None):
    """Download the newer `.tox` and schedule the swap. Returns the state text.

    BLOCKING, deliberately, unlike the installer's poll loop. That one moves 100+ MB and
    would freeze the application; this is ~340 KB and a poll loop for it would be more
    machinery than the thing it manages. The timeout is what keeps a dead network from
    holding the main thread.
    """
    comp = comp or _comp()
    if comp is None:
        return "no COMP"
    url = _url(comp)
    if not url:
        return _say(comp, "No update URL set")

    _say(comp, "Downloading...")
    tmp = os.path.join(tempfile.gettempdir(), "appletd_update.tox")
    try:
        got = subprocess.run(["curl", "-fL", "--max-time", "120", url, "-o", tmp],
                             capture_output=True, text=True, timeout=180)
    except Exception as problem:                    # noqa: BLE001
        return _say(comp, "Download failed - %%r" %% (problem,))
    if got.returncode != 0:
        return _say(comp, "Download failed - %%s"
                    %% (got.stderr.strip()[:120] or "curl exited %%d"
                       %% got.returncode))

    # WHAT ARRIVED IS CHECKED BEFORE IT IS TRUSTED. `curl -f` still writes a file when
    # a captive portal or a proxy answers with HTML, and `loadTox` on that replaces a
    # working component with nothing at all.
    try:
        size = os.path.getsize(tmp)
        with open(tmp, "rb") as handle:
            head = handle.read(len(TOX_MAGIC))
    except OSError as problem:
        return _say(comp, "Download failed - %%r" %% (problem,))
    if size < TOX_MIN_BYTES or head != TOX_MAGIC:
        return _say(comp, "Refused - what downloaded is not a .tox (%%d bytes). "
                    "Nothing was changed." %% size)

    # EVERY TUNED VALUE, to a FILE. Operator storage belongs to the COMP that is about
    # to be rewritten; a file outlives it.
    snapshot = os.path.join(tempfile.gettempdir(), "appletd_update_pars.json")
    values = {}
    for par in comp.customPars:
        if par.isPulse or par.readOnly:
            continue                      # a pulse has no value; a readonly is derived
        try:
            values[par.name] = par.eval()
        except Exception:                 # noqa: BLE001, S112 - unreadable is skippable
            continue
    with open(snapshot, "w") as handle:
        json.dump(values, handle, indent=1, default=str)

    etag = str(getattr(comp.par, "Updatefound", None)
               and comp.par.Updatefound.eval() or "")
    swap = os.path.join(tempfile.gettempdir(), "appletd_do_update.py")
    # The four values as ASSIGNMENTS rather than substitutions. `_SWAP` is a template
    # inside a template inside a template - this DAT is generated, and it generates the
    # swap script - and every `%%` in the middle layer then needs escaping twice. Getting
    # that wrong fails at BUILD if you are lucky and when somebody presses Update if you
    # are not. A header removes the layer instead of getting the escaping right.
    with open(swap, "w") as handle:
        handle.write("# Generated by appletd's About page. Safe to delete.\\n")
        handle.write("COMP_PATH = %%r\\nTOX = %%r\\nSNAPSHOT = %%r\\nETAG = %%r\\n"
                     %% (COMP_PATH, tmp, snapshot, etag))
        handle.write(_SWAP)
    # SCHEDULED, and this is the whole design. `loadTox` destroys every child of the
    # target - including THIS DAT - so the call cannot come from here. `run` executes
    # in TouchDesigner's own module context, and the delay lets this function return
    # first so nothing is unwinding through a destroyed operator.
    run("exec(open(%%r).read())" %% swap, delayFrames=5)
    return _say(comp, "Swapping in the new version...")


# The body of that script. NO substitutions in it - the values it needs are written
# above it as assignments - so the only escaping here is the single layer that gets it
# out of this builder and into the DAT.
_SWAP = """import json
import os

comp = op(COMP_PATH)
comp.loadTox(TOX)

# Put back every value the new version still has a parameter for. Names, not indices:
# a parameter that moved page keeps its value, and one that was retired is dropped
# rather than landing on whatever now sits in its place.
restored, dropped = 0, []
try:
    with open(SNAPSHOT) as handle:
        saved = json.load(handle)
except Exception as problem:
    print("[appletd] could not read the saved settings: %%r" %% (problem,))
    saved = {}
for name, value in saved.items():
    par = getattr(comp.par, name, None)
    if par is None or par.readOnly:
        dropped.append(name)
        continue
    try:
        par.val = value
        restored += 1
    except Exception:
        dropped.append(name)
if hasattr(comp.par, "Updateetag"):
    comp.par.Updateetag = ETAG
print("[appletd] updated. %%d setting(s) restored." %% restored)
if dropped:
    print("[appletd]   no parameter in this version for: %%s" %% ", ".join(dropped))
    print("[appletd]   the old values are in " + SNAPSHOT)
if hasattr(comp.par, "Updatestate"):
    comp.par.Updatestate = "Updated - %%d setting(s) restored" %% restored
try:
    os.remove(TOX)
except OSError:
    pass
"""


def open_repository(comp=None):
    """Open the project page in a browser. A pulse because a parameter cannot be a
    link, and printing a URL for somebody to copy is worse than a button."""
    comp = comp or _comp()
    url = str(comp.par.Repository.eval()) if comp is not None else ""
    if url:
        subprocess.Popen(["open", url])
    return url
'''

CALLBACK_SOURCE = '''# Generated by tools/td_add_about.py
CONTROL_PATH = %(control)r


def onPulse(par):
    control = op(CONTROL_PATH)
    if control is None:
        return
    if par.name == "Checkupdate":
        control.module.check(par.owner)
    elif par.name == "Applyupdate":
        control.module.update(par.owner)
    elif par.name == "Openrepository":
        control.module.open_repository(par.owner)
'''

NOTES = """ABOUT - what this is, and the button that replaces it with a newer one.

`Check for Updates` asks the server for the file's ETag and compares it with the one
this component was last updated from. `Update` downloads it, checks that what arrived
really is a .tox, saves every tuned parameter to a JSON file, and SCHEDULES the swap.

The swap is scheduled and not called because `loadTox` destroys every child of this
COMP - including `about_control`, which is where the calling code lives. `run()`
executes in TouchDesigner's own module context instead.

A component downloaded by hand has no stored ETag, so the first check always reports an
update. That is honest: we do not know which build is in front of us.

Built by tools/td_add_about.py. Edits here are overwritten on the next run."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.td_layout import master_xy

    comp = op(MASTER_PATH)
    if comp is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("about: the page, and the updater, on %s" % comp.path)
    print("=" * 70)

    page = None
    for existing in comp.customPages:
        if existing.name == "About":
            page = existing
            break
    if page is None:
        page = comp.appendCustomPage("About")

    # Appended only when absent, and never re-appended: `appendStr` on an existing
    # parameter RESETS it, and the reset fires a callback that outlives a write-it-back
    # fix (DESIGN.md 2.17).
    have = {par.name for par in comp.customPars}

    if "Repository" not in have:
        repo = page.appendStr("Repository", label="Repository")[0]
        repo.val = REPO_URL
        repo.readOnly = True
    if "Openrepository" not in have:
        page.appendPulse("Openrepository", label="Open in Browser")
    if "Updateurl" not in have:
        # A PARAMETER, so a fork or a branch can be pointed at without editing a DAT,
        # and so what is about to be downloaded is visible before it is.
        url = page.appendStr("Updateurl", label="Update From")[0]
        url.val = TOX_URL
    if "Checkupdate" not in have:
        page.appendPulse("Checkupdate", label="Check for Updates")
    if "Updatestate" not in have:
        state = page.appendStr("Updatestate", label="Update Status")[0]
        state.val = "Not checked"
        state.readOnly = True
    if "Applyupdate" not in have:
        page.appendPulse("Applyupdate", label="Update  (replaces this component)")
    if "Updateetag" not in have:
        # What we last updated FROM, and what the next check compares against. Not
        # readOnly: clearing it by hand is the way to force the next check to report an
        # update, which is the only escape hatch this needs.
        tag = page.appendStr("Updateetag", label="Updated From (etag)")[0]
        tag.val = ""
    if "Updatefound" not in have:
        found = page.appendStr("Updatefound", label="Server Has (etag)")[0]
        found.readOnly = True

    page.sort("Repository", "Openrepository", "Updateurl", "Checkupdate",
              "Updatestate", "Applyupdate", "Updateetag", "Updatefound")

    control = comp.op(CONTROL) or comp.create(td.textDAT, CONTROL)
    control.nodeX, control.nodeY = master_xy(CONTROL)
    control.text = CONTROL_SOURCE % {"comp": comp.path, "magic": TOX_MAGIC,
                                     "min_bytes": TOX_MIN_BYTES}

    callbacks = comp.op(CALLBACKS) or comp.create(td.parameterexecuteDAT, CALLBACKS)
    callbacks.nodeX, callbacks.nodeY = master_xy(CALLBACKS)
    callbacks.text = CALLBACK_SOURCE % {"control": control.path}
    callbacks.par.op = comp.path
    callbacks.par.pars = "Checkupdate Applyupdate Openrepository"
    callbacks.par.custom = True
    callbacks.par.builtin = False
    callbacks.par.onpulse = True
    callbacks.par.valuechange = False
    callbacks.par.active = True
    control.comment = NOTES

    # -- verification ------------------------------------------------------
    failures = []
    for name in ("Repository", "Openrepository", "Updateurl", "Checkupdate",
                 "Updatestate", "Applyupdate", "Updateetag", "Updatefound"):
        if not hasattr(comp.par, name):
            failures.append("no `%s` parameter" % name)
    module = control.module
    for name in ("check", "update", "open_repository"):
        if not hasattr(module, name):
            failures.append("`%s` is not callable on %s" % (name, CONTROL))
    # The swap script is a TEMPLATE inside a template. If its `%` escaping is wrong the
    # error appears only when somebody presses Update, on somebody else's machine - so
    # it is rendered here, at build, against the real substitutions.
    try:
        header = ("COMP_PATH = %r\nTOX = %r\nSNAPSHOT = %r\nETAG = %r\n"
                  % (comp.path, "/tmp/x.tox", "/tmp/x.json", "abc"))
        compile(header + module._SWAP, "swap", "exec")
    except Exception as problem:                   # noqa: BLE001 - reported
        failures.append("the swap script does not render or compile: %r" % (problem,))

    print()
    print("   About page: %d parameters" % len(list(page.pars)))
    print("   %s -> %s" % (comp.par.Repository.eval(), comp.par.Updateurl.eval()))
    print("   %-14s %s" % ("Updatestate", comp.par.Updatestate.eval()))
    print()
    if failures:
        print("FAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print("   verified. The swap script renders and compiles, and the three")
        print("   pulses reach `%s`. `Update` replaces this COMPONENT; `Install`" % CONTROL)
        print("   on the Vision page writes the SIDECAR's files - different things.")
    print()


main()
