#!/usr/bin/env python
"""One toggle that strips the raw normalised coordinates from every stream's output.

    Paste into a Text DAT, Run Script. Idempotent. Run it LAST, after
    td_add_coords.py, because what it deletes is decided by what that builds.

    ON THE VISION PAGE
        Screenspaceonly   off  every channel, raw normalised and adjusted
                          on   the raw normalised POSITIONS and EXTENTS are gone,
                               leaving only TouchDesigner's world and pixel spaces

WHAT IT BUILDS, in each stream, between `merge_out` and `out1`:

    merge_out -> screen_only (a Delete CHOP) -> out1

WHY A DELETE CHOP AND NOT A SELECT. A Select needs the list of channels to KEEP,
and the stream's output carries far more than this repo's contract - 87 derived
attributes, 27 temporal channels, 76 latch channels, all named by tables that live
in three different builders. Assembling a keep-list here would mean either a
wildcard, which DESIGN.md 2.11 records twice as unable to partition these channels,
or a snapshot of the live channel list, which goes stale the moment a group toggle
moves and then silently deletes whatever appeared since.

A Delete CHOP takes the list of channels to REMOVE, and that list is exactly
`spaces.companioned_names(stream)` - short, exact, and derived from the same
registry that built the companions in the first place. Nothing else can be
affected, whatever else the stream grows.

WHAT IT REMOVES, precisely: every channel that HAS a screen-space companion. So
`h0_wrist_x` goes and `h0_wrist_tx`/`h0_wrist_px` stay; `f0_bbox_w` goes and
`f0_bbox_tw` stays; every face landmark's box-relative `_x` goes and its `_tx`
stays.

WHAT IT KEEPS, and this is narrower than "channels that are not screen-space
adjusted" on purpose:

    every boolean and pulse       found, pinching, the edge pulses
    every counter and age         seq, age_ms, n_hands, sc_*
    every confidence and score    they have no meaning in pixels
    every ANGLE                   roll, yaw, pitch, hands_angle. There is no such
                                  thing as a yaw in world units, so an angle has no
                                  companion to be redundant with

The rule is "remove the SECOND copy of a number, never the only copy". A toggle that
also dropped angles and confidences would be smaller and would lose information,
which is a different feature from the one asked for.

DELETING CHANNELS IS NORMALLY THE BUG THIS PROJECT FEARS. DESIGN.md 6.2: a channel
that disappears breaks every reference to it with NO error anywhere, which is why a
disabled stream still sends zeros and a frozen group still publishes its last
values. This is the one place where making channels vanish is the point, so it is
built where it can do the least damage:

  * at the very END of the chain, after `merge_out`, so nothing inside the COMP
    reads through it and no group's verification is affected;
  * as a BYPASSED operator when the toggle is off - measured elsewhere in this repo
    as a bit-exact passthrough that also stops the operator computing;
  * and it ships OFF, because the raw channels are what every existing project
    reads and a toggle that defaulted on would delete them out from under one.

Ref: DESIGN.md 6.2 (why a vanished channel is silent), 7 (the coordinate contract),
     visionhands/spaces.py, docs/BUILD_PLAN.md step 10.
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
MASTER_PATH = "/project1/vision"
NODE = "screen_only"
PARAMETER = "Screenspaceonly"

CALLBACK = '''# Generated by tools/td_add_screenspace.py
#
# `Screenspaceonly` off sets the Delete CHOP's BYPASS flag - a bit-exact
# passthrough that also stops the operator computing. A DAT rather than an
# expression because `bypass` is an ATTRIBUTE, not a parameter: there is nothing to
# bind an expression to. The same pattern filter_callbacks uses for the filter.
STREAMS = %(streams)r
NODE = %(node)r


def _apply(comp):
    """Bypass or engage the Delete CHOP on EVERY stream. One toggle, three nodes."""
    wanted = not comp.par.%(parameter)s.eval()
    for stream in STREAMS:
        node = comp.op('%%s/%%s' %% (stream, NODE))
        if node is not None:
            node.bypass = wanted


def onValueChange(par, prev):
    _apply(par.owner)


def onValuesChanged(changes):
    if changes:
        _apply(changes[0].par.owner)
'''

NOTES = """SCREEN_ONLY - the one place in this COMP where channels are meant to vanish.

  merge_out -> screen_only -> out1

A Delete CHOP holding the exact list of channels that HAVE a screen-space
companion. With op.Vision.par.%(parameter)s on, they are removed and only
TouchDesigner's own world and pixel coordinates leave the stream. With it off this
operator is BYPASSED - bit-exact, and not computing.

  deletes   %(n_deleted)d channels
  keeps     %(n_kept)d, including every boolean, pulse, counter, confidence and ANGLE

WHY A DELETE AND NOT A SELECT. A Select needs the KEEP list, and this stream's
output carries 87 derived attributes, 27 temporal channels and 76 latch channels
named by tables in three different builders. The delete list is exactly
spaces.companioned_names() - short, exact, and derived from the same registry that
built the companions.

WHY IT SITS HERE, AFTER merge_out. A channel that disappears breaks every
reference to it with no error anywhere (DESIGN.md 6.2). Nothing inside the COMP
reads through this operator, so nothing inside can be broken by it.

Built by tools/td_add_screenspace.py. Edits here are overwritten on the next run."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    # `td_layout` is where this operator goes - the one table every builder reads.
    from visionhands.spaces import companioned_names, derived_companioned_names
    from visionhands.streams import STREAM_HANDS, STREAM_NAMES
    from visionhands.td_layout import master_xy, stream_xy

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return
    if not hasattr(master.par, PARAMETER):
        print("FAIL %s has no %s - run tools/td_build_vision.py first"
              % (MASTER_PATH, PARAMETER))
        return

    engaged = bool(getattr(master.par, PARAMETER).eval())
    failures = []
    built = []
    for stream in STREAM_NAMES:
        child = master.op(stream)
        if child is None:
            print("   (no `%s` stream in %s - skipped)" % (stream, MASTER_PATH))
            continue
        # Two lists, and the split matters. The wire-contract channels are ALWAYS
        # on the output, so one of them missing is a fault. The derived ones can be
        # absent - a disabled derive group does not emit its channels at all, unlike
        # a frozen native group, which holds them - so a missing one is normal.
        optional = derived_companioned_names() if stream == STREAM_HANDS else []
        built.append(_build_one(td, child, stream, companioned_names(stream),
                                optional, engaged, failures, stream_xy(NODE),
                                stream_xy("screen_only_notes"),
                                _keep_layout(master)))

    callbacks = master.op("screenspace_callbacks") or master.create(
        td.parameterexecuteDAT, "screenspace_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("screenspace_callbacks")
    callbacks.text = CALLBACK % {"streams": list(STREAM_NAMES), "node": NODE,
                                 "parameter": PARAMETER}
    callbacks.par.op = master.path
    callbacks.par.pars = PARAMETER
    callbacks.par.valuechange = True
    callbacks.par.active = True

    print()
    print("   %s = %s" % (PARAMETER, engaged))
    for stream, arrived, produced, deleted in built:
        counts = ("not measured - frozen" if arrived is None
                  else "%4d channels in, %4d out" % (arrived, produced))
        print("   %-5s %-26s (%d deletable%s)"
              % (stream, counts, deleted,
                 "" if engaged else ", currently bypassed"))
    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print()
        print("   verified. Flip %s on %s and every stream's output loses its raw"
              % (PARAMETER, master.path))
        print("   normalised positions, keeping _tx/_ty/_px/_py and every boolean,")
        print("   counter, confidence and angle.")


def _keep_layout(master):
    """Has the user asked the builders to leave their node arrangement alone?"""
    par = getattr(master.par, "Keeplayout", None)
    return bool(par is not None and par.eval())


def _place(node, xy, keep, existed):
    """Write nodeX/nodeY unless `Keeplayout` is on and the node already existed.

    Rule and caveats in `visionhands.td_layout.placement`.
    """
    from visionhands.td_layout import placement

    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where
    return node


def _build_one(td, child, stream, doomed, optional, engaged, failures, node_xy,
               note_xy, keep):
    """Put the Delete CHOP between `merge_out` and `out1`. Returns a report row."""
    merge = child.op("merge_out")
    chop_out = child.op("out1")
    if merge is None or chop_out is None:
        failures.append("%s has no merge_out/out1 - run tools/td_build_vision.py"
                        % child.path)
        return (stream, 0, 0, 0)

    existing = child.op(NODE)
    node = existing or child.create(td.deleteCHOP, NODE)
    _place(node, node_xy, keep, existing is not None)
    node.color = (0.5, 0.32, 0.32)
    node.inputConnectors[0].connect(merge)
    node.par.delchannels = True
    node.par.delsamples = False
    # By NAME, and `scoped` means "delete the ones named". `nonscoped` would delete
    # everything else, which is the same parameter one menu entry away from
    # inverting the whole toggle - so it is written explicitly rather than left at
    # its default.
    node.par.select = "byname"
    node.par.discard = "scoped"
    node.par.delscope = " ".join(list(doomed) + list(optional))
    node.bypass = not engaged

    # out1 reads the Delete CHOP now, not the Merge. Stated here rather than left
    # to whatever it happened to be wired to: DESIGN.md 2.11 records that a builder
    # which repoints its consumers depends on build order and lost, and this is the
    # one consumer whose input this script owns.
    chop_out.inputConnectors[0].connect(node)
    chop_out.nodeX = max(chop_out.nodeX, node_xy[0] + 200)

    existing_note = child.op("screen_only_notes")
    note = existing_note or child.create(td.textDAT, "screen_only_notes")
    _place(note, note_xy, keep, existing_note is not None)

    # A FROZEN stream cannot be verified. `allowCooking = False` on the child COMP
    # blocks a forced cook of anything inside it, so both reads below would be
    # whatever was there when it froze - and the engaged-check would report every
    # channel as "should have been deleted and was not". Reported as skipped rather
    # than checked against stale numbers.
    if not child.allowCooking:
        print("   (`%s` is frozen - built, not verified. Turn Stream%s on to check "
              "it.)" % (stream, stream))
        note.text = NOTES % {"parameter": PARAMETER,
                             "n_deleted": len(doomed) + len(optional), "n_kept": 0}
        # None, not zero: "0 channels in, 0 out" reads as a broken stream, and the
        # honest answer is that a frozen one cannot be measured.
        return (stream, None, None, len(doomed) + len(optional))

    merge.cook(force=True)
    chop_out.cook(force=True)
    arrived = {c.name for c in merge.chans()}
    produced = {c.name for c in chop_out.chans()}
    note.text = NOTES % {"parameter": PARAMETER,
                         "n_deleted": len(doomed) + len(optional),
                         "n_kept": len(arrived - set(doomed) - set(optional))}

    # -- verification -------------------------------------------------------
    # Every name in the delete list has to BE on the input, or the list has drifted
    # from the contract and the toggle silently under-deletes.
    absent = sorted(set(doomed) - arrived)
    gated_away = sorted(set(optional) - arrived)
    if gated_away:
        print("   (`%s`: %d derived channel(s) in the list are not on the output "
              "right now - a disabled derive group emits nothing. Not a fault.)"
              % (stream, len(gated_away)))
    if absent:
        failures.append("%s: %d channel(s) in the delete list are not on merge_out: "
                        "%r - spaces.companioned_names() and the live network "
                        "disagree" % (stream, len(absent), absent[:5]))
    if engaged:
        left = sorted((set(doomed) | set(optional)) & produced)
        if left:
            failures.append("%s: %d channel(s) should have been deleted and were "
                            "not: %r" % (stream, len(left), left[:5]))
        # And the far more damaging direction: something NOT on the list going
        # missing. A Delete CHOP set to `nonscoped` by accident would take out the
        # entire rest of the stream.
        collateral = sorted(arrived - produced - set(doomed) - set(optional))
        if collateral:
            failures.append("%s: %d channel(s) were deleted that are NOT on the "
                            "list: %r" % (stream, len(collateral), collateral[:5]))
    else:
        # Bypassed: it must be a passthrough, exactly.
        if arrived != produced:
            failures.append("%s: `%s` is bypassed and changed the channel set by %d"
                            % (stream, NODE, len(arrived ^ produced)))
    return (stream, len(arrived), len(produced), len(doomed) + len(optional))


main()
