"""The TouchDesigner side of the segmentation mask: shared memory -> a TOP.

WHAT THIS BUILDS, inside /project1/vision:

    seg_mask (Script TOP)  ->  seg_fit (Fit TOP)  ->  outmask (Out TOP)
       reads the mmap            undoes the             the COMP's only
       and flips y               anisotropic stretch    TOP output

and a `Segmentation` parameter page carrying the buffer path, the master toggle and
the fit toggle. Run it any time; it is idempotent.

WHY THREE OPERATORS AND NOT ONE. Each does the one thing it is cheapest at:

  * the SCRIPT TOP does what only Python can - read the shared buffer - and nothing
    else that costs. It copies `width * height` bytes straight in as `uint8`, which
    `copyNumpyArray` accepts natively (VERIFIED: no float32 conversion needed).
  * the Y FLIP is in the Script TOP, because that is the operator that knows the
    convention. Vision's mask has its origin at the TOP left and TouchDesigner's TOP
    arrays are bottom-up (visionhands/coords.py). `maskbuf.py` deliberately does NOT
    flip - a transport that silently reorients its payload cannot be tested against
    a known pattern - so somebody downstream has to, and this is that somebody.
  * the FIT TOP undoes the stretch, on the GPU. MEASURED (DESIGN.md 2.18): the mask
    does not share its source's aspect ratio - a 1280x720 frame gives a 256x192 mask
    - so the correction is a NON-UNIFORM scale. `fit = fill` with the resolution
    driven from the header's source geometry is exactly that, and it costs nothing
    on the main thread where a numpy resize would cost a 1280x720 resample per frame.

WHY `outmask` IS AN OUT TOP AND SEPARATE FROM `out1`. A COMP can carry outputs of
several families, and a mask is not a channel. `out1` stays the single CHOP output
that everything else in the project reads; `outmask` is a second connector of a
different type, so nothing about the CHOP contract moves.

WHAT DOES NOT WORK YET, and the toggle says so rather than pretending: nothing
publishes to the buffer. `visionhands/sidecar.py` does not run segmentation yet, so
`Segment` ships OFF and the mask is black until something writes. To see it work now:

    ~/.venvs/visionhands/bin/python tools/segmentation_probe.py --write-only

then switch `Segment` on. That is the shape the sidecar will have.

NO QUALITY PARAMETER. It would be a knob that cannot be honoured - the quality level
is chosen by whatever writes the buffer, and this side only reads. `engine.py` makes
the same argument about `max_hands`, and STANDARDS.md 2 is why: a control that does
nothing is worse than no control.

Ref: visionhands/maskbuf.py, visionhands/segmentation.py, design/DESIGN.md 2.18-2.19,
     docs/BUILD_PLAN.md step 16.
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
MASTER_PATH = "/project1/vision"

# Where the sidecar will publish. On Advanced with the other internals, because a
# consumer of this COMP does not choose it - it has to match what the writer uses.
DEFAULT_BUFFER = "/tmp/visionhands_mask.buf"

PAGE = "Segmentation"

CALLBACK_SOURCE = '''# Generated by tools/td_add_segmentation.py
#
# Reads the shared mask buffer and publishes it as a TOP. Everything expensive is
# deliberately elsewhere: this does one `os.stat`, one coherent read of at most a few
# hundred KB, one y-flip, and one `copyNumpyArray`.
import sys

REPO_ROOT = %(repo)r
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)

import numpy

from visionhands.maskbuf import MaskReader

# The reader lives in MODULE GLOBALS and never in operator storage. TouchDesigner
# PICKLES operator storage into the .toe on save, and an `mmap` cannot be pickled -
# which is exactly how this project lost the ability to save on 2026-08-21, over a
# dataclass. A module global is not saved, and is rebuilt on demand.
_READERS = {}

# What to publish before anything has been written. A defined black frame rather than
# the Script TOP's 2x2 default, so a project wired to `outmask` has a sane image from
# the first cook instead of something that changes shape when the sidecar starts.
_BLANK = numpy.zeros((192, 256, 1), dtype=numpy.uint8)


def _reader(path):
    """One MaskReader per path, cached. None if the file is not there yet.

    A missing file is the NORMAL state before the writer starts, so it returns None
    rather than raising - and it is not cached, so the next cook tries again.
    """
    reader = _READERS.get(path)
    if reader is not None:
        return reader
    try:
        reader = MaskReader(path)
    except (OSError, ValueError):
        # OSError: not there yet. ValueError: there but too small to hold a header,
        # which is a writer mid-creation. Both resolve on their own.
        return None
    _READERS[path] = reader
    return reader


def onCook(scriptOp):
    comp = op.Vision or scriptOp.parent()

    # The master toggle is checked HERE and not by freezing the operator. MEASURED
    # 2026-08-22: `allowCooking = False` raises "This flag can only be disabled for
    # COMPs" on a Script TOP, so the gating pattern the CHOP groups use is simply not
    # available to a bare operator. Wrapping these three in a base COMP just to get
    # the flag would buy a COMP boundary and a second output connector to explain,
    # for an operator that only cooks when something is looking at it anyway.
    #
    # The toggle still DOES something: off releases the mmap, so the buffer's file
    # handle is not held open by a project that is not using it.
    if hasattr(comp.par, "Segment") and not bool(comp.par.Segment.eval()):
        reader = _READERS.pop(str(comp.par.Maskbuffer.eval()), None)
        if reader is not None:
            reader.close()
        scriptOp.copyNumpyArray(_BLANK)
        return

    path = str(comp.par.Maskbuffer.eval()) if hasattr(comp.par, "Maskbuffer") else ""
    if not path:
        scriptOp.copyNumpyArray(_BLANK)
        return

    reader = _reader(path)
    if reader is None:
        scriptOp.copyNumpyArray(_BLANK)
        return

    try:
        frame = reader.read()
    except ValueError:
        # A non-zero wrong magic: somebody else's file. Drop the reader so a
        # corrected path is picked up, and say so once rather than every cook.
        _READERS.pop(path, None)
        scriptOp.copyNumpyArray(_BLANK)
        raise

    if frame is None:
        # Nothing published yet, or the writer won the race. HOLD the previous frame
        # by returning without copying - which is the right answer for a mask, and
        # the reason `read` never blocks (maskbuf.py).
        return

    # (h, w, components). MEASURED: `copyNumpyArray` needs THREE dimensions - a plain
    # (h, w) raises "must be 3 dimensions" - and takes uint8 without conversion.
    #
    # `[::-1]` is the y flip: Vision's mask origin is top-left, TouchDesigner's TOP
    # arrays are bottom-up. `ascontiguousarray` because the reversed view is not
    # contiguous, and it is one memcpy of the payload - 197 KB at 512x384.
    array = numpy.frombuffer(frame.pixels, dtype=numpy.uint8).reshape(
        frame.height, frame.width, frame.components)
    scriptOp.copyNumpyArray(numpy.ascontiguousarray(array[::-1]))

    # The source geometry, onto the parameters the Fit TOP reads. Written rather than
    # bound, because an expression would have to open the buffer on every cook of
    # every operator that referenced it.
    if hasattr(comp.par, "Masksourcew") and frame.source_width:
        if int(comp.par.Masksourcew.eval()) != frame.source_width:
            comp.par.Masksourcew = frame.source_width
        if int(comp.par.Masksourceh.eval()) != frame.source_height:
            comp.par.Masksourceh = frame.source_height
'''


def _page(comp, name):
    """Find or create a custom page. TRAP: `appendCustomPage` with an existing name
    makes a SECOND page of that name, so the existing one is looked up first."""
    for existing in comp.customPages:
        if existing.name == name:
            return existing
    return comp.appendCustomPage(name)


def _at(node, xy, keep, existed):
    from visionhands.td_layout import placement
    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    from visionhands.td_layout import master_xy

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("segmentation: shared memory -> a TOP, in %s" % master.path)
    print("=" * 70)

    keep_layout = bool(master.par.Keeplayout.eval()) \
        if hasattr(master.par, "Keeplayout") else False

    # -- the parameters ----------------------------------------------------
    # APPEND ONLY WHAT IS ABSENT. `append*` on an existing parameter RESETS it, and
    # the reset fires a DEFERRED callback that outlives any write-it-back fix -
    # measured 2026-08-22, DESIGN.md 2.17. Nothing that exists is touched here except
    # its `default`, which is not a value.
    page = _page(master, PAGE)
    existing = {par.name: par for par in master.customPars}

    on = existing.get("Segment")
    if on is None:
        on = page.appendToggle("Segment", label="Segment")[0]
        # OFF, and that is honest rather than cautious: nothing publishes to the
        # buffer yet, so ON would be a control that appears broken.
        on.val = False
    on.default = False

    fit = existing.get("Maskfit")
    if fit is None:
        fit = page.appendToggle("Maskfit", label="Fit Mask To Source")[0]
        fit.val = True
    fit.default = True

    # The source geometry the Script TOP reads out of the header and writes here, for
    # the Fit TOP to read. READ-ONLY to the user: they are a readout, not a setting,
    # and a settable one would silently fight the writer every frame.
    for name, label, default in (("Masksourcew", "Source Width (from the buffer)", 1280),
                                 ("Masksourceh", "Source Height (from the buffer)", 720)):
        par = existing.get(name)
        if par is None:
            par = page.appendInt(name, label=label)[0]
            par.val = default
        par.default = default
        par.readOnly = True

    # The path goes on ADVANCED, with the other internals: a consumer of this COMP
    # does not choose it, it has to match whatever writes the buffer.
    advanced = _page(master, "Advanced")
    buffer_par = existing.get("Maskbuffer")
    if buffer_par is None:
        buffer_par = advanced.appendStr("Maskbuffer",
                                       label="Mask Buffer Path")[0]
        buffer_par.val = DEFAULT_BUFFER
    buffer_par.default = DEFAULT_BUFFER

    print("1. `%s` page: Segment=%s, Maskfit=%s, source %dx%d"
          % (PAGE, bool(on.eval()), bool(fit.eval()),
             int(master.par.Masksourcew.eval()), int(master.par.Masksourceh.eval())))
    print("   Advanced: Maskbuffer=%r" % buffer_par.eval())

    # -- the callbacks DAT -------------------------------------------------
    callbacks = master.op("seg_callbacks") or master.create(td.textDAT,
                                                           "seg_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("seg_callbacks")
    callbacks.text = CALLBACK_SOURCE % {"repo": REPO_ROOT}

    # -- the Script TOP ----------------------------------------------------
    script = master.op("seg_mask")
    script_existed = script is not None
    if script is None:
        script = master.create(td.scriptTOP, "seg_mask")
        # Creating a Script TOP auto-docks its own callbacks DAT. Destroy it, or two
        # DATs claim the same job and only one of them is the generated one - the
        # same trap the Script CHOP has (DESIGN.md 2.11).
        for child in list(master.children):
            if child.name.startswith("seg_mask_callbacks") and child.valid:
                child.destroy()
    _at(script, master_xy("seg_mask"), keep_layout, script_existed)
    script.par.callbacks = callbacks.path
    # `mono8fixed`: one byte per pixel on the GPU, which is what a mask is. The
    # default rgba8fixed would carry four and copy three of them for nothing.
    script.par.format = "mono8fixed"
    script.color = (0.35, 0.45, 0.5)
    # NOT `allowCooking`. MEASURED: "This flag can only be disabled for COMPs" - it
    # raises on a bare operator, so `Segment` is checked inside `onCook` instead. See
    # the callback for why that is the right trade rather than a workaround.

    # -- the Fit TOP, undoing the anisotropic stretch ----------------------
    fit_top = master.op("seg_fit")
    fit_existed = fit_top is not None
    if fit_top is None:
        fit_top = master.create(td.fitTOP, "seg_fit")
    _at(fit_top, master_xy("seg_fit"), keep_layout, fit_existed)
    fit_top.inputConnectors[0].connect(script)
    # `fill` is the NON-UNIFORM stretch - it fills the target resolution and does not
    # preserve the aspect ratio, which is exactly the correction needed. `fitbest`
    # would letterbox, which would be right if Vision had letterboxed. It did not:
    # the subject spans the full height of the mask, verified by row occupancy
    # (DESIGN.md 2.18).
    fit_top.par.fit = "fill"
    fit_top.par.outputresolution = "custom"
    # Expressions, not written values: these follow the readout the Script TOP keeps
    # up to date, so a source resolution change needs no rebuild.
    fit_top.par.resolutionw.expr = "op('%s').par.Masksourcew" % master.path
    fit_top.par.resolutionh.expr = "op('%s').par.Masksourceh" % master.path
    fit_top.par.format = "mono8fixed"
    fit_top.bypass = not bool(fit.eval())

    # -- the output --------------------------------------------------------
    out = master.op("outmask")
    out_existed = out is not None
    if out is None:
        out = master.create(td.outTOP, "outmask")
    _at(out, master_xy("outmask"), keep_layout, out_existed)
    # PRESERVED, never recreated - an Out TOP IS a COMP output connector, and
    # destroying it disconnects whatever the project had wired to it.
    out.inputConnectors[0].connect(fit_top)

    print("2. seg_mask -> seg_fit -> outmask")
    print("   seg_mask format=mono8fixed, gated by `Segment` inside onCook")
    print("   seg_fit  fit=fill, resolution from Masksourcew/h (%dx%d), bypass=%s"
          % (int(master.par.Masksourcew.eval()), int(master.par.Masksourceh.eval()),
             fit_top.bypass))

    # -- the parameter callbacks -------------------------------------------
    # `allowCooking` and `bypass` are ATTRIBUTES, so nothing can bind an expression
    # to them - they have to be WRITTEN, here at build and again whenever a toggle
    # moves. The same pattern the filter's bypass and the group gating use.
    par_exec = master.op("seg_par_callbacks") or master.create(
        td.parameterexecuteDAT, "seg_par_callbacks")
    par_exec.nodeX, par_exec.nodeY = master_xy("seg_par_callbacks")
    par_exec.text = (
        "# Generated by tools/td_add_segmentation.py\n"
        "#\n"
        "# `bypass` is an ATTRIBUTE, not a parameter, so it cannot be bound to an\n"
        "# expression and is written on change instead - the same pattern the\n"
        "# filter's bypass and the group gating use.\n"
        "#\n"
        "# `Segment` is NOT handled here: `allowCooking` cannot be disabled on a\n"
        "# bare operator (measured - it raises), so the Script TOP checks that\n"
        "# toggle itself. It is still listed below so that switching it forces a\n"
        "# cook, or the mask would keep its last frame until something else\n"
        "# invalidated the operator.\n"
        "\n"
        "def onValueChange(par, prev):\n"
        "    comp = par.owner\n"
        "    fit = comp.op('seg_fit')\n"
        "    if fit is not None:\n"
        "        fit.bypass = not bool(comp.par.Maskfit.eval())\n"
        "    script = comp.op('seg_mask')\n"
        "    if script is not None:\n"
        "        script.cook(force=True)\n")
    par_exec.par.op = master.path
    par_exec.par.pars = "Segment Maskfit"
    par_exec.par.valuechange = True
    print("3. Segment and Maskfit wired through %s" % par_exec.name)

    # -- report ------------------------------------------------------------
    print()
    if not bool(on.eval()):
        print("   `Segment` is OFF, so `seg_mask` publishes black. Nothing writes to")
        print("   the buffer yet - visionhands/sidecar.py does not run segmentation.")
        print("   To see it work:")
        print("     ~/.venvs/visionhands/bin/python tools/segmentation_probe.py "
              "--write-only")
        print("   then switch Segment on.")
    else:
        script.cook(force=True)
        out.cook(force=True)
        print("   seg_mask %dx%d -> outmask %dx%d"
              % (script.width, script.height, out.width, out.height))
    print("=" * 70)


main()
