#!/usr/bin/env python
"""Optical flow: the read side, a TOP.

    RUN IT
        run("<repo>/tools/td_add_flow.py")

    or through the chain: tools/td_rebuild.py, layer "flow".

WHAT IT ADDS
    flow_map     a Script TOP reading the shared buffer
    outflow      the COMP's fifth output
    Streamflow   on its own Optical Flow page, with the accuracy
    Flowbuffer   on Advanced, beside the other two buffer paths

TWO FLOAT COMPONENTS, NOT ONE BYTE. Where the mask is `mono8fixed`, this is
`rg32float`: the red channel is the x displacement in pixels and the green the y. It is
full input resolution, so 720p is 7.2 MB a frame - a hundred and fifty times the mask -
which is why the stream is off by default.

WHAT THE VALUES MEAN, and it is the thing to get right before using them:

  * BACKWARD flow. MEASURED - content moving +6 px in x reads -5.53 - so the vector
    points from this frame back to where the content came from. That is what a warp
    wants and the opposite of "how did it move".
  * pixels of the INPUT image, not normalised.
  * TOP-LEFT origin, like the image, unlike every channel this component publishes.
    The y flip below moves the IMAGE into TouchDesigner's bottom-up convention but
    leaves the y COMPONENT alone: flipping one without the other gives a field that
    disagrees with the picture it describes.

Ref: appletd/flow.py, docs/BENCHMARKS.md, docs/BUILD_PLAN.md step 31.
"""

import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER_PATH = "/project1/appletd"

SCRIPT = "flow_map"
CALLBACKS = "flow_callbacks"
OUT = "outflow"
PAGE = "Optical Flow"
DEFAULT_FLOW_PATH = "/tmp/appletd_flow.buf"

CALLBACK_SOURCE = '''# Generated by tools/td_add_flow.py
import os
import sys

import numpy

%(resolver)s
_ROOT = _find_package_root(op(%(comp)r))
if _ROOT and _ROOT not in sys.path:
    sys.path.append(_ROOT)              # append, never insert

from appletd.maskbuf import MaskReader

# One reader per path, kept between cooks. Opening per cook would mmap and unmap 7 MB
# every frame.
_READERS = {}
# Two components, so a blank is (1, 1, 2). `copyNumpyArray` needs THREE dimensions.
_BLANK = numpy.zeros((1, 1, 2), dtype=numpy.float32)


def _reader(path):
    reader = _READERS.get(path)
    if reader is None:
        try:
            reader = MaskReader(path)
        except (OSError, ValueError):
            return None
        _READERS[path] = reader
    return reader


def onCook(scriptOp):
    comp = op.Appletd or scriptOp.parent()

    # The SAME toggle that puts `flow` on the sidecar's command line. What actually
    # stops the work is the `Tick` expression - `allowCooking` raises on a Script TOP
    # - and this branch is the one cook after the toggle changes, whose job is to
    # release the mmap so a project not using flow holds no handle on 7 MB.
    if hasattr(comp.par, "Streamflow") and not bool(comp.par.Streamflow.eval()):
        reader = _READERS.pop(str(comp.par.Flowbuffer.eval()), None)
        if reader is not None:
            reader.close()
        scriptOp.copyNumpyArray(_BLANK)
        return

    path = str(comp.par.Flowbuffer.eval()) if hasattr(comp.par, "Flowbuffer") else ""
    if not path:
        scriptOp.copyNumpyArray(_BLANK)
        return
    reader = _reader(path)
    if reader is None:
        scriptOp.copyNumpyArray(_BLANK)
        return

    try:
        frame = reader.read()
    except ValueError:
        _READERS.pop(path, None)
        scriptOp.copyNumpyArray(_BLANK)
        raise

    if frame is None:
        # Nothing published yet, or the writer won the race. HOLD the previous field.
        return
    if frame.components != 2:
        # A one-component buffer is a MASK. Reading it as flow would produce a
        # plausible wrong field rather than an error.
        scriptOp.copyNumpyArray(_BLANK)
        return

    # `[::-1]` flips the IMAGE into TouchDesigner's bottom-up convention. The y
    # COMPONENT is deliberately left alone - see the module docstring.
    array = numpy.frombuffer(frame.pixels, dtype=numpy.float32).reshape(
        frame.height, frame.width, frame.components)
    scriptOp.copyNumpyArray(numpy.ascontiguousarray(array[::-1]))
'''


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.streams import FLOW_ACCURACIES
    from appletd.td_layout import (
        OUTPUT_ORDER,
        PACKAGE_ROOT_SOURCE,
        ensure,
        keep_layout,
        master_xy,
    )

    comp = op(MASTER_PATH)
    if comp is None:
        print("no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    # ONE call, so `Keeplayout` reaches every operator this builder places.
    # Twenty-odd of them wrote nodeX/nodeY straight from the table, so
    # tidying the master network and switching the parameter on lasted
    # exactly until the next rebuild.
    keep = keep_layout(comp)

    print("=" * 70)
    print("flow: optical flow on %s" % comp.path)
    print("=" * 70)

    page = None
    advanced = None
    for existing in comp.customPages:
        if existing.name == PAGE:
            page = existing
        elif existing.name == "Advanced":
            advanced = existing
    if page is None:
        page = comp.appendCustomPage(PAGE)
    if advanced is None:
        print("FAIL no Advanced page - run tools/td_build_vision.py first")
        return

    have = {par.name for par in comp.customPars}
    if "Streamflow" not in have:
        toggle = page.appendToggle(
            "Streamflow", label="Optical Flow  (16-30 ms a frame)")[0]
        toggle.default = False
    if "Flowaccuracy" not in have:
        menu = page.appendMenu("Flowaccuracy", label="Accuracy")[0]
        menu.menuNames = list(FLOW_ACCURACIES)
        menu.menuLabels = ["%s  (%s)" % (name.capitalize(), note)
                           for name, note in zip(FLOW_ACCURACIES,
                                                 ("16.2 ms", "18.9 ms", "30.1 ms",
                                                  "slower still"), strict=True)]
        menu.default = "low"
    if "Flowbuffer" not in have:
        path = advanced.appendStr("Flowbuffer", label="Flow Buffer")[0]
        path.default = DEFAULT_FLOW_PATH
        path.val = DEFAULT_FLOW_PATH

    callbacks = ensure(comp, td.textDAT, CALLBACKS, master_xy(CALLBACKS), keep)
    callbacks.text = CALLBACK_SOURCE % {"comp": comp.path,
                                        "resolver": PACKAGE_ROOT_SOURCE}

    existed = comp.op(SCRIPT) is not None
    script = ensure(comp, td.scriptTOP, SCRIPT, master_xy(SCRIPT), keep)
    if not existed:
        for child in list(comp.children):
            if child.name.startswith(SCRIPT + "_callbacks") and child.valid:
                child.destroy()
    script.par.callbacks = callbacks.path
    # Two 32-bit float components - the x and y displacement. `mono8fixed` would
    # discard the sign and the magnitude both.
    script.par.format = "rg32float"
    script.color = (0.35, 0.45, 0.5)

    tick_page = None
    for existing in script.customPages:
        if existing.name == "Tick":
            tick_page = existing
            break
    if tick_page is None:
        tick_page = script.appendCustomPage("Tick")
    if not hasattr(script.par, "Tick"):
        tick_page.appendInt("Tick", label="Tick (drives the cook - do not set)")
    script.par.Tick.expr = "absTime.frame if op.Appletd.par.Streamflow else 0"
    script.par.Tick.readOnly = True

    out = ensure(comp, td.outTOP, OUT, master_xy(OUT), keep)
    out.inputConnectors[0].connect(script)
    # Pinned, and it matters more here than anywhere: `outflow` sorts BEFORE `outmask`
    # alphabetically, so without an explicit number it would insert itself in the
    # middle of the existing connectors and renumber two of them.
    out.par.connectorder = OUTPUT_ORDER[OUT]

    print("   %-11s rg32float, reading %s" % (SCRIPT, comp.par.Flowbuffer.eval()))
    print("   %-11s connector %d" % (OUT, int(out.par.connectorder.eval())))
    print("   Streamflow = %s, accuracy %s"
          % (bool(comp.par.Streamflow.eval()), comp.par.Flowaccuracy.eval()))
    print()
    print("   R is the x displacement in pixels, G the y. BACKWARD flow: the vector")
    print("   points back to where the content came from.")


main()
