"""The TouchDesigner side of the depth map: shared memory -> a TOP, plus the fit.

WHAT THIS BUILDS, inside /project1/vision:

    depth_map (Script TOP)  ->  depth_fit (Fit TOP)  ->  outdepth (Out TOP)
       reads the fp16 mmap,       undoes the              the COMP's second
       flips y, widens to         anisotropic stretch     TOP output
       float32

and a `Depth` page carrying the fit readout. Idempotent; run it any time.

THREE THINGS THAT MAKE THIS DIFFERENT FROM THE MASK, and each cost a measurement:

  * THE PAYLOAD IS FP16 and `copyNumpyArray` REFUSES IT - "Arrays with float data must
    be float32" (MEASURED, DESIGN.md 2.20). So the Script TOP widens: 406 KB in, 812
    KB out, one `astype` per frame. That is the price of the model's ~7,300 distinct
    levels, and it is worth paying - an 8-bit path would cap at 256 and quantise the
    pin solve to a sixth of its precision (DESIGN.md 2.22).
  * IT IS INVERSE DEPTH, and BIGGER MEANS NEARER. The model's graph divides by the
    frame's own maximum, so the raw map is not comparable between frames - a hand
    coming toward the lens darkens everything else. Nothing may be built on the raw
    numbers without pins. `Depthfit*` below is how a project finds out whether it has
    a usable fit, and `appletd/pins.py` is the argument.
  * THE FIT TRAVELS IN THE BUFFER'S AUX BLOCK, not on a parameter of its own, because
    it is solved from ONE frame and is meaningless against any other. The Script TOP
    unpacks it and writes it onto read-only parameters so a project can gate on it.

WHAT THIS DOES NOT DO. It does not convert to metres. `Z = 1 / (alpha*d + beta)` is
two parameters and a reciprocal, which is a GLSL TOP or an expression on whatever is
reading it - and doing it here would mean choosing a clamp and a colour map on
somebody else's behalf, on the main thread, for every project whether it wants metres
or not. `Depthfitalpha` and `Depthfitbeta` are published for exactly that.

Ref: docs/DEPTH.md (first run, and the pins), design/DESIGN.md 2.22,
     appletd/depth.py, appletd/pins.py, tools/td_add_segmentation.py.
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/appletd"
MASTER_PATH = "/project1/vision"

PAGE = "Depth"

# How many pin rows exist on the page. Eight, because the reference implementation's
# argument is "two minimum, three to survive an occlusion" and past about five the
# extra conditioning is nil - so this is generous rather than a limit anybody will
# meet, and every unused row is disabled rather than absent.
#
# WHY NOT A TOUCHDESIGNER SEQUENCE, which is what was asked for. `Page.appendSequence`
# creates the header parameter and the `Sequence` object, but nothing appended
# afterwards joins its block: `blockPars` stays empty and `numBlocks = 1` raises "Could
# not set numBlocks... check for potential name conflicts". Tried 0-based names
# (`Pin0m`), 1-based, appending before the header, appending after it, and
# `insertBlock(0)` - all four fail the same way, so custom sequences appear not to be
# constructible from Python in this build. Fixed rows with a count that greys out the
# unused ones give the same behaviour through a mechanism that demonstrably works.
MAX_PINS = 8

# The defaults, from apple-vision-examples/examples/depth/depth.py. Placed at the edges
# and the bottom because that is where a person in front of a webcam usually is NOT,
# and the distances are a plausible room rather than a measurement - the example says
# so and so does docs/DEPTH.md. They are a starting point to dial in.
EXAMPLE_PINS = ((0.06, 0.30, 2.5), (0.94, 0.30, 2.4), (0.50, 0.96, 1.1))

# Rows past the example's three. Spread across the frame so that raising the count
# lands a pin somewhere useful rather than on top of another one, and switched off by
# default because a pin nobody has measured is worse than no pin.
SPARE_PINS = ((0.06, 0.70, 2.5), (0.94, 0.70, 2.4), (0.50, 0.50, 1.8),
              (0.25, 0.10, 3.0), (0.75, 0.10, 3.0))

# Parameters this builder used to own and no longer does. Empty today, and kept
# because removing the code that creates a parameter does not remove the parameter -
# `Segment` sat on a page driving nothing for two commits before anybody noticed
# (docs/BUILD_PLAN.md, TouchDesigner facts). A retire table from the start costs
# nothing and is the only thing that cleans one up.
RETIRED_PARS: dict[str, str] = {}

CALLBACK_SOURCE = '''# Generated by tools/td_add_depth.py
#
# Reads the shared depth buffer and publishes it as a TOP. One `os.stat`, one coherent
# read of ~400 KB, one y-flip, one fp16 -> float32 widening, one `copyNumpyArray`.
import sys

REPO_ROOT = %(repo)r
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)

import numpy

from appletd.maskbuf import MaskReader
from appletd.pins import unpack

# The red a pin is drawn in. Full red and nothing else, so it cannot be mistaken for a
# depth value however the map is being coloured downstream.
PIN_RGB = (1.0, 0.0, 0.0)
ARM = 6                 # half-length of a cross arm, in map pixels
GAP = 2                 # pixels left clear at the centre, so the pin's own value shows

# The reader lives in MODULE GLOBALS and never in operator storage. TouchDesigner
# PICKLES operator storage into the .toe on save, and an `mmap` cannot be pickled -
# which is exactly how this project lost the ability to save on 2026-08-21.
_READERS = {}

# 16x16, and the SIZE is the diagnostic: a shape nothing else in this path produces,
# so "the buffer has never been read" is answerable at a glance. The mask's blank was
# once the same size as a real mask and that turned a five-minute diagnosis into a
# long one (DESIGN.md 2.21).
_BLANK = numpy.zeros((16, 16, 1), dtype=numpy.float32)


def _reader(path):
    """One MaskReader per path, cached. None if the file is not there yet."""
    reader = _READERS.get(path)
    if reader is not None:
        return reader
    try:
        reader = MaskReader(path)
    except (OSError, ValueError):
        # OSError: not there yet - the normal state before the sidecar starts.
        # ValueError: there but too small to hold a header, i.e. mid-creation.
        return None
    _READERS[path] = reader
    return reader


def onCook(scriptOp):
    comp = op.Vision or scriptOp.parent()

    # `Streamdepth` - the SAME toggle that puts `depth` on the sidecar's command line.
    # What actually stops the work is the `Tick` expression going constant (see the
    # builder); this branch runs on the one cook after the toggle changes, and releases
    # the mmap so a project not using depth holds no file handle.
    if hasattr(comp.par, "Streamdepth") and not bool(comp.par.Streamdepth.eval()):
        reader = _READERS.pop(str(comp.par.Depthbuffer.eval()), None)
        if reader is not None:
            reader.close()
        scriptOp.copyNumpyArray(_BLANK)
        return

    path = str(comp.par.Depthbuffer.eval()) if hasattr(comp.par, "Depthbuffer") else ""
    reader = _reader(path) if path else None
    if reader is None:
        scriptOp.copyNumpyArray(_BLANK)
        return

    try:
        frame = reader.read()
    except ValueError:
        # A non-zero wrong magic, or a version this reader does not speak. Drop the
        # reader so a corrected path is picked up, and let it raise - it is a wiring
        # mistake, not a race, and swallowing it would show a blank for ever.
        _READERS.pop(path, None)
        scriptOp.copyNumpyArray(_BLANK)
        raise

    if frame is None:
        # Nothing published yet, or the writer won the race. HOLD the previous frame
        # by returning without copying, which is right for a depth map and is why the
        # reader never blocks.
        return

    # fp16 -> float32, because `copyNumpyArray` REFUSES float16: "Arrays with float
    # data must be float32" (MEASURED). `[::-1]` is the y flip - the model's map has
    # its origin top-left and TouchDesigner's TOP arrays are bottom-up. The `astype`
    # already makes a new contiguous array, so no `ascontiguousarray` is needed on top.
    fit = unpack(frame.aux)
    raw = frame.as_numpy()[::-1].astype(numpy.float32)
    published, units = _corrected(comp, raw, fit)

    # THE PINS, into the array before it is published rather than as a second publish.
    # MEASURED 2026-08-22: drawing used to cost 1.4176 ms against 0.4991 without,
    # because it corrected the map twice and called `copyNumpyArray` twice - once with
    # the mono map and again with the RGB one. ONE correction, ONE upload, and the cost
    # is the widening to three channels and nothing else.
    #
    # Drawn from the PARAMETERS, not the solve: they show where the pins are
    # CONFIGURED. `Depthfitpins` says how many the solve used, and the two differ
    # whenever a pin has moved without a restart, because the solve is a launch flag.
    if bool(getattr(comp.par, "Depthpinsdraw", None) and comp.par.Depthpinsdraw.eval()):
        published = _with_pins(comp, published)

    # `-1` for the component count, so one line serves the mono map and the RGB one.
    scriptOp.copyNumpyArray(published.reshape(frame.height, frame.width, -1))
    _write_str(comp, "Depthunits", units)

    # The source geometry, for the Fit TOP.
    if hasattr(comp.par, "Depthsourcew") and frame.source_width:
        if int(comp.par.Depthsourcew.eval()) != frame.source_width:
            comp.par.Depthsourcew = frame.source_width
        if int(comp.par.Depthsourceh.eval()) != frame.source_height:
            comp.par.Depthsourceh = frame.source_height

    # THE FIT's numbers, onto read-only parameters. Published as well as APPLIED,
    # because a consumer that wants true metres rather than the windowed map needs
    # alpha and beta - `Z = 1 / (alpha*d + beta)`.
    _write(comp, "Depthfitalpha", fit.get("alpha", 0.0))
    _write(comp, "Depthfitbeta", fit.get("beta", 0.0))
    _write(comp, "Depthfitpins", fit.get("used", 0.0))
    _write(comp, "Depthfitresidual", fit.get("worst_residual_m", 0.0))
    # 1 only when the residual MEANS something. Two pins always fit a line exactly, so
    # a residual of 0.000 from two pins reads as a perfect fit while checking nothing -
    # this is the flag that says which it is (appletd/pins.py).
    _write(comp, "Depthfitchecked", fit.get("residual_is_a_check", 0.0))


def _corrected(comp, raw, fit):
    """-> `(what to publish, a word for what it is)`.

    THIS IS THE PORT OF `p` FROM apple-vision-examples/examples/depth/depth.py, and
    without it `Depthpinson` changed nothing anybody could see. The solve was running
    and its numbers were published, but the PIXELS were the raw map in both states -
    so the one observable consequence of pinning, that the image stops breathing, was
    missing. The example switches what it draws; so does this now.

    Two states, and both end with NEAR BRIGHT so that toggling shows a change in
    STABILITY rather than a change in palette - which is the example's argument and
    the reason the convention is kept identical:

      pins off, or no usable fit
          the model's own numbers. 0..1 already, because the graph divided by the
          frame's maximum - which is exactly why it breathes: the divisor moves every
          frame, so a stationary wall swings 54%% while nothing in the room moves.

      pins on with a fit
          metres, mapped onto a FIXED window. `Depthwindownear` reads 1.0 and
          `Depthwindowfar` reads 0.0, so a wall at 2 m sits at the same value in every
          frame no matter what walks in front of the lens. That stability IS the
          point of pinning, and a fixed window is the only way to see it.

    `Depthpinson` is checked HERE as well as on the command line, deliberately. On the
    command line it decides whether the sidecar solves at all - a launch flag. Here it
    decides whether the fit is applied, which takes effect at once. So the toggle feels
    like the example's `p` rather than like something that needs a restart, and if
    there is no fit in the buffer it correctly falls back whatever the toggle says.
    """
    on = not hasattr(comp.par, "Depthpinson") or bool(comp.par.Depthpinson.eval())
    if not on or not fit or not fit.get("alpha"):
        return raw, "relative, per-frame range"

    near = float(comp.par.Depthwindownear.eval())
    far = float(comp.par.Depthwindowfar.eval())
    inverse = fit["alpha"] * raw + fit["beta"]
    # Clamped before the reciprocal, or a `d` outside the range the pins covered drives
    # alpha*d + beta through zero and one infinity poisons the whole map. The same
    # clamp `appletd/pins.py` uses, and for the same reason.
    metres = 1.0 / numpy.clip(inverse, 1.0 / 60.0, 1.0 / 0.05)
    span = max(far - near, 1e-6)
    windowed = 1.0 - numpy.clip((metres - near) / span, 0.0, 1.0)
    return (windowed.astype(numpy.float32),
            "metres, fixed %%.2f-%%.2f m window" %% (near, far))


def _write_str(comp, name, value):
    """Set a string readout, only when it changed - see `_write`."""
    par = getattr(comp.par, name, None)
    if par is not None and par.eval() != value:
        par.val = value


def _active_pins(comp):
    """The pins the panel currently describes, as `[(x, y, metres)]`.

    Reads `Depthpincount` rows and no more, so a row left over from a higher count is
    ignored rather than quietly included - the greyed-out rows on the page and the list
    used here have to agree or the drawing lies about what is configured.
    """
    if not hasattr(comp.par, "Depthpincount"):
        return []
    if hasattr(comp.par, "Depthpinson") and not bool(comp.par.Depthpinson.eval()):
        return []
    out = []
    for index in range(1, int(comp.par.Depthpincount.eval()) + 1):
        try:
            out.append((float(getattr(comp.par, "Depthpin%%dx" %% index).eval()),
                        float(getattr(comp.par, "Depthpin%%dy" %% index).eval()),
                        float(getattr(comp.par, "Depthpin%%dm" %% index).eval())))
        except AttributeError:
            break
    return out


def _with_pins(comp, grey):
    """`(h, w)` corrected map -> `(h, w, 3)` with a red cross at each configured pin.

    A CROSS with a gap at the centre, not a filled dot: the point of looking is to see
    what the pin is sitting on, and a dot hides exactly the pixels the solve samples.
    The arms are in MAP pixels, so a pin looks the same size whatever the Fit TOP is
    scaling to.

    Y IS ALREADY FLIPPED in `grey`, so a pin at y = 0.96 - near the bottom of the frame
    as you see it - is near the TOP of this array. Getting that wrong would put every
    pin on the wrong side of the image and still look entirely plausible.
    """
    pins = _active_pins(comp)
    if not pins:
        # Still three channels: the format is switched by the parameter callback and a
        # one-channel array published into an RGBA format would come back as red.
        return numpy.repeat(grey[:, :, numpy.newaxis], 3, axis=2)
    height, width = grey.shape[:2]
    rgb = numpy.repeat(grey[:, :, numpy.newaxis], 3, axis=2)
    for x, y, _metres in pins:
        cx = int(min(max(x, 0.0), 1.0) * (width - 1))
        cy = int((1.0 - min(max(y, 0.0), 1.0)) * (height - 1))
        for offset in range(GAP, ARM + 1):
            for px, py in ((cx - offset, cy), (cx + offset, cy),
                           (cx, cy - offset), (cx, cy + offset)):
                if 0 <= px < width and 0 <= py < height:
                    rgb[py, px] = PIN_RGB
    return numpy.ascontiguousarray(rgb)


def _write(comp, name, value):
    """Set a readout parameter, only when it changed.

    Only when it CHANGED: writing a parameter dirties everything that depends on it,
    and four unconditional writes a frame would re-cook every expression watching them
    sixty times a second for numbers that mostly do not move.
    """
    par = getattr(comp.par, name, None)
    if par is not None and par.eval() != value:
        par.val = value
'''


PAR_CALLBACK_SOURCE = '''# Generated by tools/td_add_depth.py
#
# `bypass` and the row enables are ATTRIBUTES, not parameters, so they cannot be bound
# to an expression and are written on change instead - the same pattern the filter's
# bypass and the group gating use.
#
# `Streamdepth` is NOT handled here: `allowCooking` cannot be disabled on a bare
# operator (measured - it raises), so the Script TOP checks that toggle itself. It is
# listed in `pars` so that switching it forces a cook.
MAX_PINS = %(max_pins)d


def onValueChange(par, prev):
    comp = par.owner
    fit = comp.op('depth_fit')
    if fit is not None:
        fit.bypass = not bool(comp.par.Depthfit.eval())

    # Grey out the rows past the count, and all of them when pins are off. This is what
    # makes a fixed set of rows behave like an extendable list: the ones that are not
    # in use cannot be edited, so the page never shows a pin the solve is ignoring.
    on = bool(comp.par.Depthpinson.eval()) if hasattr(comp.par, 'Depthpinson') else True
    count = int(comp.par.Depthpincount.eval())
    for index in range(1, MAX_PINS + 1):
        live = on and index <= count
        for suffix in ('x', 'y', 'm'):
            row = getattr(comp.par, 'Depthpin%%d%%s' %% (index, suffix), None)
            if row is not None:
                row.enable = live

    script = comp.op('depth_map')
    if script is not None:
        # The FORMAT follows the visualisation, because red needs somewhere to live: a
        # mono map has one channel and no amount of drawing puts a colour in it. Set
        # here rather than inside onCook - changing a parameter from within the cook it
        # would affect is a race.
        want = 'rgba32float' if bool(comp.par.Depthpinsdraw.eval()) else 'mono32float'
        if script.par.format.eval() != want:
            script.par.format = want
        fit_top = comp.op('depth_fit')
        if fit_top is not None and fit_top.par.format.eval() != want:
            fit_top.par.format = want
        script.cook(force=True)
'''


def _page(comp, name):
    """Find or create a custom page. TRAP: `appendCustomPage` with an existing name
    makes a SECOND page of that name, so the existing one is looked up first."""
    for existing in comp.customPages:
        if existing.name == name:
            return existing
    return comp.appendCustomPage(name)


def _at(node, xy, keep, existed):
    from appletd.td_layout import placement
    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.td_layout import master_xy

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("depth: shared memory -> a TOP, in %s" % master.path)
    print("=" * 70)

    keep_layout = bool(master.par.Keeplayout.eval()) \
        if hasattr(master.par, "Keeplayout") else False

    # -- retire, then append only what is absent ---------------------------
    for stale_name in RETIRED_PARS:
        stale = getattr(master.par, stale_name, None)
        if stale is not None:
            stale.destroy()
            print("   retired `%s` - %s" % (stale_name, RETIRED_PARS[stale_name]))

    # `append*` on an EXISTING parameter resets it, and the reset fires a deferred
    # callback that outlives any write-it-back fix (DESIGN.md 2.17). So: only what is
    # absent, and nothing that exists is touched except its `default`.
    page = _page(master, PAGE)
    existing = {par.name: par for par in master.customPars}

    fit_par = existing.get("Depthfit")
    if fit_par is None:
        fit_par = page.appendToggle("Depthfit", label="Fit Map To Source")[0]
        fit_par.val = True
    fit_par.default = True

    # -- the pins -----------------------------------------------------------
    # A COUNT plus fixed rows, with the unused ones greyed out - which behaves like an
    # extendable list and is not one. See MAX_PINS for why: TouchDesigner's own
    # Sequence could not be built from Python in this version, and four different
    # orderings of `appendSequence` all left `blockPars` empty.
    on_par = existing.get("Depthpinson")
    if on_par is None:
        on_par = page.appendToggle(
            "Depthpinson", label="Use Pins  (metric depth; restart to apply)")[0]
        on_par.val = True
    on_par.default = True

    count_par = existing.get("Depthpincount")
    if count_par is None:
        count_par = page.appendInt(
            "Depthpincount", label="Pins  (2 min, 3+ for a real residual)")[0]
        count_par.val = len(EXAMPLE_PINS)
    count_par.default = len(EXAMPLE_PINS)
    # Clamped rather than merely defaulted: a count past the rows that exist would
    # silently drop pins the panel appears to be showing.
    count_par.min, count_par.max = 0, MAX_PINS
    count_par.clampMin = count_par.clampMax = True

    # THE WINDOW the corrected map is drawn on. Defaults are the example's own
    # `--window 0.4,3.0`. It has to be a FIXED range and not the frame's own, because
    # a per-frame range is exactly the breathing that pinning removes - see
    # `_corrected` in the callback.
    for name, label, default in (("Depthwindownear", "Window Near (m)  -> 1.0", 0.4),
                                 ("Depthwindowfar", "Window Far (m)  -> 0.0", 3.0)):
        par = existing.get(name)
        if par is None:
            par = page.appendFloat(name, label=label)[0]
            par.val = default
        par.default = default
        par.min, par.max = 0.05, 60.0
        par.clampMin = par.clampMax = True

    units_par = existing.get("Depthunits")
    if units_par is None:
        units_par = page.appendStr("Depthunits", label="Output Is")[0]
        units_par.val = "relative, per-frame range"
    # READ-ONLY, and it is the answer to "am I looking at metres or not". Written by
    # the Script TOP every time the mode changes, because a units change that nothing
    # announces is the worst kind: the image still looks like a depth map.
    units_par.readOnly = True

    draw_par = existing.get("Depthpinsdraw")
    if draw_par is None:
        draw_par = page.appendToggle(
            "Depthpinsdraw", label="Visualize Pins  (draws in red, output becomes RGB)")[0]
        draw_par.val = False
    draw_par.default = False

    rows = EXAMPLE_PINS + SPARE_PINS
    for index in range(1, MAX_PINS + 1):
        x_default, y_default, m_default = rows[index - 1]
        for suffix, label, default, low, high in (
                ("x", "Pin %d  x" % index, x_default, 0.0, 1.0),
                ("y", "Pin %d  y" % index, y_default, 0.0, 1.0),
                ("m", "Pin %d  metres" % index, m_default, 0.05, 60.0)):
            name = "Depthpin%d%s" % (index, suffix)
            par = existing.get(name)
            if par is None:
                par = page.appendFloat(name, label=label)[0]
                par.val = default
            par.default = default
            # NORMALISED x and y, clamped, because `pins.parse_pins` refuses anything
            # outside 0..1 - and a parameter that can hold a value the solve will
            # reject is a control that fails at startup instead of at the slider.
            par.min, par.max = low, high
            par.clampMin = par.clampMax = True

    print("1a. pins: %d rows, %d active, Use Pins=%s, Visualize=%s"
          % (MAX_PINS, int(count_par.eval()), bool(on_par.eval()),
             bool(draw_par.eval())))
    print("    defaults are the example's: %s"
          % " ".join("%g,%g,%g" % row for row in EXAMPLE_PINS))
    print("    Use Pins ON applies the fit to the PIXELS - metres on a fixed "
          "%.2f-%.2f m window," % (float(master.par.Depthwindownear.eval()),
                                   float(master.par.Depthwindowfar.eval())))
    print("    which is the port of `p` from the example. OFF publishes the model's "
          "own numbers.")

    # The READOUTS. Written by the Script TOP from the buffer's aux block, read-only
    # because they are a report and not a setting - a settable one would silently
    # fight the solve every frame.
    readouts = (
        ("Depthsourcew", "Source Width (from the buffer)", 1280),
        ("Depthsourceh", "Source Height (from the buffer)", 720),
    )
    for name, label, default in readouts:
        par = existing.get(name)
        if par is None:
            par = page.appendInt(name, label=label)[0]
            par.val = default
        par.default = default
        par.readOnly = True

    floats = (
        ("Depthfitalpha", "Fit alpha  (1/Z = alpha*d + beta)"),
        ("Depthfitbeta", "Fit beta"),
        ("Depthfitresidual", "Worst Residual (m)"),
    )
    for name, label in floats:
        par = existing.get(name)
        if par is None:
            par = page.appendFloat(name, label=label)[0]
            par.val = 0.0
        par.default = 0.0
        par.readOnly = True

    for name, label in (("Depthfitpins", "Pins Used"),
                        ("Depthfitchecked", "Residual Is A Check")):
        par = existing.get(name)
        if par is None:
            par = page.appendInt(name, label=label)[0]
            par.val = 0
        par.default = 0
        par.readOnly = True

    print("1. `%s` page: Depthfit=%s, %d readouts"
          % (PAGE, bool(fit_par.eval()), len(readouts) + len(floats) + 2))
    print("   from td_build_vision.py: Streamdepth=%s, Depthbuffer=%r"
          % (getattr(master.par, "Streamdepth", None)
             and bool(master.par.Streamdepth.eval()),
             getattr(master.par, "Depthbuffer", None)
             and master.par.Depthbuffer.eval()))

    # -- the callbacks DAT -------------------------------------------------
    callbacks = master.op("depth_callbacks") or master.create(td.textDAT,
                                                             "depth_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("depth_callbacks")
    callbacks.text = CALLBACK_SOURCE % {"repo": REPO_ROOT}

    # -- the Script TOP ----------------------------------------------------
    script = master.op("depth_map")
    script_existed = script is not None
    if script is None:
        script = master.create(td.scriptTOP, "depth_map")
        # Creating a Script TOP auto-docks its own callbacks DAT. Destroy it, or two
        # DATs claim the same job and only one is the generated one.
        for child in list(master.children):
            if child.name.startswith("depth_map_callbacks") and child.valid:
                child.destroy()
    _at(script, master_xy("depth_map"), keep_layout, script_existed)
    script.par.callbacks = callbacks.path
    # `mono32float`: one 32-bit float per pixel. The payload is fp16 and this is the
    # nearest float format TouchDesigner offers - `mono16float` would be exact, but
    # `copyNumpyArray` refuses float16 input, so the array is float32 by the time it
    # gets here and asking the GPU to narrow it again would lose the precision twice.
    script.par.format = "mono32float"
    script.color = (0.3, 0.4, 0.55)

    # THE THING THAT MAKES IT COOK. A Script TOP with no input is never dirtied, so it
    # cooks once and serves that texture for ever - there is no Cook Type parameter to
    # fix it with (MEASURED, DESIGN.md 2.21, and it cost an afternoon on the mask).
    # A custom parameter whose value changes each frame is what dirties it, gated on
    # the toggle so the expression goes constant when depth is off.
    tick_page = None
    for existing_page in script.customPages:
        if existing_page.name == "Tick":
            tick_page = existing_page
            break
    if tick_page is None:
        tick_page = script.appendCustomPage("Tick")
    if not hasattr(script.par, "Tick"):
        tick_page.appendInt("Tick", label="Tick (drives the cook - do not set)")
    script.par.Tick.expr = "absTime.frame if op.Vision.par.Streamdepth else 0"
    script.par.Tick.readOnly = True

    # -- the Fit TOP -------------------------------------------------------
    fit_top = master.op("depth_fit")
    fit_existed = fit_top is not None
    if fit_top is None:
        fit_top = master.create(td.fitTOP, "depth_fit")
    _at(fit_top, master_xy("depth_fit"), keep_layout, fit_existed)
    fit_top.inputConnectors[0].connect(script)
    # `fill` is the NON-UNIFORM stretch, which is the correction needed: the model is
    # 518x392 (1.32:1) and a webcam is 1.78:1, and `crop = fill` on the request side
    # squashed the whole frame in - so the map covers exactly the pixels you can see
    # and stretching it back is exact rather than approximate.
    fit_top.par.fit = "fill"
    fit_top.par.outputresolution = "custom"
    fit_top.par.resolutionw.expr = "op('%s').par.Depthsourcew" % master.path
    fit_top.par.resolutionh.expr = "op('%s').par.Depthsourceh" % master.path
    fit_top.par.format = "mono32float"
    fit_top.bypass = not bool(fit_par.eval())

    out = master.op("outdepth")
    out_existed = out is not None
    if out is None:
        out = master.create(td.outTOP, "outdepth")
    _at(out, master_xy("outdepth"), keep_layout, out_existed)
    # PRESERVED, never recreated - an Out TOP IS a COMP output connector.
    out.inputConnectors[0].connect(fit_top)

    print("2. depth_map -> depth_fit -> outdepth")
    print("   depth_map format=mono32float (fp16 in, widened - copyNumpyArray "
          "refuses float16)")
    print("   depth_fit  fit=fill, resolution from Depthsourcew/h (%dx%d), bypass=%s"
          % (int(master.par.Depthsourcew.eval()),
             int(master.par.Depthsourceh.eval()), fit_top.bypass))

    # -- the parameter callbacks -------------------------------------------
    par_exec = master.op("depth_par_callbacks") or master.create(
        td.parameterexecuteDAT, "depth_par_callbacks")
    par_exec.nodeX, par_exec.nodeY = master_xy("depth_par_callbacks")
    par_exec.text = PAR_CALLBACK_SOURCE % {"max_pins": MAX_PINS}
    par_exec.par.op = master.path
    par_exec.par.pars = ("Streamdepth Depthfit Depthpincount Depthpinson "
                         "Depthpinsdraw")
    par_exec.par.valuechange = True
    print("3. Streamdepth and Depthfit wired through %s" % par_exec.name)

    # -- report ------------------------------------------------------------
    print()
    on = getattr(master.par, "Streamdepth", None)
    if on is None or not bool(on.eval()):
        print("   `Streamdepth` is OFF, so `depth_map` publishes blank.")
        print("   FIRST RUN? The model is 47 MB and is not in this repo:")
        print("     ./tools/fetch_models.sh")
        print("   Check it with no camera and no TouchDesigner:")
        print("     ~/.venvs/appletd/bin/python tools/depth_probe.py")
        print("   Then switch Streamdepth on and press Active. docs/DEPTH.md has")
        print("   the pins, which are what turn the map into metres.")
    else:
        print("   `Streamdepth` is on. The map is RELATIVE and bigger means NEARER")
        print("   until pins are set - `Depthfitpins` says how many are in use, and")
        print("   `Depthfitchecked` says whether the residual means anything.")
    print("=" * 70)


main()
