#!/usr/bin/env python
"""Add the derived-attributes Script CHOP to the appletd COMP.

Paste into a Text DAT, Run Script. Idempotent.

Adds `derive_chop` (a Script CHOP) and `derive_callbacks` (its DAT) inside
/project1/appletd/hands, reading the FILTERED landmarks. The CHOP is a thin wrapper:
it reads its input into a dict, calls `appletd.derive.derive()`, and writes the
result. All the arithmetic lives in the repo, where 36 tests assert it against
synthetic hands (docs/ATTRIBUTES.md).

This is the stateless half. Velocity, filters, the Schmitt latches, edge pulses
and debounce are native CHOPs, added separately - see the implementation section
of docs/ATTRIBUTES.md for why memory stays out of Python.

IT IS THE MOST EXPENSIVE SINGLE OPERATOR IN THE COMP, and the reason is worth
knowing before editing the callback. MEASURED per cook at 87 output channels:

    reading the input into a dict   0.0610 ms   (141 channels)
    derive() itself                 0.0424
    the eight Params reads          0.0136
    the thirteen group toggles      0.0043
    sorting the output names        0.0035
    ------------------------------
    accounted                       0.1248
    the whole operator              0.2391

Most of the 0.11 ms difference was `clear()` plus 87 `appendChan()` calls, every
frame, to arrive at the identical 87 channels. MEASURED directly, in a scratch
Script CHOP with the same 87 channels and 40 repetitions per cook:

    clear() and 87 appendChan()              0.0681 ms
    87 writes into existing channels         0.0070
    the guard that decides between them      0.0041
    ------------------------------
    saved per cook                           0.0570

The channel list is a pure function of which GROUPS are enabled, so it is cached on
the operator and rebuilt only when it changes. The remaining ~0.05 ms of the gap is
the Script CHOP's own framework overhead, which is not ours to remove.
"""

import os
import sys
from dataclasses import fields

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# The master COMP holds every parameter; the hands STREAM holds this
# network. Both are named, because this script writes to both.
MASTER_PATH = "/project1/appletd"
COMP_PATH = MASTER_PATH + "/hands"

CALLBACK_SOURCE = '''# Generated by tools/td_add_derive.py
#
# A thin wrapper. Everything computed here is defined in docs/ATTRIBUTES.md and
# tested in appletd/tests/test_derive.py, which needs no TouchDesigner at
# all - which is the entire reason the maths lives in Python rather than in a
# hundred native operators of channel-alignment gymnastics.
import os
import sys

# WHERE THE PACKAGE IS, and the order matters.
#
# BUILT_AT is the checkout this DAT was generated from. `Installroot` is where the
# Install button put a copy. The checkout WINS WHEN IT EXISTS, which is the opposite
# of what looks obvious and is the point: on the machine that built this file, the
# repo is the source of truth and the installed copy may be older. Preferring the
# install would mean a developer silently running stale code - the two-copies hazard
# that `Sourceversion` exists to catch one layer up.
#
# On anybody else's machine BUILT_AT does not exist, so `Installroot` is used - which
# is what makes a shipped .tox work at all. Before 2026-08-23 this was a baked
# absolute path and nothing else, so a .tox carried one person's home directory and
# failed at its first cook everywhere else.
BUILT_AT = %(repo)r
_COMP_PATH = %(comp_for_root)r


def _package_root():
    """The directory containing `appletd`, or raise saying what to do about it."""
    tried = [BUILT_AT]
    comp = op(_COMP_PATH)
    if comp is not None:
        par = getattr(comp.par, "Installroot", None)
        if par is not None:
            tried.append(str(par.eval()))
    for root in tried:
        if root and os.path.isdir(os.path.join(root, "appletd")):
            return root
    raise RuntimeError(
        "cannot find the `appletd` package. Looked in %%s. Press Install on the "
        "Vision page, or point `Installroot` at a checkout." %% ", ".join(
            repr(t) for t in tried if t))


REPO_ROOT = _package_root()
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)          # append, never insert

from dataclasses import fields

from appletd.derive import ALL_GROUPS, Params, derive


def _params(comp):
    """Read the COMP's parameters, falling back to the dataclass defaults.

    Built by iterating `dataclasses.fields(Params)` rather than by naming each one.
    The hand-written version had drifted: it listed eight of the nine fields that
    existed, so `overlapthreshold` was silently stuck at its default however the
    panel was set - and adding a field to `Params` would have made two more.

    getattr rather than direct access, so a COMP built before a parameter existed
    still cooks rather than erroring on every frame.
    """
    values = {}
    for spec in fields(Params):
        par = getattr(comp.par, spec.name.capitalize(), None)
        if par is not None:
            values[spec.name] = float(par.eval())
    return Params(**values)


def _groups(comp):
    """Only the enabled groups, so a disabled one costs nothing in here either."""
    enabled = []
    for group in ALL_GROUPS:
        p = getattr(comp.par, group.capitalize(), None)
        if p is None or p.eval():
            enabled.append(group)
    return frozenset(enabled)


# The channel names this operator built last, cached on the operator itself.
#
# WHY: rebuilding the channel list was the largest removable cost in this CHOP.
# MEASURED, per cook, at 87 output channels: reading the input dict 0.0610 ms,
# derive() itself 0.0424, the parameters 0.0179, the sort 0.0035 - and the whole
# operator 0.2391. `clear()` plus 87 `appendChan()` calls accounts for 0.0681 of the
# gap, measured directly; writing the values into channels that already exist costs
# 0.0070, and the guard below 0.0041. So 0.0570 ms per cook, every frame, to arrive
# at exactly the same 87 channels.
#
# The name list is a pure function of which GROUPS are enabled, so it changes only
# when a toggle moves.
#
# Operator STORAGE rather than a module global: a scheduled callback in this project
# has already been observed reaching a different module object for the same DAT, and
# a stale cache here would write values onto the wrong channels.
#
# The property this depends on, MEASURED rather than assumed: a Script CHOP's
# channels PERSIST between cooks. Only the first cook after a rebuild starts with
# none, and `len(scriptOp.chans())` is how to tell - `numChans` raises mid-cook.
_CACHE_KEY = "derive_channel_names"


def onCook(scriptOp):
    # Not time-sliced. A Script CHOP defaults to Time Slice mode, where editing
    # numSamples is unsupported - TD warned about it on every cook - and where
    # the sample count per frame varies with the cook rate. This CHOP publishes a
    # SNAPSHOT of one frame's channels, so one fixed sample is what it is, and
    # the native latch bank downstream then sees a plain 1-sample CHOP with no
    # rate negotiation of its own to get wrong.
    scriptOp.isTimeSlice = False
    if not scriptOp.inputs:
        scriptOp.clear()
        scriptOp.store(_CACHE_KEY, ())
        return
    source = scriptOp.inputs[0]
    # One dict build per cook. 137 reads, which is the cheap part - the
    # alternative was aligning channel names across dozens of native operators.
    values = {chan.name: chan[0] for chan in source.chans()}

    # `op.Appletd`, not `scriptOp.parent()`: the parameters live on the MASTER COMP
    # and this Script CHOP lives in the hands STREAM, one level below it. The
    # shortcut is depth-independent, so moving this operator cannot silently start
    # reading a COMP that has no such parameters - which reads as every group being
    # enabled, because `_groups` treats a missing parameter as "on".
    comp = op.Appletd
    if comp is None:
        # Nothing to read: publish the full attribute set rather than nothing, so a
        # broken shortcut is a wrong VALUE somewhere rather than a channel list that
        # vanishes and breaks every reference downstream (DESIGN.md 6.2).
        comp = scriptOp.parent()
    out = derive(values, _params(comp), _groups(comp))

    names = tuple(sorted(out))
    # The LIVE channel count as well as the cache: the cache says what WE built, the
    # count says what the operator actually has, and they disagree whenever anything
    # else cleared the CHOP - a recompile, a builder rebuild, or the first cook after
    # either. A cache trusted alone would write 87 values onto zero channels.
    #
    # TRAP, measured: `scriptOp.numChans` RAISES inside onCook - "numChans is
    # unavailable for this CHOP while it is cooking". `len(scriptOp.chans())` gives
    # the same number and is available. Also measured, and the property this whole
    # cache depends on: a Script CHOP's channels DO persist between cooks; only the
    # first cook after a rebuild starts empty.
    existing = scriptOp.chans()
    if len(existing) != len(names) or scriptOp.fetch(_CACHE_KEY, None) != names:
        scriptOp.clear()
        scriptOp.numSamples = 1
        for name in names:
            scriptOp.appendChan(name)
        built = tuple(chan.name for chan in scriptOp.chans())
        if built != names:
            # The zip below pairs by POSITION, so a channel order that does not
            # match `names` would put one attribute's value in another's channel -
            # plausible on screen and wrong (DESIGN.md 7). Checked here, in the
            # rebuild path, which is the only place the pairing is established.
            raise RuntimeError("derive_chop built %%r, expected %%r"
                               %% (built[:3], names[:3]))
        scriptOp.store(_CACHE_KEY, names)

    # By position, against the list the channels were appended in and the check
    # above confirmed. `chan.name` per channel would be 87 more calls into C++ for
    # information we already have.
    for name, chan in zip(names, scriptOp.chans()):
        chan[0] = out[name]
'''


def _tuning_page(master, Params):
    """Put every `derive.Params` field on the Tuning page. Returns (new, names).

    WHY THIS EXISTS AT ALL, and it is a gap rather than a feature: `_params()` has
    always read these by name with a getattr fallback, and NOTHING EVER CREATED THEM.
    So every threshold in `derive()` - the confidence gate, the curl range, the spread
    range, the overlap test - has been stuck at its dataclass default since the day it
    was written, and the panel gave no sign. Eight tuning values that looked adjustable
    and were not.

    Built from `dataclasses.fields`, so the page and the dataclass cannot disagree and
    a new field arrives on the panel without a second edit.

    SHARED PAGE: `tools/td_add_latches.py` owns the fifteen latch threshold pairs on
    Tuning as well. Safe because each builder appends only its own names and restores
    only its own stored values - the hazard is two scripts appending the SAME
    parameter, where whichever runs second resets it.
    """
    page = None
    for existing in master.customPages:
        if existing.name == "Tuning":
            page = existing
            break
    if page is None:
        page = master.appendCustomPage("Tuning")

    known = {spec.name.capitalize() for spec in fields(Params)}
    was = {par.name: par.eval() for par in master.customPars if par.name in known}
    made = []
    for spec in fields(Params):
        name = spec.name.capitalize()
        par = page.appendFloat(name, label=name)[0]
        par.default = float(spec.default)
        # `.val` only when the parameter is NEW: append* resets attributes, and a
        # newly appended parameter reads 0 whatever its default says (DESIGN.md 2.11).
        # A threshold silently at 0 is worse than one at its default - a
        # `Confthreshold` of 0 passes every hand, however bad.
        if name in was:
            par.val = was[name]
        else:
            par.val = par.default
            made.append(name)
    return len(made), made


def _keep_layout(master):
    """Has the user asked the builders to leave their node arrangement alone?"""
    par = getattr(master.par, "Keeplayout", None)
    return bool(par is not None and par.eval())


def _place(node, xy, keep, existed):
    """Write nodeX/nodeY unless `Keeplayout` is on and the node already existed.

    Rule and caveats in `appletd.td_layout.placement`.
    """
    from appletd.td_layout import placement

    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where
    return node


def _attach_once(merge, node, drop_names=()):
    """Normalise a Merge CHOP's inputs: `node` exactly once, anything in
    `drop_names` gone, every other source exactly once. Returns what it removed.

    The same helper tools/td_add_coords.py and tools/td_add_filter.py carry, and
    it is duplicated rather than shared on purpose: every builder has to survive
    being pasted into a Text DAT on its own.

    Traps, all measured in this repo rather than anticipated (DESIGN.md 2.11):
      * `.inputs` is STALE inside the same script that rewired anything, so this
        reads `inputConnectors[i].connections` throughout - that is the truth.
      * `.inputs` ALSO REPORTS A GROUP COMP AS ITS INNER `out1` CHOP, and every
        group here has one, so a name-keyed dedup collapses `filter` and `coords`
        into a single entry. That is not hypothetical: it is exactly how this
        script silently dropped the 168 coordinate channels from the COMP's
        output, taking it from 392 to 224 while reporting success. Deduping by the
        OWNER OBJECT is what makes two groups two sources.
      * disconnecting SHIFTS the connector list, so a single pass skips entries.
        This restarts after every removal.
      * a Merge CHOP accepts the SAME operator on any number of inputs, silently,
        and the only symptom is the channel count.
      * `connect()` accepts an operator only where it has one unambiguous output,
        which a base COMP does not - hence `outputConnectors[0]`.
    """
    removed = []
    for _attempt in range(256):
        seen = []
        cut = False
        for conn in merge.inputConnectors:
            owners = [x.owner for x in conn.connections]
            if not owners:
                continue
            owner = owners[0]
            if owner.name in drop_names or owner in seen:
                removed.append(owner.name)
                conn.disconnect()
                cut = True
                break                       # the list has shifted; start again
            seen.append(owner)
        if not cut:
            break

    attached = any(x.owner is node for conn in merge.inputConnectors
                   for x in conn.connections)
    if not attached:
        target = node.outputConnectors[0] if node.isCOMP else node
        for conn in merge.inputConnectors:
            if not conn.connections:
                conn.connect(target)
                break
    return removed


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process (DESIGN.md 2.11),
    # and this builder is the one where that bites hardest: `appletd.derive` is
    # what the Script CHOP calls every cook, so an edited formula would be invisible
    # until TouchDesigner was restarted. Safe to purge - pure Python with no C
    # extension state, and the only thing holding a reference is the callbacks DAT,
    # whose text this script rewrites anyway, which is what makes TD recompile it
    # against the fresh import.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    # One layout table for every builder - two of them once placed their group on the
    # same coordinate, and nothing could notice.
    from appletd.derive import Params
    from appletd.td_layout import stream_xy

    comp = op(COMP_PATH)
    master = op(MASTER_PATH)
    if comp is None or master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first"
              % (COMP_PATH if comp is None else MASTER_PATH))
        return

    # -- the tuning `derive()` has always had and never exposed ------------
    made, existing = _tuning_page(master, Params)
    print("0. Tuning: %d parameters for derive(), %d new"
          % (len(fields(Params)), made))
    if made:
        print("   %s" % ", ".join(existing))

    keep = _keep_layout(op(MASTER_PATH) or comp)
    existing = comp.op("derive_callbacks")
    callbacks = existing or comp.create(td.textDAT, "derive_callbacks")
    _place(callbacks, stream_xy("derive_callbacks"), keep, existing is not None)
    callbacks.text = CALLBACK_SOURCE % {"repo": REPO_ROOT,
                                    "comp_for_root": MASTER_PATH}

    existing_chop = comp.op("derive_chop")
    chop = existing_chop or comp.create(td.scriptCHOP, "derive_chop")
    _place(chop, stream_xy("derive_chop"), keep, existing_chop is not None)
    chop.par.callbacks = callbacks.path
    # The raw OSC channels are the input; derive() needs the landmark positions.
    # The FILTERED stream, not the raw input, and this line is a bug fix. It used to
    # read `in1` and rely on tools/td_add_filter.py repointing it afterwards - which
    # never happened, because in the documented build order the filter is built
    # BEFORE this script and had nothing to repoint. Measured on the live network:
    # `derive_chop` read `in1`, so every derived attribute - every pinch distance,
    # every latch input - was computed on UNSMOOTHED landmarks while the coordinate
    # spaces used smoothed ones. Each consumer states its own input now, which is
    # the only arrangement that cannot depend on build order.
    upstream = comp.op("filter") or comp.op("in1")
    chop.inputConnectors[0].connect(
        upstream.outputConnectors[0] if upstream.isCOMP else upstream)
    # TD auto-creates a docked callbacks DAT with a Script CHOP; ours replaces it.
    orphan = comp.op("derive_chop_callbacks")
    if orphan:
        orphan.destroy()
        print("removed the auto-created docked DAT")

    merge = comp.op("merge_out")
    if merge is not None:
        # Attach derive_chop exactly once and leave every other source alone.
        #
        # The previous version rebuilt the whole list from `merge.inputs`, keyed
        # on NAME. That was wrong twice over: `.inputs` reports a group COMP as
        # its inner `out1` CHOP, and every group has one - so `filter` and
        # `coords` deduped to a single entry and the 168 coordinate channels
        # silently left the COMP's output, 392 down to 224, while the script
        # printed success. Deduping by the owner OBJECT is what makes two groups
        # two sources; `_attach_once` above has the rest of the reasoning.
        #
        # Idempotent, which matters because the MCP bridge has been observed
        # executing these scripts TWICE per call.
        dropped = _attach_once(merge, chop)
        owners = [x.owner.name for conn in merge.inputConnectors
                  for x in conn.connections]
        print("merge_out inputs: %s%s"
              % (", ".join(owners),
                 "" if not dropped else "  (dropped %s)" % ", ".join(dropped)))

    chop.cook(force=True)
    print("derive_chop: %d channels, errors=%r" % (chop.numChans, chop.errors()))
    for probe in ("h0_size", "h0_openness", "h0_pinch_index", "h0_g_open",
                  "hands_distance", "h0_valid"):
        channel = chop.chan(probe)
        print("   %-16s %s" % (probe, "MISSING" if channel is None
                               else round(channel[0], 4)))

    out_chop = comp.op("out1")
    out_chop.cook(force=True)
    print("COMP output now: %d channels" % out_chop.numChans)


main()
