#!/usr/bin/env python
"""Add the temporal channels to the visionhands COMP. Paste, Run Script. Idempotent.

    WHAT IT BUILDS
        h{i}_active     h{i}_entering   h{i}_exiting   h{i}_held
        both_active     n_active
        h{i}_vel_x  h{i}_vel_y  h{i}_speed  h{i}_accel
        h{i}_dir    h{i}_dir_x  h{i}_dir_y  h{i}_moving
        hands_approach

    Presence with a real debounce, and the velocity family. 29 channels.

THE DEBOUNCE IS THE SAME SCHMITT TRIGGER AS THE LATCHES, which is worth seeing
because it looks like a different problem. docs/ATTRIBUTES.md asks for `active` =
valid held for `Activateframes` before turning on and `Deactivateframes` before
turning off. Written as a recurrence that is:

    active = all_valid_over_last_A OR ( prev AND any_valid_over_last_D )

- `all_valid_over_last_A` is the minimum of `valid` over a Trail of A samples: 1
  only if every one of those frames was valid. That is the turn-on condition.
- `any_valid_over_last_D` is the MAXIMUM over a Trail of D samples: 0 only if all
  D frames were invalid. So its negation is the turn-off condition.
- Between them the state holds, exactly as a dead band does.

So the asymmetry docs/ATTRIBUTES.md asks for - slower to drop a hand than to
acquire one, because losing one mid-gesture is worse than gaining one late - is
just two different window lengths on the same shape, and it inherits the same
self-correcting property: every kind of desynchronisation resolves on the next
frame where the input is unambiguous.

WHY THIS MATTERS BEYOND PRESENCE. The latch bank currently gates on raw per-frame
validity, so a single low-confidence frame mid-pinch drops the state, fires a
spurious end pulse, and re-engages with a spurious start and a bumped counter.
`h{i}_active` is what it should gate on. This builder publishes it; the latch
builder ANDs it in if it finds it.

EVERY MEMORY GROUP NEEDS ITS OWN CLOCK. DESIGN.md 2.10: TouchDesigner does not
cook a branch whose channels nothing downstream asks for, and a recurrence that
cooks intermittently produces correct-looking states with nonsense edges. So this
builds its own Cook Type = Always Null pulling all of its terminal branches,
exactly as the latch bank does. Do not remove it, and do not assume the COMP's
output being consumed is enough - measured, it is not.

Ref: docs/ATTRIBUTES.md (Presence and Motion), docs/BUILD_PLAN.md step 2,
DESIGN.md 2.10 (the clock), 2.11 (the operator behaviours).
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
COMP_PATH = "/project1/visionhands"
# The group this builds. Everything it owns lives inside, so the top-level network
# shows one node - and because nothing outside reads these channels except through
# merge_out, `allowCooking` on this group genuinely gates its whole cost, which is
# not true of `filter` (that one is in the data path). docs/BUILD_PLAN.md 7.3.
GROUP = "temporal"
PREFIX = "tmp_"

# Parameters stay on the TOP-LEVEL COMP so all tuning is in one place, so an
# expression inside the group reaches them through the grandparent.
PARENT_PAR = "parent(2).par.%s"

# Advanced-page defaults, from docs/ATTRIBUTES.md.
#
# Deactivate is higher than Activate on purpose: dropping a hand mid-gesture is
# worse than acquiring one a frame late, so the filter is deliberately asymmetric.
DEFAULTS = {
    "Activateframes": 3,
    "Deactivateframes": 6,
}
# Seconds of smoothing on velocity before speed and acceleration read it.
# Differentiating anything amplifies its noise, and the positions are already
# one-euro filtered, so this is the second stage rather than the only one.
# GUESSED - per-joint jitter is what should set it (DESIGN.md 11).
# 0.15 s rather than the 0.08 that docs/ATTRIBUTES.md guessed. This is a moving
# average now, and its width has to span several DATA frames to cancel the 30-into-
# 60 sampling pattern - 0.15 s is about nine cooks, so four or five data frames.
# 0.08 s spans two and leaves the alternation visible in the output.
VELOCITY_FILTER_S = 0.15

# Below this speed a direction is noise rather than a heading, so `dir` holds its
# last value instead of spinning. Normalised units per second. GUESSED, and the
# right way to set it is the per-joint jitter measurement (DESIGN.md 11) - a floor
# below the noise floor achieves nothing.
SPEEDFLOOR = 0.05

# How far back to look for a change in `seq` before declaring the sender dead.
# Long enough to bridge the alternate zero-slope frames at a 60 fps cook rate
# against 30 fps delivery, and to survive a brief camera stall; short enough that a
# stuck latch releases promptly. GUESSED - the right value depends on how long a
# stall should be tolerated, which is a feel question.
LIVENESS_WINDOW_S = 0.5

MOTION_CALLBACK = '''# Generated by tools/td_add_temporal.py
#
# A thin wrapper, exactly like derive_callbacks: everything computed here is a pure
# function in visionhands/motion.py, tested with no TouchDesigner present. The only
# reason any of this is Python is that no CHOP does atan2 (DESIGN.md 2.11).
import sys

REPO_ROOT = %(repo)r
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)          # append, never insert

from visionhands.motion import MotionParams, directions


def onCook(scriptOp):
    # Not time-sliced: this publishes a snapshot of one frame, and editing
    # numSamples in Time Slice mode is unsupported - it warned on every cook of
    # derive_chop until that was fixed.
    scriptOp.isTimeSlice = False
    scriptOp.clear()
    if not scriptOp.inputs:
        return
    values = {chan.name: chan[0] for chan in scriptOp.inputs[0].chans()}

    comp = scriptOp.parent()
    floor = getattr(comp.par, "Speedfloor", None)
    params = MotionParams(speedfloor=%(floor)r if floor is None
                          else float(floor.eval()))

    out = directions(values, params)
    scriptOp.numSamples = 1
    for name in sorted(out):
        scriptOp.appendChan(name)[0] = out[name]
'''

ROW_Y = -2600


def _page(comp, name="Advanced"):
    """The Advanced page. Created once; tuned values survive a rebuild.

    Traps: `appendCustomPage` with an existing name makes a second page of that
           name, and `appendInt`/`appendFloat` on an existing parameter reset its
           value to zero rather than to its default. Both cost time elsewhere in
           this repo; see tools/td_add_latches.py.
    """
    page = None
    for existing in comp.customPages:
        if existing.name == name:
            page = existing
            break
    if page is None:
        page = comp.appendCustomPage(name)

    wanted = dict(DEFAULTS)
    tuned = {p.name: p.eval() for p in comp.customPars if p.name in wanted}
    for parameter, default in sorted(wanted.items()):
        par = page.appendInt(parameter, label=parameter)[0]
        par.default = default
        par.normMin, par.normMax = 1, 30
        previous = tuned.get(parameter)
        # A window of zero frames is not a shorter debounce, it is a Trail with no
        # samples. Treated as untuned.
        par.val = previous if previous and previous >= 1 else default

    for name, default, high in (("Velocityfilter", VELOCITY_FILTER_S, 0.5),
                                ("Speedfloor", SPEEDFLOOR, 1.0)):
        was = {p.name: p.eval() for p in comp.customPars if p.name == name}
        par = page.appendFloat(name, label=name)[0]
        par.default = default
        par.normMin, par.normMax = 0.0, high
        par.val = was.get(name, default)
    return page


def _attach_once(merge, node, drop_names=()):
    """Normalise a Merge CHOP's inputs: `node` exactly once, anything in
    `drop_names` gone, every other source exactly once. Returns what it removed.

    Traps, all four measured in this repo rather than anticipated (DESIGN.md 2.11):
      * `.inputs` is STALE inside the same script that rewired anything, so this
        reads `inputConnectors[i].connections` throughout - that is the truth. It
        once reported an input list containing the COMP's own `out1`, which would
        have been a loop, while the connectors showed the correct thirteen.
      * disconnecting SHIFTS the connector list, so a single pass skips entries.
        This restarts after every removal. A single-pass version dropped two of
        four stale branches and left the other two wired to operators it then
        destroyed.
      * a Merge CHOP accepts the SAME operator on any number of inputs, silently,
        and the only symptom is the channel count. `filter` reached three
        connections and put 274 duplicate channels on the output; `derive_chop`
        reached two and put 87. So this dedupes EVERY source, not just `node` -
        which means any builder run repairs the whole merge rather than only its
        own contribution.
      * `connect()` accepts an operator only where it has one unambiguous output,
        which a base COMP does not - hence `outputConnectors[0]`.
    """
    removed = []
    for _attempt in range(256):
        seen = []
        cut = False
        for conn in merge.inputConnectors:
            owners = [x.owner for x in conn.connections]
            if not owners:
                continue
            owner = owners[0]
            if owner.name in drop_names or owner in seen:
                removed.append(owner.name)
                conn.disconnect()
                cut = True
                break                       # the list has shifted; start again
            seen.append(owner)
        if not cut:
            break

    attached = any(x.owner is node for conn in merge.inputConnectors
                   for x in conn.connections)
    if not attached:
        target = node.outputConnectors[0] if node.isCOMP else node
        for conn in merge.inputConnectors:
            if not conn.connections:
                conn.connect(target)
                break
    return removed


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules across runs. See tools/td_add_latches.py.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]

    comp = op(COMP_PATH)
    if comp is None:
        print("FAIL no COMP at %s - run tools/td_build_comp.py first" % COMP_PATH)
        return
    source = comp.op("derive_chop")
    if source is None:
        print("FAIL no derive_chop - run tools/td_add_derive.py first")
        return

    # REUSE the group, clear its CHILDREN. Destroying the group orphans everything
    # wired to its output, and a dangling input is indistinguishable from one that
    # was never connected (DESIGN.md 2.11).
    group = comp.op(GROUP)
    if group is None:
        group = comp.create(td.baseCOMP, GROUP)
    else:
        for child in list(group.children):
            child.destroy()
    group.nodeX, group.nodeY = -1100, -900
    group.color = (0.3, 0.5, 0.4)
    removed = 0
    for child in list(comp.children):
        if child.name.startswith(PREFIX):
            child.destroy()
            removed += 1
    print("1. `%s` group%s" % (GROUP, ", cleared %d loose %s* operators"
                               % (removed, PREFIX) if removed else ""))

    _page(comp)
    print("2. Advanced page: %s, Velocityfilter=%.3f s" % (
        ", ".join("%s=%d" % (n, int(getattr(comp.par, n).eval()))
                  for n in sorted(DEFAULTS)), float(comp.par.Velocityfilter.eval())))

    column = [0]

    def make(kind, name, y=ROW_Y):
        node = group.create(kind, PREFIX + name)
        node.nodeX, node.nodeY = -1400 + column[0] * 170, y
        column[0] += 1
        return node

    # TWO inputs, and the split is deliberate. Input 0 is the derived attributes -
    # what presence and velocity are computed FROM. Input 1 is the RAW landmark
    # stream, used only for `seq`, because liveness must not depend on a filter
    # chain that could itself be misconfigured. Two In CHOPs make that visible in
    # the network instead of hidden in a path expression.
    derived_in = group.create(td.inCHOP, "in1")
    derived_in.nodeX, derived_in.nodeY = -1600, 0
    raw_seq_in = group.create(td.inCHOP, "in2")
    raw_seq_in.nodeX, raw_seq_in.nodeY = -1600, -150
    group.inputConnectors[0].connect(source)
    group.inputConnectors[1].connect(comp.op("in1"))

    def wire(node, *inputs):
        for index, source_op in enumerate(inputs):
            node.inputConnectors[index].connect(source_op)
        return node

    def maths(name, *inputs, y=ROW_Y, **pars):
        node = make(td.mathCHOP, name, y)
        wire(node, *inputs)
        for key, value in pars.items():
            if key.endswith("_expr"):
                node.par[key[:-5]].expr = value
            else:
                node.par[key] = value
        if len(inputs) > 1:
            node.par.match = "name"     # never the `index` default, DESIGN.md 2.11
        return node

    def derivative(name, input_op, y):
        """d/dt of every channel, per second, frame to frame.

        NOT the Slope CHOP. Slope differentiates along the SAMPLE axis, and every
        CHOP here carries one sample per frame - a snapshot, not a time-sliced
        signal - so it has no neighbour to difference against. Measured: it
        reported palm velocities of 12.5 and 32.5 units per second on coordinates
        that cannot leave 0..1, and an acceleration of 1950.

        So the same construction as everything else with memory, and the same one
        the one-euro filter uses for its own speed estimate:

            v = (x - x_on_the_previous_frame) * rate

        Returns the raw derivative; the caller filters it.
        """
        previous = make(td.feedbackCHOP, name + "_prev", y)
        previous.par.output = "previous"
        # Input 1 is the Feedback's template AND its initial value, and here it is
        # the INPUT rather than a zero CHOP. Seeding it with zeros makes the very
        # first frame report `x * rate` - measured, a palm at 0.208 gave a velocity
        # of 12.5 units per second on a coordinate that cannot leave 0..1, which
        # then propagated into acceleration as 1950 and took the velocity filter
        # 0.08 s to shed. Seeded from the input, the first frame reports 0, which is
        # the only defensible answer when there is no previous frame to difference
        # against.
        wire(previous, input_op, input_op)
        difference = maths(name + "_d", input_op, previous, chopop="sub", y=y)
        return maths(name, difference, gain_expr="me.time.rate", y=y)

    def moving_average(name, input_op, y, width_par="Velocityfilter"):
        """The mean of every channel over `width_par` seconds. Trail + Analyze.

        NOT the Filter CHOP, and NOT the Lag CHOP. The Filter CHOP smooths along
        the SAMPLE axis, and every CHOP here carries one sample per frame, so it
        has nothing to smooth across. Measured: all nine of its filter types
        returned the identical value, unchanged by width - it was a passthrough,
        silently. Same family as the Slope CHOP above.

        The rule that falls out, and it applies to everything still to build:
        operators that CONSUME a sample axis (Slope, Filter) are inert on a
        one-sample-per-frame CHOP; operators that CREATE one from successive frames
        (Trail) work, which is why the debounce above does.

        And a moving average is not merely a smoothing choice here, it is the
        correction. The raw derivative divides a position step by the COOK interval,
        but positions only change when a frame ARRIVES - at 30 fps into a 60 fps
        cook that is every other frame, so the per-cook derivative alternates
        between double-size and zero. Measured: a palm step of 0.0592 in one cook,
        where 0.0292 was a cook's worth of motion. The mean over a window is
        (x_now - x_then) / elapsed, which is exactly right regardless of how the
        updates land, so averaging is what makes the number true rather than just
        smooth.
        """
        trail = make(td.trailCHOP, name + "_trail", y)
        wire(trail, input_op)
        trail.par.wlengthunit = "seconds"
        trail.par.wlength.expr = PARENT_PAR % width_par
        averaged = make(td.analyzeCHOP, name, y)
        wire(averaged, trail)
        averaged.par.function = "average"
        return averaged

    def select(name, source_op, names, renames=None, y=ROW_Y):
        node = make(td.selectCHOP, name, y)
        wire(node, source_op)
        node.par.channames = " ".join(names)
        if renames:
            # Keyed on names, so a missing source costs one channel rather than
            # shifting every later one onto the wrong data.
            node.par.renamefrom = " ".join(names)
            node.par.renameto = " ".join(renames)
        return node

    # =====================================================================
    # Presence: the debounce
    # =====================================================================
    # =====================================================================
    # Liveness: is anything still SENDING?
    # =====================================================================
    # Lives here rather than in the latch builder, where it started. It is a
    # property of the STREAM, both groups need it, and having the latch bank own it
    # created a dependency cycle - the bank read `active` from here while this read
    # `live` from there. Flat, TouchDesigner tolerated that because the real data
    # dependencies were acyclic; as wired COMPs it would not.
    #
    # DESIGN.md 2.9: a dead sidecar leaves the OSC In CHOP FROZEN rather than
    # zeroed, so `found`, `conf_median` and every distance keep reporting the last
    # good frame indefinitely. Measured, before this existed: `h0_active` read 1 and
    # `h0_held` climbed to 54 seconds with nothing sending, and a latch engaged at
    # that moment never released.
    #
    # `seq` increments once per delivered frame and freezes when the sender stops,
    # so a non-zero slope IS liveness. Two details:
    #   * the Logic CHOP's `ne` convert ("On When Not Equal to Zero") turns the
    #     slope straight into a boolean, so no absolute value is needed - which also
    #     means the once-per-2**23 negative wrap still reads as alive;
    #   * at a 60 fps cook rate against 30 fps delivery the slope is zero on
    #     alternate frames, so the raw signal flickers. A Trail plus an Analyze
    #     maximum answers "did seq change at all in the last LIVENESS_WINDOW_S"
    #     exactly, with no filter constant and no epsilon to tune.
    #
    # Read from the RAW `in1`, never through the smoothing filter: liveness must not
    # depend on a filter chain that could itself be misconfigured.
    seq = select("seq", raw_seq_in, ["seq"], y=ROW_Y - 1200)
    seq_slope = make(td.slopeCHOP, "seq_slope", ROW_Y - 1200)
    wire(seq_slope, seq)
    changed = make(td.logicCHOP, "changed", ROW_Y - 1200)
    wire(changed, seq_slope)
    changed.par.convert = "ne"
    changed_trail = make(td.trailCHOP, "changed_trail", ROW_Y - 1200)
    wire(changed_trail, changed)
    changed_trail.par.wlength = LIVENESS_WINDOW_S
    changed_trail.par.wlengthunit = "seconds"
    live = make(td.analyzeCHOP, "live", ROW_Y - 1200)
    wire(live, changed_trail)
    live.par.function = "maximum"       # 1 if it changed at all in the window

    valid_raw = select("valid_raw", derived_in, ["h0_valid", "h1_valid"],
                       ["h0_active", "h1_active"])

    # Liveness ANDed in BEFORE the debounce, so presence decays through the normal
    # Deactivateframes path rather than snapping off.
    live2 = make(td.constantCHOP, "live2")
    live2.seq.const.numBlocks = 2
    for index, hand in enumerate(("h0_active", "h1_active")):
        live2.par["name%d" % index] = hand
        live2.par["value%d" % index].expr = "op('%slive')['seq']" % PREFIX
    valid = make(td.logicCHOP, "valid")
    wire(valid, valid_raw, live2)
    valid.par.chopop = "and"
    valid.par.match = "name"
    zero = maths("zero", valid, gain=0.0)       # template for the feedbacks

    # ALL valid over the last Activateframes: the minimum of a Trail. `samples`
    # rather than `frames` or `seconds`, because the parameter is a frame count and
    # this branch is clocked once per frame by tmp_tick.
    trail_on = make(td.trailCHOP, "trail_on")
    wire(trail_on, valid)
    trail_on.par.wlengthunit = "samples"
    trail_on.par.wlength.expr = PARENT_PAR % "Activateframes"
    all_valid = make(td.analyzeCHOP, "all_valid")
    wire(all_valid, trail_on)
    all_valid.par.function = "minimum"

    # ANY valid over the last Deactivateframes: the maximum. Its negation is the
    # turn-off condition, so this is the term that HOLDS the state.
    trail_off = make(td.trailCHOP, "trail_off")
    wire(trail_off, valid)
    trail_off.par.wlengthunit = "samples"
    trail_off.par.wlength.expr = PARENT_PAR % "Deactivateframes"
    any_valid = make(td.analyzeCHOP, "any_valid")
    wire(any_valid, trail_off)
    any_valid.par.function = "maximum"

    prev = make(td.feedbackCHOP, "active_prev")
    prev.par.output = "previous"
    held_on = make(td.logicCHOP, "held_on")
    wire(held_on, prev, any_valid)
    held_on.par.chopop = "and"
    held_on.par.match = "name"
    active = make(td.logicCHOP, "active")
    wire(active, all_valid, held_on)
    active.par.chopop = "or"
    active.par.match = "name"
    # Input 1 is the template AND the initial value: starting released means a hand
    # already in shot when the project loads produces an `entering` pulse, which is
    # the honest reading - nothing knows it was there before.
    wire(prev, active, zero)

    not_prev = make(td.logicCHOP, "not_active_prev")
    wire(not_prev, prev)
    not_prev.par.preop = "invert"
    not_active = make(td.logicCHOP, "not_active")
    wire(not_active, active)
    not_active.par.preop = "invert"
    entering = make(td.logicCHOP, "entering")
    wire(entering, active, not_prev)
    entering.par.chopop = "and"
    entering.par.match = "name"
    exiting = make(td.logicCHOP, "exiting")
    wire(exiting, prev, not_active)
    exiting.par.chopop = "and"
    exiting.par.match = "name"

    # `held`: seconds active, reset to zero the moment it is not.
    #
    #     held = (held_prev + 1/rate) * active
    #
    # The multiply is the reset - no separate reset path, and no state that can be
    # left stale, because an inactive frame zeroes it unconditionally.
    held_prev = make(td.feedbackCHOP, "held_prev", ROW_Y - 150)
    held_prev.par.output = "previous"
    ticked = maths("held_tick", held_prev, y=ROW_Y - 150,
                   postoff_expr="1.0 / me.time.rate")
    held = maths("held", ticked, active, chopop="mul", y=ROW_Y - 150)
    wire(held_prev, held, zero)

    both_active = make(td.logicCHOP, "both_active", ROW_Y - 150)
    wire(both_active, active)
    both_active.par.chanop = "and"          # combine CHANNELS, not inputs
    both_active.par.renamefrom = "*"
    both_active.par.renameto = "both_active"
    n_active = maths("n_active", active, chanop="add", y=ROW_Y - 150,
                     renamefrom="*", renameto="n_active")

    out_active = select("out_active", active, ["h0_active", "h1_active"], y=ROW_Y)
    out_entering = select("out_entering", entering, ["h0_active", "h1_active"],
                          ["h0_entering", "h1_entering"], y=ROW_Y)
    out_exiting = select("out_exiting", exiting, ["h0_active", "h1_active"],
                         ["h0_exiting", "h1_exiting"], y=ROW_Y)
    out_held = select("out_held", held, ["h0_active", "h1_active"],
                      ["h0_held", "h1_held"], y=ROW_Y)

    # =====================================================================
    # Motion: velocity, speed, acceleration
    # =====================================================================
    # The palm rather than the wrist, because the palm is the mean of six joints
    # and does not swing as the hand rotates (docs/ATTRIBUTES.md).
    palm = select("palm", derived_in, ["h0_palm_x", "h0_palm_y",
                                   "h1_palm_x", "h1_palm_y"], y=ROW_Y - 300)
    slope = derivative("slope", palm, ROW_Y - 300)
    # Averaged, not merely smoothed - see moving_average. Differentiating also
    # amplifies noise, and the positions are already one-euro filtered upstream, so
    # this is the second stage as well as the correction.
    velocity = moving_average("vel", slope, ROW_Y - 300)
    out_vel = select("out_vel", velocity,
                     ["h0_palm_x", "h0_palm_y", "h1_palm_x", "h1_palm_y"],
                     ["h0_vel_x", "h0_vel_y", "h1_vel_x", "h1_vel_y"], y=ROW_Y - 300)

    # speed = hypot(vel_x, vel_y). Both components are renamed to the SAME channel
    # name so the add pairs them, then `preop = root` is the square root (verified
    # live, 9 -> 3).
    vx = select("vx", velocity, ["h0_palm_x", "h1_palm_x"],
                ["h0_speed", "h1_speed"], y=ROW_Y - 450)
    vy = select("vy", velocity, ["h0_palm_y", "h1_palm_y"],
                ["h0_speed", "h1_speed"], y=ROW_Y - 450)
    vx2 = maths("vx2", vx, preop="square", y=ROW_Y - 450)
    vy2 = maths("vy2", vy, preop="square", y=ROW_Y - 450)
    sumsq = maths("sumsq", vx2, vy2, chopop="add", y=ROW_Y - 450)
    speed = maths("speed", sumsq, preop="root", y=ROW_Y - 450)

    accel_slope = derivative("accel_slope", speed, ROW_Y - 450)
    accel = select("accel", accel_slope, ["h0_speed", "h1_speed"],
                   ["h0_accel", "h1_accel"], y=ROW_Y - 450)

    # =====================================================================
    # Heading: dir, the unit vector, and holding it when the hand is slow
    # =====================================================================
    # The Script CHOP needs velocity AND speed in one input, so it can gate on the
    # speed a consumer actually sees rather than recomputing one.
    motion_in = make(td.mergeCHOP, "motion_in", ROW_Y - 750)
    wire(motion_in, out_vel, speed)

    motion_dat = comp.op(PREFIX + "motion_callbacks") or comp.create(
        td.textDAT, PREFIX + "motion_callbacks")
    motion_dat.nodeX, motion_dat.nodeY = -1600, ROW_Y - 750
    motion_dat.text = MOTION_CALLBACK % {"repo": REPO_ROOT, "floor": SPEEDFLOOR}
    motion = make(td.scriptCHOP, "motion", ROW_Y - 750)
    wire(motion, motion_in)
    motion.par.callbacks = motion_dat.path
    orphan = comp.op(PREFIX + "motion_callbacks1")
    if orphan:
        # Creating a Script CHOP auto-creates a docked callbacks DAT; ours replaces
        # it, and the stray one would sit there cooking (DESIGN.md 2.11).
        orphan.destroy()

    # HOLD `dir` when the hand is slower than Speedfloor, so it stops spinning on
    # noise. Done in CHOPs rather than in motion.py because holding a value is
    # MEMORY, and the module publishes the condition (`moving`) precisely so that
    # the decision about what to remember stays out of Python.
    #
    #     held = moving * dir  +  (1 - moving) * held_on_the_previous_frame
    #
    # A blend rather than a Switch CHOP: the gate is per CHANNEL - one hand can be
    # moving while the other is still - and a Switch selects whole inputs.
    # ALL THREE heading channels are held together, not just the angle. Holding
    # `dir` alone left `dir_x`/`dir_y` following the live velocity, so a stationary
    # hand reported `dir` = 180 and a vector of (+1, 0) - one saying left and the
    # other saying right. A consumer has no way to know which to believe, and the
    # two disagreeing is worse than either alone.
    HELD = ["h0_dir", "h0_dir_x", "h0_dir_y", "h1_dir", "h1_dir_x", "h1_dir_y"]
    dir_now = select("dir_now", motion, HELD, y=ROW_Y - 900)

    # The gate broadcast onto all six names. A Constant CHOP of expressions, the
    # same trick the thresholds and liveness use in the latch bank: one Select
    # cannot emit `h0_moving` three times, and this keeps the pairing by NAME
    # rather than reintroducing a positional match.
    gate = make(td.constantCHOP, "gate", ROW_Y - 900)
    gate.seq.const.numBlocks = len(HELD)
    for index, name in enumerate(HELD):
        gate.par["name%d" % index] = name
        gate.par["value%d" % index].expr = (
            "op('%smotion')['%s_moving']" % (PREFIX, name.split("_")[0]))

    not_gate = make(td.logicCHOP, "not_gate", ROW_Y - 900)
    wire(not_gate, gate)
    not_gate.par.preop = "invert"
    dir_prev = make(td.feedbackCHOP, "dir_prev", ROW_Y - 900)
    dir_prev.par.output = "previous"
    fresh = maths("dir_fresh", dir_now, gate, chopop="mul", y=ROW_Y - 900)
    stale = maths("dir_stale", dir_prev, not_gate, chopop="mul", y=ROW_Y - 900)
    dir_held = maths("dir", fresh, stale, chopop="add", y=ROW_Y - 900)
    # Seeded from the live heading, not from zeros: with no previous frame the
    # honest answer is the current one, and a zero would read as "pointing right"
    # on the first frame of every session.
    wire(dir_prev, dir_held, dir_now)

    out_dir = select("out_dir", dir_held, HELD, y=ROW_Y - 900)
    out_moving = select("out_moving", motion, ["h0_moving", "h1_moving"],
                        y=ROW_Y - 1050)

    # =====================================================================
    # Two hands: the closing rate
    # =====================================================================
    # `hands_approach` is the derivative of a distance, so it has no wrapping
    # problem and needs nothing special. `hands_twist` is the derivative of an
    # ANGLE and does - see the note at the end.
    approach_in = select("approach_in", derived_in, ["hands_distance"],
                         y=ROW_Y - 600)
    approach_slope = derivative("approach_slope", approach_in, ROW_Y - 600)
    approach = moving_average("approach", approach_slope, ROW_Y - 600)
    out_approach = select("out_approach", approach, ["hands_distance"],
                          ["hands_approach"], y=ROW_Y - 600)

    # =====================================================================
    # tmp_ready: what the latch bank gates on
    # =====================================================================
    # `active AND live`, under the names the latch bank's validity column uses, so
    # its `_fan` can broadcast them onto the fifteen working names directly. One
    # CHOP with three channels rather than the two 15-channel broadcasts this
    # replaced - which cost 0.074 ms a frame to deliver four numbers (MEASURED).
    #
    # `active` already has liveness ANDed in, so this only has to add `both_active`
    # for the two-hand latch.
    ready = make(td.constantCHOP, "ready", ROW_Y - 1200)
    ready.seq.const.numBlocks = 3
    for index, (name, source_expr) in enumerate((
            ("h0_valid", "op('%sout_active')['h0_active']" % PREFIX),
            ("h1_valid", "op('%sout_active')['h1_active']" % PREFIX),
            ("both_valid", "op('%sboth_active')['both_active']" % PREFIX))):
        ready.par["name%d" % index] = name
        ready.par["value%d" % index].expr = source_expr

    # =====================================================================
    # The clock, and the output
    # =====================================================================
    terminals = [out_active, out_entering, out_exiting, out_held, both_active,
                 n_active, out_vel, speed, accel, out_approach,
                 out_dir, out_moving]
    merged = make(td.mergeCHOP, "out", ROW_Y - 750)
    wire(merged, *terminals)
    # `ready` is pulled by the clock too. It is what the latch bank gates on and it
    # is not upstream of anything in `terminals`, so without this it would only cook
    # when the latch bank happened to ask - which is the stale-recurrence failure
    # DESIGN.md 2.10 is about.
    pulled = make(td.mergeCHOP, "pulled", ROW_Y - 1350)
    wire(pulled, merged, ready)

    # Its own clock, for the reason in DESIGN.md 2.10: this branch has memory - two
    # Trails and three Feedbacks - and TouchDesigner will not cook it just because
    # merge_out exists downstream. Measured on the latch bank: terminal branches
    # cooked 4 times against merge_out's 420,613.
    clock = make(td.nullCHOP, "tick", ROW_Y - 750)
    wire(clock, pulled)
    clock.par.cooktype = "always"

    # The group's output. `tmp_ready` goes out too, on a second connector, because
    # the latch bank gates on it - which makes that cross-group dependency a wire
    # in the network rather than an `op('tmp_ready')` buried in an expression.
    group_out = group.create(td.outCHOP, "out1")
    group_out.nodeX, group_out.nodeY = 400, 0
    group_out.inputConnectors[0].connect(merged)
    ready_out = group.create(td.outCHOP, "out2")
    ready_out.nodeX, ready_out.nodeY = 400, -150
    ready_out.inputConnectors[0].connect(ready)

    print("   presence gate: validity AND liveness (owned here now, not by the "
          "latch bank)")
    print("3. %d operators inside `%s`" % (len(group.children), GROUP))

    # -- verification -------------------------------------------------------
    failures = []
    expected = {
        "tmp_out_active": ("h0_active", "h1_active"),
        "tmp_out_entering": ("h0_entering", "h1_entering"),
        "tmp_out_exiting": ("h0_exiting", "h1_exiting"),
        "tmp_out_held": ("h0_held", "h1_held"),
        "tmp_both_active": ("both_active",),
        "tmp_n_active": ("n_active",),
        "tmp_out_vel": ("h0_vel_x", "h0_vel_y", "h1_vel_x", "h1_vel_y"),
        "tmp_speed": ("h0_speed", "h1_speed"),
        "tmp_accel": ("h0_accel", "h1_accel"),
        "tmp_out_approach": ("hands_approach",),
        "tmp_out_dir": ("h0_dir", "h0_dir_x", "h0_dir_y",
                        "h1_dir", "h1_dir_x", "h1_dir_y"),
        "tmp_out_moving": ("h0_moving", "h1_moving"),
    }
    print("4. structure:")
    for node in terminals:
        node.cook(force=True)
        actual = tuple(c.name for c in node.chans())
        want = expected[node.name]
        ok = set(actual) == set(want) and len(actual) == len(want)
        if not ok:
            failures.append("%s: expected %r, got %r" % (node.name, want, actual))
        if node.errors():
            failures.append("%s: %s" % (node.name, node.errors()))
        print("   %s %-20s %d chans  %s" % ("ok " if ok else "BAD", node.name,
                                            len(actual), " ".join(sorted(actual))))

    # -- into the COMP's output -------------------------------------------
    merge_out = comp.op("merge_out")
    if merge_out is not None:
        # Exactly once, dropping the loose `tmp_out` this group replaced.
        _attach_once(merge_out, group, drop_names=("tmp_out",))
        merge_out.cook(force=True)
        owners = [x.owner for conn in merge_out.inputConnectors
                  for x in conn.connections]
        if owners.count(group) != 1:
            failures.append("`%s` feeds merge_out %d times, not once"
                            % (GROUP, owners.count(group)))

    out_chop = comp.op("out1")
    out_chop.cook(force=True)
    print("5. COMP output: %d channels" % out_chop.numChans)
    for probe in ("h0_active", "h0_entering", "h0_held", "both_active", "n_active",
                  "h0_vel_x", "h0_speed", "h0_accel", "hands_approach",
                  "h0_dir", "h0_dir_x", "h0_moving"):
        channel = out_chop.chan(probe)
        print("   %-16s %s" % (probe, "MISSING" if channel is None
                               else round(channel[0], 4)))

    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print("\nstructure verified. Exercise it over TIME:")
        print("   send_synthetic.py swipe  --period 0.8 --cycles 20   (velocity)")
        print("   send_synthetic.py absent --cycles 1                 (exiting)")
        print("   send_synthetic.py open   --cycles 2                 (entering, held)")
    print("\nNOT YET BUILT, and each needs something this file does not have:")
    print("   hands_twist   the derivative of an ANGLE, which wraps at +/-180 and")
    print("                 spikes if differentiated naively. Publish sin/cos of")
    print("                 hands_angle from derive() and use")
    print("                 cos*d(sin) - sin*d(cos), which is wrap-free")
    print("   steadiness    Trail(Steadywindow) into Analyze, inverted")
    print("   dwell         Count gated on a radius test against a Hold")
    print("   hands_scale   needs a Hold latched by the Scalereset pulse")
    print("   swipe/wave/cross/twist events - thresholds plus a refractory Count")


main()
