#!/usr/bin/env python
"""`/project1/handtips`: fingertip x and y as two channels, paired hand by hand.

    Paste into a Text DAT, Run Script. Idempotent. Independent of every other
    builder - it READS `/project1/vision`'s hands output and writes nothing inside it.

    WHAT IT BUILDS

        vision out1 -> in1 -> tip_x -> out1     10 channels
                           -> tip_y -> out2     10 channels

    Both in PAIRED order, so index i of one lines up with index i of the other and
    consecutive pairs are the same finger on the two hands:

        0 h0_thumb   1 h1_thumb   2 h0_index   3 h1_index   4 h0_middle
        5 h1_middle  6 h0_ring    7 h1_ring    8 h0_little  9 h1_little

WHY PAIRED RATHER THAN GROUPED BY HAND. The stream's own order is every h0 channel
then every h1 channel, so this is a REORDER - and it is the whole point of the
builder. A Select CHOP emits in the order its `channames` lists, not the input's, so
one operator does it. Interleaving means a Shuffle or a geometry instancer sees
finger pairs as adjacent samples, which is what makes "draw a line between the two
index tips" or "one instance per fingertip" a one-operator job downstream.

WHY IT IS OUTSIDE THE VISION COMP. Nothing in here is part of the contract - it is a
view for looking at, and the seven builders that own `/project1/vision` all destroy
and rebuild what they own. A Select living in there would be either destroyed or a
permanent exception. Out here it is yours: rename it, duplicate it, wire it anywhere,
and re-running any vision builder cannot touch it.

    THE ONE THING IT DEPENDS ON: `vision`'s output 1 (hands). If a vision rebuild
    ever orphans this COMP's input, re-run this script - it re-wires and reports.

SPACE. `Space` on the COMP picks which coordinates:

    world     `_tx` `_ty`   ortho-camera units, centred on 0. THE DEFAULT, because
                            it is what geometry and instancing want
    normalised `_x` `_y`    the raw 0..1 off the wire, origin BOTTOM LEFT. For UVs,
                            or for anything that wants the untransformed number
    pixels    `_px` `_py`   pixels in the source image

Changing it rewrites both Selects. **The world and pixel spaces are gated** - they
come from `vision`'s `coords` group, so `Coordstx` / `Coordspx` on the vision COMP
have to be on or the channels are frozen at their last value (`ATTRIBUTES.md`). The
builder checks and says so rather than leaving you to wonder why nothing moves.

Ref: docs/ATTRIBUTES.md (the coordinate spaces and their toggles), DESIGN.md 7.
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
PARENT_PATH = "/project1"
VISION_PATH = "/project1/vision"
COMP_NAME = "handtips"

# `vision`'s output connector for the hands stream. 0-indexed: out1 is hands,
# out2 pose, out3 face (DESIGN.md 6.5).
HANDS_OUTPUT = 0

# Which coordinate pair each `Space` choice selects, and which vision toggle has to
# be on for it to be live rather than frozen. `normalised` has no toggle: it comes
# straight off the wire through the filter, which is always in the data path.
SPACES = {
    "world": ("_tx", "_ty", "Coordstx"),
    "normalised": ("_x", "_y", None),
    "pixels": ("_px", "_py", "Coordspx"),
}
SPACE_ORDER = ("world", "normalised", "pixels")

# ---- layout -----------------------------------------------------------------
COL_W = 200
ROW_H = 150

CALLBACK = '''# Generated by tools/td_add_tips.py
#
# `Space` rewrites both Selects' `channames`. A DAT rather than an expression on the
# parameter because the two lists are built from a table of joint names and a suffix,
# and an expression long enough to do that in-place is an expression nobody can read.
SPACES = %(spaces)r
TIPS = %(tips)r


def _names(suffix):
    """The paired order: h0 then h1 for each fingertip in turn."""
    return " ".join("h%%d_%%s%%s" %% (hand, tip, suffix)
                    for tip in TIPS for hand in (0, 1))


def _apply(comp):
    space = str(comp.par.Space.eval())
    x_suffix, y_suffix = SPACES.get(space, SPACES["world"])[:2]
    for name, suffix in (("tip_x", x_suffix), ("tip_y", y_suffix)):
        node = comp.op(name)
        if node is not None:
            node.par.channames = _names(suffix)


def onValueChange(par, prev):
    _apply(par.owner)


def onValuesChanged(changes):
    if changes:
        _apply(changes[0].par.owner)
'''

NOTES = """HANDTIPS - fingertip x and y, paired hand by hand. A VIEW, not contract.

  vision out1 -> in1 -> tip_x -> out1
                     -> tip_y -> out2

Both Selects emit 10 channels in the SAME paired order, so index i of one lines up
with index i of the other:

  0 h0_thumb   1 h1_thumb   2 h0_index   3 h1_index   4 h0_middle
  5 h1_middle  6 h0_ring    7 h1_ring    8 h0_little  9 h1_little

That is a REORDER: the stream's own order is every h0 channel then every h1. A
Select CHOP emits in the order its `channames` lists rather than the input's, so one
operator does it - which is what makes a Shuffle or an instancer downstream see
finger pairs as adjacent samples.

`Space` picks world (_tx/_ty), normalised (_x/_y) or pixels (_px/_py). World is the
default because it is what geometry wants. NOTE: world and pixels come from vision's
`coords` group, so Coordstx / Coordspx over there have to be ON or these channels
are FROZEN at their last value - which looks exactly like a hand that stopped moving.

THIS COMP IS YOURS. No vision builder touches it: rename it, duplicate it, wire it
wherever. The one thing it depends on is vision's output 1, and if a vision rebuild
ever orphans that input, re-run tools/td_add_tips.py.

Built by tools/td_add_tips.py."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    # The fingertip joint names, from the contract rather than typed here - so a
    # rename in the joint table reaches this builder instead of silently selecting
    # nothing.
    from visionhands.derive import FINGER_NAMES, FINGERS

    tips = [FINGERS[finger][1][-1] for finger in FINGER_NAMES]

    parent = op(PARENT_PATH)
    vision = op(VISION_PATH)
    if parent is None or vision is None:
        print("FAIL no operator at %s"
              % (PARENT_PATH if parent is None else VISION_PATH))
        return

    comp = parent.op(COMP_NAME)
    existed = comp is not None
    previous = {}
    if existed:
        previous = {par.name: par.eval() for par in comp.customPars}
    else:
        comp = parent.create(td.baseCOMP, COMP_NAME)
    comp.nodeX, comp.nodeY = 250, -400
    comp.color = (0.3, 0.45, 0.35)

    par_space = _space_par(comp)
    if "Space" not in previous:
        par_space.val = par_space.default
    else:
        par_space.val = previous["Space"]
    space = str(par_space.eval())
    x_suffix, y_suffix, toggle = SPACES[space]

    chop_in = comp.op("in1") or comp.create(td.inCHOP, "in1")
    chop_in.nodeX, chop_in.nodeY = 0, 0
    # `outputConnectors[HANDS_OUTPUT]`, not the COMP: connect() takes an operator
    # only where it has ONE unambiguous output, and `vision` has three
    # (DESIGN.md 2.11). Wired every run, so a vision rebuild that orphaned this
    # input is repaired by re-running rather than by hand.
    comp.inputConnectors[0].connect(vision.outputConnectors[HANDS_OUTPUT])

    outputs = []
    for index, (name, suffix) in enumerate((("tip_x", x_suffix),
                                            ("tip_y", y_suffix))):
        select = comp.op(name) or comp.create(td.selectCHOP, name)
        select.nodeX, select.nodeY = COL_W, -index * ROW_H
        select.inputConnectors[0].connect(chop_in)
        # The PAIRED order, and the order of this list is the order of the output -
        # which is the entire reason a Select does the job on its own.
        select.par.channames = _paired(tips, suffix)
        chop_out = comp.op("out%d" % (index + 1)) or comp.create(
            td.outCHOP, "out%d" % (index + 1))
        chop_out.nodeX, chop_out.nodeY = 2 * COL_W, -index * ROW_H
        chop_out.inputConnectors[0].connect(select)
        outputs.append((select, chop_out))

    callbacks = comp.op("space_callbacks") or comp.create(
        td.parameterexecuteDAT, "space_callbacks")
    callbacks.nodeX, callbacks.nodeY = 0, ROW_H
    callbacks.text = CALLBACK % {
        "spaces": {k: list(v[:2]) for k, v in SPACES.items()}, "tips": tips}
    callbacks.par.op = comp.path
    callbacks.par.pars = "Space"
    callbacks.par.valuechange = True
    callbacks.par.active = True

    notes = comp.op("notes") or comp.create(td.textDAT, "notes")
    notes.nodeX, notes.nodeY = 0, 2 * ROW_H
    notes.text = NOTES

    # -- verification -------------------------------------------------------
    failures = []
    chop_in.cook(force=True)
    arrived = {c.name for c in chop_in.chans()}
    for select, chop_out in outputs:
        select.cook(force=True)
        chop_out.cook(force=True)
        wanted = select.par.channames.eval().split()
        got = [c.name for c in chop_out.chans()]
        missing = [n for n in wanted if n not in arrived]
        if missing:
            failures.append(
                "%s: %d channel(s) are not on vision's output: %r. %s"
                % (select.name, len(missing), missing[:4],
                   "Turn %s on over there." % toggle if toggle
                   else "Check the hands stream is arriving."))
        elif got != wanted:
            # The property the whole builder rests on. Checked rather than trusted,
            # because a Select that fell back to input order would look almost right
            # - the same ten channels, silently grouped by hand instead of paired.
            failures.append("%s: emitted %r, asked for %r - the Select did NOT "
                            "honour the listed order" % (select.name, got[:4],
                                                         wanted[:4]))

    print("=" * 70)
    print("%s %s" % ("reusing" if existed else "created", comp.path))
    print("=" * 70)
    print("   Space = %s   ->   %s / %s" % (space, x_suffix, y_suffix))
    for select, chop_out in outputs:
        print("   %-6s -> %s  %2d channels"
              % (select.name, chop_out.name, chop_out.numChans))
    print()
    print("   paired order, both outputs identical:")
    for slot, chan in enumerate(outputs[0][1].chans()):
        print("     %d  %-22s %+.4f" % (slot, chan.name, chan[0]))

    if toggle is not None:
        live = getattr(vision.par, toggle, None)
        if live is not None and not live.eval():
            print()
            print("   NOTE %s is OFF on %s, so the %s channels are FROZEN at their"
                  % (toggle, vision.path, space))
            print("        last value - which looks exactly like a hand that has")
            print("        stopped moving. Turn it on, or set Space to normalised.")

    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print()
        print("   verified: both Selects emit the paired order they were given, and")
        print("   every channel they name is on vision's output.")
    print("=" * 70)


def _paired(tips, suffix):
    """h0 then h1 for each fingertip in turn, as a `channames` string.

    The order of this string IS the order of the Select's output, which the user
    confirmed and the builder re-checks anyway.
    """
    return " ".join("h%d_%s%s" % (hand, tip, suffix)
                    for tip in tips for hand in (0, 1))


def _space_par(comp):
    """The `Space` menu. Created once; a chosen value survives a rebuild.

    Traps: `appendCustomPage` with an existing name makes a SECOND page of that name,
           and `appendMenu` on an existing parameter RESETS it to index 0 - which here
           would silently move somebody from pixels back to world (DESIGN.md 2.11).
           The caller writes the stored value back afterwards.
    """
    page = None
    for existing in comp.customPages:
        if existing.name == "Tips":
            page = existing
            break
    if page is None:
        page = comp.appendCustomPage("Tips")
    menu = page.appendMenu("Space", label="Space")[0]
    menu.menuNames = list(SPACE_ORDER)
    menu.menuLabels = ["World (_tx/_ty)", "Normalised (_x/_y)", "Pixels (_px/_py)"]
    menu.default = "world"
    return menu


main()
