#!/usr/bin/env python
"""TOP Input: hand the sidecar an image instead of opening a camera.

    RUN IT
        run("<repo>/tools/td_add_topinput.py")

    or through the chain: tools/td_rebuild.py, layer "topinput".

WHAT IT ADDS
    in_frames      an In TOP - the COMP's image input
    frames_write   a Script TOP that copies it into the shared buffer
    Inputmode      Camera | TOP Input, on General above `Camera`
    Framesbuffer   where the buffer lives, on Advanced beside the other two

WHY A BUFFER AND NOT A PIPE. It is the transport this project already has: the mask
and the depth map arrive the same way, `appletd/maskbuf.py` is a seqlock rather than a
lock so neither side can block the other, and the reader gets a whole frame or the
previous one - never half of each.

WHAT IT COSTS, MEASURED (docs/BENCHMARKS.md): 0.26 ms at 720p on
TouchDesigner's main thread, 0.57 at 1080p. `numpyArray(delayed=True)` is what keeps it
there - `delayed=False` forces a GPU sync and spikes to 3.3 ms at 720p. The cost of
`delayed` is one frame of latency on a path that is already a frame behind.

NO CAMERA PERMISSION IS NEEDED in this mode, because no capture device is opened. That
is the second reason to want it, after "my image is not a camera".

Ref: appletd/frames.py, docs/BUILD_PLAN.md step 28.
"""

import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER_PATH = "/project1/appletd"

IN_TOP = "in_frames"
WRITER = "frames_write"
CALLBACKS = "frames_callbacks"
DEFAULT_FRAMES_PATH = "/tmp/appletd_frames.buf"

# The Script TOP's cook. Writes whatever the In TOP holds into the shared buffer.
WRITER_SOURCE = '''# Generated by tools/td_add_topinput.py
#
# One direction only: TouchDesigner -> sidecar. Every other image operator in this
# component runs the other way.
import os
import sys

%(resolver)s
_ROOT = _find_package_root(op(%(comp)r))
if _ROOT and _ROOT not in sys.path:
    sys.path.append(_ROOT)              # append, never insert

import numpy

from appletd.maskbuf import MaskWriter

# One writer for the life of the operator, reopened when the geometry changes. Opening
# per cook would mmap and unmap a megabyte every frame.
_WRITER = None
_SHAPE = None


def _writer(path, width, height):
    global _WRITER, _SHAPE
    if _WRITER is not None and _SHAPE == (path, width, height):
        return _WRITER
    if _WRITER is not None:
        _WRITER.close()
    _WRITER = MaskWriter(path, width, height, components=4)
    _SHAPE = (path, width, height)
    print("[appletd] TOP Input writing %%dx%%d to %%s" %% (width, height, path))
    return _WRITER


def onCook(scriptOp):
    comp = op(%(comp)r)
    if comp is None:
        return
    # Checked HERE and not with allowCooking, which raises on a bare operator - the
    # same arrangement seg_mask uses. The `Tick` expression already stops the cook
    # when the mode is Camera; this is the second line of defence.
    if str(comp.par.Inputmode.eval()) != "top":
        return
    source = scriptOp.inputs[0] if scriptOp.inputs else None
    if source is None:
        return
    width, height = int(source.width), int(source.height)
    if width <= 0 or height <= 0:
        return
    # `delayed=True` returns the PREVIOUS frame and does not stall the GPU.
    # MEASURED: delayed=False costs 3.3 ms at 720p in the worst case against 0.26
    # median, and the frame it buys is one this path is already behind by.
    pixels = source.numpyArray(delayed=True)
    if pixels is None:
        return
    # TouchDesigner hands back RGBA, FLOAT32, bottom row first - whatever the TOP's
    # own format is. Vision wants BGRA bytes, top row first.
    #
    # CLIPPED, and this is not defensive tidiness. `numpyArray` normalises 8-bit
    # formats to 0..1, but a float TOP is not bounded: MEASURED, a plain
    # noiseTOP at rgba16float returned -0.060 to 1.149. Scaling that without a clip
    # wraps in the uint8 cast, so the brightest pixels in an HDR image come out DARK
    # and the mistake looks like a bad camera rather than a bad conversion.
    frame = numpy.clip(pixels[::-1, :, [2, 1, 0, 3]], 0.0, 1.0)
    frame = (frame * 255.0 + 0.5).astype("uint8")     # + 0.5 rounds, cast truncates
    _writer(str(comp.par.Framesbuffer.eval()), width, height).write(
        numpy.ascontiguousarray(frame).tobytes())
    # The operator passes its input through, so it shows what it sent rather than
    # whatever it last held - a Script TOP that publishes nothing is hard to tell
    # from one that is not cooking.
    scriptOp.copyNumpyArray(pixels)
'''


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.td_layout import PACKAGE_ROOT_SOURCE, master_xy

    comp = op(MASTER_PATH)
    if comp is None:
        print("no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("topinput: an image input on %s" % comp.path)
    print("=" * 70)

    general = advanced = None
    for page in comp.customPages:
        if page.name == "General":
            general = page
        elif page.name == "Advanced":
            advanced = page
    if general is None or advanced is None:
        print("FAIL no General/Advanced page - run tools/td_build_vision.py first")
        return

    existing = {par.name for par in comp.customPars}
    if "Inputmode" not in existing:
        # A MENU and not a toggle: "Camera or not" is two states today and the third
        # - a file, a stream - would have nowhere to go on a toggle.
        mode = general.appendMenu("Inputmode", label="Input Mode")[0]
        mode.menuNames = ["camera", "top"]
        mode.menuLabels = ["Camera", "TOP Input"]
        mode.default = "camera"
    if "Framesbuffer" not in existing:
        # Beside `Maskbuffer` and `Depthbuffer` on Advanced: a path that has to match
        # on both sides is not something a consumer of this COMP chooses.
        path = advanced.appendStr("Framesbuffer", label="Frames Buffer")[0]
        path.default = DEFAULT_FRAMES_PATH
        path.val = DEFAULT_FRAMES_PATH

    # -- the input, and the writer ----------------------------------------
    in_top = comp.op(IN_TOP) or comp.create(td.inTOP, IN_TOP)
    in_top.nodeX, in_top.nodeY = master_xy(IN_TOP)
    # PRESERVED, never recreated - an In TOP IS the COMP's input connector, and
    # destroying it disconnects whatever the project had wired to it.

    # The code goes in a DAT, not on the operator: a Script TOP has no `.text` - its
    # cook lives in whatever its `callbacks` parameter points at.
    callbacks = comp.op(CALLBACKS) or comp.create(td.textDAT, CALLBACKS)
    callbacks.nodeX, callbacks.nodeY = master_xy(CALLBACKS)
    callbacks.text = WRITER_SOURCE % {"comp": comp.path,
                                      "resolver": PACKAGE_ROOT_SOURCE}

    existed = comp.op(WRITER) is not None
    writer = comp.op(WRITER) or comp.create(td.scriptTOP, WRITER)
    writer.nodeX, writer.nodeY = master_xy(WRITER)
    if not existed:
        # Creating a Script TOP auto-docks a callbacks DAT of its own. Destroyed, or
        # two of them sit there and only one is the one being edited - the same
        # cleanup td_add_segmentation.py does for `seg_mask`.
        for child in list(comp.children):
            if child.name.startswith(WRITER + "_callbacks") and child.valid:
                child.destroy()
    writer.par.callbacks = callbacks.path
    writer.inputConnectors[0].connect(in_top)
    writer.color = (0.35, 0.45, 0.5)

    tick_page = None
    for page in writer.customPages:
        if page.name == "Tick":
            tick_page = page
            break
    if tick_page is None:
        tick_page = writer.appendCustomPage("Tick")
    if not hasattr(writer.par, "Tick"):
        tick_page.appendInt("Tick", label="Tick (drives the cook - do not set)")
    # An input-less Script TOP is never dirtied on its own, and this one has an input
    # that only changes when the project changes it. The expression goes CONSTANT when
    # the mode is Camera, which is what stops the cook (DESIGN.md 2.21).
    writer.par.Tick.expr = (
        "absTime.frame if op.Appletd.par.Inputmode == 'top' else 0")
    writer.par.Tick.readOnly = True

    print("   %-14s <- the COMP's image input" % IN_TOP)
    print("   %-14s -> %s" % (WRITER, comp.par.Framesbuffer.eval()))
    print("   Input Mode  = %s" % comp.par.Inputmode.eval())
    print()
    print("   verified. In TOP Input mode no camera is opened at all, so no camera")
    print("   permission is needed. MEASURED: 0.26 ms a frame at 720p.")


main()
