"""The TouchDesigner side of the depth map: shared memory -> a TOP, plus the fit.

WHAT THIS BUILDS, inside /project1/vision:

    depth_map (Script TOP)  ->  depth_fit (Fit TOP)  ->  outdepth (Out TOP)
       reads the fp16 mmap,       undoes the              the COMP's second
       flips y, widens to         anisotropic stretch     TOP output
       float32

and a `Depth` page carrying the fit readout. Idempotent; run it any time.

THREE THINGS THAT MAKE THIS DIFFERENT FROM THE MASK, and each cost a measurement:

  * THE PAYLOAD IS FP16 and `copyNumpyArray` REFUSES IT - "Arrays with float data must
    be float32" (MEASURED, DESIGN.md 2.20). So the Script TOP widens: 406 KB in, 812
    KB out, one `astype` per frame. That is the price of the model's ~7,300 distinct
    levels, and it is worth paying - an 8-bit path would cap at 256 and quantise the
    pin solve to a sixth of its precision (DESIGN.md 2.22).
  * IT IS INVERSE DEPTH, and BIGGER MEANS NEARER. The model's graph divides by the
    frame's own maximum, so the raw map is not comparable between frames - a hand
    coming toward the lens darkens everything else. Nothing may be built on the raw
    numbers without pins. `Depthfit*` below is how a project finds out whether it has
    a usable fit, and `visionhands/pins.py` is the argument.
  * THE FIT TRAVELS IN THE BUFFER'S AUX BLOCK, not on a parameter of its own, because
    it is solved from ONE frame and is meaningless against any other. The Script TOP
    unpacks it and writes it onto read-only parameters so a project can gate on it.

WHAT THIS DOES NOT DO. It does not convert to metres. `Z = 1 / (alpha*d + beta)` is
two parameters and a reciprocal, which is a GLSL TOP or an expression on whatever is
reading it - and doing it here would mean choosing a clamp and a colour map on
somebody else's behalf, on the main thread, for every project whether it wants metres
or not. `Depthfitalpha` and `Depthfitbeta` are published for exactly that.

Ref: docs/DEPTH.md (first run, and the pins), design/DESIGN.md 2.22,
     visionhands/depth.py, visionhands/pins.py, tools/td_add_segmentation.py.
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
MASTER_PATH = "/project1/vision"

PAGE = "Depth"

# Parameters this builder used to own and no longer does. Empty today, and kept
# because removing the code that creates a parameter does not remove the parameter -
# `Segment` sat on a page driving nothing for two commits before anybody noticed
# (docs/BUILD_PLAN.md, TouchDesigner facts). A retire table from the start costs
# nothing and is the only thing that cleans one up.
RETIRED_PARS: dict[str, str] = {}

CALLBACK_SOURCE = '''# Generated by tools/td_add_depth.py
#
# Reads the shared depth buffer and publishes it as a TOP. One `os.stat`, one coherent
# read of ~400 KB, one y-flip, one fp16 -> float32 widening, one `copyNumpyArray`.
import sys

REPO_ROOT = %(repo)r
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)

import numpy

from visionhands.maskbuf import MaskReader
from visionhands.pins import unpack

# The reader lives in MODULE GLOBALS and never in operator storage. TouchDesigner
# PICKLES operator storage into the .toe on save, and an `mmap` cannot be pickled -
# which is exactly how this project lost the ability to save on 2026-08-21.
_READERS = {}

# 16x16, and the SIZE is the diagnostic: a shape nothing else in this path produces,
# so "the buffer has never been read" is answerable at a glance. The mask's blank was
# once the same size as a real mask and that turned a five-minute diagnosis into a
# long one (DESIGN.md 2.21).
_BLANK = numpy.zeros((16, 16, 1), dtype=numpy.float32)


def _reader(path):
    """One MaskReader per path, cached. None if the file is not there yet."""
    reader = _READERS.get(path)
    if reader is not None:
        return reader
    try:
        reader = MaskReader(path)
    except (OSError, ValueError):
        # OSError: not there yet - the normal state before the sidecar starts.
        # ValueError: there but too small to hold a header, i.e. mid-creation.
        return None
    _READERS[path] = reader
    return reader


def onCook(scriptOp):
    comp = op.Vision or scriptOp.parent()

    # `Streamdepth` - the SAME toggle that puts `depth` on the sidecar's command line.
    # What actually stops the work is the `Tick` expression going constant (see the
    # builder); this branch runs on the one cook after the toggle changes, and releases
    # the mmap so a project not using depth holds no file handle.
    if hasattr(comp.par, "Streamdepth") and not bool(comp.par.Streamdepth.eval()):
        reader = _READERS.pop(str(comp.par.Depthbuffer.eval()), None)
        if reader is not None:
            reader.close()
        scriptOp.copyNumpyArray(_BLANK)
        return

    path = str(comp.par.Depthbuffer.eval()) if hasattr(comp.par, "Depthbuffer") else ""
    reader = _reader(path) if path else None
    if reader is None:
        scriptOp.copyNumpyArray(_BLANK)
        return

    try:
        frame = reader.read()
    except ValueError:
        # A non-zero wrong magic, or a version this reader does not speak. Drop the
        # reader so a corrected path is picked up, and let it raise - it is a wiring
        # mistake, not a race, and swallowing it would show a blank for ever.
        _READERS.pop(path, None)
        scriptOp.copyNumpyArray(_BLANK)
        raise

    if frame is None:
        # Nothing published yet, or the writer won the race. HOLD the previous frame
        # by returning without copying, which is right for a depth map and is why the
        # reader never blocks.
        return

    # fp16 -> float32, because `copyNumpyArray` REFUSES float16: "Arrays with float
    # data must be float32" (MEASURED). `[::-1]` is the y flip - the model's map has
    # its origin top-left and TouchDesigner's TOP arrays are bottom-up. The `astype`
    # already makes a new contiguous array, so no `ascontiguousarray` is needed on top.
    array = frame.as_numpy()
    scriptOp.copyNumpyArray(
        array[::-1].astype(numpy.float32).reshape(frame.height, frame.width, 1))

    # The source geometry, for the Fit TOP.
    if hasattr(comp.par, "Depthsourcew") and frame.source_width:
        if int(comp.par.Depthsourcew.eval()) != frame.source_width:
            comp.par.Depthsourcew = frame.source_width
        if int(comp.par.Depthsourceh.eval()) != frame.source_height:
            comp.par.Depthsourceh = frame.source_height

    # THE FIT, unpacked out of the aux block that travelled with these pixels. Written
    # onto read-only parameters rather than published as channels: they are four
    # numbers per frame, and a CHOP for them would be a fifth transport for a project
    # that may not want metres at all.
    fit = unpack(frame.aux)
    _write(comp, "Depthfitalpha", fit.get("alpha", 0.0))
    _write(comp, "Depthfitbeta", fit.get("beta", 0.0))
    _write(comp, "Depthfitpins", fit.get("used", 0.0))
    _write(comp, "Depthfitresidual", fit.get("worst_residual_m", 0.0))
    # 1 only when the residual MEANS something. Two pins always fit a line exactly, so
    # a residual of 0.000 from two pins reads as a perfect fit while checking nothing -
    # this is the flag that says which it is (visionhands/pins.py).
    _write(comp, "Depthfitchecked", fit.get("residual_is_a_check", 0.0))


def _write(comp, name, value):
    """Set a readout parameter, only when it changed.

    Only when it CHANGED: writing a parameter dirties everything that depends on it,
    and four unconditional writes a frame would re-cook every expression watching them
    sixty times a second for numbers that mostly do not move.
    """
    par = getattr(comp.par, name, None)
    if par is not None and par.eval() != value:
        par.val = value
'''


def _page(comp, name):
    """Find or create a custom page. TRAP: `appendCustomPage` with an existing name
    makes a SECOND page of that name, so the existing one is looked up first."""
    for existing in comp.customPages:
        if existing.name == name:
            return existing
    return comp.appendCustomPage(name)


def _at(node, xy, keep, existed):
    from visionhands.td_layout import placement
    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    from visionhands.td_layout import master_xy

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("depth: shared memory -> a TOP, in %s" % master.path)
    print("=" * 70)

    keep_layout = bool(master.par.Keeplayout.eval()) \
        if hasattr(master.par, "Keeplayout") else False

    # -- retire, then append only what is absent ---------------------------
    for stale_name in RETIRED_PARS:
        stale = getattr(master.par, stale_name, None)
        if stale is not None:
            stale.destroy()
            print("   retired `%s` - %s" % (stale_name, RETIRED_PARS[stale_name]))

    # `append*` on an EXISTING parameter resets it, and the reset fires a deferred
    # callback that outlives any write-it-back fix (DESIGN.md 2.17). So: only what is
    # absent, and nothing that exists is touched except its `default`.
    page = _page(master, PAGE)
    existing = {par.name: par for par in master.customPars}

    fit_par = existing.get("Depthfit")
    if fit_par is None:
        fit_par = page.appendToggle("Depthfit", label="Fit Map To Source")[0]
        fit_par.val = True
    fit_par.default = True

    # The READOUTS. Written by the Script TOP from the buffer's aux block, read-only
    # because they are a report and not a setting - a settable one would silently
    # fight the solve every frame.
    readouts = (
        ("Depthsourcew", "Source Width (from the buffer)", 1280),
        ("Depthsourceh", "Source Height (from the buffer)", 720),
    )
    for name, label, default in readouts:
        par = existing.get(name)
        if par is None:
            par = page.appendInt(name, label=label)[0]
            par.val = default
        par.default = default
        par.readOnly = True

    floats = (
        ("Depthfitalpha", "Fit alpha  (1/Z = alpha*d + beta)"),
        ("Depthfitbeta", "Fit beta"),
        ("Depthfitresidual", "Worst Residual (m)"),
    )
    for name, label in floats:
        par = existing.get(name)
        if par is None:
            par = page.appendFloat(name, label=label)[0]
            par.val = 0.0
        par.default = 0.0
        par.readOnly = True

    for name, label in (("Depthfitpins", "Pins Used"),
                        ("Depthfitchecked", "Residual Is A Check")):
        par = existing.get(name)
        if par is None:
            par = page.appendInt(name, label=label)[0]
            par.val = 0
        par.default = 0
        par.readOnly = True

    print("1. `%s` page: Depthfit=%s, %d readouts"
          % (PAGE, bool(fit_par.eval()), len(readouts) + len(floats) + 2))
    print("   from td_build_vision.py: Streamdepth=%s, Depthbuffer=%r"
          % (getattr(master.par, "Streamdepth", None)
             and bool(master.par.Streamdepth.eval()),
             getattr(master.par, "Depthbuffer", None)
             and master.par.Depthbuffer.eval()))

    # -- the callbacks DAT -------------------------------------------------
    callbacks = master.op("depth_callbacks") or master.create(td.textDAT,
                                                             "depth_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("depth_callbacks")
    callbacks.text = CALLBACK_SOURCE % {"repo": REPO_ROOT}

    # -- the Script TOP ----------------------------------------------------
    script = master.op("depth_map")
    script_existed = script is not None
    if script is None:
        script = master.create(td.scriptTOP, "depth_map")
        # Creating a Script TOP auto-docks its own callbacks DAT. Destroy it, or two
        # DATs claim the same job and only one is the generated one.
        for child in list(master.children):
            if child.name.startswith("depth_map_callbacks") and child.valid:
                child.destroy()
    _at(script, master_xy("depth_map"), keep_layout, script_existed)
    script.par.callbacks = callbacks.path
    # `mono32float`: one 32-bit float per pixel. The payload is fp16 and this is the
    # nearest float format TouchDesigner offers - `mono16float` would be exact, but
    # `copyNumpyArray` refuses float16 input, so the array is float32 by the time it
    # gets here and asking the GPU to narrow it again would lose the precision twice.
    script.par.format = "mono32float"
    script.color = (0.3, 0.4, 0.55)

    # THE THING THAT MAKES IT COOK. A Script TOP with no input is never dirtied, so it
    # cooks once and serves that texture for ever - there is no Cook Type parameter to
    # fix it with (MEASURED, DESIGN.md 2.21, and it cost an afternoon on the mask).
    # A custom parameter whose value changes each frame is what dirties it, gated on
    # the toggle so the expression goes constant when depth is off.
    tick_page = None
    for existing_page in script.customPages:
        if existing_page.name == "Tick":
            tick_page = existing_page
            break
    if tick_page is None:
        tick_page = script.appendCustomPage("Tick")
    if not hasattr(script.par, "Tick"):
        tick_page.appendInt("Tick", label="Tick (drives the cook - do not set)")
    script.par.Tick.expr = "absTime.frame if op.Vision.par.Streamdepth else 0"
    script.par.Tick.readOnly = True

    # -- the Fit TOP -------------------------------------------------------
    fit_top = master.op("depth_fit")
    fit_existed = fit_top is not None
    if fit_top is None:
        fit_top = master.create(td.fitTOP, "depth_fit")
    _at(fit_top, master_xy("depth_fit"), keep_layout, fit_existed)
    fit_top.inputConnectors[0].connect(script)
    # `fill` is the NON-UNIFORM stretch, which is the correction needed: the model is
    # 518x392 (1.32:1) and a webcam is 1.78:1, and `crop = fill` on the request side
    # squashed the whole frame in - so the map covers exactly the pixels you can see
    # and stretching it back is exact rather than approximate.
    fit_top.par.fit = "fill"
    fit_top.par.outputresolution = "custom"
    fit_top.par.resolutionw.expr = "op('%s').par.Depthsourcew" % master.path
    fit_top.par.resolutionh.expr = "op('%s').par.Depthsourceh" % master.path
    fit_top.par.format = "mono32float"
    fit_top.bypass = not bool(fit_par.eval())

    out = master.op("outdepth")
    out_existed = out is not None
    if out is None:
        out = master.create(td.outTOP, "outdepth")
    _at(out, master_xy("outdepth"), keep_layout, out_existed)
    # PRESERVED, never recreated - an Out TOP IS a COMP output connector.
    out.inputConnectors[0].connect(fit_top)

    print("2. depth_map -> depth_fit -> outdepth")
    print("   depth_map format=mono32float (fp16 in, widened - copyNumpyArray "
          "refuses float16)")
    print("   depth_fit  fit=fill, resolution from Depthsourcew/h (%dx%d), bypass=%s"
          % (int(master.par.Depthsourcew.eval()),
             int(master.par.Depthsourceh.eval()), fit_top.bypass))

    # -- the parameter callbacks -------------------------------------------
    par_exec = master.op("depth_par_callbacks") or master.create(
        td.parameterexecuteDAT, "depth_par_callbacks")
    par_exec.nodeX, par_exec.nodeY = master_xy("depth_par_callbacks")
    par_exec.text = (
        "# Generated by tools/td_add_depth.py\n"
        "#\n"
        "# `bypass` is an ATTRIBUTE, not a parameter, so it cannot be bound to an\n"
        "# expression and is written on change instead.\n"
        "#\n"
        "# `Streamdepth` is NOT handled here: `allowCooking` cannot be disabled on a\n"
        "# bare operator (measured - it raises), so the Script TOP checks that\n"
        "# toggle itself. It is listed below so that switching it forces a cook.\n"
        "\n"
        "def onValueChange(par, prev):\n"
        "    comp = par.owner\n"
        "    fit = comp.op('depth_fit')\n"
        "    if fit is not None:\n"
        "        fit.bypass = not bool(comp.par.Depthfit.eval())\n"
        "    script = comp.op('depth_map')\n"
        "    if script is not None:\n"
        "        script.cook(force=True)\n")
    par_exec.par.op = master.path
    par_exec.par.pars = "Streamdepth Depthfit"
    par_exec.par.valuechange = True
    print("3. Streamdepth and Depthfit wired through %s" % par_exec.name)

    # -- report ------------------------------------------------------------
    print()
    on = getattr(master.par, "Streamdepth", None)
    if on is None or not bool(on.eval()):
        print("   `Streamdepth` is OFF, so `depth_map` publishes blank.")
        print("   FIRST RUN? The model is 47 MB and is not in this repo:")
        print("     ./tools/fetch_models.sh")
        print("   Check it with no camera and no TouchDesigner:")
        print("     ~/.venvs/visionhands/bin/python tools/depth_probe.py")
        print("   Then switch Streamdepth on and press Active. docs/DEPTH.md has")
        print("   the pins, which are what turn the map into metres.")
    else:
        print("   `Streamdepth` is on. The map is RELATIVE and bigger means NEARER")
        print("   until pins are set - `Depthfitpins` says how many are in use, and")
        print("   `Depthfitchecked` says whether the residual means anything.")
    print("=" * 70)


main()
