#!/usr/bin/env python
"""`/project1/handtips`: fingertip x and y as two channels, paired hand by hand.

    Paste into a Text DAT, Run Script. Idempotent. Independent of every other
    builder - it READS `/project1/vision`'s hands output and writes nothing inside it.

    WHAT IT BUILDS

        vision out1 -> in1 -> tips -> out1     20 channels

    ONE Select, both axes, because a Shuffle CHOP downstream reshapes them - which
    is the user's own finding and it is a better arrangement than two Selects: the
    two axes cannot drift out of step if they are one operator's output.

    Ten fingertips in PAIRED order - h0 then h1 for each tip in turn - so
    consecutive samples after the shuffle are the same finger on the two hands:

        0 h0_thumb   1 h1_thumb   2 h0_index   3 h1_index   4 h0_middle
        5 h1_middle  6 h0_ring    7 h1_ring    8 h0_little  9 h1_little

WHY PAIRED RATHER THAN GROUPED BY HAND. The stream's own order is every h0 channel
then every h1 channel, so this is a REORDER - and it is the whole point of the
builder. A Select CHOP emits in the order its `channames` lists, not the input's, so
one operator does it. Pairing means a Shuffle or a geometry instancer sees finger
pairs as adjacent samples, which is what makes "draw a line between the two index
tips" or "one instance per fingertip" a one-operator job downstream.

ORDER. `Order` picks how the two axes sit in the channel list, because which one a
Shuffle wants depends on how it is reshaping:

    blocked      all ten x, then all ten y. THE DEFAULT - contiguous blocks are
                 what a Shuffle splitting channels into samples wants, and it is
                 the usual instancing shape: 20 channels -> 2 channels x 10 samples
    interleaved  x then y for each tip in turn - h0_thumb_tx, h0_thumb_ty,
                 h1_thumb_tx, h1_thumb_ty, ... For a shuffle that walks the list in
                 pairs, or for reading a single tip's xy off adjacent channels

Both keep the same paired fingertip order; only the axis grouping changes.

WHY IT IS OUTSIDE THE VISION COMP. Nothing in here is part of the contract - it is a
view for looking at, and the seven builders that own `/project1/vision` all destroy
and rebuild what they own. A Select living in there would be either destroyed or a
permanent exception. Out here it is yours: rename it, duplicate it, wire it anywhere,
and re-running any vision builder cannot touch it.

    THE ONE THING IT DEPENDS ON: `vision`'s output 1 (hands). If a vision rebuild
    ever orphans this COMP's input, re-run this script - it re-wires and reports.

SPACE. `Space` on the COMP picks which coordinates:

    world     `_tx` `_ty`   ortho-camera units, centred on 0. THE DEFAULT, because
                            it is what geometry and instancing want
    normalised `_x` `_y`    the raw 0..1 off the wire, origin BOTTOM LEFT. For UVs,
                            or for anything that wants the untransformed number
    pixels    `_px` `_py`   pixels in the source image

Changing it rewrites both Selects. **The world and pixel spaces are gated** - they
come from `vision`'s `coords` group, so `Coordstx` / `Coordspx` on the vision COMP
have to be on or the channels are frozen at their last value (`ATTRIBUTES.md`). The
builder checks and says so rather than leaving you to wonder why nothing moves.

Ref: docs/ATTRIBUTES.md (the coordinate spaces and their toggles), DESIGN.md 7.
"""

import os
import sys

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARENT_PATH = "/project1"
VISION_PATH = "/project1/vision"
COMP_NAME = "handtips"

# `vision`'s output connector for the hands stream. 0-indexed: out1 is hands,
# out2 pose, out3 face (DESIGN.md 6.5).
HANDS_OUTPUT = 0

# Which coordinate pair each `Space` choice selects, and which vision toggle has to
# be on for it to be live rather than frozen. `normalised` has no toggle: it comes
# straight off the wire through the filter, which is always in the data path.
SPACES = {
    "world": ("_tx", "_ty", "Coordstx"),
    "normalised": ("_x", "_y", None),
    "pixels": ("_px", "_py", "Coordspx"),
}
SPACE_ORDER = ("world", "normalised", "pixels")

# How the two axes sit in the one channel list. Which a Shuffle wants depends on how
# it reshapes, so both are here and the default is the contiguous one.
ORDER_BLOCKED = "blocked"
ORDER_INTERLEAVED = "interleaved"
ORDERS = (ORDER_BLOCKED, ORDER_INTERLEAVED)

# ---- layout -----------------------------------------------------------------
COL_W = 200
ROW_H = 150

CALLBACK = '''# Generated by tools/td_add_tips.py
#
# `Space` and `Order` rewrite the one Select's `channames`. A DAT rather than an
# expression on the parameter because the list is built from a table of joint names
# and two suffixes, and an expression long enough to do that in place is one nobody
# can read.
SPACES = %(spaces)r
TIPS = %(tips)r
INTERLEAVED = %(interleaved)r


def _names(x_suffix, y_suffix, order):
    """Fingertips always PAIRED - h0 then h1 per tip. `order` places the axes."""
    pairs = [(hand, tip) for tip in TIPS for hand in (0, 1)]
    if order == INTERLEAVED:
        return " ".join("h%%d_%%s%%s" %% (hand, tip, suffix)
                        for hand, tip in pairs
                        for suffix in (x_suffix, y_suffix))
    return " ".join("h%%d_%%s%%s" %% (hand, tip, suffix)
                    for suffix in (x_suffix, y_suffix)
                    for hand, tip in pairs)


def _apply(comp):
    space = str(comp.par.Space.eval())
    x_suffix, y_suffix = SPACES.get(space, SPACES["world"])[:2]
    node = comp.op("tips")
    if node is not None:
        node.par.channames = _names(x_suffix, y_suffix,
                                    str(comp.par.Order.eval()))


def onValueChange(par, prev):
    _apply(par.owner)


def onValuesChanged(changes):
    if changes:
        _apply(changes[0].par.owner)
'''

NOTES = """HANDTIPS - fingertip x and y in ONE Select. A VIEW, not contract.

  vision out1 -> in1 -> tips -> out1      20 channels

Ten fingertips in PAIRED order - h0 then h1 for each tip in turn - so consecutive
samples after a Shuffle are the same finger on the two hands:

  0 h0_thumb   1 h1_thumb   2 h0_index   3 h1_index   4 h0_middle
  5 h1_middle  6 h0_ring    7 h1_ring    8 h0_little  9 h1_little

That is a REORDER: the stream's own order is every h0 channel then every h1. A
Select CHOP emits in the order its `channames` lists rather than the input's, so one
operator does it.

ONE Select rather than two, because a Shuffle downstream reshapes both axes - and
the two axes cannot drift out of step if they are one operator's output.

  Order   blocked      all ten x, then all ten y. The default: contiguous blocks
                       are what a Shuffle splitting channels into samples wants
          interleaved  x then y per tip - h0_thumb_tx, h0_thumb_ty, h1_thumb_tx, ...

  Space   world (_tx/_ty), normalised (_x/_y) or pixels (_px/_py). World is the
          default because it is what geometry wants.

NOTE: world and pixels come from vision's `coords` group, so Coordstx / Coordspx
over there have to be ON or these channels are FROZEN at their last value - which
looks exactly like a hand that stopped moving.

AN ABSENT HAND reads -0.5 * Orthowidth in world space, not zero: raw 0 goes through
(0 - 0.5) * Orthowidth. `h1_found` on the vision output is the gate. In normalised
space it reads 0.

THIS COMP IS YOURS. No vision builder touches it: rename it, duplicate it, wire it
wherever. The one thing it depends on is vision's output 1, and if a vision rebuild
ever orphans that input, re-run tools/td_add_tips.py.

Built by tools/td_add_tips.py."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    # The fingertip joint names, from the contract rather than typed here - so a
    # rename in the joint table reaches this builder instead of silently selecting
    # nothing.
    from appletd.derive import FINGER_NAMES, FINGERS

    tips = [FINGERS[finger][1][-1] for finger in FINGER_NAMES]

    parent = op(PARENT_PATH)
    vision = op(VISION_PATH)
    if parent is None or vision is None:
        print("FAIL no operator at %s"
              % (PARENT_PATH if parent is None else VISION_PATH))
        return

    comp = parent.op(COMP_NAME)
    existed = comp is not None
    previous = {}
    if existed:
        previous = {par.name: par.eval() for par in comp.customPars}
    else:
        comp = parent.create(td.baseCOMP, COMP_NAME)
    comp.nodeX, comp.nodeY = 250, -400
    comp.color = (0.3, 0.45, 0.35)

    par_space, par_order = _menus(comp)
    # `appendMenu` on an EXISTING parameter resets it to index 0 (DESIGN.md 2.11), so
    # a stored choice is written back unconditionally - otherwise a rebuild would
    # silently move somebody from pixels to world, or from interleaved to blocked.
    for name, par in (("Space", par_space), ("Order", par_order)):
        par.val = previous.get(name, par.default)
    space = str(par_space.eval())
    order = str(par_order.eval())
    x_suffix, y_suffix, toggle = SPACES[space]

    chop_in = comp.op("in1") or comp.create(td.inCHOP, "in1")
    chop_in.nodeX, chop_in.nodeY = 0, 0
    # `outputConnectors[HANDS_OUTPUT]`, not the COMP: connect() takes an operator
    # only where it has ONE unambiguous output, and `vision` has three
    # (DESIGN.md 2.11). Wired every run, so a vision rebuild that orphaned this
    # input is repaired by re-running rather than by hand.
    comp.inputConnectors[0].connect(vision.outputConnectors[HANDS_OUTPUT])

    # RETIRE the two-Select shape this replaces. Nothing outside the COMP was wired
    # to either output when this changed - checked before restructuring, because
    # collapsing them alters out1's channel count and removes out2, and an orphaned
    # consumer is indistinguishable from one that was never connected
    # (DESIGN.md 2.11).
    retired = []
    for name in ("tip_x", "tip_y", "out2"):
        stale = comp.op(name)
        if stale is not None and stale.valid:
            stale.destroy()
            retired.append(name)

    select = comp.op("tips") or comp.create(td.selectCHOP, "tips")
    select.nodeX, select.nodeY = COL_W, 0
    select.inputConnectors[0].connect(chop_in)
    # The order of this list IS the order of the output, which is the entire reason
    # one Select does the job on its own.
    select.par.channames = _paired(tips, x_suffix, y_suffix, order)
    chop_out = comp.op("out1") or comp.create(td.outCHOP, "out1")
    chop_out.nodeX, chop_out.nodeY = 2 * COL_W, 0
    chop_out.inputConnectors[0].connect(select)

    callbacks = comp.op("space_callbacks") or comp.create(
        td.parameterexecuteDAT, "space_callbacks")
    callbacks.nodeX, callbacks.nodeY = 0, ROW_H
    callbacks.text = CALLBACK % {
        "spaces": {k: list(v[:2]) for k, v in SPACES.items()}, "tips": tips,
        "interleaved": ORDER_INTERLEAVED}
    callbacks.par.op = comp.path
    callbacks.par.pars = "Space Order"
    callbacks.par.valuechange = True
    callbacks.par.active = True

    notes = comp.op("notes") or comp.create(td.textDAT, "notes")
    notes.nodeX, notes.nodeY = 0, 2 * ROW_H
    notes.text = NOTES

    # -- verification -------------------------------------------------------
    failures = []
    chop_in.cook(force=True)
    arrived = {c.name for c in chop_in.chans()}
    select.cook(force=True)
    chop_out.cook(force=True)
    wanted = select.par.channames.eval().split()
    got = [c.name for c in chop_out.chans()]
    missing = [n for n in wanted if n not in arrived]
    if missing:
        failures.append(
            "%d channel(s) are not on vision's output: %r. %s"
            % (len(missing), missing[:4],
               "Turn %s on over there." % toggle if toggle
               else "Check the hands stream is arriving."))
    elif got != wanted:
        # The property the whole builder rests on. Checked rather than trusted,
        # because a Select that fell back to input order would look almost right -
        # the same twenty channels, silently grouped by hand instead of paired.
        failures.append("emitted %r, asked for %r - the Select did NOT honour the "
                        "listed order" % (got[:4], wanted[:4]))

    print("=" * 70)
    print("%s %s" % ("reusing" if existed else "created", comp.path))
    print("=" * 70)
    if retired:
        print("   retired %s (the two-Select shape this replaces)"
              % ", ".join(retired))
    print("   Space = %-11s -> %s / %s" % (space, x_suffix, y_suffix))
    print("   Order = %-11s -> %s" % (order, "all x then all y"
                                      if order == ORDER_BLOCKED
                                      else "x, y per tip"))
    print("   tips -> out1  %d channels" % chop_out.numChans)
    print()
    for slot, chan in enumerate(chop_out.chans()):
        print("     %2d  %-24s %+.4f" % (slot, chan.name, chan[0]))

    if toggle is not None:
        live = getattr(vision.par, toggle, None)
        if live is not None and not live.eval():
            print()
            print("   NOTE %s is OFF on %s, so the %s channels are FROZEN at their"
                  % (toggle, vision.path, space))
            print("        last value - which looks exactly like a hand that has")
            print("        stopped moving. Turn it on, or set Space to normalised.")

    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print()
        print("   verified: the Select emits the paired order it was given, and")
        print("   every channel it names is on vision's output.")
    print("=" * 70)


def _paired(tips, x_suffix, y_suffix, order):
    """The one channel list, as a `channames` string.

    Contract: fingertips always in PAIRED order - h0 then h1 for each tip in turn.
              `order` decides only where the two axes go:
                `blocked`      ten x in that order, then ten y
                `interleaved`  x then y for each tip-hand in turn
    The order of this string IS the order of the Select's output, which the user
    confirmed and the builder re-checks anyway.
    """
    pairs = [(hand, tip) for tip in tips for hand in (0, 1)]
    if order == ORDER_INTERLEAVED:
        return " ".join("h%d_%s%s" % (hand, tip, suffix)
                        for hand, tip in pairs
                        for suffix in (x_suffix, y_suffix))
    return " ".join("h%d_%s%s" % (hand, tip, suffix)
                    for suffix in (x_suffix, y_suffix)
                    for hand, tip in pairs)


def _menus(comp):
    """The `Space` and `Order` menus. Created once; chosen values survive a rebuild.

    Traps: `appendCustomPage` with an existing name makes a SECOND page of that name,
           and `appendMenu` on an existing parameter RESETS it to index 0 - which here
           would silently move somebody from pixels back to world (DESIGN.md 2.11).
           The caller writes the stored values back afterwards.
    """
    page = None
    for existing in comp.customPages:
        if existing.name == "Tips":
            page = existing
            break
    if page is None:
        page = comp.appendCustomPage("Tips")

    space = page.appendMenu("Space", label="Space")[0]
    space.menuNames = list(SPACE_ORDER)
    space.menuLabels = ["World (_tx/_ty)", "Normalised (_x/_y)", "Pixels (_px/_py)"]
    space.default = "world"

    order = page.appendMenu("Order", label="Channel Order")[0]
    order.menuNames = list(ORDERS)
    order.menuLabels = ["Blocked (all x, then all y)", "Interleaved (x, y per tip)"]
    order.default = ORDER_BLOCKED
    return space, order


main()
