"""The TouchDesigner side of the segmentation mask: shared memory -> a TOP.

WHAT THIS BUILDS, inside /project1/vision:

    seg_mask (Script TOP)  ->  seg_fit (Fit TOP)  ->  outmask (Out TOP)
       reads the mmap            undoes the             the COMP's only
       and flips y               anisotropic stretch    TOP output

and a `Segmentation` parameter page carrying the buffer path, the master toggle and
the fit toggle. Run it any time; it is idempotent.

WHY THREE OPERATORS AND NOT ONE. Each does the one thing it is cheapest at:

  * the SCRIPT TOP does what only Python can - read the shared buffer - and nothing
    else that costs. It copies `width * height` bytes straight in as `uint8`, which
    `copyNumpyArray` accepts natively (VERIFIED: no float32 conversion needed).
  * the Y FLIP is in the Script TOP, because that is the operator that knows the
    convention. Vision's mask has its origin at the TOP left and TouchDesigner's TOP
    arrays are bottom-up (appletd/coords.py). `maskbuf.py` deliberately does NOT
    flip - a transport that silently reorients its payload cannot be tested against
    a known pattern - so somebody downstream has to, and this is that somebody.
  * the FIT TOP undoes the stretch, on the GPU. MEASURED (DESIGN.md 2.18): the mask
    does not share its source's aspect ratio - a 1280x720 frame gives a 256x192 mask
    - so the correction is a NON-UNIFORM scale. `fit = fill` with the resolution
    driven from the header's source geometry is exactly that, and it costs nothing
    on the main thread where a numpy resize would cost a 1280x720 resample per frame.

WHY `outmask` IS AN OUT TOP AND SEPARATE FROM `out1`. A COMP can carry outputs of
several families, and a mask is not a channel. `out1` stays the single CHOP output
that everything else in the project reads; `outmask` is a second connector of a
different type, so nothing about the CHOP contract moves.

WHICH PARAMETERS THIS OWNS, AND WHICH IT DOES NOT. This builder owns the READ side:
`Maskfit`, and the two read-only `Masksourcew`/`Masksourceh` fields the Script TOP
fills in from the buffer's header. It does NOT own `Streamsegment`, `Segquality` or
`Maskbuffer` - `tools/td_build_vision.py` does, because those three go on the
SIDECAR's command line and one of them has to exist before its `start()` can read it.

ONE toggle for the mask, not two. `Streamsegment` puts `segment` on the sidecar's
command line AND gates this Script TOP. The read side and the write side are always
wanted together, and two toggles a letter apart would have been a trap of my own
making. Off releases the mmap, so a project not using the mask holds no file handle.

TO SEE IT WITH NO CAMERA, which is also how it was verified:

    ~/.venvs/appletd/bin/python tools/segmentation_probe.py --write-only

then switch `Streamsegment` on. That is exactly the shape the sidecar has.

Ref: appletd/maskbuf.py, appletd/segmentation.py, design/DESIGN.md 2.18-2.19,
     docs/BUILD_PLAN.md step 16.
"""

import os
import sys

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER_PATH = "/project1/vision"

PAGE = "Segmentation"

# Parameters this builder used to own and no longer does, with why. Destroyed on the
# next run, because a parameter outlives the code that created it - see the retire
# block in main().
RETIRED_PARS = {
    "Segment": "`Streamsegment` on the Vision page does both jobs now: it puts "
               "`segment` on the sidecar's command line AND gates this Script TOP. "
               "Two toggles a letter apart, one of them dead, was a trap.",
}

CALLBACK_SOURCE = '''# Generated by tools/td_add_segmentation.py
#
# Reads the shared mask buffer and publishes it as a TOP. Everything expensive is
# deliberately elsewhere: this does one `os.stat`, one coherent read of at most a few
# hundred KB, one y-flip, and one `copyNumpyArray`.
import os
import sys

# WHERE THE PACKAGE IS, and the order matters.
#
# BUILT_AT is the checkout this DAT was generated from. `Installroot` is where the
# Install button put a copy. The checkout WINS WHEN IT EXISTS, which is the opposite
# of what looks obvious and is the point: on the machine that built this file, the
# repo is the source of truth and the installed copy may be older. Preferring the
# install would mean a developer silently running stale code - the two-copies hazard
# that `Sourceversion` exists to catch one layer up.
#
# On anybody else's machine BUILT_AT does not exist, so `Installroot` is used - which
# is what makes a shipped .tox work at all. Before 2026-08-23 this was a baked
# absolute path and nothing else, so a .tox carried one person's home directory and
# failed at its first cook everywhere else.
BUILT_AT = %(repo)r
_COMP_PATH = %(comp_for_root)r


def _package_root():
    """The directory containing `appletd`, or raise saying what to do about it."""
    tried = [BUILT_AT]
    comp = op(_COMP_PATH)
    if comp is not None:
        par = getattr(comp.par, "Installroot", None)
        if par is not None:
            tried.append(str(par.eval()))
    for root in tried:
        if root and os.path.isdir(os.path.join(root, "appletd")):
            return root
    raise RuntimeError(
        "cannot find the `appletd` package. Looked in %%s. Press Install on the "
        "Vision page, or point `Installroot` at a checkout." %% ", ".join(
            repr(t) for t in tried if t))


REPO_ROOT = _package_root()
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)          # append, never insert

import numpy

from appletd.maskbuf import MaskReader

# The reader lives in MODULE GLOBALS and never in operator storage. TouchDesigner
# PICKLES operator storage into the .toe on save, and an `mmap` cannot be pickled -
# which is exactly how this project lost the ability to save on 2026-08-21, over a
# dataclass. A module global is not saved, and is rebuilt on demand.
_READERS = {}

# What to publish before anything has been written. A defined frame rather than the
# Script TOP's 2x2 default, so a project wired to `outmask` has a sane image from the
# first cook instead of something that changes shape when the sidecar starts.
#
# 16x16, and the SIZE is the diagnostic. It used to be 256x192 - which is exactly the
# size of a `fast` mask, so "the buffer has never been read" and "a real mask arrived"
# looked identical in the operator's resolution. That cost real time on 2026-08-22:
# the mask was black and the only way to tell which case it was involved running the
# callback's own logic by hand. A shape nothing else produces answers it at a glance.
_BLANK = numpy.zeros((16, 16, 1), dtype=numpy.uint8)


def _reader(path):
    """One MaskReader per path, cached. None if the file is not there yet.

    A missing file is the NORMAL state before the writer starts, so it returns None
    rather than raising - and it is not cached, so the next cook tries again.
    """
    reader = _READERS.get(path)
    if reader is not None:
        return reader
    try:
        reader = MaskReader(path)
    except (OSError, ValueError):
        # OSError: not there yet. ValueError: there but too small to hold a header,
        # which is a writer mid-creation. Both resolve on their own.
        return None
    _READERS[path] = reader
    return reader


def onCook(scriptOp):
    comp = op.Vision or scriptOp.parent()

    # `Streamsegment`, the SAME toggle that puts `segment` on the sidecar's command
    # line - one control for "am I using the mask", not two. The read side and the
    # write side are always wanted together, and two toggles a letter apart
    # (`Segment` and `Streamsegment`) would have been a trap of my own making.
    #
    # WHAT ACTUALLY STOPS THE WORK is the `Tick` parameter, not this check - see the
    # builder. `allowCooking = False` raises "This flag can only be disabled for
    # COMPs" on a Script TOP (MEASURED), so the gating pattern the CHOP groups use is
    # unavailable here; the Tick expression goes constant when this toggle is off,
    # the operator stops being dirtied, and it stops cooking altogether. VERIFIED:
    # totalCooks settles instead of climbing.
    #
    # This branch is what runs on the ONE cook after the toggle changes, and its job
    # is to release the mmap so a project not using the mask holds no file handle.
    if hasattr(comp.par, "Streamsegment") and not bool(comp.par.Streamsegment.eval()):
        reader = _READERS.pop(str(comp.par.Maskbuffer.eval()), None)
        if reader is not None:
            reader.close()
        scriptOp.copyNumpyArray(_BLANK)
        return

    path = str(comp.par.Maskbuffer.eval()) if hasattr(comp.par, "Maskbuffer") else ""
    if not path:
        scriptOp.copyNumpyArray(_BLANK)
        return

    reader = _reader(path)
    if reader is None:
        scriptOp.copyNumpyArray(_BLANK)
        return

    try:
        frame = reader.read()
    except ValueError:
        # A non-zero wrong magic: somebody else's file. Drop the reader so a
        # corrected path is picked up, and say so once rather than every cook.
        _READERS.pop(path, None)
        scriptOp.copyNumpyArray(_BLANK)
        raise

    if frame is None:
        # Nothing published yet, or the writer won the race. HOLD the previous frame
        # by returning without copying - which is the right answer for a mask, and
        # the reason `read` never blocks (maskbuf.py).
        return

    # (h, w, components). MEASURED: `copyNumpyArray` needs THREE dimensions - a plain
    # (h, w) raises "must be 3 dimensions" - and takes uint8 without conversion.
    #
    # `[::-1]` is the y flip: Vision's mask origin is top-left, TouchDesigner's TOP
    # arrays are bottom-up. `ascontiguousarray` because the reversed view is not
    # contiguous, and it is one memcpy of the payload - 197 KB at 512x384.
    array = numpy.frombuffer(frame.pixels, dtype=numpy.uint8).reshape(
        frame.height, frame.width, frame.components)
    scriptOp.copyNumpyArray(numpy.ascontiguousarray(array[::-1]))

    # The source geometry, onto the parameters the Fit TOP reads. Written rather than
    # bound, because an expression would have to open the buffer on every cook of
    # every operator that referenced it.
    if hasattr(comp.par, "Masksourcew") and frame.source_width:
        if int(comp.par.Masksourcew.eval()) != frame.source_width:
            comp.par.Masksourcew = frame.source_width
        if int(comp.par.Masksourceh.eval()) != frame.source_height:
            comp.par.Masksourceh = frame.source_height
'''


def _page(comp, name):
    """Find or create a custom page. TRAP: `appendCustomPage` with an existing name
    makes a SECOND page of that name, so the existing one is looked up first."""
    for existing in comp.customPages:
        if existing.name == name:
            return existing
    return comp.appendCustomPage(name)


def _at(node, xy, keep, existed):
    from appletd.td_layout import placement
    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.td_layout import master_xy

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return

    print("=" * 70)
    print("segmentation: shared memory -> a TOP, in %s" % master.path)
    print("=" * 70)

    keep_layout = bool(master.par.Keeplayout.eval()) \
        if hasattr(master.par, "Keeplayout") else False

    # -- the parameters ----------------------------------------------------
    # APPEND ONLY WHAT IS ABSENT. `append*` on an existing parameter RESETS it, and
    # the reset fires a DEFERRED callback that outlives any write-it-back fix -
    # measured 2026-08-22, DESIGN.md 2.17. Nothing that exists is touched here except
    # its `default`, which is not a value.
    page = _page(master, PAGE)
    existing = {par.name: par for par in master.customPars}

    # -- retire what this builder used to own ------------------------------
    # BEFORE anything is appended. REMOVING THE CODE THAT CREATES A PARAMETER DOES
    # NOT REMOVE THE PARAMETER: `Segment` stopped being created when `Streamsegment`
    # took over both jobs, and it sat on this page reading True and driving nothing
    # until the user asked what the difference was. A control that does nothing is
    # worse than no control (STANDARDS.md 2), and this is the same shape as operator
    # storage outliving the code that wrote it (DESIGN.md 2.11) - TouchDesigner keeps
    # what you made until you unmake it.
    #
    # Idempotent and reported: the first run after the change removes it, every run
    # after finds nothing.
    for stale_name in RETIRED_PARS:
        stale = getattr(master.par, stale_name, None)
        if stale is not None:
            stale.destroy()
            print("   retired `%s` - %s" % (stale_name, RETIRED_PARS[stale_name]))

    # `Streamsegment`, `Segquality` and `Maskbuffer` are NOT created here.
    # tools/td_build_vision.py owns them: the first two are launch flags that go on
    # the sidecar's command line beside the other three stream toggles, and the third
    # has to exist before `start()` can read it. This builder owns only the read
    # side. If they are missing, that script has not run yet.
    on = existing.get("Streamsegment")
    if on is None:
        print("   NOTE: no `Streamsegment` parameter - run "
              "tools/td_build_vision.py, which owns it, or the mask stays off.")

    fit = existing.get("Maskfit")
    if fit is None:
        fit = page.appendToggle("Maskfit", label="Fit Mask To Source")[0]
        fit.val = True
    fit.default = True

    # The source geometry the Script TOP reads out of the header and writes here, for
    # the Fit TOP to read. READ-ONLY to the user: they are a readout, not a setting,
    # and a settable one would silently fight the writer every frame.
    for name, label, default in (("Masksourcew", "Source Width (from the buffer)", 1280),
                                 ("Masksourceh", "Source Height (from the buffer)", 720)):
        par = existing.get(name)
        if par is None:
            par = page.appendInt(name, label=label)[0]
            par.val = default
        par.default = default
        par.readOnly = True

    buffer_par = existing.get("Maskbuffer")
    print("1. `%s` page: Maskfit=%s, source %dx%d"
          % (PAGE, bool(fit.eval()),
             int(master.par.Masksourcew.eval()), int(master.par.Masksourceh.eval())))
    print("   from td_build_vision.py: Streamsegment=%s, Segquality=%s, "
          "Maskbuffer=%r"
          % ("ABSENT" if on is None else bool(on.eval()),
             getattr(master.par, "Segquality", None)
             and master.par.Segquality.eval(),
             "ABSENT" if buffer_par is None else buffer_par.eval()))

    # -- the callbacks DAT -------------------------------------------------
    callbacks = master.op("seg_callbacks") or master.create(td.textDAT,
                                                           "seg_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("seg_callbacks")
    callbacks.text = CALLBACK_SOURCE % {"repo": REPO_ROOT,
                                    "comp_for_root": MASTER_PATH}

    # -- the Script TOP ----------------------------------------------------
    script = master.op("seg_mask")
    script_existed = script is not None
    if script is None:
        script = master.create(td.scriptTOP, "seg_mask")
        # Creating a Script TOP auto-docks its own callbacks DAT. Destroy it, or two
        # DATs claim the same job and only one of them is the generated one - the
        # same trap the Script CHOP has (DESIGN.md 2.11).
        for child in list(master.children):
            if child.name.startswith("seg_mask_callbacks") and child.valid:
                child.destroy()
    _at(script, master_xy("seg_mask"), keep_layout, script_existed)
    script.par.callbacks = callbacks.path

    # THE THING THAT MAKES IT COOK AT ALL, and it took a black mask to find.
    #
    # A Script TOP with NO INPUT is never dirtied, so TouchDesigner cooks it once and
    # then serves that texture for ever. MEASURED 2026-08-22: `totalCooks` sat at 151
    # across many frames while the buffer held a perfectly good mask, because the
    # single cook had happened before the file existed and published the blank. There
    # is no Cook Type parameter on a Script TOP to fix it with - the Common page has
    # none. This project had already recorded the same trap for an input-less Script
    # CHOP ("it cooks once and freezes", docs/BUILD_PLAN.md) and I did not connect it.
    #
    # A custom parameter whose VALUE CHANGES each frame is what dirties it. Gated on
    # `Streamsegment` so the expression goes constant when the mask is off - which
    # stops the cook entirely and is the gating `allowCooking` refused to give.
    # VERIFIED both ways: cooks climb with it on, and settle with it off.
    tick_page = None
    for existing_page in script.customPages:
        if existing_page.name == "Tick":
            tick_page = existing_page
            break
    if tick_page is None:
        tick_page = script.appendCustomPage("Tick")
    # Append only what is absent: `append*` on an existing parameter resets it, and
    # the reset fires a deferred callback that outlives any write-it-back fix
    # (DESIGN.md 2.17).
    if not hasattr(script.par, "Tick"):
        tick_page.appendInt("Tick", label="Tick (drives the cook - do not set)")
    script.par.Tick.expr = (
        "absTime.frame if op.Vision.par.Streamsegment else 0")
    script.par.Tick.readOnly = True
    # `mono8fixed`: one byte per pixel on the GPU, which is what a mask is. The
    # default rgba8fixed would carry four and copy three of them for nothing.
    script.par.format = "mono8fixed"
    script.color = (0.35, 0.45, 0.5)
    # NOT `allowCooking`. MEASURED: "This flag can only be disabled for COMPs" - it
    # raises on a bare operator, so `Segment` is checked inside `onCook` instead. See
    # the callback for why that is the right trade rather than a workaround.

    # -- the Fit TOP, undoing the anisotropic stretch ----------------------
    fit_top = master.op("seg_fit")
    fit_existed = fit_top is not None
    if fit_top is None:
        fit_top = master.create(td.fitTOP, "seg_fit")
    _at(fit_top, master_xy("seg_fit"), keep_layout, fit_existed)
    fit_top.inputConnectors[0].connect(script)
    # `fill` is the NON-UNIFORM stretch - it fills the target resolution and does not
    # preserve the aspect ratio, which is exactly the correction needed. `fitbest`
    # would letterbox, which would be right if Vision had letterboxed. It did not:
    # the subject spans the full height of the mask, verified by row occupancy
    # (DESIGN.md 2.18).
    fit_top.par.fit = "fill"
    fit_top.par.outputresolution = "custom"
    # Expressions, not written values: these follow the readout the Script TOP keeps
    # up to date, so a source resolution change needs no rebuild.
    fit_top.par.resolutionw.expr = "op('%s').par.Masksourcew" % master.path
    fit_top.par.resolutionh.expr = "op('%s').par.Masksourceh" % master.path
    fit_top.par.format = "mono8fixed"
    fit_top.bypass = not bool(fit.eval())

    # -- the output --------------------------------------------------------
    out = master.op("outmask")
    out_existed = out is not None
    if out is None:
        out = master.create(td.outTOP, "outmask")
    _at(out, master_xy("outmask"), keep_layout, out_existed)
    # PRESERVED, never recreated - an Out TOP IS a COMP output connector, and
    # destroying it disconnects whatever the project had wired to it.
    out.inputConnectors[0].connect(fit_top)

    print("2. seg_mask -> seg_fit -> outmask")
    print("   seg_mask format=mono8fixed, cooked by its `Tick` expression")
    print("            (an input-less Script TOP is never dirtied on its own - "
          "DESIGN.md 2.21)")
    print("   seg_fit  fit=fill, resolution from Masksourcew/h (%dx%d), bypass=%s"
          % (int(master.par.Masksourcew.eval()), int(master.par.Masksourceh.eval()),
             fit_top.bypass))

    # -- the parameter callbacks -------------------------------------------
    # `allowCooking` and `bypass` are ATTRIBUTES, so nothing can bind an expression
    # to them - they have to be WRITTEN, here at build and again whenever a toggle
    # moves. The same pattern the filter's bypass and the group gating use.
    par_exec = master.op("seg_par_callbacks") or master.create(
        td.parameterexecuteDAT, "seg_par_callbacks")
    par_exec.nodeX, par_exec.nodeY = master_xy("seg_par_callbacks")
    par_exec.text = (
        "# Generated by tools/td_add_segmentation.py\n"
        "#\n"
        "# `bypass` is an ATTRIBUTE, not a parameter, so it cannot be bound to an\n"
        "# expression and is written on change instead - the same pattern the\n"
        "# filter's bypass and the group gating use.\n"
        "#\n"
        "# `Streamsegment` is NOT handled here: `allowCooking` cannot be disabled\n"
        "# on a bare operator (measured - it raises), so the Script TOP checks that\n"
        "# toggle itself. It is still listed below so that switching it forces a\n"
        "# cook, or the mask would keep its last frame until something else\n"
        "# invalidated the operator.\n"
        "\n"
        "def onValueChange(par, prev):\n"
        "    comp = par.owner\n"
        "    fit = comp.op('seg_fit')\n"
        "    if fit is not None:\n"
        "        fit.bypass = not bool(comp.par.Maskfit.eval())\n"
        "    script = comp.op('seg_mask')\n"
        "    if script is not None:\n"
        "        script.cook(force=True)\n")
    par_exec.par.op = master.path
    par_exec.par.pars = "Streamsegment Maskfit"
    par_exec.par.valuechange = True
    print("3. Streamsegment and Maskfit wired through %s" % par_exec.name)

    # -- report ------------------------------------------------------------
    print()
    if on is None or not bool(on.eval()):
        print("   `Streamsegment` is OFF, so `seg_mask` publishes black. Switch it")
        print("   on and press Active to have the sidecar publish masks, or drive")
        print("   the buffer yourself with no camera:")
        print("     ~/.venvs/appletd/bin/python tools/segmentation_probe.py "
              "--write-only")
    else:
        script.cook(force=True)
        out.cook(force=True)
        print("   seg_mask %dx%d -> outmask %dx%d"
              % (script.width, script.height, out.width, out.height))
    print("=" * 70)


main()
