#!/usr/bin/env python
"""One toggle that strips the raw normalised coordinates from every stream's output.

    Paste into a Text DAT, Run Script. Idempotent. Run it LAST, after
    td_add_coords.py, because what it deletes is decided by what that builds.

    ON THE VISION PAGE
        Screenspaceonly   off  every channel, raw normalised and adjusted
                          on   the raw normalised POSITIONS and EXTENTS are gone,
                               leaving only TouchDesigner's world and pixel spaces

WHAT IT BUILDS, in each stream, between `merge_out` and `out1`:

    merge_out -> screen_only (a Delete CHOP) -> out1

WHY A DELETE CHOP AND NOT A SELECT. A Select needs the list of channels to KEEP,
and the stream's output carries far more than this repo's contract - 87 derived
attributes, 27 temporal channels, 76 latch channels, all named by tables that live
in three different builders. Assembling a keep-list here would mean either a
wildcard, which DESIGN.md 2.11 records twice as unable to partition these channels,
or a snapshot of the live channel list, which goes stale the moment a group toggle
moves and then silently deletes whatever appeared since.

A Delete CHOP takes the list of channels to REMOVE, and that list is exactly
`spaces.companioned_names(stream)` - short, exact, and derived from the same
registry that built the companions in the first place. Nothing else can be
affected, whatever else the stream grows.

WHAT IT REMOVES, precisely: every channel that HAS a screen-space companion. So
`h0_wrist_x` goes and `h0_wrist_tx`/`h0_wrist_px` stay; `f0_bbox_w` goes and
`f0_bbox_tw` stays; every face landmark's box-relative `_x` goes and its `_tx`
stays.

WHAT IT KEEPS, and this is narrower than "channels that are not screen-space
adjusted" on purpose:

    every boolean and pulse       found, pinching, the edge pulses
    every counter and age         seq, age_ms, n_hands, sc_*
    every confidence and score    they have no meaning in pixels
    every ANGLE                   roll, yaw, pitch, hands_angle. There is no such
                                  thing as a yaw in world units, so an angle has no
                                  companion to be redundant with

The rule is "remove the SECOND copy of a number, never the only copy". A toggle that
also dropped angles and confidences would be smaller and would lose information,
which is a different feature from the one asked for.

DELETING CHANNELS IS NORMALLY THE BUG THIS PROJECT FEARS. DESIGN.md 6.2: a channel
that disappears breaks every reference to it with NO error anywhere, which is why a
disabled stream still sends zeros and a frozen group still publishes its last
values. This is the one place where making channels vanish is the point, so it is
built where it can do the least damage:

  * at the very END of the chain, after `merge_out`, so nothing inside the COMP
    reads through it and no group's verification is affected;
  * as a BYPASSED operator when the toggle is off - measured elsewhere in this repo
    as a bit-exact passthrough that also stops the operator computing;
  * and it ships OFF, because the raw channels are what every existing project
    reads and a toggle that defaulted on would delete them out from under one.

Ref: DESIGN.md 6.2 (why a vanished channel is silent), 7 (the coordinate contract),
     appletd/spaces.py, docs/BUILD_PLAN.md step 10.
"""

import os
import sys

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER_PATH = "/project1/appletd"
NODE = "screen_only"
PARAMETER = "Screenspaceonly"

CALLBACK = '''# Generated by tools/td_add_screenspace.py
#
# `Screenspaceonly` off sets the Delete CHOP's BYPASS flag - a bit-exact
# passthrough that also stops the operator computing. A DAT rather than an
# expression because `bypass` is an ATTRIBUTE, not a parameter: there is nothing to
# bind an expression to. The same pattern filter_callbacks uses for the filter.
NODE = %(node)r


def _apply(comp):
    """Bypass or engage the one Delete CHOP. It was three, one per stream, until the
    coordinate spaces moved to the master on 2026-08-24 - BUILD_PLAN step 25."""
    node = comp.op(NODE)
    if node is not None:
        node.bypass = not comp.par.%(parameter)s.eval()


def onValueChange(par, prev):
    _apply(par.owner)


def onValuesChanged(changes):
    if changes:
        _apply(changes[0].par.owner)
'''

NOTES = """SCREEN_ONLY - the one place in this COMP where channels are meant to vanish.

  merge_out -> screen_only -> out1

A Delete CHOP holding the exact list of channels that HAVE a screen-space
companion. With op.Appletd.par.%(parameter)s on, they are removed and only
TouchDesigner's own world and pixel coordinates leave the stream. With it off this
operator is BYPASSED - bit-exact, and not computing.

  deletes   %(n_deleted)d channels
  keeps     %(n_kept)d, including every boolean, pulse, counter, confidence and ANGLE

WHY A DELETE AND NOT A SELECT. A Select needs the KEEP list, and this stream's
output carries 87 derived attributes, 27 temporal channels and 76 latch channels
named by tables in three different builders. The delete list is exactly
spaces.companioned_names() - short, exact, and derived from the same registry that
built the companions.

WHY IT SITS HERE, AFTER merge_out. A channel that disappears breaks every
reference to it with no error anywhere (DESIGN.md 6.2). Nothing inside the COMP
reads through this operator, so nothing inside can be broken by it.

Built by tools/td_add_screenspace.py. Edits here are overwritten on the next run."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process. DESIGN.md 2.11.
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    # `td_layout` is where this operator goes - the one table every builder reads.
    from appletd.spaces import (
        STREAM_MERGED,
        companioned_names,
        derived_companioned_names,
    )
    from appletd.streams import STREAM_NAMES
    from appletd.td_layout import master_xy, rewire_master_chain

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first" % MASTER_PATH)
        return
    if not hasattr(master.par, PARAMETER):
        print("FAIL %s has no %s - run tools/td_build_vision.py first"
              % (MASTER_PATH, PARAMETER))
        return

    # BEFORE anything is built: a drifted list would make the merged pattern fail to
    # verify, and the fallback is the 4 ms literal list this candidate exists to avoid.
    _check_keypoints()

    print("=" * 70)
    print("screenspace: ONE Delete CHOP at %s, after `coords`" % master.path)
    print("=" * 70)

    # THE PER-STREAM NODES GO FIRST. Left in place they would delete the raw
    # normalised channels BEFORE `merge_streams`, so `coords` - which now reads the
    # merge - would find nothing to compose and every landmark branch would select
    # zero channels. The symptom is an empty output, not an error.
    retired = []
    for stream in STREAM_NAMES:
        child = master.op(stream)
        old_node = None if child is None else child.op(NODE)
        if old_node is not None:
            merge_out = child.op("merge_out")
            chop_out = child.op("out1")
            if merge_out is not None and chop_out is not None:
                chop_out.inputConnectors[0].connect(merge_out)
            old_node.destroy()
            retired.append("%s/%s" % (stream, NODE))
        stale_note = None if child is None else child.op("screen_only_notes")
        if stale_note is not None:
            stale_note.destroy()
    if retired:
        print("   retired the per-stream nodes: %s" % ", ".join(retired))

    engaged = bool(getattr(master.par, PARAMETER).eval())
    failures = []
    # Two lists, and the split matters. The wire-contract channels are ALWAYS on the
    # output, so one of them missing is a fault. The derived ones can be absent - a
    # disabled derive group does not emit its channels at all, unlike a frozen native
    # group, which holds them - so a missing one is normal.
    arrived, produced, deletable = _build_one(
        td, master, STREAM_MERGED, companioned_names(STREAM_MERGED),
        derived_companioned_names(), engaged, failures,
        master_xy(NODE), _keep_layout(master))

    wired = rewire_master_chain(master)

    callbacks = master.op("screenspace_callbacks") or master.create(
        td.parameterexecuteDAT, "screenspace_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("screenspace_callbacks")
    callbacks.text = CALLBACK % {"node": NODE, "parameter": PARAMETER}
    callbacks.par.op = master.path
    callbacks.par.pars = PARAMETER
    callbacks.par.valuechange = True
    callbacks.par.active = True

    print()
    print("   %s = %s" % (PARAMETER, engaged))
    counts = ("not measured - nothing cooking" if arrived is None
              else "%4d channels in, %4d out" % (arrived, produced))
    print("   %-30s (%d deletable%s)"
          % (counts, deletable, "" if engaged else ", currently bypassed"))
    print("   chain: %s" % " -> ".join(
        [pair[0] for pair in wired] + [wired[-1][1]] if wired else ["(nothing)"]))
    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print()
        print("   verified. Flip %s on %s and the output loses its raw"
              % (PARAMETER, master.path))
        print("   normalised positions, keeping _tx/_ty/_px/_py and every boolean,")
        print("   counter, confidence and angle.")


def _keep_layout(master):
    """Has the user asked the builders to leave their node arrangement alone?"""
    par = getattr(master.par, "Keeplayout", None)
    return bool(par is not None and par.eval())


def _place(node, xy, keep, existed):
    """Write nodeX/nodeY unless `Keeplayout` is on and the node already existed.

    Rule and caveats in `appletd.td_layout.placement`.
    """
    from appletd.td_layout import placement

    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where
    return node


# Candidates, cheapest first. Every one is verified before use; none is trusted.
# `*_x *_y *_w *_h` is the whole companioned set BY CONSTRUCTION - a channel has a
# `_tx`/`_px` twin exactly when it is a normalised position or extent - so where it
# verifies it is not a guess, it is the contract restated compactly.
_AXES = ("x", "y", "w", "h")
# Plain suffixes: exact for pose and face, which have no hand-local descriptors.
_SIMPLE = " ".join("*_%s" % a for a in _AXES)
# TRIED FOR HANDS AND REJECTED BY THE VERIFIER, kept because the reason is what the
# working pattern below is built from: it selects 104 channels where 100 are wanted.
# The extras are `h?_point_x/y` - unit vectors, which spaces.py records as NOT
# transformable and therefore uncompanioned. Deleting one would lose information that
# has no other copy.
#
# `[a-ce-z]` is every letter except `d`, so `h?_[a-ce-z]*_x` takes `h0_palm_x` and
# `h0_bbox_x` and leaves the 84 hand-local `h?_d_<joint>_x` descriptor channels alone -
# which is the one distinction a wildcard could not make before, and the reason
# DESIGN.md 2.11 says a wildcard cannot partition these.
#
# `hands_*` and `index_*` are listed separately because `h?_` needs exactly one
# character between `h` and `_`, and `hands_center_x` has four.
_HANDS_LOOSE = " ".join(
    ["h?_[a-ce-z]*_%s" % a for a in _AXES]
    + ["hands_*_%s" % a for a in ("x", "y")]
    + ["index_*_%s" % a for a in ("x", "y")])

# AND THE ONE THAT FITS, which uses NOTHING but `?` and `*`.
#
# MEASURED 2026-08-24: the literal list this replaced cost **0.4885 ms** per cook -
# the most expensive single operator in the component outside the face landmarks, and
# every microsecond of it spent deciding which channels to throw away. A Delete CHOP's
# cost is list length x input channels, so 24 terms against 100 names is the saving.
#
# The list is one term per LEADING LETTER of a channel that must go, which is a long
# way of saying "everything except `d` and `point`":
#
#     w  wrist          t  thumb_*      i  index_*     m  middle_*
#     r  ring_*         l  little_*     b  bbox        v  vel
#     pa palm           pi pinch                   ... and NOT `point`, NOT `d_*`
#
# NO `_w`/`_h` TERMS. On hands a `_w` is a SCALAR - `spaces._role_of` classifies by
# suffix and only `_x`/`_y` are positions there - so `h?_bbox_w` has no `_tw` twin and
# must survive. Face is the stream where an extent is an extent.
#
# WHY NOT A CHARACTER CLASS, which is shorter and was tried first:
# `h?_[a-ce-oq-z]*_x` is every letter but `d` and `p`, `fnmatchcase` accepts it,
# `compact_pattern` therefore chose it - and TOUCHDESIGNER'S MATCHER SELECTED NOTHING
# WITH IT. The build reported 88 channels that should have been deleted and were not.
# So a three-range class is not portable to TD's matcher, DESIGN.md 2.11's note that
# it "agrees with fnmatchcase on `*`, `?` and `[0-9]`" is the limit of what has been
# verified, and this stays inside it. The verifier is what caught it; the offline
# expansion agreed with itself all the way to the network.
_HEADS = ("w", "t", "i", "m", "r", "l", "b", "v", "pa", "pi")
# The face's four key points. A LITERAL, not an import: this module is exec'd before
# anything puts REPO_ROOT on sys.path - `main()` does that - so a module-scope
# `from appletd...` fails on a fresh TouchDesigner process. `_check_keypoints()`
# holds it against the contract at build time, which is where it can raise.
_KEYPOINTS = ("eye_left", "eye_right", "nose_tip", "mouth")

_HANDS = " ".join(
    ["h?_%s*_%s" % (head, axis) for axis in ("x", "y") for head in _HEADS]
    + ["hands_*_%s" % a for a in ("x", "y")]
    + ["index_*_%s" % a for a in ("x", "y")])
# AND THE MERGED ONE, which is what this operator actually gets since the coordinate
# spaces moved to the master (BUILD_PLAN step 25). It is `_HANDS` plus pose, plus the
# face's box, its 348 landmark points and its four key points - every raw channel with
# a composed twin, in one universe.
#
# MEASURED, and this is why it exists: without it `compact_pattern` fell through to
# the literal list and the merged Delete carried **564 names over 1,783 channels for
# 4.4211 ms a frame** - more than the entire component had cost before the move. A
# Delete's cost is list length x input channels, so 38 terms against 564 names is the
# whole difference. The three per-stream operators it replaced cost 0.22 + 0.13 + 0.04.
#
# `h?_vel_*` is here and NOT in the position pattern in appletd/spaces.py, because a
# velocity is a RATE - it takes the extent rule there - but it is still a raw channel
# with a composed twin, so it still gets deleted.
_MERGED = " ".join(
    [term for axis in ("x", "y") for term in
     ["h?_%s*_%s" % (head, axis) for head in _HEADS]
     + ["hands_*_%s" % axis, "index_*_%s" % axis, "p?_*_%s" % axis,
        "f?_bbox_%s" % axis, "h?_vel_%s" % axis,
        # A landmark carries a two-digit point index; a key point does not.
        "f?_*_[0-9][0-9]_%s" % axis]
     + ["f?_%s_%s" % (point, axis) for point in _KEYPOINTS]]
    + ["f?_bbox_w", "f?_bbox_h"])
SCOPE_CANDIDATES = (_SIMPLE, _MERGED, _HANDS, _HANDS_LOOSE, "*_x *_y")


def _scope_for(master, stream, doomed, optional):
    """The Delete CHOP's scope: a verified pattern, or the literal names.

    THE UNIVERSE IS WIDENED ON PURPOSE. Verifying against only the channels that
    happen to be live today would accept `*_x` for hands while `Descriptor` is off,
    and then over-delete the 84 hand-local `h?_d_<joint>_x` channels the moment
    somebody turns it on - a pattern that is correct until a toggle moves is worse
    than a literal list, because it is correct when you test it.

    So the descriptor names are added to the universe whether or not they exist yet.
    A pattern that would swallow them fails here and the literal list is used, which
    is what hands gets and why face and pose do not.
    """
    from appletd.spaces import compact_pattern
    from appletd.streams import STREAM_HANDS
    from appletd.types import JOINT_NAMES

    # ORDER MATTERS, and this is the subtle part of `compact_pattern`'s contract: it
    # compares the expansion to the target as LISTS, not sets. Handing it a set makes
    # the expansion order arbitrary, so no candidate ever matches and every stream
    # silently falls back to its literal list - which looks exactly like "no pattern
    # fits" and is not.
    #
    # So the universe is the merge's own channel ORDER, and the target is that same
    # order filtered down. Both then agree by construction.
    wanted_set = set(doomed) | set(optional)
    # The universe is what actually ARRIVES at this operator, which is `coords`'
    # output - the raw channels passed through plus every composed one. Read off the
    # network rather than constructed, because `derived_roles` classifies 24 of the
    # 171 channels `derive_chop` publishes and the rest would be missing from a
    # contract-only universe (appletd/spaces.py says so in `channel_roles`).
    source = _chop(_upstream(master))
    universe = [chan.name for chan in source.chans()] if source is not None else []
    seen = set(universe)
    universe += [name for name in list(doomed) + list(optional) if name not in seen]
    # The channels that MIGHT appear, for THIS stream only. Hand-local descriptors are
    # what make a wildcard unsafe, and they are absent from the universe whenever
    # `Descriptor` is off - which is the default, and therefore the dangerous case.
    #
    # Scoped to hands, which cost a rebuild to learn: adding them for every stream put
    # `h0_d_wrist_x` in FACE's universe, `*_x` matched it, and the pattern was rejected
    # for a stream that has no descriptors and never will.
    if stream in (STREAM_HANDS, "merged"):
        for hand in range(2):
            for joint in JOINT_NAMES:
                for axis in ("x", "y"):
                    name = "h%d_d_%s_%s" % (hand, joint, axis)
                    if name not in seen:
                        universe.append(name)
    target = [name for name in universe if name in wanted_set]
    return compact_pattern(target, universe, SCOPE_CANDIDATES)


def _build_one(td, master, stream, doomed, optional, engaged, failures, node_xy,
               keep):
    """Put the Delete CHOP after `coords`. Returns (arrived, produced, deletable)."""
    from appletd.td_layout import MASTER_CHAIN

    upstream = _upstream(master)
    if upstream is None:
        failures.append("%s has nothing before `%s` in the chain - run "
                        "tools/td_build_vision.py" % (master.path, NODE))
        return (None, None, len(doomed) + len(optional))

    existing = master.op(NODE)
    node = existing or master.create(td.deleteCHOP, NODE)
    _place(node, node_xy, keep, existing is not None)
    node.color = (0.5, 0.32, 0.32)
    # A COMP is connected by its OUTPUT CONNECTOR, not by itself - `coords` is a
    # baseCOMP, and passing it raises `Invalid number or type of arguments`.
    node.inputConnectors[0].connect(
        upstream.outputConnectors[0] if upstream.isCOMP else upstream)
    node.par.delchannels = True
    node.par.delsamples = False
    # By NAME, and `scoped` means "delete the ones named". `nonscoped` would delete
    # everything else, which is the same parameter one menu entry away from
    # inverting the whole toggle - so it is written explicitly rather than left at
    # its default.
    node.par.select = "byname"
    node.par.discard = "scoped"
    # A VERIFIED PATTERN where one exists, the literal list where none does.
    #
    # MEASURED 2026-08-24 in a fresh project: this operator was the single most
    # expensive thing in the component. `face/screen_only` carried 356 literal names
    # over 1,083 input channels and cost **2.1595 ms a frame** - more than everything
    # else put together, and it was paying that with the sidecar switched OFF.
    #
    # A Delete CHOP's cost grows with list length x input channels (BENCHMARKS.md).
    # It is still the right OPERATOR here - measured again on 2026-08-24 against a
    # Select carrying the complement, and the Delete won on two streams of three and
    # by 1.8x on face - because its list is patterns and the Select's would be names.
    #
    # `compact_pattern` EXPANDS each candidate against the universe and accepts it
    # only on an exact match, so a pattern is never used on the strength of looking
    # right - DESIGN.md 2.11 records two silent failures from exactly that.
    node.par.delscope = _scope_for(master, stream, doomed, optional)
    node.bypass = not engaged

    note = master.op("screen_only_notes")
    if note is None:
        note = master.create(td.textDAT, "screen_only_notes")
    note.nodeX, note.nodeY = node_xy[0], node_xy[1] + 200

    # NOTHING COOKING cannot be verified. `Active` off freezes every group, so both
    # reads below would be whatever was there when they froze - and the engaged-check
    # would report every channel as "should have been deleted and was not".
    source = _chop(upstream)
    if source is None or not source.numChans:
        print("   (nothing upstream is cooking - built, not verified. Turn `Active` "
              "on, or run a synthetic sender, to check it.)")
        node.par.delscope = _scope_for(master, stream, doomed, optional)
        note.text = NOTES % {"parameter": PARAMETER,
                             "n_deleted": len(doomed) + len(optional), "n_kept": 0}
        return (None, None, len(doomed) + len(optional))

    source.cook(force=True)
    node.cook(force=True)
    arrived = {c.name for c in source.chans()}
    produced = {c.name for c in node.chans()}
    note.text = NOTES % {"parameter": PARAMETER,
                         "n_deleted": len(doomed) + len(optional),
                         "n_kept": len(arrived - set(doomed) - set(optional))}

    # -- verification -------------------------------------------------------
    # A name in the delete list that is not on the input means the list has drifted
    # from the contract and the toggle silently under-deletes. `early_trim` and the
    # frozen groups both legitimately remove channels before this point, though, so
    # an absent name is only a FAILURE when nothing upstream is trimming.
    absent = sorted(set(doomed) - arrived)
    gated_away = sorted(set(optional) - arrived)
    if gated_away:
        print("   (%d derived channel(s) in the list are not on the input right now "
              "- a disabled derive group emits nothing. Not a fault.)"
              % len(gated_away))
    if absent:
        trimming = any(master.op(name) is not None and not master.op(name).bypass
                       for name in MASTER_CHAIN
                       if name in ("early_trim",))
        if trimming:
            print("   (%d channel(s) in the delete list were removed upstream by "
                  "`early_trim`. Not a fault.)" % len(absent))
        else:
            failures.append("%d channel(s) in the delete list are not on the input: "
                            "%r - spaces.companioned_names() and the live network "
                            "disagree" % (len(absent), absent[:5]))
    if engaged:
        left = sorted((set(doomed) | set(optional)) & produced)
        if left:
            failures.append("%d channel(s) should have been deleted and were not: "
                            "%r" % (len(left), left[:5]))
        # And the far more damaging direction: something NOT on the list going
        # missing. A Delete CHOP set to `nonscoped` by accident would take out the
        # entire rest of the output.
        collateral = sorted(arrived - produced - set(doomed) - set(optional))
        if collateral:
            failures.append("%d channel(s) were deleted that are NOT on the list: %r"
                            % (len(collateral), collateral[:5]))
    elif arrived != produced:
        # Bypassed: it must be a passthrough, exactly.
        failures.append("`%s` is bypassed and changed the channel set by %d"
                        % (NODE, len(arrived ^ produced)))
    return (len(arrived), len(produced), len(doomed) + len(optional))


def _check_keypoints():
    """`_KEYPOINTS` must be exactly the contract's key points.

    A second copy of something owned by appletd/face_types.py, and it fails silently
    if it drifts: the merged pattern would stop matching a renamed key point,
    `compact_pattern` would fall through to the literal list, and the only symptom
    would be this operator quietly costing 4 ms again.
    """
    from appletd.face_types import FACE_KEYPOINTS

    if tuple(_KEYPOINTS) != tuple(FACE_KEYPOINTS):
        raise RuntimeError(
            "_KEYPOINTS has drifted from face_types.FACE_KEYPOINTS.\n"
            "  literal:  %s\n  contract: %s"
            % (" ".join(_KEYPOINTS), " ".join(FACE_KEYPOINTS)))


def _chop(node):
    """The CHOP to read channels from, given a chain stage that may be a COMP.

    `coords` is a baseCOMP, and a COMP has no `.chans()` - its channels live on the
    `out1` inside it. Every other stage is a CHOP and is returned unchanged. Returns
    None when a COMP has no `out1` yet, which is a half-built group rather than an
    error.
    """
    if node is None:
        return None
    return node.op("out1") if node.isCOMP else node


def _upstream(master):
    """The operator this one reads: the stage before it in MASTER_CHAIN.

    Asked of the chain rather than named, for the reason `rewire_master_chain`
    exists - `coords` and `early_trim` are built by other scripts at other points in
    tools/td_rebuild.py, so on a partial build the neighbour is a different operator.
    """
    from appletd.td_layout import MASTER_CHAIN

    before = MASTER_CHAIN[:MASTER_CHAIN.index(NODE)]
    for name in reversed(before):
        node = master.op(name)
        if node is not None:
            return node
    return None


main()
