#!/usr/bin/env python
"""PROTOTYPE: `temporal` as ONE Script CHOP, beside the 74-operator version.

    Paste into a Text DAT, Run Script. Idempotent. Builds
    `/project1/vision/hands/temporal_proto` with `allowCooking = False`, wired from
    the same two inputs as the real group and attached to NOTHING downstream.

    TO A/B IT
        op('/project1/vision/hands/temporal_proto').allowCooking = True
        op('/project1/vision/hands/temporal').allowCooking = False
        ...then tools/td_profile.py, and swap them back.

WHAT QUESTION THIS ANSWERS. Whether collapsing a chain of native CHOPs into a single
Script CHOP is faster, and by enough to matter. `temporal` is 74 operators for 27
channels, and at the measured ~1.2 microseconds per channel per operator
(DESIGN.md 2.14) that is where its cost comes from. A Script CHOP pays that once.
The verdict is in `docs/BUILD_PLAN.md` step 12.

WHY IT IS BUILT HERE AND NOT IN A DUPLICATED COMP. The obvious way to sandbox this
is to duplicate `/project1/vision` and freeze the copy - and it would bind port
10000 a SECOND TIME. A whole builder was retired for exactly that
(`td_setup_osc.py`, see `tools/td_build_vision.py`). Two OSC In CHOPs on one port is
a stream arriving in a CHOP nobody is reading, and it would be indistinguishable from
the prototype simply not working.

Beside the real group is also the better experiment: both see the SAME input on the
SAME frame, so the comparison is not across two runs with whatever else the machine
was doing in between.

WHAT IT IS NOT. Not wired into `merge_out`, so none of its channels reach the COMP's
output and nothing downstream can come to depend on it. Frozen by default, so
building it costs nothing until somebody deliberately turns it on.

THE CLOCK IS NOT OPTIONAL, for the same reason the real group has one. TouchDesigner
does not cook a branch whose channels nothing asks for, and a recurrence that cooks
intermittently produces correct-looking states with nonsense edges between frames
that were never adjacent (DESIGN.md 2.10). The Null at Cook Type = Always sits INSIDE
the group so it freezes with it.

Ref: visionhands/temporal.py (the arithmetic, tested with no TouchDesigner),
     docs/BUILD_PLAN.md step 12, DESIGN.md 2.10, 2.14.
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
MASTER_PATH = "/project1/vision"
COMP_PATH = MASTER_PATH + "/hands"
GROUP = "temporal_proto"

COL_W = 200
ROW_H = 150

CALLBACK = '''# Generated by tools/td_add_temporal_proto.py
#
# A thin wrapper, the same shape as derive_callbacks: every recurrence is in
# `visionhands/temporal.py`, which is tested with no TouchDesigner present.
#
# THE STATE LIVES IN OPERATOR STORAGE, and that is the experiment's whole cost.
# `docs/ATTRIBUTES.md` gives three reasons memory belongs in native CHOPs, and the
# third is this: hidden Python state that a project reload treats unpredictably. A
# TemporalState in storage survives a save and reload as whatever it happened to be,
# or not at all, and nothing anywhere reports which.
import sys

REPO_ROOT = %(repo)r
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)          # append, never insert

from visionhands.temporal import TemporalParams, TemporalState, advance

STATE_KEY = "temporal_proto_state"
NAMES_KEY = "temporal_proto_names"


def _params(comp):
    """Read the Advanced page, falling back to the module defaults."""
    def par(name, default):
        p = getattr(comp.par, name, None)
        return default if p is None else float(p.eval())
    return TemporalParams(
        activate_frames=int(par("Activateframes", 3)),
        deactivate_frames=int(par("Deactivateframes", 6)),
        velocity_filter_s=par("Velocityfilter", 0.15),
        speedfloor=par("Speedfloor", 0.05))


def onCook(scriptOp):
    # Not time-sliced: this publishes a snapshot of one frame, and editing
    # numSamples in Time Slice mode is unsupported.
    scriptOp.isTimeSlice = False
    if len(scriptOp.inputs) < 2:
        scriptOp.clear()
        return

    values = {chan.name: chan[0] for chan in scriptOp.inputs[0].chans()}
    # `seq` off the RAW stream, and ONLY `seq`. Liveness must not depend on the
    # filter chain it is watching, and reading input 1 in full would be another 141
    # channel reads for one number.
    raw_seq = scriptOp.inputs[1].chan("seq")
    values["seq"] = 0.0 if raw_seq is None else raw_seq[0]

    state = scriptOp.fetch(STATE_KEY, None)
    if not isinstance(state, TemporalState):
        # Also the path a project reload takes, which is the point being measured.
        state = TemporalState()
        scriptOp.store(STATE_KEY, state)

    # dt from TouchDesigner's own frame step, NOT from a clock kept in operator
    # storage. That is a bug fix and it is the most expensive thing this prototype
    # taught: `store()` on EVERY cook took the whole COMP from 2.1 ms to 13.8 ms and
    # the cook rate from 89 frames in 89 to 25 - a 5x collapse. `derive_chop` gets
    # away with storage because it only writes when the channel SET changes, which is
    # almost never. Per-cook `store()` is not a scratchpad.
    dt = max(0.0, float(absTime.stepSeconds))

    comp = op.Vision or scriptOp.parent(2)
    out = advance(values, state, _params(comp), dt)

    # The same channel cache derive_chop uses: `len(scriptOp.chans())` because
    # `numChans` RAISES inside onCook, and a Script CHOP's channels persist between
    # cooks so 28 appends per frame are avoidable.
    names = tuple(sorted(out))
    if len(scriptOp.chans()) != len(names) or scriptOp.fetch(NAMES_KEY, None) != names:
        scriptOp.clear()
        scriptOp.numSamples = 1
        for name in names:
            scriptOp.appendChan(name)
        scriptOp.store(NAMES_KEY, names)
    for name, chan in zip(names, scriptOp.chans()):
        chan[0] = out[name]
'''

NOTES = """TEMPORAL_PROTO - an EXPERIMENT. Frozen by default. Not wired to anything.

  in1 (derive_chop) --+
                      +-> proto (Script CHOP) -> out1
  in2 (the raw stream)|                       -> tick (Cook Type = Always)
                      +   ...for `seq` only

The question: is one Script CHOP faster than the 74 native operators next door, and
by enough to be worth what it costs? All the arithmetic is in
visionhands/temporal.py, tested with no TouchDesigner present. The verdict is in
docs/BUILD_PLAN.md step 12 - read that before acting on this.

TO A/B IT, one at a time, then run tools/td_profile.py:

  op('.../temporal_proto').allowCooking = True
  op('.../temporal').allowCooking = False

WHAT IT COSTS IF IT WINS, which is the part a stopwatch does not show:

  * the state is a Python object in operator storage. A save and reload treats it
    unpredictably - the third reason docs/ATTRIBUTES.md put memory in CHOPs.
  * the windows are counted in COOKS, not in time. A Trail CHOP's window is a
    window whatever the cook rate does.
  * 74 operators can be inspected in the network with a hand in front of the
    camera. A dict cannot.

Built by tools/td_add_temporal_proto.py. Edits here are overwritten."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    from visionhands.temporal import channel_names

    master = op(MASTER_PATH)
    comp = op(COMP_PATH)
    if master is None or comp is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first"
              % (MASTER_PATH if master is None else COMP_PATH))
        return
    source = comp.op("derive_chop")
    raw = comp.op("in1")
    if source is None or raw is None:
        print("FAIL need derive_chop and in1 - run tools/td_add_derive.py first")
        return

    group = comp.op(GROUP)
    if group is None:
        group = comp.create(td.baseCOMP, GROUP)
    for child in list(group.children):
        if child.valid:
            # A Script CHOP takes its docked callbacks DAT down with it, so a
            # snapshot list can hold an already-deleted operator (DESIGN.md 2.11).
            child.destroy()
    # Below the real group, so the two sit next to each other in the network and the
    # A/B is visible rather than something you have to remember.
    group.nodeX, group.nodeY = -1 * COL_W, -8 * ROW_H
    group.color = (0.55, 0.45, 0.2)

    group_in = group.create(td.inCHOP, "in1")
    group_in.nodeX, group_in.nodeY = 0, 0
    raw_in = group.create(td.inCHOP, "in2")
    raw_in.nodeX, raw_in.nodeY = 0, -ROW_H
    group.inputConnectors[0].connect(source)
    group.inputConnectors[1].connect(raw)

    proto = group.create(td.scriptCHOP, "proto")
    proto.nodeX, proto.nodeY = COL_W, 0
    proto.inputConnectors[0].connect(group_in)
    proto.inputConnectors[1].connect(raw_in)
    # TD auto-docks `proto_callbacks` beside a new Script CHOP; use it rather than
    # creating a second one and guessing which name the collision took.
    callbacks = group.op("proto_callbacks") or group.create(td.textDAT,
                                                           "proto_callbacks")
    callbacks.nodeX, callbacks.nodeY = 0, ROW_H
    callbacks.text = CALLBACK % {"repo": REPO_ROOT}
    proto.par.callbacks = callbacks.path

    group_out = group.create(td.outCHOP, "out1")
    group_out.nodeX, group_out.nodeY = 2 * COL_W, 0
    group_out.inputConnectors[0].connect(proto)

    clock = group.create(td.nullCHOP, "tick")
    clock.nodeX, clock.nodeY = 2 * COL_W, -ROW_H
    clock.inputConnectors[0].connect(proto)
    clock.par.cooktype = "always"

    notes = group.create(td.textDAT, "notes")
    notes.nodeX, notes.nodeY = 0, 2 * ROW_H
    notes.text = NOTES

    # FROZEN, and last - so it cooks once here and has channels to show before it
    # stops. A group frozen before its first cook has no channels at all, which
    # looks exactly like a broken build.
    proto.cook(force=True)
    produced = tuple(c.name for c in proto.chans())
    group.allowCooking = False

    expected = channel_names()
    print("`%s` built, %d operators, FROZEN." % (GROUP, len(group.children)))
    print("   %d channels: %s" % (len(produced), ", ".join(produced[:6]) + " ..."))
    if produced != expected:
        missing = sorted(set(expected) - set(produced))
        extra = sorted(set(produced) - set(expected))
        print("   FAIL the Script CHOP and visionhands.temporal disagree.")
        print("        missing %r extra %r" % (missing[:5], extra[:5]))
    elif proto.errors():
        print("   FAIL %s" % proto.errors()[:200])
    else:
        print("   matches visionhands.temporal.channel_names() exactly.")
    print()
    print("   A/B it one at a time, then run tools/td_profile.py:")
    print("     op('%s').allowCooking = True" % group.path)
    print("     op('%s/temporal').allowCooking = False" % comp.path)
    print("   It is attached to NOTHING downstream, so nothing can come to depend")
    print("   on it while the question is still open.")


main()
