#!/usr/bin/env python
"""Add the proximity latch bank to the visionhands COMP. Paste, Run Script.

    WHAT IT BUILDS
        h{i}_pinching             h{i}_e_pinch_start   h{i}_e_pinch_end
        h{i}_snapping             h{i}_e_snap          h{i}_e_snap_end
        hands_together            e_clap               e_apart
        h{i}_{finger}_trigger     h{i}_e_{finger}_trigger
                                  h{i}_e_{finger}_release
        h{i}_grabbing             h{i}_e_grab          h{i}_e_release
        ...plus a fire count and a release count for every one of them,
        and both_pinching.

    Pinch, snap, clap, grab, and a uniform thumb-contact trigger for all four long
    fingers on both hands. Fifteen latches, 76 channels, no Python in the cook
    path - and grab needed no new operators, only two more rows in the table
    below, because a fist is a hand whose `openness` has crossed a threshold and
    that is the same shape of problem as a pinch.

Idempotent: every operator it owns is prefixed `lat_` and destroyed before the
rebuild, so running it twice leaves one network rather than two. Custom
parameters keep any value you have tuned - see `_threshold` below.

THE ONE MECHANISM, from docs/ATTRIBUTES.md:

    state = valid AND ( below_on OR (prev AND NOT above_off) )

Every one of them is that same recurrence over a different distance, so this
builds ONE network as wide as there are latches rather than one copy per gesture.
Thirteen latches, thirteen channels, one set of operators - and adding the eight
finger triggers to the original five was a matter of adding rows to the table
below, with no operator added and no logic touched. That is the whole argument for
the shape: the alternative, a base COMP duplicated per gesture, was the original
plan in docs/BUILD_PLAN.md and was abandoned because duplication is how most of
the copies end up subtly different.

WHY EVERY OPERATOR HERE IS NATIVE. The state has memory, and Python state inside
a Script CHOP survives a project reload in ways nothing controls - a latch that
comes back engaged after a reload emits a release pulse for a gesture that never
happened. Native CHOPs keep their state where TouchDesigner manages it, and the
whole recurrence is visible in the network rather than hidden in a callback.
docs/ATTRIBUTES.md makes this call and explains it at length.

THREE THINGS TOUCHDESIGNER DOES THAT THIS DEPENDS ON, all verified live against
the running instance (099) rather than taken from documentation:

  1. The Logic CHOP's `convert` parameter is a COMPARATOR: `lt` is "On When Less
     Than Zero" and `gt` is "On When Greater Than Zero". So `dist < on` is a Math
     CHOP subtract followed by one Logic CHOP - no Expression CHOP, no Python,
     and the threshold arrives as a channel rather than as a string of code.
  2. The Feedback CHOP takes NO target parameter. Input 0 is the operator whose
     PREVIOUS output it emits, and input 1 supplies the channel template and the
     initial values. With input 1 unconnected it produces ZERO channels, silently
     and with no error - and everything downstream then evaluates on nothing.
     That is the trap in this file; see `lat_zero`.
  3. The Logic CHOP defaults to `match = index`, so it pairs channels by POSITION
     and keeps the first input's names. Verified: ANDing a channel called `aaa`
     with one called `zzz` produced one channel called `aaa`, no error and no
     warning. Every multi-input operator here is set to `match = name`, and
     `_verify` then checks the names really are what the wiring assumed.

Ref: docs/ATTRIBUTES.md (the definitions, the thresholds, why a latch and not a
counter), docs/BUILD_PLAN.md step 1, visionhands/sequences.py (how it is tested).
"""

import sys

REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
COMP_PATH = "/project1/visionhands"
# The group this builds. Everything it owns lives inside, so the top-level network
# shows one node - and since nothing outside reads these channels except through
# merge_out, `allowCooking` on this group gates its whole cost honestly, unlike the
# `filter` group which sits in the data path. docs/BUILD_PLAN.md 7.3.
GROUP = "latches"
# The group that publishes `ready` - the debounced active, ANDed with liveness -
# on its SECOND output. A wire rather than an `op('tmp_ready')` in an expression,
# so the cross-group dependency is visible in the network.
READY_SOURCE = "temporal"

# Every operator this script owns. Destroyed before rebuilding, so the script is
# idempotent and so a renamed operator cannot leave an orphan behind cooking.
PREFIX = "lat_"

THRESHOLD_CALLBACK = '''# Generated by tools/td_add_latches.py
#
# Rewrites lat_on and lat_off when a Tuning threshold changes, and at no other
# time. The values used to be Python EXPRESSIONS on the Constant CHOPs, which cost
# 0.110 ms every frame (MEASURED) - thirty expression evaluations per cook to
# deliver six numbers that change only when somebody drags a slider.
#
# The table is baked in rather than derived, because this DAT runs inside
# TouchDesigner with no access to the builder that made it. It is generated FROM
# that builder's own LATCHES table, so the two cannot drift.
ROWS = %(rows)r


def _write(comp):
    for node_name, column in (("lat_on", 0), ("lat_off", 1)):
        node = comp.op('%(group)s/' + node_name)
        if node is None:
            continue
        for index, pair in enumerate(ROWS):
            parameter = getattr(comp.par, pair[column], None)
            if parameter is not None:
                node.par["value%%d" %% index] = float(parameter.eval())


def onValueChange(par, prev):
    _write(par.owner)


def onValuesChanged(changes):
    if changes:
        _write(changes[0].par.owner)
'''

# ---------------------------------------------------------------------------
# The five latches
# ---------------------------------------------------------------------------
# ONE row per latch, and this order IS the channel order through every operator
# in the bank. Read it as: watch `distance`, gate on `valid`, engage below the
# `on` parameter, release above `off`, and publish under the last three names.
#
# `working` is the internal channel name. All five distances, all five validity
# flags and both threshold sets are renamed to these, which is what lets one set
# of operators serve all five latches: with the names identical across inputs,
# every Logic CHOP pairs the right channels by name instead of by luck.
NAMED_LATCHES = (
    # 0 working  1 distance          2 valid       3 on          4 off
    # 5 state    6 start pulse       7 end pulse   8 fire count  9 release count
    ("pinch0",   "h0_pinch_index",   "h0_valid",   "Pinchon",    "Pinchoff",
     "h0_pinching", "h0_e_pinch_start", "h0_e_pinch_end",
     "h0_pinch_count", "h0_pinch_end_count"),
    ("pinch1",   "h1_pinch_index",   "h1_valid",   "Pinchon",    "Pinchoff",
     "h1_pinching", "h1_e_pinch_start", "h1_e_pinch_end",
     "h1_pinch_count", "h1_pinch_end_count"),
    ("snap0",    "h0_pinch_middle",  "h0_valid",   "Snapon",     "Snapoff",
     "h0_snapping", "h0_e_snap", "h0_e_snap_end",
     "h0_snap_count", "h0_snap_end_count"),
    ("snap1",    "h1_pinch_middle",  "h1_valid",   "Snapon",     "Snapoff",
     "h1_snapping", "h1_e_snap", "h1_e_snap_end",
     "h1_snap_count", "h1_snap_end_count"),
    # `both_valid` rather than either hand's own flag: a two-hand distance is
    # meaningless unless both hands are there, and derive() already publishes 0
    # for `hands_distance` in that case - which is below every threshold, which
    # is exactly the absent-hand trap this gate exists to stop.
    ("together", "hands_distance",   "both_valid", "Togetheron", "Togetheroff",
     "hands_together", "e_clap", "e_apart",
     "clap_count", "apart_count"),
    # GRAB, which is the same recurrence over `openness` rather than a distance.
    # Worth seeing that it needed no new machinery at all: a fist is a hand whose
    # openness has fallen below a threshold, so "closed" is `below_on` exactly as
    # "touching" is for a pinch, and the hysteresis stops a hand hovering near
    # half-closed from chattering.
    #
    # `openness` is 0..1 rather than a ratio of hand size - see visionhands/tuning.py.
    ("grab0",    "h0_openness",      "h0_valid",   "Grabon",     "Graboff",
     "h0_grabbing", "h0_e_grab", "h0_e_release",
     "h0_grab_count", "h0_release_count"),
    ("grab1",    "h1_openness",      "h1_valid",   "Grabon",     "Graboff",
     "h1_grabbing", "h1_e_grab", "h1_e_release",
     "h1_grab_count", "h1_release_count"),
)

FINGER_LATCHES = tuple(
    # THE FINGER TRIGGERS: thumb-to-fingertip contact for all four long fingers on
    # both hands, one uniform grid, sharing a single `Trigger` threshold pair.
    #
    # They deliberately OVERLAP the named gestures: `h0_index_trigger` watches the
    # same distance as `h0_pinching`, and `h0_middle_trigger` the same as
    # `h0_snapping`. That is not redundancy to be tidied away - the two serve
    # different jobs. Pinch and snap are named gestures you tune by feel, each
    # with its own thresholds. The triggers are a uniform grid you map to eight
    # things, and their value is that all eight behave identically, which a
    # per-finger threshold would destroy.
    #
    # No thumb trigger. Every distance here is measured TO the thumb tip, so the
    # thumb is the common reference and cannot contact itself. A thumb gesture
    # would have to be a curl threshold rather than a distance, which is a
    # different mechanism and not what was asked for.
    ("%s%d" % (finger, hand), "h%d_pinch_%s" % (hand, finger), "h%d_valid" % hand,
     "Triggeron", "Triggeroff",
     "h%d_%s_trigger" % (hand, finger),
     "h%d_e_%s_trigger" % (hand, finger),
     "h%d_e_%s_release" % (hand, finger),
     "h%d_%s_trigger_count" % (hand, finger),
     "h%d_%s_release_count" % (hand, finger))
    for hand in range(2)
    for finger in ("index", "middle", "ring", "little")
)

LATCHES = (*NAMED_LATCHES, *FINGER_LATCHES)
WORKING = tuple(row[0] for row in LATCHES)

# Tuning defaults come from visionhands/tuning.py, not from a copy here. They were
# written down in three places - this builder, the tests, and docs/ATTRIBUTES.md -
# and nothing tied them together, so raising `Pinchon` here alone left the whole
# suite green while silently pushing the dead-band sweep's crest below the engage
# threshold: the hysteresis test stopped testing hysteresis and kept reporting
# success. Imported inside main(), after sys.path is set up.
THRESHOLD_DEFAULTS = None       # populated by main() from visionhands.tuning

# Where the bank is laid out, below the derive Script CHOP at y = -800.
ROW_Y = -1100
COLUMN_W = 200


def _threshold_page(comp, page_name="Tuning"):
    """The Tuning page, created once and never overwriting a tuned value.

    Traps: `appendCustomPage` with an existing name creates a SECOND page of that
           name, so the existing one is looked up first. And `appendFloat`
           replaces a parameter's attributes wholesale, so `.default` is set every
           time while `.val` is set only on creation - the same mistake in
           tools/td_build_comp.py once snapped a tuned Orthowidth back to 1.0.
    """
    page = None
    for existing in comp.customPages:
        if existing.name == page_name:
            page = existing
            break
    if page is None:
        page = comp.appendCustomPage(page_name)

    # Read the tuned values BEFORE touching anything, because appendFloat on an
    # existing parameter resets its VALUE to zero - not to its default, to zero.
    # Setting `.default` afterwards does not bring the value back. Measured: a
    # second run of this script left every threshold at 0.000, which disabled
    # every latch while the network still looked correct and reported no error.
    #
    # The note in tools/td_build_comp.py - ".default always, .val only when
    # creating" - is necessary but NOT sufficient. It stops a rebuild overwriting
    # a tuned value with a default; it does nothing about the append itself
    # clearing it. Only saving and restoring works.
    # `> 0` and not merely "present": a threshold is a ratio of hand size, so
    # zero is never a value anyone chose - it disables the latch it belongs to
    # while the network still cooks cleanly. Treating it as untuned means a COMP
    # damaged by the bug above heals itself on the next build instead of
    # preserving the damage faithfully for ever.
    tuned = {p.name: p.eval() for p in comp.customPars
             if p.name in THRESHOLD_DEFAULTS and p.eval() > 0.0}
    for name in sorted(THRESHOLD_DEFAULTS):
        par = page.appendFloat(name, label=name.replace("on", " On").replace(
            "off", " Off"))[0]
        par.default = THRESHOLD_DEFAULTS[name]
        par.normMin, par.normMax = 0.0, 2.0     # slider range; ratios of hand size
        # A value the user had tuned wins; otherwise the spec default.
        par.val = tuned.get(name, THRESHOLD_DEFAULTS[name])
    return page


def _fan(td, make, wire, source, name, column, y):
    """Pick `column` of every latch row out of `source`, renamed to the working
    names, however often a source channel repeats. Returns the merged CHOP.

    Traps: A Select CHOP can emit a given source channel only ONCE, and both
           columns this serves now repeat. `h0_valid` gates six latches (pinch,
           snap and four finger triggers), and `h0_pinch_index` is the distance
           for BOTH `pinch0` and `index0`, because the named gestures and the
           uniform trigger grid deliberately overlap.

           Asking one Select for a repeated channel does not error. It emits the
           unique set, silently, and the rename then maps each source to the first
           target that claims it - so with thirteen latches `lat_dist` came back
           with eleven renamed channels in a scrambled order and two still under
           their source names. Caught by the structural check, which is the only
           reason it was not shipped.

           So the rows are packed first-fit into the fewest groups such that no
           group asks for the same source twice, one Select per group, merged.
           Computed rather than hand-listed, because the latch table is generated
           and its shape will change again.

           Keyed on NAMES rather than on position throughout: `renamefrom = "*"`
           would map the To list onto whatever order channels arrive in, which
           made channel identity positional - and `derive_chop` publishes
           alphabetically, which is not this order. Worse, `derive()` takes an
           enabled-groups set, so once the Attributes page exists, unchecking
           Contacts would drop the pinch channels and silently publish the clap
           latch as `h0_pinching`. A literal From/To list is pairwise by name
           (verified live), and a missing source keeps its own name while the rest
           still map correctly - so a dropped group costs one latch rather than
           shifting every later one onto the wrong data.
    """
    groups = []
    for row in LATCHES:
        for group in groups:
            if all(existing[column] != row[column] for existing in group):
                group.append(row)
                break
        else:
            groups.append([row])

    parts = []
    for index, rows in enumerate(groups):
        part = make(td.selectCHOP, "%s_%d" % (name, index), y)
        wire(part, source)
        part.par.channames = " ".join(row[column] for row in rows)
        part.par.renamefrom = " ".join(row[column] for row in rows)
        part.par.renameto = " ".join(row[0] for row in rows)
        parts.append(part)
    merged = make(td.mergeCHOP, name, y)
    wire(merged, *parts)
    return merged


def _attach_once(merge, node, drop_names=()):
    """Normalise a Merge CHOP's inputs: `node` exactly once, anything in
    `drop_names` gone, every other source exactly once. Returns what it removed.

    Traps, all four measured in this repo rather than anticipated (DESIGN.md 2.11):
      * `.inputs` is STALE inside the same script that rewired anything, so this
        reads `inputConnectors[i].connections` throughout - that is the truth. It
        once reported an input list containing the COMP's own `out1`, which would
        have been a loop, while the connectors showed the correct thirteen.
      * disconnecting SHIFTS the connector list, so a single pass skips entries.
        This restarts after every removal. A single-pass version dropped two of
        four stale branches and left the other two wired to operators it then
        destroyed.
      * a Merge CHOP accepts the SAME operator on any number of inputs, silently,
        and the only symptom is the channel count. `filter` reached three
        connections and put 274 duplicate channels on the output; `derive_chop`
        reached two and put 87. So this dedupes EVERY source, not just `node` -
        which means any builder run repairs the whole merge rather than only its
        own contribution.
      * `connect()` accepts an operator only where it has one unambiguous output,
        which a base COMP does not - hence `outputConnectors[0]`.
    """
    removed = []
    for _attempt in range(256):
        seen = []
        cut = False
        for conn in merge.inputConnectors:
            owners = [x.owner for x in conn.connections]
            if not owners:
                continue
            owner = owners[0]
            if owner.name in drop_names or owner in seen:
                removed.append(owner.name)
                conn.disconnect()
                cut = True
                break                       # the list has shifted; start again
            seen.append(owner)
        if not cut:
            break

    attached = any(x.owner is node for conn in merge.inputConnectors
                   for x in conn.connections)
    if not attached:
        target = node.outputConnectors[0] if node.isCOMP else node
        for conn in merge.inputConnectors:
            if not conn.connections:
                conn.connect(target)
                break
    return removed


def _fan(td, make, wire, source, name, column, y):
    """Pick `column` of every latch row out of `source`, renamed to the working
    names, however often a source channel repeats. Returns the merged CHOP.

    Traps: A Select CHOP can emit a given source channel only ONCE, and both
           columns this serves now repeat. `h0_valid` gates six latches (pinch,
           snap and four finger triggers), and `h0_pinch_index` is the distance
           for BOTH `pinch0` and `index0`, because the named gestures and the
           uniform trigger grid deliberately overlap.

           Asking one Select for a repeated channel does not error. It emits the
           unique set, silently, and the rename then maps each source to the first
           target that claims it - so with thirteen latches `lat_dist` came back
           with eleven renamed channels in a scrambled order and two still under
           their source names. Caught by the structural check, which is the only
           reason it was not shipped.

           So the rows are packed first-fit into the fewest groups such that no
           group asks for the same source twice, one Select per group, merged.
           Computed rather than hand-listed, because the latch table is generated
           and its shape will change again.

           Keyed on NAMES rather than on position throughout: `renamefrom = "*"`
           would map the To list onto whatever order channels arrive in, which
           made channel identity positional - and `derive_chop` publishes
           alphabetically, which is not this order. Worse, `derive()` takes an
           enabled-groups set, so once the Attributes page exists, unchecking
           Contacts would drop the pinch channels and silently publish the clap
           latch as `h0_pinching`. A literal From/To list is pairwise by name
           (verified live), and a missing source keeps its own name while the rest
           still map correctly - so a dropped group costs one latch rather than
           shifting every later one onto the wrong data.
    """
    groups = []
    for row in LATCHES:
        for group in groups:
            if all(existing[column] != row[column] for existing in group):
                group.append(row)
                break
        else:
            groups.append([row])

    parts = []
    for index, rows in enumerate(groups):
        part = make(td.selectCHOP, "%s_%d" % (name, index), y)
        wire(part, source)
        part.par.channames = " ".join(row[column] for row in rows)
        part.par.renamefrom = " ".join(row[column] for row in rows)
        part.par.renameto = " ".join(row[0] for row in rows)
        parts.append(part)
    merged = make(td.mergeCHOP, name, y)
    wire(merged, *parts)
    return merged


def _rewire_merge(merge, nodes):
    """Set merge_out's inputs to exactly: what was there, then `nodes`, once each.

    Why it rebuilds the whole list instead of adding what is missing. Two
    behaviours of the Merge CHOP make the obvious approach wrong, and both were
    measured here rather than read anywhere:

      * Connecting to an input connector that reports itself FREE can INSERT
          rather than fill, pushing the existing connection down and leaving it
          attached at both positions. Five nodes connected that way produced five
          duplicate `derive_chop` connections - and `derive_chop` is 171 channels,
          so the COMP published 1710 where 171 were meant. A Merge CHOP accepts
          the same operator on any number of inputs without a word of complaint,
          and the duplicates are invisible downstream because `chan()` returns the
          first match. The output channel count is the only symptom.
      * The connection list does not settle after a destroy, even across a forced
          cook, so "is it already connected?" cannot be answered reliably at the
          moment a builder wants to know.

    So nothing is inspected and patched. The end state is asserted: disconnect
    everything, then connect the intended list in order. Idempotent however many
    times this script runs - which matters, because the MCP bridge has been
    observed executing it TWICE per call.

    Returns the names it wired, in order.
    """
    owned = {node.name for node in nodes}
    keep = []
    seen = set()
    for existing in merge.inputs:
        # First occurrence only, and never one of ours - ours are appended below
        # in a known order.
        if existing.name not in owned and existing.name not in seen:
            keep.append(existing)
            seen.add(existing.name)
    desired = keep + list(nodes)

    # Disconnect connector 0 repeatedly rather than iterating: the list shifts
    # under a disconnect, and a single pass leaves entries behind.
    for _attempt in range(256):         # bounded; a runaway loop is not a fix
        if not merge.inputs:
            break
        merge.inputConnectors[0].disconnect()
    for index, node in enumerate(desired):
        merge.inputConnectors[index].connect(node)
    return [node.name for node in desired]


def _refresh_thresholds(comp):
    """Write the current Tuning values into lat_on and lat_off. Returns how many.

    Called once at build and once per parameter change, never per frame. The single
    place the threshold values are copied, so a retune and a rebuild cannot produce
    different networks.
    """
    written = 0
    for node_name, column in (("lat_on", 3), ("lat_off", 4)):
        # Inside the group now, so the path is relative to the top-level COMP.
        node = comp.op("%s/%s" % (GROUP, node_name))
        if node is None:
            continue
        for index, row in enumerate(LATCHES):
            parameter = getattr(comp.par, row[column], None)
            if parameter is None:
                continue
            node.par["value%d" % index] = float(parameter.eval())
            written += 1
    return written


def _verify_hysteresis(comp):
    """Every `off` must exceed its `on`, or there is no dead band to hold in."""
    problems = []
    for name in sorted({n[:-2] if n.endswith("on") else n[:-3]
                        for n in THRESHOLD_DEFAULTS}):
        on = float(getattr(comp.par, name + "on").eval())
        off = float(getattr(comp.par, name + "off").eval())
        if off <= on:
            problems.append("%s: on %.3f >= off %.3f - no dead band, will chatter"
                            % (name, on, off))
    return problems


def main():
    global THRESHOLD_DEFAULTS
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # PURGE FIRST. TouchDesigner's Python process outlives every run of this
    # script, so `import visionhands.tuning` returns whatever was imported hours
    # ago - editing the repo does nothing. Not a subtle failure, but a silent one:
    # adding the Trigger thresholds to tuning.py and re-running this built a bank
    # referencing `parent().par.Triggeron`, which the Tuning page did not have,
    # because the page was built from the STALE table. Every affected Constant CHOP
    # then errored once per channel per cook.
    #
    # Safe to purge: these are pure Python with no C extension state, and the only
    # thing holding references into them is the callbacks DAT, whose text this
    # script rewrites anyway - which is what makes TD recompile it against the
    # fresh import.
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    # One table, shared with the tests. Its import-time self-check refuses a
    # threshold pair with no dead band, which is a build that would chatter.
    from visionhands.tuning import THRESHOLD_DEFAULTS as DEFAULTS
    THRESHOLD_DEFAULTS = DEFAULTS

    comp = op(COMP_PATH)
    if comp is None:
        print("FAIL no COMP at %s - run tools/td_build_comp.py first" % COMP_PATH)
        return
    source = comp.op("derive_chop")
    if source is None:
        print("FAIL no derive_chop - run tools/td_add_derive.py first")
        return

    # -- clear our own operators ------------------------------------------
    # REUSE the group, clear its CHILDREN - destroying it orphans everything wired
    # to its output, and a dangling input cannot be told from one never connected
    # (DESIGN.md 2.11).
    group = comp.op(GROUP)
    if group is None:
        group = comp.create(td.baseCOMP, GROUP)
    else:
        for child in list(group.children):
            child.destroy()
    group.nodeX, group.nodeY = -1100, -1500
    group.color = (0.5, 0.35, 0.45)
    removed = 0
    for child in list(comp.children):
        if child.name.startswith(PREFIX):
            child.destroy()
            removed += 1
    print("1. `%s` group%s" % (GROUP, ", cleared %d loose %s* operators"
                               % (removed, PREFIX) if removed else ""))

    _threshold_page(comp)
    print("2. Tuning page: " + ", ".join(
        "%s=%.2f" % (n, float(getattr(comp.par, n).eval()))
        for n in sorted(THRESHOLD_DEFAULTS)))

    column = [0]

    def make(kind, name, y=ROW_Y):
        node = group.create(kind, PREFIX + name)
        node.nodeX, node.nodeY = -1400 + column[0] * COLUMN_W, y
        column[0] += 1
        return node

    # TWO inputs. Input 0 is the derived attributes - the distances and validity
    # flags every latch watches. Input 1 is `ready` from the temporal group, which
    # is what the gate ANDs in. Wired rather than looked up by name, so the
    # dependency is a line in the network.
    derived_in = group.create(td.inCHOP, "in1")
    derived_in.nodeX, derived_in.nodeY = -1600, ROW_Y
    ready_in = group.create(td.inCHOP, "in2")
    ready_in.nodeX, ready_in.nodeY = -1600, ROW_Y - 150
    group.inputConnectors[0].connect(source)
    ready_group = comp.op(READY_SOURCE)
    if ready_group is not None and len(ready_group.outputConnectors) > 1:
        group.inputConnectors[1].connect(ready_group.outputConnectors[1])

    def wire(node, *inputs):
        for index, source_op in enumerate(inputs):
            node.inputConnectors[index].connect(source_op)
        return node

    def named(node):
        node.cook(force=True)
        return [c.name for c in node.chans()]

    # -- the distances and the validity flags, renamed to the working names
    # One helper for both, because both columns repeat a source channel and a
    # Select can emit each source only once - see _fan.
    dist = _fan(td, make, wire, derived_in, "dist", 1, ROW_Y)

    valid_raw = _fan(td, make, wire, derived_in, "valid_raw", 2, ROW_Y - 150)

    # -- the gate: raw validity AND whatever the temporal group says --------
    # docs/ATTRIBUTES.md gates the latches on `h{i}_active` - `valid` DEBOUNCED
    # over Activateframes/Deactivateframes - and on the stream being LIVE, because
    # a dead sidecar leaves TouchDesigner's channels frozen rather than zeroed
    # (DESIGN.md 2.9) so every term of raw validity keeps reporting the last good
    # frame for ever.
    #
    # Both of those live in tools/td_add_temporal.py now, which publishes them
    # already combined as `tmp_ready` - three channels, `h{i}_valid` and
    # `both_valid`, each `active AND live`. Liveness used to be computed HERE, and
    # moving it out is what breaks the dependency cycle between the two groups:
    # the latch bank read `active` from temporal while temporal read `live` from
    # the latch bank. Flat, TouchDesigner tolerated that because the real data
    # dependencies were acyclic; as wired COMPs it would not.
    #
    # An OPTIONAL dependency: if `tmp_ready` is not there the bank gates on raw
    # validity and says so, rather than erroring per channel per cook - which is
    # what a missing reference does (measured, when the Trigger thresholds were
    # added).
    ready = ready_in if group.inputConnectors[1].connections else None
    if ready is not None:
        gate13 = _fan(td, make, wire, ready, "gate", 2, ROW_Y - 150)
        valid = make(td.logicCHOP, "valid", ROW_Y - 150)
        wire(valid, valid_raw, gate13)
        valid.par.chopop = "and"
        valid.par.match = "name"
    else:
        gate13 = None
        valid = valid_raw

    # -- the thresholds, as channels ---------------------------------------
    # Constant CHOPs with the working names, values bound by expression to the
    # Tuning parameters. Thresholds as CHANNELS rather than as numbers inside an
    # expression is what makes the comparison one operator wide instead of five:
    # `dist - on` is a channel-wise subtract, and every latch gets its own
    # threshold from its own channel.
    def thresholds(name, column_index, y):
        """A Constant CHOP of STATIC threshold values, not of expressions.

        Expressions were the obvious choice and cost 0.110 ms a frame between the
        two of them - MEASURED - because each of the 15 values was a separate
        Python expression re-evaluated every cook, to deliver six numbers that
        change only when somebody drags a slider. Thirty evaluations per frame for
        six numbers.

        Static values with a Parameter Execute DAT rewriting them on change gives
        identical channels for no per-frame Python at all. `_refresh_thresholds`
        below is the one function both this and the DAT call, so the build path and
        the retune path cannot disagree.
        """
        node = make(td.constantCHOP, name, y)
        node.seq.const.numBlocks = len(LATCHES)     # default is 1
        for index, row in enumerate(LATCHES):
            node.par["name%d" % index] = row[0]
        return node

    on = thresholds("on", 3, ROW_Y - 300)
    off = thresholds("off", 4, ROW_Y - 450)
    _refresh_thresholds(comp)

    # The latch's INITIAL state: released. Also the Feedback CHOP's channel
    # template - see trap 2 in the module docstring. Zeros rather than the
    # validity flags, because initialising to "valid" would engage every latch on
    # the first frame a hand appeared and emit a start pulse for a gesture nobody
    # made.
    zero = make(td.constantCHOP, "zero", ROW_Y - 600)
    zero.seq.const.numBlocks = len(LATCHES)
    for index, row in enumerate(LATCHES):
        zero.par["name%d" % index] = row[0]
        zero.par["value%d" % index] = 0.0

    # -- the two comparisons -----------------------------------------------
    # Math sub is input1 - input2 (verified live), so these are dist - on and
    # dist - off, and the Logic CHOP's convert does the sign test.
    def compare(name, threshold, convert):
        sub = make(td.mathCHOP, "sub_" + name)
        wire(sub, dist, threshold)
        sub.par.chopop = "sub"
        sub.par.match = "name"
        test = make(td.logicCHOP, name)
        wire(test, sub)
        test.par.convert = convert          # 'lt' = On When Less Than Zero
        return test

    below_on = compare("below_on", on, "lt")        # dist < on
    above_off = compare("above_off", off, "gt")     # dist > off

    # -- the recurrence -----------------------------------------------------
    def logic(name, *inputs, **kwargs):
        node = make(td.logicCHOP, name)
        wire(node, *inputs)
        for key, value in kwargs.items():
            node.par[key] = value
        if len(inputs) > 1:
            # Never leave this at the default `index`. See trap 3.
            node.par.match = "name"
        return node

    # `prev` - the state on the previous frame. Input 0 closes the loop from
    # lat_state; input 1 is the template and the initial value.
    previous = make(td.feedbackCHOP, "prev")
    previous.par.output = "previous"                 # Previous Channels at Previous Time

    not_off = logic("not_above_off", above_off, preop="invert")
    held = logic("held", previous, not_off, chopop="and")        # prev AND NOT above_off
    engage = logic("engage", below_on, held, chopop="or")        # below_on OR held
    state = logic("state", engage, valid, chopop="and")          # ... AND valid

    # Close the loop. Wired last because lat_state has to exist first, and this
    # is the edge that makes the whole thing a latch rather than a comparator.
    previous.inputConnectors[0].connect(state)
    previous.inputConnectors[1].connect(zero)

    # -- the edge pulses ----------------------------------------------------
    # Derived from `prev` rather than from a Logic CHOP's own `rise`/`fall`
    # convert. Both work, but `prev` is the SAME previous state the latch itself
    # consulted, so a start pulse is provably the transition the latch made. An
    # independent edge detector keeps its own history, and if it ever cooks a
    # different number of times than the loop, the pulses drift away from the
    # state they are supposed to describe.
    not_prev = logic("not_prev", previous, preop="invert")
    not_state = logic("not_state", state, preop="invert")
    start = logic("start", state, not_prev, chopop="and")        # rose this frame
    end = logic("end", previous, not_state, chopop="and")        # fell this frame

    # -- the fire counters --------------------------------------------------
    # docs/ATTRIBUTES.md asks for `h{i}_pinch_count` - how many times the gesture
    # has fired - and is explicit that a counter is the right tool for that and
    # the wrong tool for the state itself.
    #
    # An accumulator (Feedback plus an add) rather than a Count CHOP. The Count
    # CHOP is the obvious operator and was tried first; two things made it the
    # harder of two equivalent options. Its `offtoon`/`on`/`ontooff`/`off`
    # parameters LOOK like toggles and are actually menus of actions
    # (none / inc / dec / inctime / dectime / reset), so assigning True leaves
    # them at 'none' with no error and the counter sits at zero for ever; and once
    # that was corrected it still read zero through four full sweeps, with Time
    # Slice as the remaining suspect and no way to see inside it. This is instead
    # the same construction as the latch's own `prev`, already proven to carry
    # state across frames in this exact network:
    #
    #     count = count_on_the_previous_frame + pulse
    #
    # The pulse is 0 or 1, so this counts the FRAMES it was high - deliberately
    # stricter than counting rising edges. `start = state AND NOT prev` is one
    # frame wide by construction, so the two agree exactly when the network is
    # right, and a pulse that ever lingered two frames doubles the count instead
    # of passing silently. Off-to-on counting would have reported 4 either way.
    def accumulate(name, pulse, y):
        """count = count_on_the_previous_frame + pulse. Frames-high, so strict."""
        previous_count = make(td.feedbackCHOP, name + "_prev", y)
        previous_count.par.output = "previous"
        total = make(td.mathCHOP, name, y)
        wire(total, previous_count, pulse)
        total.par.chopop = "add"
        total.par.match = "name"
        # Same trap as the latch's own feedback: input 1 is the channel template
        # and the initial value, and without it the operator emits nothing at all.
        # `lat_zero` also makes a project reload come back at 0 and RELEASED, so
        # the phantom-end-pulse-on-reload hazard docs/ATTRIBUTES.md warns about
        # cannot happen. The converse does: reloading mid-gesture fires one
        # spurious start. That is inherent to a level-driven latch and correct.
        previous_count.inputConnectors[0].connect(total)
        previous_count.inputConnectors[1].connect(zero)
        return total

    counter = accumulate("count", start, ROW_Y - 600)
    # The falling edges get their own counter, because otherwise NOTHING measures
    # them: every sweep passed with `h{i}_e_pinch_end`, `h{i}_e_snap_end` and
    # `e_apart` structurally present and behaviourally untested. With both, a
    # four-sweep ramp must give +4 on each, and the two counts must agree to
    # within the currently-engaged state.
    counter_end = accumulate("count_end", end, ROW_Y - 750)

    # -- publish under the documented names --------------------------------
    def publish(node, name, column_index, y):
        """Rename the working names to the published ones, keyed on the names."""
        out = make(td.renameCHOP, "out_" + name, y)
        wire(out, node)
        # Same reasoning as `lat_dist`: keyed on names so a missing channel drops
        # one latch rather than renaming four onto the wrong data.
        out.par.renamefrom = " ".join(WORKING)
        out.par.renameto = " ".join(row[column_index] for row in LATCHES)
        return out

    out_state = publish(state, "state", 5, ROW_Y)
    out_start = publish(start, "start", 6, ROW_Y - 150)
    out_end = publish(end, "end", 7, ROW_Y - 300)
    out_count = publish(counter, "count", 8, ROW_Y - 600)
    out_count_end = publish(counter_end, "count_end", 9, ROW_Y - 750)

    # both_pinching: the one channel that combines two latches rather than
    # running alongside them. `chanop` combines channels WITHIN one CHOP, which
    # is what collapses two into one; `chopop` would have combined inputs.
    both_sel = make(td.selectCHOP, "both_sel", ROW_Y - 450)
    wire(both_sel, out_state)
    both_sel.par.channames = "h0_pinching h1_pinching"
    both = make(td.logicCHOP, "both_pinching", ROW_Y - 450)
    wire(both, both_sel)
    both.par.chanop = "and"
    both.par.renamefrom = "*"
    both.par.renameto = "both_pinching"

    # -- the clock ----------------------------------------------------------
    # THE LEAST OBVIOUS OPERATORS HERE, and the reasoning has now been wrong twice.
    # What follows is what is actually measured, plus a design that does not depend
    # on which explanation is right.
    #
    # MEASURED, six operators at once, in this project: every terminal branch of
    # this bank - `lat_out_state`, `lat_out_start`, `lat_out_end`, `lat_out_count`,
    # `lat_out_count_end`, `lat_both_pinching` - had cooked FOUR times, all four
    # forced by this script, while `merge_out` downstream of them had cooked
    # 420,613 times. The only chain advancing was the one the clock happened to
    # pull. So TouchDesigner really does not cook a Merge input whose channels
    # nothing downstream asks for: this project's consumers select `*_tx` and
    # `*_ty`, and nothing else gets pulled.
    #
    # An earlier, single measurement appeared to contradict that - a detached clock
    # with `lat_state` still advancing in step with `merge_out`. It could not be
    # reproduced, and it is one observation against six. Recorded because it was
    # persuasive enough to make me rewrite DESIGN.md 2.10 in the wrong direction.
    #
    # WHY IT MATTERS AT ALL. For a stateless branch, cooking on demand is a pure
    # optimisation - an uncooked distance is recomputed the moment anyone asks. For
    # a recurrence it is fatal, and it fails silently: the state self-corrects
    # because it is level-driven, but every edge pulse is computed between two
    # frames that were never adjacent. Here it showed up as release counters stuck
    # at zero while the fire counters climbed - `lat_end` had cooked 4 times.
    #
    # AND SEPARATELY, the reason a clock is needed even where consumption is
    # guaranteed: the bank has to react to data STOPPING. When the sidecar dies the
    # OSC In CHOP freezes rather than zeroing (DESIGN.md 2.9), so `in1` stops
    # changing and nothing downstream of it cooks - including the liveness detector
    # whose whole job is to notice. Measured: `lat_live` sat at 1 for ever with
    # nothing sending, and a latch engaged at that moment never released.
    #
    # SO: one Null at Cook Type = Always, consuming a Merge of EVERY terminal
    # branch. Not just one of them, which is the mistake that left the end counters
    # dead. Nothing here depends on what any project downstream happens to select.
    terminals = make(td.mergeCHOP, "terminals", ROW_Y - 900)
    wire(terminals, out_state, out_start, out_end, out_count, out_count_end,
         both)
    clock = make(td.nullCHOP, "tick", ROW_Y - 900)
    wire(clock, terminals)
    clock.par.cooktype = "always"

    # One output for the whole bank - 76 channels - instead of five Merge inputs at
    # the top level. `lat_terminals` already merges everything the clock has to
    # pull, so it is exactly what should go out.
    group_out = group.create(td.outCHOP, "out1")
    group_out.nodeX, group_out.nodeY = 600, ROW_Y - 900
    group_out.inputConnectors[0].connect(terminals)

    # WHAT IT COSTS, stated honestly: the clock pulls `derive_chop`, which is
    # main-thread Python at 0.210 ms for 171 channels (DESIGN.md 2.7), so that
    # cooks on 100% of frames rather than only when a frame arrives - about 1.3% of
    # a 60 fps frame, paid always. It buys edge pulses that are correct and a bank
    # that releases when the camera goes away.
    #
    # TODO(M-groups): step 3 of docs/BUILD_PLAN.md gates groups with `allowCooking`
    # off on a group COMP. Cook Type = Always does not run inside a COMP whose
    # cooking is disabled, so a disabled group would freeze its latches and resume
    # with a stale `prev`. The clock has to live outside any gated group.

    # The DAT that keeps lat_on/lat_off current without costing a frame.
    threshold_dat = comp.op("lat_threshold_callbacks") or comp.create(
        td.parameterexecuteDAT, "lat_threshold_callbacks")
    threshold_dat.nodeX, threshold_dat.nodeY = 200, ROW_Y - 300
    threshold_dat.text = THRESHOLD_CALLBACK % {
        "rows": [(row[3], row[4]) for row in LATCHES], "group": GROUP}
    threshold_dat.par.op = comp.path
    threshold_dat.par.pars = " ".join(sorted(THRESHOLD_DEFAULTS))
    threshold_dat.par.valuechange = True

    print("3. %d operators inside `%s`" % (len(group.children), GROUP))

    # -- structural verification -------------------------------------------
    # Not a formality. `match = name` silently drops a channel it cannot pair,
    # and a Feedback CHOP missing its second input emits nothing at all - both
    # would leave a network that cooks cleanly and computes the wrong thing.
    print("4. structure:")
    failures = []
    checks = [(dist, WORKING), (valid_raw, WORKING), (valid, WORKING)]
    if gate13 is not None:
        checks.append((gate13, WORKING))
    checks += [
              (on, WORKING), (off, WORKING), (zero, WORKING),
              (below_on, WORKING), (above_off, WORKING), (previous, WORKING),
              (held, WORKING), (engage, WORKING), (state, WORKING),
              (start, WORKING), (end, WORKING),
              (out_state, tuple(r[5] for r in LATCHES)),
              (out_start, tuple(r[6] for r in LATCHES)),
              (out_end, tuple(r[7] for r in LATCHES)),
              (counter, WORKING), (counter_end, WORKING),
              (out_count, tuple(r[8] for r in LATCHES)),
              (out_count_end, tuple(r[9] for r in LATCHES)),
              # Checked explicitly because the AND collapses two channels into
              # one: if `h1_pinching` were ever missing, the Select would emit a
              # single channel, the AND would still emit one channel called
              # `both_pinching`, and it would silently equal `h0_pinching`.
              (both_sel, ("h0_pinching", "h1_pinching")),
              (both, ("both_pinching",)),
              # Every published channel, plus both_pinching. The gate broadcast
              # is NOT here: it is upstream of lat_valid, so it is pulled anyway,
              # and tmp_ready has the temporal group's own clock behind it.
              (terminals, (*(n for row in LATCHES for n in row[5:10]),
                           "both_pinching"))]
    for node, expected in checks:
        actual = tuple(named(node))
        # Compared as SETS. Every rename is now keyed on channel names rather than
        # on position, so order carries no meaning and every multi-input operator
        # pairs by name - asserting an order here would be asserting something the
        # network no longer depends on, and would fail on a harmless reordering.
        ok = set(actual) == set(expected) and len(actual) == len(expected)
        if not ok:
            failures.append("%s: expected %r, got %r" % (node.name, expected, actual))
        print("   %s %-22s %d chans  %s" % ("ok " if ok else "BAD", node.name,
                                            len(actual), " ".join(sorted(actual)[:4])))
        if node.errors():
            failures.append("%s: %s" % (node.name, node.errors()))

    for problem in _verify_hysteresis(comp):
        failures.append(problem)

    # -- into the COMP's output -------------------------------------------
    merge = comp.op("merge_out")
    if merge is not None:
        stale = (*("lat_out_%s" % s for s in
                   ("state", "start", "end", "count", "count_end")),
                 "lat_both_pinching")
        _attach_once(merge, group, drop_names=stale)
        merge.cook(force=True)
        owners = [x.owner for conn in merge.inputConnectors
                  for x in conn.connections]
        if owners.count(group) != 1:
            failures.append("`%s` feeds merge_out %d times, not once"
                            % (GROUP, owners.count(group)))

    out_chop = comp.op("out1")
    out_chop.cook(force=True)
    print("5. COMP output: %d channels" % out_chop.numChans)
    for probe in ("h0_pinching", "h0_e_pinch_start", "h0_snapping",
                  "hands_together", "e_clap", "both_pinching", "h0_pinch_count",
                  "h0_pinch_end_count"):
        channel = out_chop.chan(probe)
        print("   %-18s %s" % (probe, "MISSING" if channel is None
                               else round(channel[0], 3)))

    # Both cook counts are ~0 here because everything was just created; what
    # matters is that lat_state CLIMBS on its own afterwards, which is what
    # tools/td_verify_latches.py checks on every run. Reported here only so the
    # numbers exist to compare against.
    print("6. cooks: lat_state=%d, merge_out=%d (both climb from here; "
          "tools/td_verify_latches.py checks that lat_state really does)"
          % (state.totalCooks, comp.op("merge_out").totalCooks))
    print("   gate: raw validity%s"
          % (" AND tmp_ready (the debounced active, AND liveness)" if ready is not None
             else " ONLY - run tools/td_add_temporal.py, then this again"))
    print("   clock pulls %d terminal channels; tools/td_verify_latches.py checks "
          "that lat_end cooks as often as lat_start" % terminals.numChans)

    if failures:
        print("\nFAILURES (%d):" % len(failures))
        for failure in failures:
            print("   " + failure)
    else:
        print("\nstructure verified. Now exercise it over TIME - a latch cannot be")
        print("checked from one frame:")
        print("   ~/.venvs/visionhands/bin/python tools/send_synthetic.py ramp --cycles 4")


main()
