#!/usr/bin/env python
"""PROTOTYPE: `temporal` as ONE Script CHOP, beside the 74-operator version.

    Paste into a Text DAT, Run Script. Idempotent. Builds
    `/project1/vision/hands/temporal_proto` with `allowCooking = False`, wired from
    the same two inputs as the real group and attached to NOTHING downstream.

    TO A/B IT
        op('/project1/vision/hands/temporal_proto').allowCooking = True
        op('/project1/vision/hands/temporal').allowCooking = False
        ...then tools/td_profile.py, and swap them back.

WHAT QUESTION THIS ANSWERS. Whether collapsing a chain of native CHOPs into a single
Script CHOP is faster, and by enough to matter. `temporal` is 74 operators for 27
channels, and at the measured ~1.2 microseconds per channel per operator
(DESIGN.md 2.14) that is where its cost comes from. A Script CHOP pays that once.
The verdict is in `docs/BUILD_PLAN.md` step 12.

WHY IT IS BUILT HERE AND NOT IN A DUPLICATED COMP. The obvious way to sandbox this
is to duplicate `/project1/vision` and freeze the copy - and it would bind port
10000 a SECOND TIME. A whole builder was retired for exactly that
(`td_setup_osc.py`, see `tools/td_build_vision.py`). Two OSC In CHOPs on one port is
a stream arriving in a CHOP nobody is reading, and it would be indistinguishable from
the prototype simply not working.

Beside the real group is also the better experiment: both see the SAME input on the
SAME frame, so the comparison is not across two runs with whatever else the machine
was doing in between.

WHAT IT IS NOT. Not wired into `merge_out`, so none of its channels reach the COMP's
output and nothing downstream can come to depend on it. Frozen by default, so
building it costs nothing until somebody deliberately turns it on.

THE CLOCK IS NOT OPTIONAL, for the same reason the real group has one. TouchDesigner
does not cook a branch whose channels nothing asks for, and a recurrence that cooks
intermittently produces correct-looking states with nonsense edges between frames
that were never adjacent (DESIGN.md 2.10). The Null at Cook Type = Always sits INSIDE
the group so it freezes with it.

Ref: appletd/temporal.py (the arithmetic, tested with no TouchDesigner),
     docs/BUILD_PLAN.md step 12, DESIGN.md 2.10, 2.14.
"""

import os
import sys

# Derived from this file's own location. A literal path here meant the project
# opened on exactly one machine; `__file__` is set by the shell, by
# TouchDesigner's run(), and by tools/td_rebuild.py before each exec.
# tools/td_paths.py has the full reasoning and why it is not imported from there.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER_PATH = "/project1/vision"
COMP_PATH = MASTER_PATH + "/hands"
GROUP = "temporal_proto"

COL_W = 200
ROW_H = 150

CALLBACK = '''# Generated by tools/td_add_temporal_proto.py
#
# A thin wrapper, the same shape as derive_callbacks: every recurrence is in
# `appletd/temporal.py`, which is tested with no TouchDesigner present.
#
# THE STATE LIVES IN THIS MODULE'S GLOBALS, and the reason it does NOT live in
# operator storage is the sharpest evidence this whole experiment produced.
#
# It was in `scriptOp.store()` first. TouchDesigner PICKLES operator storage into the
# .toe on save, so saving the project failed:
#
#   Warning: Error saving storage for operator .../temporal_proto/proto:
#   PicklingError: Can't pickle <class 'appletd.temporal.TemporalState'>:
#   it's not the same object as appletd.temporal.TemporalState
#
# Two things at once. Pickle compares the instance's class against the module's
# current class BY IDENTITY, and every builder here purges `appletd.*` from
# `sys.modules` (DESIGN.md 2.11) - so after any rebuild the stored object's class is a
# different object with the same name, and pickle refuses. And more fundamentally: a
# recurrence's state is not something a project file should be carrying at all.
#
# `docs/ATTRIBUTES.md` gave "no hidden Python state for a project reload to treat
# unpredictably" as the third reason memory belongs in native CHOPs. It turned out to
# be stronger than that: the state does not merely reload unpredictably, it stops the
# project SAVING cleanly. Module globals are not pickled, so they are the right place
# - and they are lost on a recompile, which for a level-driven recurrence is one
# self-correcting frame.
import sys

REPO_ROOT = %(repo)r
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)          # append, never insert

from appletd.temporal import TemporalParams, TemporalState, advance

# Module state, deliberately. NOT operator storage - see above.
_STATE = {}

# This one IS in operator storage, and safely: a tuple of strings pickles fine.
NAMES_KEY = "temporal_proto_names"


def _params(comp):
    """Read the Advanced page, falling back to the module defaults."""
    def par(name, default):
        p = getattr(comp.par, name, None)
        return default if p is None else float(p.eval())
    return TemporalParams(
        activate_frames=int(par("Activateframes", 3)),
        deactivate_frames=int(par("Deactivateframes", 6)),
        velocity_filter_s=par("Velocityfilter", 0.15),
        speedfloor=par("Speedfloor", 0.05))


def onCook(scriptOp):
    # Not time-sliced: this publishes a snapshot of one frame, and editing
    # numSamples in Time Slice mode is unsupported.
    scriptOp.isTimeSlice = False
    if len(scriptOp.inputs) < 2:
        scriptOp.clear()
        return

    values = {chan.name: chan[0] for chan in scriptOp.inputs[0].chans()}
    # `seq` off the RAW stream, and ONLY `seq`. Liveness must not depend on the
    # filter chain it is watching, and reading input 1 in full would be another 141
    # channel reads for one number.
    raw_seq = scriptOp.inputs[1].chan("seq")
    values["seq"] = 0.0 if raw_seq is None else raw_seq[0]

    # `isinstance` against the FRESHLY IMPORTED class, which is what makes this
    # self-healing: after a builder purges `appletd.*` from sys.modules the old
    # instance's class is a different object, the check fails, and the recurrence
    # starts over. One frame, and it is level-driven.
    state = _STATE.get("state")
    if not isinstance(state, TemporalState):
        _STATE["state"] = state = TemporalState()

    # dt from TouchDesigner's own frame step, NOT from a clock kept in operator
    # storage. That is a bug fix and it is the most expensive thing this prototype
    # taught: `store()` on EVERY cook took the whole COMP from 2.1 ms to 13.8 ms and
    # the cook rate from 89 frames in 89 to 25 - a 5x collapse. `derive_chop` gets
    # away with storage because it only writes when the channel SET changes, which is
    # almost never. Per-cook `store()` is not a scratchpad.
    dt = max(0.0, float(absTime.stepSeconds))

    comp = op.Vision or scriptOp.parent(2)
    out = advance(values, state, _params(comp), dt)

    # The same channel cache derive_chop uses: `len(scriptOp.chans())` because
    # `numChans` RAISES inside onCook, and a Script CHOP's channels persist between
    # cooks so 28 appends per frame are avoidable.
    names = tuple(sorted(out))
    if len(scriptOp.chans()) != len(names) or scriptOp.fetch(NAMES_KEY, None) != names:
        scriptOp.clear()
        scriptOp.numSamples = 1
        for name in names:
            scriptOp.appendChan(name)
        scriptOp.store(NAMES_KEY, names)
    for name, chan in zip(names, scriptOp.chans()):
        chan[0] = out[name]
'''

NOTES = """TEMPORAL_PROTO - an EXPERIMENT. Frozen by default. Not wired to anything.

  in1 (derive_chop) --+
                      +-> proto (Script CHOP) -> out1
  in2 (the raw stream)|                       -> tick (Cook Type = Always)
                      +   ...for `seq` only

The question: is one Script CHOP faster than the 74 native operators next door, and
by enough to be worth what it costs? All the arithmetic is in
appletd/temporal.py, tested with no TouchDesigner present. The verdict is in
docs/BUILD_PLAN.md step 12 - read that before acting on this.

TO A/B IT, one at a time, then run tools/td_profile.py:

  op('.../temporal_proto').allowCooking = True
  op('.../temporal').allowCooking = False

WHAT IT COSTS IF IT WINS, which is the part a stopwatch does not show:

  * the state is a Python object in operator storage. A save and reload treats it
    unpredictably - the third reason docs/ATTRIBUTES.md put memory in CHOPs.
  * the windows are counted in COOKS, not in time. A Trail CHOP's window is a
    window whatever the cook rate does.
  * 74 operators can be inspected in the network with a hand in front of the
    camera. A dict cannot.

Built by tools/td_add_temporal_proto.py. Edits here are overwritten."""


def main():
    import td

    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    for stale in [n for n in list(sys.modules)
                  if n == "appletd" or n.startswith("appletd.")]:
        del sys.modules[stale]
    from appletd.temporal import channel_names

    master = op(MASTER_PATH)
    comp = op(COMP_PATH)
    if master is None or comp is None:
        print("FAIL no COMP at %s - run tools/td_build_vision.py first"
              % (MASTER_PATH if master is None else COMP_PATH))
        return
    source = comp.op("derive_chop")
    raw = comp.op("in1")
    if source is None or raw is None:
        print("FAIL need derive_chop and in1 - run tools/td_add_derive.py first")
        return

    group = comp.op(GROUP)
    if group is None:
        group = comp.create(td.baseCOMP, GROUP)
    for child in list(group.children):
        if child.valid:
            # A Script CHOP takes its docked callbacks DAT down with it, so a
            # snapshot list can hold an already-deleted operator (DESIGN.md 2.11).
            child.destroy()
    # Below the real group, so the two sit next to each other in the network and the
    # A/B is visible rather than something you have to remember.
    group.nodeX, group.nodeY = -1 * COL_W, -8 * ROW_H
    group.color = (0.55, 0.45, 0.2)

    group_in = group.create(td.inCHOP, "in1")
    group_in.nodeX, group_in.nodeY = 0, 0
    raw_in = group.create(td.inCHOP, "in2")
    raw_in.nodeX, raw_in.nodeY = 0, -ROW_H
    group.inputConnectors[0].connect(source)
    group.inputConnectors[1].connect(raw)

    proto = group.create(td.scriptCHOP, "proto")
    proto.nodeX, proto.nodeY = COL_W, 0
    proto.inputConnectors[0].connect(group_in)
    proto.inputConnectors[1].connect(raw_in)
    # TD auto-docks `proto_callbacks` beside a new Script CHOP; use it rather than
    # creating a second one and guessing which name the collision took.
    callbacks = group.op("proto_callbacks") or group.create(td.textDAT,
                                                           "proto_callbacks")
    callbacks.nodeX, callbacks.nodeY = 0, ROW_H
    callbacks.text = CALLBACK % {"repo": REPO_ROOT}
    proto.par.callbacks = callbacks.path
    # Remove the unpicklable state an earlier version of this builder stored on the
    # operator. Without this, the .toe keeps failing to save even though the callback
    # no longer writes it - storage outlives the code that put it there.
    for stale_key in ("temporal_proto_state", "temporal_proto_clock"):
        if stale_key in proto.storage:
            proto.unstore(stale_key)

    group_out = group.create(td.outCHOP, "out1")
    group_out.nodeX, group_out.nodeY = 2 * COL_W, 0
    group_out.inputConnectors[0].connect(proto)

    clock = group.create(td.nullCHOP, "tick")
    clock.nodeX, clock.nodeY = 2 * COL_W, -ROW_H
    clock.inputConnectors[0].connect(proto)
    clock.par.cooktype = "always"

    notes = group.create(td.textDAT, "notes")
    notes.nodeX, notes.nodeY = 0, 2 * ROW_H
    notes.text = NOTES

    # FROZEN, and last - so it cooks once here and has channels to show before it
    # stops. A group frozen before its first cook has no channels at all, which
    # looks exactly like a broken build.
    proto.cook(force=True)
    produced = tuple(c.name for c in proto.chans())
    group.allowCooking = False

    expected = channel_names()
    print("`%s` built, %d operators, FROZEN." % (GROUP, len(group.children)))
    print("   %d channels: %s" % (len(produced), ", ".join(produced[:6]) + " ..."))
    if produced != expected:
        missing = sorted(set(expected) - set(produced))
        extra = sorted(set(produced) - set(expected))
        print("   FAIL the Script CHOP and appletd.temporal disagree.")
        print("        missing %r extra %r" % (missing[:5], extra[:5]))
    elif proto.errors():
        print("   FAIL %s" % proto.errors()[:200])
    else:
        print("   matches appletd.temporal.channel_names() exactly.")
    print()
    print("   A/B it one at a time, then run tools/td_profile.py:")
    print("     op('%s').allowCooking = True" % group.path)
    print("     op('%s/temporal').allowCooking = False" % comp.path)
    print("   It is attached to NOTHING downstream, so nothing can come to depend")
    print("   on it while the question is still open.")


main()
