#!/usr/bin/env python
"""Build `/project1/vision`: one COMP holding all three streams and every control.

    HOW TO USE
      Paste into a Text DAT in TouchDesigner, right-click > "Run Script".
      Then, in order:
        td_add_filter.py    the one-euro filter, in EVERY stream
        td_add_coords.py    the world and pixel spaces, in EVERY stream
        td_add_derive.py    the stateless hand attributes
        td_add_temporal.py  presence, liveness, velocity  (hands)
        td_add_latches.py   the proximity latches         (hands)
        td_add_groups.py    the Attributes page and the cook gating
      Idempotent: run any of them as often as you like.

    WHAT IT PRODUCES

        /project1/vision            every user parameter, and the sidecar control
          hands_osc  port 10000  ->  hands   ->  out1
          pose_osc   port 10001  ->  pose    ->  out2
          face_osc   port 10002  ->  face    ->  out3
          status                                 the sidecar's own sc_* channels

WHY ONE COMP AROUND THE THREE, replacing the three siblings this supersedes. The
filter and the coordinate spaces were built inside the hands COMP because hands
came first, and neither is remotely hand-specific: a body's joints and a face's
bounding box want the same smoothing and the same conversion into TouchDesigner
world and pixel space. Three copies of the Filter page, three Ortho Widths to keep
in step, and three Start buttons for one process would all have been wrong. So the
parameters live here, once, and every stream reads them.

    OLD PATH                      NEW PATH
    /project1/visionhands         /project1/vision/hands
    /project1/visionpose          /project1/vision/pose
    /project1/visionface          /project1/vision/face

An operator OUTSIDE this COMP cannot wire to a nested one - a TouchDesigner
connection joins siblings - so the master exposes each stream on its own output
connector, in that order. An expression can still reach inside:
`op('/project1/vision/hands')['h0_index_tip_tx']`.

HOW A NESTED OPERATOR REACHES THESE PARAMETERS: `op.Vision.par.Orthowidth`, via the
COMP's Global OP Shortcut, which is set below and VERIFIED to resolve from a nested
network. Not `parent(2).par.X`, which is what the groups used before: the depth is
now different for a group inside a stream than for one at the top, so a relative
reference would have to be counted per operator and would break the next time
anything moved. A shortcut is depth-independent and survives a rename.

WHAT IT DELIBERATELY DOES NOT DO. No joint renaming: the sidecar sends
`h0_index_tip_x` already, because naming belongs at the single source of truth
rather than in a lookup two hops downstream. An earlier version renamed
`h0_lm08_x` with a Rename CHOP, which works and renames BY POSITION - so the
mapping silently depended on channel order decided somewhere else.

Ref: DESIGN.md 6.4 (the streams and their ports), 7 (the coordinate contract),
     docs/BUILD_PLAN.md step 8.
"""

SIDECAR_CONTROL_SOURCE = '''# Generated by tools/td_build_vision.py
#
# Runs on TouchDesigner's main thread, on a pulse or at project exit. Never
# per-frame: pgrep costs a few milliseconds, which is nothing on a button press
# and would be rude every cook.
import os
import signal
import subprocess

SIDECAR_PYTHON = %(python)r
REPO_ROOT = %(repo)r
PORT = %(port)d
MATCH = "visionhands.sidecar"


def running_pids():
    """Every sidecar process on this machine, ours or not.

    Matching on the command line rather than tracking a Popen handle is what
    makes Stop work on a sidecar started from a terminal - which is how it gets
    started while developing, and exactly when you most want to stop it from
    here.

    TWO-STAGE MATCH, and the second stage is not paranoia - it was written after
    the first version SIGTERMed the shell that was grepping for the sidecar.
    `pgrep -f` matches the pattern anywhere in a full command line, so a
    terminal running `pgrep -f visionhands.sidecar`, an editor with the file
    open, or a `tail` on its log all match. Killing those is unacceptable, so
    every candidate is confirmed with `ps` before it is signalled:

        argv[0] must be a python             (a shell or a grep is not)
        the argv must contain -m visionhands.sidecar

    A shell whose command line merely mentions the sidecar has argv[0] of sh or
    zsh and is rejected; a python running `-c` with the string in it fails the
    second test.
    """
    try:
        found = subprocess.run(["pgrep", "-f", MATCH],
                               capture_output=True, text=True, timeout=5)
    except Exception as exc:
        print("[visionhands] pgrep failed: %%r" %% (exc,))
        return []

    pids = []
    for line in found.stdout.split():
        try:
            pid = int(line)
        except ValueError:
            continue
        if pid == os.getpid():
            continue                      # never signal TouchDesigner itself
        if _is_sidecar(pid):
            pids.append(pid)
    return pids


def _is_sidecar(pid):
    """Confirm a pid really is a sidecar, not something that merely mentions it."""
    try:
        # `command=` only. NOT `comm=`, which macOS truncates to 16 characters:
        # a venv interpreter comes back as "/Users/omer/.ven", whose basename is
        # ".ven", and the check silently matches nothing. That cost a debugging
        # round trip and would have been invisible - Stop would simply never
        # find anything.
        proc = subprocess.run(["ps", "-p", str(pid), "-o", "command="],
                              capture_output=True, text=True, timeout=5)
    except Exception:
        return False
    line = proc.stdout.strip()
    if not line:
        return False                      # already gone
    tokens = line.split()
    if not tokens or "python" not in os.path.basename(tokens[0]):
        return False
    # `-m` and the module name must be ADJACENT ARGUMENTS, not a substring of
    # the command line. A python running `-c "x='-m visionhands.sidecar'"`
    # contains the text but is not a sidecar, and signalling it would be exactly
    # the class of mistake that killed a shell a moment ago.
    for index, token in enumerate(tokens[:-1]):
        if token == "-m" and tokens[index + 1] == MATCH:
            return True
    return False


def start():
    """Start a sidecar, after stopping any that already exist.

    Stop-first for the same reason engine.start() does it: two processes holding
    one camera is the failure DESIGN.md 8 names, and it is easy to reach by
    pressing a button twice.
    """
    stop()
    # The toggle reaches the sidecar as a LAUNCH FLAG, read once at startup.
    # That is the whole mechanism, and it is why the toggle says "restart to
    # apply": the sidecar is a separate process and there is no control channel
    # into it. Adding one to change a hand partition would be a great deal of
    # machinery for something nobody changes mid-session. The same pattern is
    # settled for the future stream toggles - docs/BUILD_PLAN.md step 5.
    comp = op(%(comp)r)
    assign = comp is None or bool(comp.par.Slotassign.eval())
    # Which Vision requests the process will run. Each toggle is one name on the
    # command line; the sidecar validates the list and refuses an empty one.
    # A stream that is OFF still has all of its channels in TouchDesigner, as
    # zeros - what the toggle saves is the inference (DESIGN.md 6.4).
    streams = []
    for name, par_name in (("hands", "Streamhands"), ("pose", "Streampose"),
                           ("face", "Streamface")):
        if comp is None or bool(getattr(comp.par, par_name).eval()):
            streams.append(name)
    if not streams:
        # Checked here rather than left to the sidecar, so the message lands in
        # the Textport next to the button that was pressed. A sidecar with no
        # streams opens the camera and looks exactly like a working one with
        # nobody in frame.
        print("[visionhands] NOT STARTING: every stream toggle is off, so the "
              "sidecar would open the camera and run no inference at all.")
        return 0

    process = subprocess.Popen(
        [SIDECAR_PYTHON, "-m", "visionhands.sidecar",
         "--port", str(PORT), "--parent-pid", str(os.getpid()),
         "--slots", "chirality" if assign else "off",
         "--streams", ",".join(streams)],
        cwd=REPO_ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("[visionhands] sidecar started, pid %%d, slots=%%s, streams=%%s"
          %% (process.pid, "chirality (h0=right, h1=left)" if assign else "off",
              ",".join(streams)))
    # The ports each stream lands on, printed because "which port is pose on" is
    # the first question when the pose COMP shows no channels.
    print("[visionhands]   hands -> %%d   pose -> %%d   face -> %%d  (base + 0/1/2)"
          %% (PORT, PORT + 1, PORT + 2))
    return process.pid


def stop():
    """Stop every running sidecar. Returns how many were stopped.

    SIGTERM, not SIGKILL: the sidecar handles SIGTERM by stopping its capture
    session properly, and killing it outright would leave the camera to be
    reclaimed by the OS rather than released (DESIGN.md 8).
    """
    pids = running_pids()
    for pid in pids:
        try:
            os.kill(pid, signal.SIGTERM)
            print("[visionhands] stopped sidecar pid %%d" %% pid)
        except ProcessLookupError:
            pass
        except PermissionError:
            print("[visionhands] cannot signal pid %%d - not ours" %% pid)
    return len(pids)


def status():
    pids = running_pids()
    return "sidecar: %%s" %% (("running, pid %%s" %% pids) if pids else "not running")
'''

# The Parameter Execute DAT that turns a button press into a call.
SIDECAR_CALLBACK_SOURCE = '''# Generated by tools/td_build_vision.py
#
# TouchDesigner calls onPulse when a pulse parameter is pressed. The work lives
# in sidecar_control so it can also be called directly:
#     op('/project1/visionhands/sidecar_control').module.status()


def onPulse(par):
    control = op("sidecar_control").module
    if par.name == "Startsidecar":
        pid = control.start()
        par.owner.par.Sidecarpid = pid
    elif par.name == "Stopsidecar":
        stopped = control.stop()
        par.owner.par.Sidecarpid = 0
        print("[visionhands] stopped %d process(es)" % stopped)
    elif par.name == "Sidecarstatus":
        print("[visionhands] " + control.status())
'''

# Stops the sidecar when the project closes. Belt and braces with the sidecar's
# own parent-pid watch: this handles a clean quit, that handles a crash.
SIDECAR_EXIT_SOURCE = '''# Generated by tools/td_build_vision.py


def onExit():
    op("sidecar_control").module.stop()
'''

PARENT_PATH = "/project1"
COMP_NAME = "vision"
# The Global OP Shortcut every nested expression uses. Capitalised because that is
# how `op.Vision` reads at a call site, and it must not collide with anything else
# in the project - TD shortcuts are global.
OP_SHORTCUT = "Vision"

# One child COMP and one OSC In CHOP per stream, in the order their outputs are
# exposed. The ports come from the package, so the receiver cannot end up listening
# where the sender is not sending (DESIGN.md 6.4).
STREAM_NAMES = ("hands", "pose", "face")

OSC_PORT = 10000
REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
SIDECAR_PYTHON = "/Users/omer/.venvs/visionhands/bin/python"

# Defaults for the aspect and pixel conversions. MEASURED: the sidecar requests and
# receives 1280x720 (DESIGN.md 2.6), and Vision is fastest there.
#
# These are COMP parameters rather than baked-in numbers so a different camera does
# not need a rebuild, and they are read from the project's own render and camera
# when those exist. They are NOT read from the incoming channels: the wire contract
# deliberately does not carry width and height, and adding it would be a contract
# change to solve what a parameter already solves.
DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 720

# TouchDesigner's Camera COMP defaults to an Ortho Width of 1.0, so the visible
# world space is x in [-0.5, +0.5] and y in [-0.5/aspect, +0.5/aspect]. Matching
# that default means the common case needs no tuning at all.
DEFAULT_ORTHO_WIDTH = 1.0

# What the three COMPs this replaces were called. Destroyed at the end, once the new
# structure has been built and verified - so a half-finished run leaves the old one
# working rather than nothing working.
SUPERSEDED = ("visionhands", "visionpose", "visionface",
              "visionhands_osc", "visionpose_osc", "visionface_osc")


def main():
    import td

    print("=" * 70)
    print("vision: building the master COMP and its three streams")
    print("=" * 70)

    import sys
    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process (DESIGN.md 2.11).
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    from visionhands.streams import STATUS_PREFIX, port_for

    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s" % PARENT_PATH)
        return

    comp = parent.op(COMP_NAME)
    existed = comp is not None
    previous = {}
    if existed:
        # Remember what the user tuned, so a rebuild restores it rather than
        # resetting it. Every custom parameter, not a hand-maintained list: the
        # pages are built by six different scripts now and a list here would go
        # stale silently.
        previous = {par.name: par.eval() for par in comp.customPars}
    else:
        # First run: inherit whatever the COMP this supersedes was tuned to, so the
        # restructure does not quietly reset somebody's Ortho Width.
        old = parent.op("visionhands")
        if old is not None:
            previous = {par.name: par.eval() for par in old.customPars}
            print("0. inheriting %d tuned parameters from %s"
                  % (len(previous), old.path))
        comp = parent.create(td.baseCOMP, COMP_NAME)
    comp.nodeX, comp.nodeY = 250, 0
    comp.color = (0.25, 0.35, 0.45)
    # Everything inside is rebuilt by this script and the six that follow it, so
    # clearing is what keeps them all idempotent. The STREAM CHILDREN are spared:
    # destroying those would throw away the networks the other builders own, and
    # they clear their own contents when they run (DESIGN.md 2.11 - destroying a
    # group orphans its consumers).
    kept = set(STREAM_NAMES)
    for child in list(comp.children):
        if child.name not in kept:
            child.destroy()
    print("1. %s %s" % ("reusing" if existed else "created", comp.path))

    # The Global OP Shortcut, and it is load-bearing rather than convenience: every
    # expression in every nested group reads `op.Vision.par.X`. Set BEFORE anything
    # that writes such an expression, or the first cook reports a name error.
    comp.par.opshortcut = OP_SHORTCUT

    # -- the shared parameters --------------------------------------------
    page = _page(comp, "Vision")
    par_w = page.appendInt("Resw", label="Source Width")[0]
    par_h = page.appendInt("Resh", label="Source Height")[0]
    # `.default` always, `.val` only when the parameter is NEW. TD's append* reset
    # a parameter's attributes on rebuild, and a newly appended one reads 0 whatever
    # its default says - both measured, both in DESIGN.md 2.11. `previous` is the
    # record of what existed, so it answers the only question that matters here.
    par_w.default, par_h.default = DEFAULT_WIDTH, DEFAULT_HEIGHT
    par_ortho = page.appendFloat("Orthowidth", label="Camera Ortho Width")[0]
    par_ortho.default = DEFAULT_ORTHO_WIDTH
    par_rw = page.appendInt("Renderw", label="Render Width")[0]
    par_rh = page.appendInt("Renderh", label="Render Height")[0]
    par_rw.default, par_rh.default = DEFAULT_WIDTH, DEFAULT_HEIGHT
    for name, parameter in (("Resw", par_w), ("Resh", par_h),
                            ("Orthowidth", par_ortho),
                            ("Renderw", par_rw), ("Renderh", par_rh)):
        if name not in previous:
            parameter.val = parameter.default

    lifecycle = _page(comp, "Sidecar")
    # Slot assignment: h0 = the right hand, h1 = the left, whichever order Vision
    # reports them in (visionhands/slots.py). On the Sidecar page rather than with
    # the attribute toggles, because it is a property of the PROCESS and only takes
    # effect when one is started. NOTE the consequence: with this on, a single LEFT
    # hand puts nothing in h0, so every h0_* channel reads zero.
    par_slots = lifecycle.appendToggle(
        "Slotassign", label="Assign Slots (restart to apply)")[0]
    par_slots.default = True
    # Which Vision requests the sidecar runs. LAUNCH FLAGS, read once when the
    # process starts (DESIGN.md 6.4) - hence "restart to apply" on all three. What
    # they save is INFERENCE, not channels: a disabled stream keeps every channel it
    # has, reading zero, because a channel that vanishes breaks its consumers
    # silently (DESIGN.md 6.2).
    stream_pars = {}
    for stream, label, default in (("hands", "Hands Stream", True),
                                   ("pose", "Body Pose Stream", False),
                                   ("face", "Face Stream", False)):
        par = lifecycle.appendToggle("Stream" + stream,
                                     label="%s (restart to apply)" % label)[0]
        par.default = default
        stream_pars[stream] = par
    for name, parameter in [("Slotassign", par_slots)] + [
            ("Stream" + s, p) for s, p in stream_pars.items()]:
        if name not in previous:
            parameter.val = parameter.default

    lifecycle.appendPulse("Startsidecar", label="Start Sidecar")
    lifecycle.appendPulse("Stopsidecar", label="Stop Sidecar")
    lifecycle.appendPulse("Sidecarstatus", label="Print Status")
    par_pid = lifecycle.appendInt("Sidecarpid", label="Sidecar PID")[0]
    par_pid.readOnly = True

    filter_page = _page(comp, "Filter")
    # The filter's own parameters live here, not in a stream, because ONE filter
    # setting applies to all three - which is the whole reason this COMP exists.
    # `td_add_filter.py` builds a group per stream and every one of them reads these.
    par_smooth = filter_page.appendToggle("Smoothing", label="Smoothing")[0]
    par_smooth.default = True
    par_mincut = filter_page.appendFloat("Mincutoff", label="Min Cutoff (Hz)")[0]
    par_beta = filter_page.appendFloat("Beta", label="Beta (speed coefficient)")[0]
    # GUESSES, and labelled as such: what should set them is per-joint jitter, which
    # is unmeasured (docs/BUILD_PLAN.md). 1.5 Hz is a visible smoothing at rest and
    # 2.0 opens the cutoff enough to keep a fast gesture crisp.
    par_mincut.default, par_beta.default = 1.5, 2.0
    for name, parameter in (("Smoothing", par_smooth), ("Mincutoff", par_mincut),
                            ("Beta", par_beta)):
        if name not in previous:
            parameter.val = parameter.default

    # Read the render's real resolution and the camera's real ortho width when they
    # are there to read, so the common case needs no tuning at all.
    render = parent.op("render1")
    if render is not None:
        par_rw.val = int(render.par.resolutionw.eval())
        par_rh.val = int(render.par.resolutionh.eval())
        print("   (took render %dx%d from %s)"
              % (par_rw.eval(), par_rh.eval(), render.path))
    camera = parent.op("cam1")
    if camera is not None and camera.par.projection.eval() == "ortho":
        par_ortho.val = float(camera.par.orthowidth.eval())
        print("   (took Orthowidth %.3f from %s)" % (par_ortho.eval(), camera.path))

    # Anything the user had tuned wins, except where the render and camera just gave
    # a better answer.
    for name, value in previous.items():
        if not hasattr(comp.par, name):
            continue                    # a parameter a later builder owns
        if name in ("Orthowidth", "Renderw", "Renderh") and (
                render is not None or camera is not None):
            continue
        getattr(comp.par, name).val = value

    print("2. parameters: source %dx%d, render %dx%d, Orthowidth=%.3f, "
          "Smoothing=%s" % (par_w.eval(), par_h.eval(), par_rw.eval(),
                            par_rh.eval(), par_ortho.eval(),
                            bool(par_smooth.eval())))

    # -- the three streams -------------------------------------------------
    outputs = []
    for index, stream in enumerate(STREAM_NAMES):
        row = -400 * index
        osc = comp.op(stream + "_osc")
        if osc is None:
            osc = comp.create(td.oscinCHOP, stream + "_osc")
        osc.nodeX, osc.nodeY = -900, row
        osc.par.port = port_for(stream, OSC_PORT)
        osc.par.active = True

        child = comp.op(stream)
        if child is None:
            child = comp.create(td.baseCOMP, stream)
            # Only a fresh child gets its shell built here. An existing one already
            # holds the networks the other six builders own, and rebuilding its
            # insides would silently discard them.
            _shell(td, child)
        child.nodeX, child.nodeY = -600, row
        child.color = (0.35, 0.45, 0.55)
        child.inputConnectors[0].connect(osc)

        out = comp.op("out%d" % (index + 1))
        if out is None:
            out = comp.create(td.outCHOP, "out%d" % (index + 1))
        out.nodeX, out.nodeY = -300, row
        # `outputConnectors[0]`, not the COMP: connect() takes an operator only
        # where it has one unambiguous output, which a base COMP does not.
        out.inputConnectors[0].connect(child.outputConnectors[0])
        outputs.append((stream, osc, child, out))
        print("3.%d %-5s port %d -> %s -> out%d"
              % (index + 1, stream, osc.par.port.eval(), child.name, index + 1))

    # The sidecar's own status channels, split out for the panel. They arrive on the
    # HANDS port (DESIGN.md 6.4) and are left in that stream as well - this is a
    # second READ of them, not a partition of the data path, which is the mistake
    # that once ate them silently.
    status = comp.create(td.selectCHOP, "status")
    status.nodeX, status.nodeY = -600, 250
    status.inputConnectors[0].connect(comp.op("hands_osc"))
    status.par.channames = STATUS_PREFIX + "*"

    # -- sidecar lifecycle -------------------------------------------------
    control = comp.create(td.textDAT, "sidecar_control")
    control.nodeX, control.nodeY = -900, 400
    control.text = SIDECAR_CONTROL_SOURCE % {
        "python": SIDECAR_PYTHON, "repo": REPO_ROOT, "port": OSC_PORT,
        "comp": comp.path}

    callbacks = comp.create(td.parameterexecuteDAT, "sidecar_callbacks")
    callbacks.nodeX, callbacks.nodeY = -650, 400
    callbacks.text = SIDECAR_CALLBACK_SOURCE
    callbacks.par.op = comp.path
    callbacks.par.pars = "Startsidecar Stopsidecar Sidecarstatus"
    callbacks.par.active = True
    callbacks.par.onpulse = True
    callbacks.par.custom = True

    on_exit = comp.create(td.executeDAT, "sidecar_exit")
    on_exit.nodeX, on_exit.nodeY = -400, 400
    on_exit.text = SIDECAR_EXIT_SOURCE
    on_exit.par.active = True
    on_exit.par.exit = True

    # -- retire what this replaces ----------------------------------------
    # Last, and only now: everything above has to have worked first, or a
    # half-finished run would leave the old structure destroyed and the new one
    # incomplete. The OSC In CHOPs matter most - two of them on one port is a
    # stream arriving in a CHOP nobody is reading.
    retired, rewired = [], []
    for name in SUPERSEDED:
        old = parent.op(name)
        if old is None:
            continue
        # Anything wired to the old COMP is repointed at this one's matching
        # output, so a project does not silently lose its input.
        target = {"visionhands": 0, "visionpose": 1, "visionface": 2}.get(name)
        if target is not None:
            for sibling in parent.children:
                if sibling is comp:
                    continue
                for conn in sibling.inputConnectors:
                    if any(x.owner is old for x in conn.connections):
                        conn.connect(comp.outputConnectors[target])
                        rewired.append("%s <- out%d" % (sibling.name, target + 1))
        old.destroy()
        retired.append(name)
    if retired:
        print("4. retired %s" % ", ".join(retired))
    if rewired:
        print("   rewired %s" % ", ".join(rewired))

    # -- report ------------------------------------------------------------
    comp.cook(force=True)
    print()
    print("5. %d operators in %s" % (len(comp.children), comp.path))
    for stream, osc, child, out in outputs:
        print("   %-5s osc %3d chans -> %s out %3d chans"
              % (stream, osc.numChans, child.name, out.numChans))
        if osc.numChans == 0:
            print("         (zero until something SENDS on port %d - the OSC In "
                  "CHOP creates" % osc.par.port.eval())
            print("          channels as they arrive, so an idle port looks "
                  "exactly like this)")
    print()
    print("   NEXT, in order: td_add_filter.py, td_add_coords.py,")
    print("   td_add_derive.py, td_add_temporal.py, td_add_latches.py,")
    print("   td_add_groups.py")
    print()
    print("   Reference a fingertip as:  op('%s/hands')['h0_index_tip_tx']"
          % comp.path)
    print("   Outputs, in order: out1 hands, out2 pose, out3 face.")
    print("=" * 70)


def _page(comp, name):
    """Find or create a custom page. TRAP: `appendCustomPage` with an existing name
    creates a SECOND page of that name, and the duplicate holds different
    parameters (DESIGN.md 2.11)."""
    for existing in comp.customPages:
        if existing.name == name:
            return existing
    return comp.appendCustomPage(name)


def _shell(td, child):
    """The empty stream network: in1 -> merge_out -> out1.

    One Merge with one input today, so every group builder attaches itself to it
    rather than restructuring anything - the discipline that survived contact is
    `_attach_once`, and it needs a Merge to attach to.
    """
    for existing in list(child.children):
        existing.destroy()
    chop_in = child.create(td.inCHOP, "in1")
    chop_in.nodeX, chop_in.nodeY = -600, 0
    merge = child.create(td.mergeCHOP, "merge_out")
    merge.nodeX, merge.nodeY = 450, 0
    merge.inputConnectors[0].connect(chop_in)
    chop_out = child.create(td.outCHOP, "out1")
    chop_out.nodeX, chop_out.nodeY = 650, 0
    chop_out.inputConnectors[0].connect(merge)


main()
