#!/usr/bin/env python
"""Build `/project1/vision`: one COMP holding all three streams and every control.

    HOW TO USE
      Paste into a Text DAT in TouchDesigner, right-click > "Run Script".
      Then, in order:
        td_add_filter.py    the one-euro filter, in EVERY stream
        td_add_derive.py    the stateless hand attributes
        td_add_temporal.py  presence, liveness, velocity  (hands)
        td_add_latches.py   the proximity latches         (hands)
        td_add_coords.py    the world and pixel spaces, in EVERY stream. AFTER
                            derive and temporal, because it reads them
        td_add_screenspace.py  the Screen Space Only filter on each output
        td_add_groups.py    the Attributes page and the cook gating
      Idempotent: run any of them as often as you like.

    WHAT IT PRODUCES

        /project1/vision            every user parameter, and the sidecar control
          hands_osc  port 10000  ->  hands   ->  out1
          pose_osc   port 10001  ->  pose    ->  out2
          face_osc   port 10002  ->  face    ->  out3
          status                                 the sidecar's own sc_* channels

WHY ONE COMP AROUND THE THREE, replacing the three siblings this supersedes. The
filter and the coordinate spaces were built inside the hands COMP because hands
came first, and neither is remotely hand-specific: a body's joints and a face's
bounding box want the same smoothing and the same conversion into TouchDesigner
world and pixel space. Three copies of the Filter page, three Ortho Widths to keep
in step, and three Start buttons for one process would all have been wrong. So the
parameters live here, once, and every stream reads them.

    OLD PATH                      NEW PATH
    /project1/visionhands         /project1/vision/hands
    /project1/visionpose          /project1/vision/pose
    /project1/visionface          /project1/vision/face

An operator OUTSIDE this COMP cannot wire to a nested one - a TouchDesigner
connection joins siblings - so the master exposes each stream on its own output
connector, in that order. An expression can still reach inside:
`op('/project1/vision/hands')['h0_index_tip_tx']`.

HOW A NESTED OPERATOR REACHES THESE PARAMETERS: `op.Vision.par.Orthowidth`, via the
COMP's Global OP Shortcut, which is set below and VERIFIED to resolve from a nested
network. Not `parent(2).par.X`, which is what the groups used before: the depth is
now different for a group inside a stream than for one at the top, so a relative
reference would have to be counted per operator and would break the next time
anything moved. A shortcut is depth-independent and survives a rename.

WHAT IT DELIBERATELY DOES NOT DO. No joint renaming: the sidecar sends
`h0_index_tip_x` already, because naming belongs at the single source of truth
rather than in a lookup two hops downstream. An earlier version renamed
`h0_lm08_x` with a Rename CHOP, which works and renames BY POSITION - so the
mapping silently depended on channel order decided somewhere else.

Ref: DESIGN.md 6.4 (the streams and their ports), 7 (the coordinate contract),
     docs/BUILD_PLAN.md step 8.
"""

SIDECAR_CONTROL_SOURCE = '''# Generated by tools/td_build_vision.py
#
# Runs on TouchDesigner's main thread, on a pulse or at project exit. Never
# per-frame: pgrep costs a few milliseconds, which is nothing on a button press
# and would be rude every cook.
import os
import signal
import subprocess

SIDECAR_PYTHON = %(python)r
REPO_ROOT = %(repo)r
PORT = %(port)d
MATCH = "visionhands.sidecar"


def running_pids():
    """Every sidecar process on this machine, ours or not.

    Matching on the command line rather than tracking a Popen handle is what
    makes Stop work on a sidecar started from a terminal - which is how it gets
    started while developing, and exactly when you most want to stop it from
    here.

    TWO-STAGE MATCH, and the second stage is not paranoia - it was written after
    the first version SIGTERMed the shell that was grepping for the sidecar.
    `pgrep -f` matches the pattern anywhere in a full command line, so a
    terminal running `pgrep -f visionhands.sidecar`, an editor with the file
    open, or a `tail` on its log all match. Killing those is unacceptable, so
    every candidate is confirmed with `ps` before it is signalled:

        argv[0] must be a python             (a shell or a grep is not)
        the argv must contain -m visionhands.sidecar

    A shell whose command line merely mentions the sidecar has argv[0] of sh or
    zsh and is rejected; a python running `-c` with the string in it fails the
    second test.
    """
    try:
        found = subprocess.run(["pgrep", "-f", MATCH],
                               capture_output=True, text=True, timeout=5)
    except Exception as exc:
        print("[visionhands] pgrep failed: %%r" %% (exc,))
        return []

    pids = []
    for line in found.stdout.split():
        try:
            pid = int(line)
        except ValueError:
            continue
        if pid == os.getpid():
            continue                      # never signal TouchDesigner itself
        if _is_sidecar(pid):
            pids.append(pid)
    return pids


def _is_sidecar(pid):
    """Confirm a pid really is a sidecar, not something that merely mentions it."""
    try:
        # `command=` only. NOT `comm=`, which macOS truncates to 16 characters:
        # a venv interpreter comes back as "/Users/omer/.ven", whose basename is
        # ".ven", and the check silently matches nothing. That cost a debugging
        # round trip and would have been invisible - Stop would simply never
        # find anything.
        proc = subprocess.run(["ps", "-p", str(pid), "-o", "command="],
                              capture_output=True, text=True, timeout=5)
    except Exception:
        return False
    line = proc.stdout.strip()
    if not line:
        return False                      # already gone
    tokens = line.split()
    if not tokens or "python" not in os.path.basename(tokens[0]):
        return False
    # `-m` and the module name must be ADJACENT ARGUMENTS, not a substring of
    # the command line. A python running `-c "x='-m visionhands.sidecar'"`
    # contains the text but is not a sidecar, and signalling it would be exactly
    # the class of mistake that killed a shell a moment ago.
    for index, token in enumerate(tokens[:-1]):
        if token == "-m" and tokens[index + 1] == MATCH:
            return True
    return False


def start():
    """Start a sidecar, after stopping any that already exist.

    Stop-first for the same reason engine.start() does it: two processes holding
    one camera is the failure DESIGN.md 8 names, and it is easy to reach by
    pressing a button twice.
    """
    stop()
    # The toggle reaches the sidecar as a LAUNCH FLAG, read once at startup.
    # That is the whole mechanism, and it is why the toggle says "restart to
    # apply": the sidecar is a separate process and there is no control channel
    # into it. Adding one to change a hand partition would be a great deal of
    # machinery for something nobody changes mid-session. The same pattern is
    # settled for the future stream toggles - docs/BUILD_PLAN.md step 5.
    comp = op(%(comp)r)
    assign = comp is None or bool(comp.par.Slotassign.eval())
    # The camera as a NAME SUBSTRING, straight through to `--camera`. Blank means
    # "whatever the engine defaults to", so clearing the field is not an error.
    camera = "" if comp is None else str(comp.par.Camera.eval()).strip()
    # The base port. Read from the COMP rather than baked in, so the OSC In CHOPs -
    # which bind it through an expression on the same parameter - and the process we
    # start cannot disagree about where the data goes.
    port = PORT if comp is None else int(comp.par.Oscport.eval())
    # Which Vision requests the process will run. Each toggle is one name on the
    # command line; the sidecar validates the list and refuses an empty one.
    # A stream that is OFF still has all of its channels in TouchDesigner, as
    # zeros - what the toggle saves is the inference (DESIGN.md 6.4).
    streams = []
    for name, par_name in (("hands", "Streamhands"), ("pose", "Streampose"),
                           ("face", "Streamface")):
        if comp is None or bool(getattr(comp.par, par_name).eval()):
            streams.append(name)
    if not streams:
        # Checked here rather than left to the sidecar, so the message lands in
        # the Textport next to the button that was pressed. A sidecar with no
        # streams opens the camera and looks exactly like a working one with
        # nobody in frame.
        print("[visionhands] NOT STARTING: every stream toggle is off, so the "
              "sidecar would open the camera and run no inference at all.")
        return 0

    argv = [SIDECAR_PYTHON, "-m", "visionhands.sidecar",
            "--port", str(port), "--parent-pid", str(os.getpid()),
            "--slots", "chirality" if assign else "off",
            "--streams", ",".join(streams)]
    if camera:
        argv += ["--camera", camera]
    process = subprocess.Popen(
        argv, cwd=REPO_ROOT,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("[visionhands] capture started, pid %%d, camera=%%s, slots=%%s, "
          "streams=%%s"
          %% (process.pid, camera or "(default)",
              "chirality (h0=right, h1=left)" if assign else "off",
              ",".join(streams)))
    # The ports each stream lands on, printed because "which port is pose on" is
    # the first question when the pose COMP shows no channels.
    print("[visionhands]   hands -> %%d   pose -> %%d   face -> %%d  (base + 0/1/2)"
          %% (port, port + 1, port + 2))
    return process.pid


def stop():
    """Stop every running sidecar. Returns how many were stopped.

    SIGTERM, not SIGKILL: the sidecar handles SIGTERM by stopping its capture
    session properly, and killing it outright would leave the camera to be
    reclaimed by the OS rather than released (DESIGN.md 8).
    """
    pids = running_pids()
    for pid in pids:
        try:
            os.kill(pid, signal.SIGTERM)
            print("[visionhands] stopped sidecar pid %%d" %% pid)
        except ProcessLookupError:
            pass
        except PermissionError:
            print("[visionhands] cannot signal pid %%d - not ours" %% pid)
    return len(pids)


def list_cameras():
    """Print the capture devices, by asking the sidecar module rather than importing.

    `python -m visionhands.sidecar --list-cameras` enumerates and exits. Two reasons
    it is a subprocess and not an import: pyobjc must never be imported inside
    TouchDesigner (that separation is the whole point of the sidecar), and the list
    then comes from the same code that `--camera` matches against, so the names in
    front of you are exactly the names the flag will accept.

    Enumeration opens no device and starts no session, so this takes the camera from
    nothing and raises no permission prompt.
    """
    try:
        found = subprocess.run(
            [SIDECAR_PYTHON, "-m", "visionhands.sidecar", "--list-cameras"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=20)
    except Exception as exc:
        print("[visionhands] could not list cameras: %%r" %% (exc,))
        return []
    if found.returncode != 0:
        print("[visionhands] --list-cameras exited %%d: %%s"
              %% (found.returncode, found.stderr.strip()[:400]))
        return []
    names = []
    print("[visionhands] capture devices - put any part of a name in `Camera`:")
    for line in found.stdout.splitlines():
        name = line.split("\t")[0].strip()
        if not name:
            continue
        names.append(name)
        print("[visionhands]    %%s" %% line.replace("\t", "   "))
    return names


def status():
    pids = running_pids()
    return "capture: %%s" %% (("running, pid %%s" %% pids) if pids else "not running")
'''

# The Parameter Execute DAT that turns a button press into a call.
SIDECAR_CALLBACK_SOURCE = '''# Generated by tools/td_build_vision.py
#
# `Active` is a TOGGLE now, not a Start pulse and a Stop pulse. The work still lives
# in sidecar_control so it can be called directly:
#     op('/project1/vision/sidecar_control').module.status()
#
# WHAT A TOGGLE CANNOT DO, stated here because the label can only hint at it: this
# is a COMMAND, not a reading. The process can die without telling anyone - a camera
# unplugged, a crash, a kill from a terminal - and `Active` would still read on.
# `sc_uptime_s` is the truth, because it arrives FROM the process; `Capturepid` is
# only what we last started. Reconciling the toggle would mean running pgrep on a
# timer, and pgrep costs milliseconds - fine on a button press, rude every frame.


def onValueChange(par, prev):
    control = op("sidecar_control").module
    if par.name != "Active":
        return
    if par.eval():
        # `start()` stops any existing process first, so pressing this twice cannot
        # leave two processes holding one camera (DESIGN.md 8).
        par.owner.par.Capturepid = control.start()
    else:
        stopped = control.stop()
        par.owner.par.Capturepid = 0
        print("[visionhands] stopped %d process(es)" % stopped)


def onPulse(par):
    control = op("sidecar_control").module
    if par.name == "Printstatus":
        print("[visionhands] " + control.status())
    elif par.name == "Listcameras":
        control.list_cameras()
'''

# Stops the sidecar when the project closes. Belt and braces with the sidecar's
# own parent-pid watch: this handles a clean quit, that handles a crash.
SIDECAR_EXIT_SOURCE = '''# Generated by tools/td_build_vision.py


def onExit():
    op("sidecar_control").module.stop()
'''

MASTER_NOTES = """VISION - one COMP around the three streams, and every control.

%(ports)s
  status                            the sidecar's own sc_* channels

WHY ONE COMP. The filter and the coordinate spaces were built inside the hands COMP
because hands came first, and neither is hand-specific: a body's joints and a face's
bounding box want the same smoothing and the same conversion into TouchDesigner
world and pixel space. Three copies of the Filter page, three Ortho Widths to keep
in step and three Start buttons for one process would all have been wrong. So the
parameters live HERE, once, and every stream reads them.

HOW A NESTED OPERATOR REACHES THEM: op.Vision.par.Orthowidth, through this COMP's
Global OP Shortcut, which is set by the builder BEFORE anything that writes such an
expression. Not parent(2).par.X - a group is two levels down now and a relative
reference would have to be counted per operator.

AN OPERATOR OUTSIDE CANNOT WIRE TO A NESTED ONE, so each stream is exposed on its
own output connector, in the order above. An expression can still reach inside:
op('/project1/vision/hands')['h0_index_tip_tx'].

THE SIX PAGES
  Vision     resolutions, Orthowidth, Screenspaceonly
  Sidecar    Start/Stop, slot assignment, the three stream toggles
  Filter     Smoothing, Mincutoff, Beta        - one filter setting for all three
  Advanced   debounce frames, velocity filter, speed floor
  Tuning     the fifteen latch threshold pairs
  Attributes the group toggles and the Verbosity presets

THE STREAM TOGGLES DO TWO THINGS. They are LAUNCH FLAGS for the sidecar, read once
when the process starts - hence "restart to apply" - and they also drive
`allowCooking` on the stream's child COMP, which takes effect at once. A disabled
stream keeps every channel it has, reading zero, because a channel that VANISHES
breaks its consumers with no error anywhere (DESIGN.md 6.2).

Built by tools/td_build_vision.py, then six more builders in the order its
docstring lists. Every one is idempotent. Edits here are overwritten.
"""

PARENT_PATH = "/project1"
COMP_NAME = "vision"
# The Global OP Shortcut every nested expression uses. Capitalised because that is
# how `op.Vision` reads at a call site, and it must not collide with anything else
# in the project - TD shortcuts are global.
OP_SHORTCUT = "Vision"
# How a nested operator reaches a parameter on this COMP. Same form every builder
# uses, and it is depth-independent - see the module docstring.
MASTER_PAR = "op.%s.par.%%s" % OP_SHORTCUT

# One child COMP and one OSC In CHOP per stream, in the order their outputs are
# exposed. The ports come from the package, so the receiver cannot end up listening
# where the sender is not sending (DESIGN.md 6.4).
STREAM_NAMES = ("hands", "pose", "face")

OSC_PORT = 10000
REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
SIDECAR_PYTHON = "/Users/omer/.venvs/visionhands/bin/python"

# Which camera, as a substring of the device name. Matches
# `visionhands.engine.DEFAULT_CAMERA_NAME`, and the substring form is deliberate:
# MEASURED on this machine, `--list-cameras` returns four devices - the built-in
# camera plus an OBS virtual camera, a Camo camera and an iPhone - so "the first
# device" would be the wrong answer more often than not, and a device INDEX would
# change meaning whenever something was plugged in.
DEFAULT_CAMERA = "MacBook"

# The page reorganisation of 2026-08-21. The Sidecar page named an implementation
# detail - a consumer of this COMP does not care that a separate process holds the
# camera - so what was operational moved to Vision and what was diagnostic moved to
# Advanced. These two lists are what has to be DESTROYED to finish the move, because
# TouchDesigner will not hold one custom parameter name on two pages and `append*`
# does not remove anything.
#
# Two lists, because the two cases deserve to be told apart by a reader even though
# `_retire` treats them identically.
#
# GONE for good. Nothing here had a value worth keeping: `Active` replaces the two
# pulses, `Printstatus` and `Capturepid` replace the last two under names that do not
# say "sidecar".
RETIRED_PARS = ("Startsidecar", "Stopsidecar", "Sidecarstatus", "Sidecarpid")
# MOVED. Same names, different page - so they are destroyed here and appended to
# Vision below, and `previous` (captured before any of this) puts the tuned value
# back. They have to be destroyed FIRST: TouchDesigner will not hold one custom
# parameter name on two pages, so the append would fail while the old one exists.
MOVED_PARS = ("Slotassign", "Streamhands", "Streampose", "Streamface")
RETIRED_PAGES = ("Sidecar",)

# The order the Vision page reads in: is it running, what is it looking at, what is
# it computing, what geometry, what comes out, and one build-time preference. Set
# with `Page.sort`, which reorders without destroying - and destroying a page
# destroys its parameters and every tuned value with them.
VISION_PAGE_ORDER = (
    "Active", "Camera", "Listcameras",
    "Streamhands", "Streampose", "Streamface", "Slotassign",
    "Resw", "Resh", "Renderw", "Renderh", "Orthowidth",
    "Screenspaceonly", "Keeplayout",
)

# Defaults for the aspect and pixel conversions. MEASURED: the sidecar requests and
# receives 1280x720 (DESIGN.md 2.6), and Vision is fastest there.
#
# These are COMP parameters rather than baked-in numbers so a different camera does
# not need a rebuild, and they are read from the project's own render and camera
# when those exist. They are NOT read from the incoming channels: the wire contract
# deliberately does not carry width and height, and adding it would be a contract
# change to solve what a parameter already solves.
DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 720

# TouchDesigner's Camera COMP defaults to an Ortho Width of 1.0, so the visible
# world space is x in [-0.5, +0.5] and y in [-0.5/aspect, +0.5/aspect]. Matching
# that default means the common case needs no tuning at all.
DEFAULT_ORTHO_WIDTH = 1.0

# What the three COMPs this replaces were called. Destroyed at the end, once the new
# structure has been built and verified - so a half-finished run leaves the old one
# working rather than nothing working.
SUPERSEDED = ("visionhands", "visionpose", "visionface",
              "visionhands_osc", "visionpose_osc", "visionface_osc")


def main():
    import td

    print("=" * 70)
    print("vision: building the master COMP and its three streams")
    print("=" * 70)

    import sys
    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)
    # TouchDesigner caches our modules for the life of the process (DESIGN.md 2.11).
    for stale in [n for n in list(sys.modules)
                  if n == "visionhands" or n.startswith("visionhands.")]:
        del sys.modules[stale]
    # `td_layout` is every coordinate a MASTER-level operator gets. One table,
    # because seven builders place operators in here and two of them once chose the
    # same spot with nothing able to notice.
    from visionhands.streams import STATUS_PREFIX, port_for
    from visionhands.td_layout import COL_W, master_xy, stream_row

    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s" % PARENT_PATH)
        return

    comp = parent.op(COMP_NAME)
    existed = comp is not None
    previous = {}
    if existed:
        # Remember what the user tuned, so a rebuild restores it rather than
        # resetting it. Every custom parameter, not a hand-maintained list: the
        # pages are built by six different scripts now and a list here would go
        # stale silently.
        previous = {par.name: par.eval() for par in comp.customPars}
    else:
        # First run: inherit whatever the COMP this supersedes was tuned to, so the
        # restructure does not quietly reset somebody's Ortho Width.
        old = parent.op("visionhands")
        if old is not None:
            previous = {par.name: par.eval() for par in old.customPars}
            print("0. inheriting %d tuned parameters from %s"
                  % (len(previous), old.path))
        comp = parent.create(td.baseCOMP, COMP_NAME)
    comp.nodeX, comp.nodeY = 250, 0
    comp.color = (0.25, 0.35, 0.45)
    # Everything inside is rebuilt by this script and the six that follow it, so
    # clearing is what keeps them all idempotent. Two kinds of child are spared.
    #
    # The STREAM CHILDREN, because destroying those would throw away the networks
    # the other builders own, and they clear their own contents when they run
    # (DESIGN.md 2.11 - destroying a group orphans its consumers).
    #
    # The OSC IN CHOPS, which is a fix rather than an optimisation: an OSC In CHOP
    # only has the channels that have ARRIVED, so a fresh one starts empty and
    # regains only what is being sent right now. MEASURED: rebuilding took the hands
    # port from 141 channels to 137, because the four `sc_*` status channels come
    # from the sidecar and no sidecar was running - and 137 is a plausible number
    # that nothing complains about. Reusing the CHOP keeps whatever it has learned,
    # and re-binding a port it already holds is not something to do for no reason.
    #
    # And THE OUT CHOPS, which is the same fix as `_clear_keeping_ports` in every
    # group builder, applied one level up where it had been missed. An Out CHOP IS
    # the COMP's output connector: destroying it disconnects whatever the PROJECT
    # had wired to that output, and recreating it does not bring the wire back.
    #
    # MEASURED, on this project, by running this builder: three operators reading
    # `vision` output 1 were silently orphaned - `select3`, `select4` and `select5`,
    # feeding a live chain - and the only symptom was that the hands stream stopped
    # cooking, because nothing was pulling it any more. `temporal` and `latches` kept
    # cooking off their own clocks, so the COMP still looked busy. Nothing errored.
    # This is precisely the failure DESIGN.md 2.11 records for group builders; the
    # master had the same hole.
    kept = (set(STREAM_NAMES) | {name + "_osc" for name in STREAM_NAMES}
            | {"out%d" % (index + 1) for index in range(len(STREAM_NAMES))})
    for child in list(comp.children):
        if child.name not in kept:
            child.destroy()
    print("1. %s %s" % ("reusing" if existed else "created", comp.path))

    # The Global OP Shortcut, and it is load-bearing rather than convenience: every
    # expression in every nested group reads `op.Vision.par.X`. Set BEFORE anything
    # that writes such an expression, or the first cook reports a name error.
    comp.par.opshortcut = OP_SHORTCUT

    # -- retire what the page reorganisation replaces ----------------------
    # BEFORE anything is appended, because four of these names are being re-created
    # on a different page and TouchDesigner will not hold the same custom parameter
    # name twice. `previous` was captured above, so a tuned value survives the move.
    #
    # WHY the Sidecar page is gone: it named an implementation detail. A consumer of
    # this COMP does not care that a separate process holds the camera, and the page
    # made them read about it before they could pick a stream. What was on it is
    # operational - which camera, which streams, is it running - so it belongs on
    # Vision beside the resolutions, and the two genuinely diagnostic parameters
    # (the status pulse and the process id) belong on Advanced with the other
    # internals.
    retired_pars = _retire(comp, RETIRED_PARS + MOVED_PARS, RETIRED_PAGES)

    # -- the shared parameters --------------------------------------------
    page = _page(comp, "Vision")

    # Is the capture process running. ONE toggle, replacing a Start pulse and a Stop
    # pulse, because a pulse pair cannot show state and this is state.
    #
    # THE HONEST CAVEAT, and it is on the label: a toggle implies the truth and this
    # one is only a COMMAND. The process can die on its own - a camera unplugged, a
    # crash, someone killing it from a terminal - and the toggle would still read on.
    # `sc_uptime_s` on the status channels is the truth, because it comes FROM the
    # process; `Capturepid` on Advanced is what we last started.
    par_active = page.appendToggle("Active", label="Active")[0]
    par_active.default = False

    # Which camera, as a SUBSTRING of the device name - which is what the sidecar's
    # `--camera` has always taken, so this parameter and the flag cannot disagree.
    #
    # A string and not a MENU, deliberately. A menu would have to be populated at
    # build time, and this machine has an OBS virtual camera, a Camo camera and an
    # iPhone alongside the built-in one: a baked list goes wrong the moment a device
    # is unplugged, and a menu whose entries no longer exist is worse than a field
    # that simply does not match. `Listcameras` prints what is actually there.
    par_camera = page.appendStr("Camera", label="Camera (name contains)")[0]
    par_camera.default = DEFAULT_CAMERA
    page.appendPulse("Listcameras", label="List Cameras")

    # Slot assignment: h0 = the right hand, h1 = the left, whichever order Vision
    # reports them in (visionhands/slots.py). NOTE the consequence: with this on, a
    # single LEFT hand puts nothing in h0, so every h0_* channel reads zero.
    par_slots = page.appendToggle(
        "Slotassign", label="Assign Slots (restart to apply)")[0]
    par_slots.default = True

    # Which Vision requests the sidecar runs. LAUNCH FLAGS, read once when the
    # process starts (DESIGN.md 6.4) - hence "restart to apply". What they save is
    # INFERENCE, not channels: a disabled stream keeps every channel it has, reading
    # zero, because a channel that vanishes breaks its consumers silently
    # (DESIGN.md 6.2).
    #
    # TWO effects since 2026-08-21, and the label says so. The flag reaches the
    # sidecar only on a restart, but `tools/td_add_groups.py` also binds
    # `allowCooking` on the stream's child COMP to this toggle, and THAT takes effect
    # at once. So turning a stream off stops its network processing the zeros the
    # sidecar still sends - which is the saving - and turning one on unfreezes the
    # network immediately while the inference waits for a restart.
    stream_pars = {}
    for stream, label, default in (("hands", "Hands", True),
                                   ("pose", "Body Pose", False),
                                   ("face", "Face", False)):
        par = stream_pars.setdefault(stream, page.appendToggle(
            "Stream" + stream,
            label="%s (off freezes it; restart to apply)" % label)[0])
        par.default = default

    par_w = page.appendInt("Resw", label="Source Width")[0]
    par_h = page.appendInt("Resh", label="Source Height")[0]
    # `.default` always, `.val` only when the parameter is NEW. TD's append* reset
    # a parameter's attributes on rebuild, and a newly appended one reads 0 whatever
    # its default says - both measured, both in DESIGN.md 2.11. `previous` is the
    # record of what existed, so it answers the only question that matters here.
    par_w.default, par_h.default = DEFAULT_WIDTH, DEFAULT_HEIGHT
    par_rw = page.appendInt("Renderw", label="Render Width")[0]
    par_rh = page.appendInt("Renderh", label="Render Height")[0]
    par_rw.default, par_rh.default = DEFAULT_WIDTH, DEFAULT_HEIGHT
    par_ortho = page.appendFloat("Orthowidth", label="Camera Ortho Width")[0]
    par_ortho.default = DEFAULT_ORTHO_WIDTH

    # The output shaping: what LEAVES the COMP, as opposed to what it computes.
    par_screen = page.appendToggle(
        "Screenspaceonly", label="Screen Space Only (drop raw normalised)")[0]
    # OFF. The raw normalised channels are what every existing project reads, and a
    # toggle that ships ON would delete them out from under one.
    par_screen.default = False

    # Whether the builders may move nodes. `visionhands.td_layout.placement` has the
    # rule and what it cannot protect - the short version is that it holds the group
    # COMPs, the stream shell and the OSC In CHOPs, and cannot hold operators INSIDE
    # a group, because those are destroyed and regenerated on every run.
    par_keep = page.appendToggle(
        "Keeplayout", label="Keep Layout (builders leave existing nodes)")[0]
    par_keep.default = False

    # The page reads in the order a user meets it: is it running, what is it
    # looking at, what is it computing, what geometry, what comes out. `sort` rather
    # than destroy-and-rebuild, because destroying a page destroys its parameters
    # and every tuned value with them.
    page.sort(*VISION_PAGE_ORDER)

    # -- Advanced: the internals, including two that moved off Sidecar ------
    # SHARED PAGE, and this is the one place in the repo where two builders write to
    # one: `tools/td_add_temporal.py` owns the debounce and velocity parameters here.
    # That is safe only because each appends its OWN names and each restores its own
    # stored values - the hazard the comment in td_add_filter.py warns about is two
    # scripts appending the SAME parameter, where whichever runs second resets it.
    advanced = _page(comp, "Advanced")

    # The OSC base port. The three streams take base + 0/1/2 (DESIGN.md 6.4), and
    # the OSC In CHOPs bind it through an EXPRESSION, so changing this rebinds them
    # at once while the sidecar keeps sending to the old one until it is restarted.
    # The visible symptom of that gap is `sc_uptime_s` freezing, which is the same
    # signal as a dead sidecar - so the label says restart.
    par_port = advanced.appendInt("Oscport", label="OSC Base Port (restart to apply)")[0]
    par_port.default = OSC_PORT

    advanced.appendPulse("Printstatus", label="Print Status")
    par_pid = advanced.appendInt("Capturepid", label="Capture Process PID")[0]
    par_pid.readOnly = True

    filter_page = _page(comp, "Filter")
    # The filter's own parameters live here, not in a stream, because ONE filter
    # setting applies to all three - which is the whole reason this COMP exists.
    # `td_add_filter.py` builds a group per stream and every one of them reads these.
    par_smooth = filter_page.appendToggle("Smoothing", label="Smoothing")[0]
    par_smooth.default = True
    par_mincut = filter_page.appendFloat("Mincutoff", label="Min Cutoff (Hz)")[0]
    par_beta = filter_page.appendFloat("Beta", label="Beta (speed coefficient)")[0]
    # GUESSES, and labelled as such: what should set them is per-joint jitter, which
    # is unmeasured (docs/BUILD_PLAN.md). 1.5 Hz is a visible smoothing at rest and
    # 2.0 opens the cutoff enough to keep a fast gesture crisp.
    par_mincut.default, par_beta.default = 1.5, 2.0

    # One pass for every parameter this script owns: `.val` from `.default` only
    # where the parameter is NEW. A newly appended parameter reads 0 whatever its
    # default says (DESIGN.md 2.11), and `previous` is the record of what existed.
    owned = [("Active", par_active), ("Camera", par_camera),
             ("Slotassign", par_slots), ("Resw", par_w), ("Resh", par_h),
             ("Renderw", par_rw), ("Renderh", par_rh),
             ("Orthowidth", par_ortho), ("Screenspaceonly", par_screen),
             ("Keeplayout", par_keep), ("Oscport", par_port),
             ("Smoothing", par_smooth), ("Mincutoff", par_mincut),
             ("Beta", par_beta)]
    owned += [("Stream" + name, par) for name, par in stream_pars.items()]
    for name, parameter in owned:
        if name not in previous:
            parameter.val = parameter.default

    # Read the render's real resolution and the camera's real ortho width when they
    # are there to read, so the common case needs no tuning at all.
    render = parent.op("render1")
    if render is not None:
        par_rw.val = int(render.par.resolutionw.eval())
        par_rh.val = int(render.par.resolutionh.eval())
        print("   (took render %dx%d from %s)"
              % (par_rw.eval(), par_rh.eval(), render.path))
    camera = parent.op("cam1")
    if camera is not None and camera.par.projection.eval() == "ortho":
        par_ortho.val = float(camera.par.orthowidth.eval())
        print("   (took Orthowidth %.3f from %s)" % (par_ortho.eval(), camera.path))

    # Anything the user had tuned wins, except where the render and camera just gave
    # a better answer.
    for name, value in previous.items():
        if not hasattr(comp.par, name):
            continue                    # a parameter a later builder owns
        if name in ("Orthowidth", "Renderw", "Renderh") and (
                render is not None or camera is not None):
            continue
        getattr(comp.par, name).val = value

    if retired_pars:
        # Reported because it is destructive and idempotent: the FIRST run after the
        # page reorganisation removes these, and every run after it finds nothing.
        print("2. retired %s" % ", ".join(retired_pars))
    print("   pages: %s" % ", ".join(p.name for p in comp.customPages))
    print("   Active=%s, Camera=%r, OSC base port %d, source %dx%d, render %dx%d, "
          "Orthowidth=%.3f, Smoothing=%s"
          % (bool(par_active.eval()), par_camera.eval(), par_port.eval(),
             par_w.eval(), par_h.eval(), par_rw.eval(), par_rh.eval(),
             par_ortho.eval(), bool(par_smooth.eval())))

    # -- the three streams -------------------------------------------------
    # Read once. Everything below that PERSISTS across a rebuild honours it; the
    # loose DATs at the top level do not, because this script destroys and recreates
    # them every run and there is nothing to preserve.
    keep_layout = bool(par_keep.eval())
    outputs = []
    for index, stream in enumerate(STREAM_NAMES):
        row = stream_row(index)
        osc = comp.op(stream + "_osc")
        osc_existed = osc is not None
        if osc is None:
            osc = comp.create(td.oscinCHOP, stream + "_osc")
        _at(osc, (-4 * COL_W, row), keep_layout, osc_existed)
        # An EXPRESSION on `Oscport`, not a baked number: the port is a parameter
        # now, and the receiver has to follow it the moment it changes. The offset
        # comes from the package (DESIGN.md 6.4), so the receiver cannot end up
        # listening where the sender is not sending.
        osc.par.port.expr = "%s + %d" % (MASTER_PAR % "Oscport",
                                         port_for(stream, 0))
        osc.par.active = True

        child = comp.op(stream)
        child_existed = child is not None
        if child is None:
            child = comp.create(td.baseCOMP, stream)
            # Only a fresh child gets its shell BUILT here. An existing one already
            # holds the networks the other six builders own, and rebuilding its
            # insides would silently discard them.
            _shell(td, child)
        # But the shell's POSITIONS are re-applied every run, on a fresh child and
        # an existing one alike. Otherwise a layout change reaches new projects only
        # - which is how the master and the streams ended up laid out to two
        # different conventions at once.
        _place_shell(td, child, stream, keep_layout)
        _at(child, (-2 * COL_W, row), keep_layout, child_existed)
        child.color = (0.35, 0.45, 0.55)
        child.inputConnectors[0].connect(osc)

        out = comp.op("out%d" % (index + 1))
        out_existed = out is not None
        if out is None:
            out = comp.create(td.outCHOP, "out%d" % (index + 1))
        _at(out, (COL_W, row), keep_layout, out_existed)
        # REUSED, never recreated - see the `kept` set above. The connector index a
        # project's wire is attached to follows these operators, so replacing one
        # moves every output the project reads.
        # `outputConnectors[0]`, not the COMP: connect() takes an operator only
        # where it has one unambiguous output, which a base COMP does not.
        out.inputConnectors[0].connect(child.outputConnectors[0])
        outputs.append((stream, osc, child, out))
        print("3.%d %-5s port %d -> %s -> out%d"
              % (index + 1, stream, osc.par.port.eval(), child.name, index + 1))

    # The sidecar's own status channels, split out for the panel. They arrive on the
    # HANDS port (DESIGN.md 6.4) and are left in that stream as well - this is a
    # second READ of them, not a partition of the data path, which is the mistake
    # that once ate them silently.
    status = comp.create(td.selectCHOP, "status")
    status.nodeX, status.nodeY = master_xy("status")
    status.inputConnectors[0].connect(comp.op("hands_osc"))
    status.par.channames = STATUS_PREFIX + "*"

    # -- sidecar lifecycle -------------------------------------------------
    control = comp.create(td.textDAT, "sidecar_control")
    control.nodeX, control.nodeY = master_xy("sidecar_control")
    control.text = SIDECAR_CONTROL_SOURCE % {
        "python": SIDECAR_PYTHON, "repo": REPO_ROOT, "port": OSC_PORT,
        "comp": comp.path}

    callbacks = comp.create(td.parameterexecuteDAT, "sidecar_callbacks")
    callbacks.nodeX, callbacks.nodeY = master_xy("sidecar_callbacks")
    callbacks.text = SIDECAR_CALLBACK_SOURCE
    callbacks.par.op = comp.path
    callbacks.par.pars = "Active Printstatus Listcameras"
    callbacks.par.active = True
    callbacks.par.onpulse = True
    callbacks.par.valuechange = True
    callbacks.par.custom = True

    on_exit = comp.create(td.executeDAT, "sidecar_exit")
    on_exit.nodeX, on_exit.nodeY = master_xy("sidecar_exit")
    on_exit.text = SIDECAR_EXIT_SOURCE
    on_exit.par.active = True
    on_exit.par.exit = True

    notes = comp.create(td.textDAT, "notes")
    notes.nodeX, notes.nodeY = master_xy("notes")
    notes.text = MASTER_NOTES % {
        "ports": "\n".join(
            "  %-5s port %-6d -> %-5s -> out%d"
            % (name, port_for(name, OSC_PORT), name, index + 1)
            for index, name in enumerate(STREAM_NAMES))}

    # -- retire what this replaces ----------------------------------------
    # Last, and only now: everything above has to have worked first, or a
    # half-finished run would leave the old structure destroyed and the new one
    # incomplete. The OSC In CHOPs matter most - two of them on one port is a
    # stream arriving in a CHOP nobody is reading.
    retired, rewired = [], []
    for name in SUPERSEDED:
        old = parent.op(name)
        if old is None:
            continue
        # Anything wired to the old COMP is repointed at this one's matching
        # output, so a project does not silently lose its input.
        target = {"visionhands": 0, "visionpose": 1, "visionface": 2}.get(name)
        if target is not None:
            for sibling in parent.children:
                if sibling is comp:
                    continue
                for conn in sibling.inputConnectors:
                    if any(x.owner is old for x in conn.connections):
                        conn.connect(comp.outputConnectors[target])
                        rewired.append("%s <- out%d" % (sibling.name, target + 1))
        old.destroy()
        retired.append(name)
    if retired:
        print("4. retired %s" % ", ".join(retired))
    if rewired:
        print("   rewired %s" % ", ".join(rewired))

    # -- report ------------------------------------------------------------
    comp.cook(force=True)
    print()
    print("5. %d operators in %s" % (len(comp.children), comp.path))
    for stream, osc, child, out in outputs:
        print("   %-5s osc %3d chans -> %s out %3d chans"
              % (stream, osc.numChans, child.name, out.numChans))
        if osc.numChans == 0:
            print("         (zero until something SENDS on port %d - the OSC In "
                  "CHOP creates" % osc.par.port.eval())
            print("          channels as they arrive, so an idle port looks "
                  "exactly like this)")
    print()
    print("   NEXT, in order: td_add_filter.py, td_add_derive.py,")
    print("   td_add_temporal.py, td_add_latches.py, td_add_coords.py,")
    print("   td_add_screenspace.py, td_add_groups.py")
    print()
    print("   Reference a fingertip as:  op('%s/hands')['h0_index_tip_tx']"
          % comp.path)
    print("   Outputs, in order: out1 hands, out2 pose, out3 face.")
    print("=" * 70)


def _at(node, xy, keep, existed):
    """Write nodeX/nodeY unless `Keeplayout` is on and the node already existed.

    The rule lives in `visionhands.td_layout.placement`, including what the flag
    cannot hold: anything a builder destroys and regenerates, which is every
    operator inside a group.
    """
    from visionhands.td_layout import placement

    where = placement(xy, keep, existed)
    if where is not None:
        node.nodeX, node.nodeY = where
    return node


def _retire(comp, par_names, page_names):
    """Destroy named custom parameters, then any of `page_names` left empty.

    Returns what it removed, for the build report.

    Why parameters are destroyed rather than moved: TouchDesigner has no "move to
    another page", so a parameter that changes page is a destroy plus an append -
    and the append CANNOT run first, because the name would exist twice. Hence this
    is called before anything is appended, with `previous` already captured so a
    tuned value survives the round trip.

    Why the page is only destroyed when EMPTY: another builder may own something on
    it. `Advanced` is shared by this script and td_add_temporal.py, and destroying a
    page takes its parameters with it - which is exactly how a tuned threshold would
    disappear without anything saying so.
    """
    gone = []
    for name in par_names:
        par = getattr(comp.par, name, None)
        if par is not None:
            par.destroy()
            gone.append(name)
    for name in page_names:
        for page in list(comp.customPages):
            if page.name != name:
                continue
            leftover = [par.name for par in page.pars]
            if leftover:
                # Reported, not forced. A page this script thinks is finished but
                # which still holds something belongs to somebody else now.
                print("   (page %r still holds %s - left in place)"
                      % (name, ", ".join(leftover)))
            else:
                page.destroy()
                gone.append("page:" + name)
    return gone


def _page(comp, name):
    """Find or create a custom page. TRAP: `appendCustomPage` with an existing name
    creates a SECOND page of that name, and the duplicate holds different
    parameters (DESIGN.md 2.11)."""
    for existing in comp.customPages:
        if existing.name == name:
            return existing
    return comp.appendCustomPage(name)


STREAM_NOTES = """%(stream)s - one vision stream, from the port to the output.

  in1 -> filter -> coords ----+
                             |
         derive_chop --------+-> merge_out -> screen_only -> out1
         temporal -----------+
         latches ------------+

Row 0 is the DATA PATH; everything below it only reads the stream. That is why
`filter` cannot be gated by allowCooking - freezing it would freeze every position
rather than bypass the filter - while `coords`, `temporal` and `latches` can be.

EACH CONSUMER STATES ITS OWN INPUT, and that is load-bearing. An earlier version
had td_add_filter.py push a named list of consumers onto its output; two of the
names had moved inside the `coords` group and `derive_chop` does not exist yet when
the filter is built, so it wired itself to the RAW input and stayed there - every
derived attribute computed on unsmoothed landmarks while the coordinate spaces used
smoothed ones. Build order cannot be depended on; a consumer naming its own source
can.

merge_out IS THE ONLY JOIN, and a Merge CHOP accepts the same operator on any
number of inputs, silently. The only symptom is the channel count - `filter` once
reached three connections and put 274 duplicate channels on the output. Every
builder attaches through `_attach_once`, which dedupes by OWNER OBJECT, because
`.inputs` reports a group COMP as its inner `out1` and a name-keyed dedup collapsed
two groups into one and dropped 168 channels.

Built by tools/td_build_vision.py and six more builders. Edits here are overwritten.
"""


def _place_shell(td, child, stream, keep):
    """Re-apply the stream shell's positions, and its notes DAT. Every run.

    Separate from `_shell` because that one only runs for a NEW stream: an existing
    child already holds the networks six other builders own, so its INSIDES must not
    be rebuilt - but its layout should still follow the current table.

    `keep` is `Keeplayout`: with it on, an operator that already existed keeps
    whatever position it has. The notes DAT's TEXT is rewritten either way - the flag
    is about arrangement, not about letting documentation go stale.
    """
    from visionhands.td_layout import placement, stream_xy

    for name in ("in1", "merge_out", "out1"):
        node = child.op(name)
        if node is None:
            continue
        where = placement(stream_xy(name), keep, True)
        if where is not None:
            node.nodeX, node.nodeY = where
    existing = child.op("notes")
    notes = existing or child.create(td.textDAT, "notes")
    where = placement(stream_xy("notes"), keep, existing is not None)
    if where is not None:
        notes.nodeX, notes.nodeY = where
    notes.text = STREAM_NOTES % {"stream": stream.upper()}


def _shell(td, child):
    """The empty stream network: in1 -> merge_out -> out1.

    One Merge with one input today, so every group builder attaches itself to it
    rather than restructuring anything - the discipline that survived contact is
    `_attach_once`, and it needs a Merge to attach to.

    `screen_only` is NOT built here: it belongs between `merge_out` and `out1` and
    `tools/td_add_screenspace.py` owns it, so it survives this builder running again
    on an existing stream - which is exactly when this function does not run at all.

    Positions come from `_place_shell`, which the caller runs afterwards on a new
    and an existing stream alike.
    """
    for existing in list(child.children):
        existing.destroy()
    chop_in = child.create(td.inCHOP, "in1")
    merge = child.create(td.mergeCHOP, "merge_out")
    merge.inputConnectors[0].connect(chop_in)
    chop_out = child.create(td.outCHOP, "out1")
    chop_out.inputConnectors[0].connect(merge)


main()
