#!/usr/bin/env python
"""A control bridge into a running TouchDesigner. Paste once, run once.

    WHAT IT IS FOR. There is no TouchDesigner MCP server, so an agent working on
    this project cannot see inside TD or drive it. Every question - "did the
    callbacks import?", "how many channels?", "what does numpyArray() cost?" -
    otherwise costs a round trip through a human copying Textport output. This
    turns all of that into something the agent can do directly.

    HOW TO INSTALL
      1. Create a Text DAT in TouchDesigner, paste this whole file in.
      2. Right-click > "Run Script". It prints a confirmation and exits.
      3. That is it. The bridge now runs itself, once per frame.

    HOW TO REMOVE
      Delete the Execute DAT it created (default name: visionhands_bridge), or
      run:  op('/project1/visionhands_bridge').destroy()

HOW IT WORKS, and why it is built this way.

TouchDesigner's Python API is only safe to touch from its main thread, and the
main thread is the one running the frame loop. So the bridge does not open a
socket and it does not start a thread - both would mean calling TD's API from
somewhere it does not expect. Instead an Execute DAT's `onFrameStart` callback,
which TD calls on its main thread once per frame, checks for a request file. If
one is there, it runs it and writes a response file.

That means: file in, file out, main thread only, no networking of any kind, and
nothing listening on any port. The cost when idle is one `os.path.exists()` per
frame - about 1 microsecond.

    PROTOCOL, for whatever is driving it
      write   /tmp/visionhands_bridge/request.py     (atomically: .tmp + rename)
      read    /tmp/visionhands_bridge/response.txt   (appears within ~1 frame)

    The request is plain Python, exec'd in a namespace with TD's builtins
    available. Whatever it prints, plus the repr of a variable named `result` if
    it sets one, comes back in the response. A traceback comes back too.

SECURITY, stated plainly: this executes arbitrary Python from a file in /tmp, so
anything that can write that file can drive TouchDesigner. It is a development
tool for a single-user machine, it touches no network, and it is one `destroy()`
away from gone. Do not leave it in a project you ship or install on a machine
you share.

Built against TouchDesigner 099 / Python 3.11.15 on macOS.
"""

import os

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BRIDGE_DIR = "/tmp/visionhands_bridge"
PARENT_PATH = "/project1"
BRIDGE_DAT_NAME = "visionhands_bridge"

# The repo, so the bridge can `import visionhands`. Appended, never inserted.
REPO_ROOT = os.path.expanduser("~/Documents/GitHub/visionhands-touchdesigner")

# The script that becomes the Execute DAT's contents. It is a separate program
# from this one: this file runs once to install it, that one runs every frame.
#
# Written as a literal rather than assembled, so that what lands in the DAT is
# exactly what is reviewable here.
BRIDGE_SOURCE = '''# visionhands bridge - generated by tools/td_bridge.py
#
# Runs on TouchDesigner's MAIN thread, once per frame, via onFrameStart. Reads a
# request file, executes it, writes a response file. No sockets, no threads.
#
# Idle cost: one os.path.exists() per frame.

import os
import sys
import traceback
from io import StringIO

BRIDGE_DIR = %(bridge_dir)r
REQUEST_PATH = os.path.join(BRIDGE_DIR, "request.py")
RESPONSE_PATH = os.path.join(BRIDGE_DIR, "response.txt")
REPO_ROOT = %(repo_root)r


def _write_response(text):
    """Write the response atomically, so a reader never sees half of one."""
    temp_path = RESPONSE_PATH + ".tmp"
    with open(temp_path, "w") as handle:
        handle.write(text)
    os.replace(temp_path, RESPONSE_PATH)


def onFrameStart(frame):
    # The fast path, run 60 times a second: one stat call and out.
    if not os.path.exists(REQUEST_PATH):
        return

    try:
        with open(REQUEST_PATH) as handle:
            source = handle.read()
    except OSError:
        # A half-written request. The writer renames atomically, so this should
        # not happen - but if it does, leave the file and try again next frame
        # rather than reporting a corrupt request as a failure.
        return
    # Delete BEFORE running, so a request that crashes TouchDesigner does not
    # re-run on every frame after a restart and crash it again.
    try:
        os.remove(REQUEST_PATH)
    except OSError:
        pass

    # TD's API lives in builtins (op, me, ops, ...), so a plain exec namespace
    # already has it. REPO_ROOT is added so requests can import visionhands.
    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)          # append, never insert
    namespace = {"__name__": "__bridge__"}

    captured = StringIO()
    real_stdout = sys.stdout
    sys.stdout = captured
    try:
        exec(compile(source, "<bridge-request>", "exec"), namespace)
        status = "OK"
    except BaseException:
        # BaseException, not Exception: a request that raises SystemExit or
        # KeyboardInterrupt must still produce a response, or whatever is
        # driving this waits forever for a file that never arrives.
        traceback.print_exc(file=captured)
        status = "ERROR"
    finally:
        sys.stdout = real_stdout

    body = captured.getvalue()
    if "result" in namespace:
        body += "\\nresult: %%r\\n" %% (namespace["result"],)
    _write_response("STATUS: %%s\\n%%s" %% (status, body))
    # Echo to the Textport too, so a human watching sees what was run.
    print("[bridge] %%s (%%d chars out)" %% (status, len(body)))


def onExit():
    """Stop the camera when the project closes.

    This is the teardown DESIGN.md 8 requires and that nothing else was wiring
    up: a Vision call landing on a torn-down capture session is a native crash
    that takes TouchDesigner with it. Having the bridge own it means the camera
    gets stopped even when a human forgets.
    """
    try:
        if REPO_ROOT not in sys.path:
            sys.path.append(REPO_ROOT)
        from visionhands.td import bootstrap
        bootstrap.stop()
        print("[bridge] onExit: visionhands stopped")
    except Exception as exc:
        print("[bridge] onExit: could not stop visionhands: %%r" %% (exc,))
'''


def main():
    print("=" * 68)
    print("visionhands bridge: install")
    print("=" * 68)

    os.makedirs(BRIDGE_DIR, exist_ok=True)
    # Clear any stale files, so the first request is not answered by an old
    # response and the bridge does not immediately run a request from last time.
    for name in ("request.py", "response.txt", "response.txt.tmp"):
        path = os.path.join(BRIDGE_DIR, name)
        if os.path.exists(path):
            os.remove(path)
    print("1. bridge dir: %s (cleared)" % BRIDGE_DIR)

    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s - edit PARENT_PATH" % PARENT_PATH)
        return

    bridge = parent.op(BRIDGE_DAT_NAME)
    if bridge is None:
        bridge = parent.create(executeDAT, BRIDGE_DAT_NAME)
        print("2. created Execute DAT %s" % bridge.path)
    else:
        print("2. reusing Execute DAT %s" % bridge.path)

    bridge.text = BRIDGE_SOURCE % {"bridge_dir": BRIDGE_DIR, "repo_root": REPO_ROOT}

    # The callbacks only fire if their toggles are on - the shipped template
    # says so in its own docstring, and this is the single easiest thing to
    # forget when wiring an Execute DAT by hand.
    bridge.par.active = True
    bridge.par.framestart = True
    bridge.par.exit = True
    bridge.nodeX, bridge.nodeY = 0, 200
    print("3. enabled: active, framestart, exit")

    print()
    print("4. bridge is live. It will answer requests written to")
    print("   %s/request.py" % BRIDGE_DIR)
    print()
    print("   It also stops the camera on project exit, which is the teardown")
    print("   DESIGN.md 8 requires and nothing else was wiring up.")
    print()
    print("To remove: op('%s').destroy()" % bridge.path)
    print("=" * 68)


main()
