#!/usr/bin/env python
"""Build the visionhands COMP: TD-ready coordinate spaces from the OSC channels.

    HOW TO USE
      Paste into a Text DAT in TouchDesigner, right-click > "Run Script".
      It builds /project1/visionhands and wires the OSC In CHOP into it.
      Idempotent: run it as often as you like.

WHAT IT PRODUCES, and what it deliberately does NOT.

Joint NAMING is not done here. The sidecar sends `h0_index_tip_x` directly,
because naming belongs at the single source of truth rather than in a lookup two
hops downstream. An earlier version of this COMP renamed `h0_lm08_x` with a
Rename CHOP; that works - including the name-reference trick of feeding it a
Table DAT through a DAT to CHOP, which is verified - but it renames BY POSITION,
so the mapping would silently depend on channel order matching, decided
somewhere else. So the wire carries readable names and this COMP does only the
thing that genuinely belongs in TouchDesigner: coordinate spaces.

    in                    out
    h0_index_tip_x   ->   h0_index_tip_x     unchanged: normalised 0..1, bottom-left
                          h0_index_tip_tx    centred, aspect-corrected
                          h0_index_tip_px    pixels

Everything else - the frame scalars, the per-hand scalars, every `_conf` -
passes through untouched.

WHY THREE SPACES rather than picking one. They are each a one-operator branch and
cost nothing, and which one you want depends entirely on what you hook up:

    _x, _y    normalised 0..1 with the origin BOTTOM-LEFT. This is Vision's own
              space and it is already what TouchDesigner's UVs use, so it maps
              straight onto a TOP without conversion (DESIGN.md 7). Use it for
              texture lookups and for anything expecting UVs.
    _tx, _ty  world units for an ORTHOGRAPHIC camera, matching its Ortho Width
              parameter and the RENDER's aspect - not the source image's.
              Feed these straight into a Geometry COMP's instance translate.
              See the Orthowidth parameter below - getting this convention wrong
              is the one thing that makes an overlay land almost, but not quite,
              on the hand.
    _px, _py  pixels, for hit-testing against a TOP's resolution or for anything
              that thinks in pixels. Still bottom-left, like TD's TOPs.

THE ORTHO WIDTH PARAMETER, and why it exists rather than a bare aspect scale.
TouchDesigner's Camera COMP in orthographic mode has an Ortho Width parameter
that sets the visible WIDTH in world units - default 1.0, so the visible space is
x from -0.5 to +0.5 and y from -0.5/aspect to +0.5/aspect. An earlier version of
this COMP normalised to unit HEIGHT instead (y from -0.5 to +0.5, x scaled out to
+/-0.889), which is equally defensible and does not match TD's camera. Against a
default camera it left an overlay needing a hand-dialled 0.5625 on BOTH axes -
which is exactly 1/aspect, the conversion between the two conventions.

So the scale is now the camera's own number. Set Orthowidth here to whatever
cam1's Ortho Width is and the coordinates land exactly, with nothing to tune.

TWO ASPECTS, AND THEY ARE NOT THE SAME ONE. This is the same conflation as the
0.56 problem, one level deeper, and it was caught in review rather than in use.
TouchDesigner derives an ortho camera's vertical extent from the RENDER's
resolution (Camera COMP docs: aperture_y = resy/resx * aperture_x), so the
visible half-height is Orthowidth/2 * Renderh/Renderw. The SOURCE image's
resolution is a different number entirely - it decides the pixel branch and
nothing else.

They happen to be equal in the setup this was built against (a 1280x720 camera
rendered to a 1280x720 TOP), which is exactly why using one for both looked
correct. Render the same 1280x720 source into a square 1080x1080 TOP and `ty`
lands at 56% of where it should; into a portrait 720x1280 TOP, 32%.

NO PYTHON RUNS IN A COOK. Every operator here is a built-in doing built-in work;
the joint-name mapping is generated once, at build time, into a Rename CHOP's
parameters. The only Python is in two parameter expressions that read the COMP's
own resolution parameters, which TouchDesigner evaluates itself.

Built against TouchDesigner 099 / Python 3.11.15 on macOS.
"""

# The sidecar's own lifecycle, driven from the COMP.
#
# The COMP owns Start/Stop pulses rather than leaving the sidecar to a terminal,
# because a component you cannot stop from inside TouchDesigner is a component
# that outlives the project - and this one holds the camera. Stop finds ANY
# running sidecar by command line, not only one this COMP started, so a process
# launched from a shell (or left behind by a crash) can still be killed from here.
SIDECAR_CONTROL_SOURCE = '''# Generated by tools/td_build_comp.py
#
# Runs on TouchDesigner's main thread, on a pulse or at project exit. Never
# per-frame: pgrep costs a few milliseconds, which is nothing on a button press
# and would be rude every cook.
import os
import signal
import subprocess

SIDECAR_PYTHON = %(python)r
REPO_ROOT = %(repo)r
PORT = %(port)d
MATCH = "visionhands.sidecar"


def running_pids():
    """Every sidecar process on this machine, ours or not.

    Matching on the command line rather than tracking a Popen handle is what
    makes Stop work on a sidecar started from a terminal - which is how it gets
    started while developing, and exactly when you most want to stop it from
    here.

    TWO-STAGE MATCH, and the second stage is not paranoia - it was written after
    the first version SIGTERMed the shell that was grepping for the sidecar.
    `pgrep -f` matches the pattern anywhere in a full command line, so a
    terminal running `pgrep -f visionhands.sidecar`, an editor with the file
    open, or a `tail` on its log all match. Killing those is unacceptable, so
    every candidate is confirmed with `ps` before it is signalled:

        argv[0] must be a python             (a shell or a grep is not)
        the argv must contain -m visionhands.sidecar

    A shell whose command line merely mentions the sidecar has argv[0] of sh or
    zsh and is rejected; a python running `-c` with the string in it fails the
    second test.
    """
    try:
        found = subprocess.run(["pgrep", "-f", MATCH],
                               capture_output=True, text=True, timeout=5)
    except Exception as exc:
        print("[visionhands] pgrep failed: %%r" %% (exc,))
        return []

    pids = []
    for line in found.stdout.split():
        try:
            pid = int(line)
        except ValueError:
            continue
        if pid == os.getpid():
            continue                      # never signal TouchDesigner itself
        if _is_sidecar(pid):
            pids.append(pid)
    return pids


def _is_sidecar(pid):
    """Confirm a pid really is a sidecar, not something that merely mentions it."""
    try:
        # `command=` only. NOT `comm=`, which macOS truncates to 16 characters:
        # a venv interpreter comes back as "/Users/omer/.ven", whose basename is
        # ".ven", and the check silently matches nothing. That cost a debugging
        # round trip and would have been invisible - Stop would simply never
        # find anything.
        proc = subprocess.run(["ps", "-p", str(pid), "-o", "command="],
                              capture_output=True, text=True, timeout=5)
    except Exception:
        return False
    line = proc.stdout.strip()
    if not line:
        return False                      # already gone
    tokens = line.split()
    if not tokens or "python" not in os.path.basename(tokens[0]):
        return False
    # `-m` and the module name must be ADJACENT ARGUMENTS, not a substring of
    # the command line. A python running `-c "x='-m visionhands.sidecar'"`
    # contains the text but is not a sidecar, and signalling it would be exactly
    # the class of mistake that killed a shell a moment ago.
    for index, token in enumerate(tokens[:-1]):
        if token == "-m" and tokens[index + 1] == MATCH:
            return True
    return False


def start():
    """Start a sidecar, after stopping any that already exist.

    Stop-first for the same reason engine.start() does it: two processes holding
    one camera is the failure DESIGN.md 8 names, and it is easy to reach by
    pressing a button twice.
    """
    stop()
    # The toggle reaches the sidecar as a LAUNCH FLAG, read once at startup.
    # That is the whole mechanism, and it is why the toggle says "restart to
    # apply": the sidecar is a separate process and there is no control channel
    # into it. Adding one to change a hand partition would be a great deal of
    # machinery for something nobody changes mid-session. The same pattern is
    # settled for the future stream toggles - docs/BUILD_PLAN.md step 5.
    comp = op(%(comp)r)
    assign = comp is None or bool(comp.par.Slotassign.eval())
    process = subprocess.Popen(
        [SIDECAR_PYTHON, "-m", "visionhands.sidecar",
         "--port", str(PORT), "--parent-pid", str(os.getpid()),
         "--slots", "chirality" if assign else "off"],
        cwd=REPO_ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("[visionhands] sidecar started, pid %%d, slots=%%s"
          %% (process.pid, "chirality (h0=right, h1=left)" if assign else "off"))
    return process.pid


def stop():
    """Stop every running sidecar. Returns how many were stopped.

    SIGTERM, not SIGKILL: the sidecar handles SIGTERM by stopping its capture
    session properly, and killing it outright would leave the camera to be
    reclaimed by the OS rather than released (DESIGN.md 8).
    """
    pids = running_pids()
    for pid in pids:
        try:
            os.kill(pid, signal.SIGTERM)
            print("[visionhands] stopped sidecar pid %%d" %% pid)
        except ProcessLookupError:
            pass
        except PermissionError:
            print("[visionhands] cannot signal pid %%d - not ours" %% pid)
    return len(pids)


def status():
    pids = running_pids()
    return "sidecar: %%s" %% (("running, pid %%s" %% pids) if pids else "not running")
'''

# The Parameter Execute DAT that turns a button press into a call.
SIDECAR_CALLBACK_SOURCE = '''# Generated by tools/td_build_comp.py
#
# TouchDesigner calls onPulse when a pulse parameter is pressed. The work lives
# in sidecar_control so it can also be called directly:
#     op('/project1/visionhands/sidecar_control').module.status()


def onPulse(par):
    control = op("sidecar_control").module
    if par.name == "Startsidecar":
        pid = control.start()
        par.owner.par.Sidecarpid = pid
    elif par.name == "Stopsidecar":
        stopped = control.stop()
        par.owner.par.Sidecarpid = 0
        print("[visionhands] stopped %d process(es)" % stopped)
    elif par.name == "Sidecarstatus":
        print("[visionhands] " + control.status())
'''

# Stops the sidecar when the project closes. Belt and braces with the sidecar's
# own parent-pid watch: this handles a clean quit, that handles a crash.
SIDECAR_EXIT_SOURCE = '''# Generated by tools/td_build_comp.py


def onExit():
    op("sidecar_control").module.stop()
'''

PARENT_PATH = "/project1"
COMP_NAME = "visionhands"
SOURCE_CHOP = "visionhands_osc"
OSC_PORT = 10000
REPO_ROOT = "/Users/omer/Documents/GitHub/visionhands-touchdesigner"
SIDECAR_PYTHON = "/Users/omer/.venvs/visionhands/bin/python"

# Defaults for the aspect and pixel conversions. MEASURED: the sidecar requests
# and receives 1280x720 (DESIGN.md 2.6), and Vision is fastest there.
#
# These are COMP parameters rather than baked-in numbers so a different camera
# does not need a rebuild. They are NOT read from the incoming channels because
# the wire contract deliberately does not carry width and height - adding them
# would be a contract change to solve something a parameter already solves.
DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 720

# TouchDesigner's Camera COMP defaults to an Ortho Width of 1.0, so the visible
# world space is x in [-0.5, +0.5] and y in [-0.5/aspect, +0.5/aspect]. Matching
# that default means the common case needs no tuning at all.
DEFAULT_ORTHO_WIDTH = 1.0


# The rename approach that is no longer needed, recorded because the knowledge
# cost something to get: TouchDesigner's Rename CHOP DOES support wildcard
# back-references, so `*_lm08_*` -> `*_index_tip_*` renames h0 and h1 and _x,
# _y and _conf from one rule (verified live). What it does NOT do is apply 21
# such rules pairwise - a space-separated From/To list applies the first
# replacement to everything the whole From list matches, which turned all 126
# landmark channels into `h0_wrist_x`, `h0_wrist_x1`, `h0_wrist_x2`... The
# working alternative is the second input, a name reference built from a Table
# DAT through a DAT to CHOP (its DAT arrives by PARAMETER, not by a wire - a
# DAT to CHOP has no CHOP input connector), but that renames by position.


def main():
    import td

    print("=" * 70)
    print("visionhands: building the translation COMP")
    print("=" * 70)

    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s" % PARENT_PATH)
        return

    comp = parent.op(COMP_NAME)
    existed = comp is not None
    previous = {}
    if existed:
        # Remember what the user tuned, so a rebuild restores it rather than
        # resetting it.
        for name in ("Resw", "Resh", "Orthowidth", "Renderw", "Renderh"):
            if hasattr(comp.par, name):
                previous[name] = getattr(comp.par, name).eval()
    if comp is None:
        comp = parent.create(td.baseCOMP, COMP_NAME)
        print("1. created %s" % comp.path)
    else:
        # Rebuild the insides from scratch rather than patching them, so running
        # this twice cannot leave a half-old network behind.
        for child in list(comp.children):
            child.destroy()
        print("1. reusing %s (contents cleared)" % comp.path)
    comp.nodeX, comp.nodeY = 250, 0

    # -- custom parameters -------------------------------------------------
    page = comp.appendCustomPage("Visionhands")
    par_w = page.appendInt("Resw", label="Source Width")[0]
    par_h = page.appendInt("Resh", label="Source Height")[0]
    # `.default` always, `.val` only when the parameter is being created.
    # TD's appendInt/appendFloat replace a parameter's attributes on rebuild, so
    # assigning .val unconditionally silently snapped a tuned Orthowidth back to
    # 1.0 and put a correctly-aligned overlay back off-target - the exact failure
    # this COMP exists to prevent, caused by re-running its own builder.
    par_w.default = DEFAULT_WIDTH
    par_h.default = DEFAULT_HEIGHT
    if not existed:
        par_w.val, par_h.val = DEFAULT_WIDTH, DEFAULT_HEIGHT
    # Match your Camera COMP's Ortho Width. TD's default is 1.0.
    par_ortho = page.appendFloat("Orthowidth", label="Camera Ortho Width")[0]
    par_ortho.default = DEFAULT_ORTHO_WIDTH
    if not existed:
        par_ortho.val = DEFAULT_ORTHO_WIDTH

    par_rw = page.appendInt("Renderw", label="Render Width")[0]
    par_rh = page.appendInt("Renderh", label="Render Height")[0]
    par_rw.default = DEFAULT_WIDTH
    par_rh.default = DEFAULT_HEIGHT

    lifecycle = comp.appendCustomPage("Sidecar")
    # Slot assignment: h0 = the right hand, h1 = the left, whichever order Vision
    # reports them in (visionhands/slots.py). On the Sidecar page rather than with
    # the attribute toggles, because it is a property of the PROCESS and only takes
    # effect when one is started - putting it beside Start is what makes that
    # obvious. NOTE the behavioural consequence: with this on, a single LEFT hand
    # puts nothing in h0, so every h0_* channel reads zero and h1_* carries the
    # hand. That is what "h0 is always the right hand" means.
    par_slots = lifecycle.appendToggle("Slotassign",
                                       label="Assign Slots (restart to apply)")[0]
    par_slots.default = True
    if not existed:
        par_slots.val = True
    lifecycle.appendPulse("Startsidecar", label="Start Sidecar")
    lifecycle.appendPulse("Stopsidecar", label="Stop Sidecar")
    lifecycle.appendPulse("Sidecarstatus", label="Print Status")
    par_pid = lifecycle.appendInt("Sidecarpid", label="Sidecar PID")[0]
    par_pid.readOnly = True
    # Read the render's real resolution and the camera's real ortho width when
    # they are there to read, so the common case needs no tuning at all.
    render = parent.op("render1")
    if render is not None:
        par_rw.val = int(render.par.resolutionw.eval())
        par_rh.val = int(render.par.resolutionh.eval())
        print("   (took render %dx%d from %s)" % (par_rw.eval(), par_rh.eval(), render.path))
    elif not existed:
        par_rw.val, par_rh.val = DEFAULT_WIDTH, DEFAULT_HEIGHT

    camera = parent.op("cam1")
    if camera is not None and camera.par.projection.eval() == "ortho":
        par_ortho.val = float(camera.par.orthowidth.eval())
        print("   (took Orthowidth %.3f from %s)" % (par_ortho.eval(), camera.path))

    # Anything the user had tuned wins over the defaults above, except where we
    # just read a better answer from the actual camera and render.
    for name, value in previous.items():
        if name not in ("Orthowidth", "Renderw", "Renderh") or (
                render is None and camera is None):
            getattr(comp.par, name).val = value

    print("2. parameters: source %dx%d, render %dx%d, Orthowidth=%.3f, plus a Sidecar page"
          % (par_w.eval(), par_h.eval(), par_rw.eval(), par_rh.eval(), par_ortho.eval()))

    def make(kind, name, x, y):
        node = comp.create(kind, name)
        node.nodeX, node.nodeY = x, y
        return node

    # -- the network -------------------------------------------------------
    chop_in = make(td.inCHOP, "in1", -600, 0)

    print("3. no rename stage: the sidecar already sends readable joint names")

    # Branches. Each is Select -> Math -> Rename, which is the whole trick:
    # pick the channels, do the arithmetic, give the result its own suffix.
    def branch(label, select_pattern, suffix, pre_offset, mult_expr, y):
        select = make(td.selectCHOP, "sel_%s" % label, -200, y)
        select.inputConnectors[0].connect(chop_in)
        select.par.channames = select_pattern

        math = make(td.mathCHOP, "math_%s" % label, 0, y)
        math.inputConnectors[0].connect(select)
        # Math CHOP applies pre-offset, then multiply. So (v - 0.5) * aspect is
        # exactly preoff=-0.5, mult=aspect - no expression gymnastics needed.
        math.par.preoff = pre_offset
        math.par.gain.expr = mult_expr

        rename = make(td.renameCHOP, "ren_%s" % label, 200, y)
        rename.inputConnectors[0].connect(math)
        rename.par.renamefrom = select_pattern
        rename.par.renameto = select_pattern.replace("_x", "_%s" % suffix).replace(
            "_y", "_%s" % suffix)
        return rename

    # World units for an orthographic camera of the given Ortho Width. x spans
    # the full width; y spans width/aspect, because a 16:9 render is shorter than
    # it is wide and the camera's number describes the WIDTH.
    tx = branch("tx", "*_x", "tx", -0.5,
                "me.parent().par.Orthowidth", -150)
    ty = branch("ty", "*_y", "ty", -0.5,
                "me.parent().par.Orthowidth * me.parent().par.Renderh "
                "/ me.parent().par.Renderw", -300)
    # Pixels.
    px = branch("px", "*_x", "px", 0.0, "me.parent().par.Resw", -450)
    py = branch("py", "*_y", "py", 0.0, "me.parent().par.Resh", -600)

    merge = make(td.mergeCHOP, "merge_out", 450, 0)
    for index, source in enumerate((chop_in, tx, ty, px, py)):
        merge.inputConnectors[index].connect(source)

    chop_out = make(td.outCHOP, "out1", 650, 0)
    chop_out.inputConnectors[0].connect(merge)

    # -- sidecar lifecycle -------------------------------------------------
    control = comp.create(td.textDAT, "sidecar_control")
    control.nodeX, control.nodeY = -600, 200
    control.text = SIDECAR_CONTROL_SOURCE % {
        "python": SIDECAR_PYTHON, "repo": REPO_ROOT, "port": OSC_PORT,
        "comp": comp.path}

    callbacks = comp.create(td.parameterexecuteDAT, "sidecar_callbacks")
    callbacks.nodeX, callbacks.nodeY = -350, 200
    callbacks.text = SIDECAR_CALLBACK_SOURCE
    callbacks.par.op = comp.path
    callbacks.par.pars = "Startsidecar Stopsidecar Sidecarstatus"
    callbacks.par.active = True
    callbacks.par.onpulse = True
    callbacks.par.custom = True

    on_exit = comp.create(td.executeDAT, "sidecar_exit")
    on_exit.nodeX, on_exit.nodeY = -100, 200
    on_exit.text = SIDECAR_EXIT_SOURCE
    on_exit.par.active = True
    on_exit.par.exit = True

    print("4. built %d operators, including sidecar Start/Stop" % len(comp.children))

    # -- wire the OSC CHOP in ---------------------------------------------
    source = parent.op(SOURCE_CHOP)
    if source is None:
        print("5. no %s to wire up - run tools/td_setup_osc.py first" % SOURCE_CHOP)
    else:
        comp.inputConnectors[0].connect(source)
        print("5. wired %s -> %s" % (source.path, comp.path))

    comp.cook(force=True)
    out_chop = comp.op("out1")
    print()
    print("6. output: %d channels" % out_chop.numChans)
    names = [c.name for c in out_chop.chans()]
    for probe in ("h0_wrist_x", "h0_index_tip_x", "h0_index_tip_tx",
                  "h0_index_tip_px", "h0_index_tip_conf", "n_hands", "age_ms"):
        mark = "ok " if probe in names else "MISSING"
        value = ""
        channel = out_chop.chan(probe)
        if channel is not None:
            value = " = %.4f" % channel[0]
        print("   %-8s %s%s" % (mark, probe, value))
    print()
    print("   Reference a fingertip as:  op('%s')['h0_index_tip_tx']" % comp.path)
    print()
    print("   Sidecar page on %s:" % comp.path)
    print("     Start Sidecar / Stop Sidecar / Print Status")
    print("   Stop finds ANY running sidecar, including one started from a")
    print("   terminal, and the project's exit stops it too.")
    print("=" * 70)


main()
