#!/usr/bin/env python
"""Profile `/project1/appletd` HONESTLY: cook time and cook COUNT, across frames.

    Paste into a Text DAT, Run Script. Then, a second later:
        op('/project1/appletd/profiler').module.report()
    or read the JSON it writes to /tmp/vision_profile.json.

WHY THIS EXISTS, and it is the only reason. `cookTime` is a LAST-VALUE GAUGE: it
holds the duration of the operator's previous cook forever, so an operator that has
stopped cooking entirely reports exactly the same number as one that is cooking
every frame. Every figure this project has had to throw away came from reading it
the obvious way:

  * 1.2 ms and 1.55 ms, quoted as a regression, measured while the synthetic feeder
    was dead of a ModuleNotFoundError into /dev/null. Nothing was cooking at all.
  * 2.946 ms, read immediately after a `cook(force=True)`, against a real 1.030.
  * a cook-count comparison that "proved" a gate worked, both counts read inside
    one script, so both were the same frame's value.

So this samples ACROSS FRAMES, from a scheduled callback rather than from a script
that blocks the frame loop it is trying to measure, and it reports:

    cooks     how many times the operator cooked over the window. THE honest
              answer to "is this gated?" - a frozen group's count is flat and its
              duration is not.
    ms        median, min and max over the samples where it actually cooked. A
              median rather than a mean because the first cook after a rebuild is
              always an outlier and one outlier moves a mean.

AND IT PROVES THE INPUT WAS MOVING. `seq` on the hands stream has to change between
the first sample and the last, or the whole run is discarded with a message saying
so - which is the check that would have caught the dead feeder immediately.

Thread: TouchDesigner's main thread only, via `run(..., delayFrames=n)`. Nothing
here touches a TD object from anywhere else.
Ref: DESIGN.md 2.11 (the gauge), docs/BUILD_PLAN.md step 10.
"""

MASTER_PATH = "/project1/appletd"
DAT_NAME = "profiler"
# 90 frames at TouchDesigner's default 60 fps is 1.5 s - long enough to span about
# 45 data frames at the sidecar's 30 fps, so an operator that cooks on alternate
# frames is visibly distinguishable from one that is frozen.
DEFAULT_FRAMES = 90
REPORT_PATH = "/tmp/vision_profile.json"

PROFILER_SOURCE = '''# Generated by tools/td_profile.py - which says why any of this
# is needed.
#
# Runs on TouchDesigner's MAIN THREAD, one `sample()` per frame, scheduled with
# `run(..., delayFrames=n)`. Deliberately not a loop with a sleep in it: a script
# that sleeps blocks the frame loop it is measuring, which is how a "distribution"
# of one value repeated got recorded as a distribution.
import json

MASTER_PATH = %(master)r
REPORT_PATH = %(report)r

# Filled by `start()`, appended to by `sample()`, read by `report()`.
# Samples live in the DAT's own OPERATOR STORAGE, not in a module global. TRAP,
# measured here: a scheduled `run()` string that calls back into this module can
# reach a DIFFERENT module object, so a module-level list accumulated nothing and
# the report saw zero samples while the schedule had fired 90 times. Storage is
# owned by the operator and is the same dict whoever reaches it.
STORE_KEY = "profile_samples"


def _store():
    dat = op(%(dat)r)
    got = dat.fetch(STORE_KEY, None)
    if got is None:
        got = []
        dat.store(STORE_KEY, got)
    return got


def _snapshot(comp):
    """One frame's cook counters and durations for every operator in the COMP tree.

    Contract: keys are paths RELATIVE to the master COMP, so a report reads
              `hands/temporal` rather than an absolute path repeated 200 times.
              Values are (totalCooks, cookTime, childrenCookTime, allowCooking).
    Traps:    the counter is `totalCooks`. There is no `cookCount` - reaching for
              that name raises tdAttributeError from inside a scheduled callback,
              which prints to a textport and looks exactly like the schedule never
              having fired.
              `childrenCookTime` on a COMP is the sum for everything INSIDE it,
              which is the number that answers "what does this group cost"; a
              group COMP's own `cookTime` is a few microseconds of wiring.
    """
    rows = {}

    def walk(parent):
        for child in parent.children:
            rows[child.path[len(comp.path) + 1:]] = (
                child.totalCooks, child.cookTime,
                child.childrenCookTime if child.isCOMP else 0.0,
                child.allowCooking)
            if child.isCOMP:
                walk(child)

    walk(comp)
    rows[""] = (comp.totalCooks, comp.cookTime, comp.childrenCookTime,
                comp.allowCooking)
    return rows


def sample():
    """One frame's worth. Called once per frame by the schedule `start()` sets up."""
    comp = op(MASTER_PATH)
    if comp is None:
        return
    hands = comp.op("hands/in1")
    seq = None
    if hands is not None:
        channel = hands.chan("seq")
        seq = None if channel is None else channel[0]
    _store().append({"frame": absTime.frame, "seq": seq,
                     "clock": absTime.seconds, "ops": _snapshot(comp)})


def start(frames):
    """Schedule `frames` samples, one per frame, then a report.

    Two things here are not the obvious spelling, and both were measured:
      * `td.run`, not the bare `run`. This builder is run by pasting into a Text
        DAT AND through the MCP bridge with `exec(open(path).read())`, and the
        bridge's exec context has no `run` in it - "name 'run' is not defined".
        `td.run` is the same scheduler and resolves in both.
      * `op(path).module.sample()`, not `mod(path).sample()`. `mod` is likewise
        absent from the bridge's context, and a scheduled string that raises
        NameError does so silently - the schedule fired 90 times and the report
        saw zero samples, with nothing printed anywhere.
    """
    import td

    op(%(dat)r).store(STORE_KEY, [])
    for index in range(frames):
        td.run("op(%(dat)r).module.sample()", delayFrames=index + 1)
    td.run("op(%(dat)r).module.report()", delayFrames=frames + 2)


def report():
    """Reduce the samples to per-operator cook counts and median durations.

    Writes JSON to REPORT_PATH and prints the top of the table. Refuses to report
    anything if `seq` did not move, because every figure would be a stale gauge
    reading and a plausible one.
    """
    samples = _store()
    if len(samples) < 2:
        print("[profile] only %%d sample(s) - nothing to say" %% len(samples))
        return None

    seqs = [s["seq"] for s in samples if s["seq"] is not None]
    moved = len(set(seqs)) > 1
    span_frames = samples[-1]["frame"] - samples[0]["frame"]
    # The ACHIEVED frame rate, and it belongs in every report. MEASURED the hard
    # way: a set of figures taken while a browser was using 60%% of the machine put
    # the whole COMP at 12.8 ms and the cook rate at 26 frames in 89, and every
    # per-operator number in that run was inflated with it. cookTime is wall-clock,
    # so a profile taken at 24 fps is not comparable to one taken at 60 - and
    # nothing in the numbers themselves says which you have.
    elapsed = samples[-1]["clock"] - samples[0]["clock"]
    fps = (span_frames / elapsed) if elapsed > 0 else 0.0

    rows = {}
    for path in samples[0]["ops"]:
        counts, times, inner, cooking = [], [], [], None
        for snap in samples:
            entry = snap["ops"].get(path)
            if entry is None:
                continue
            counts.append(entry[0])
            times.append(entry[1])
            inner.append(entry[2])
            cooking = entry[3]
        if not counts:
            continue
        # The DELTA in cookCount is the honest gate check; a duration is not.
        cooked = counts[-1] - counts[0]
        # Only the samples where the operator actually advanced its counter carry a
        # meaningful duration; the rest are the gauge repeating itself.
        advanced = [b > a for a, b in zip(counts, counts[1:])]
        live = sorted(t for t, moved_on in zip(times[1:], advanced) if moved_on)
        deep = sorted(t for t, moved_on in zip(inner[1:], advanced) if moved_on)
        rows[path] = {
            "cooks": cooked,
            "cooking": bool(cooking),
            "ms_med": (live[len(live) // 2] if live else 0.0),
            "ms_min": (live[0] if live else 0.0),
            "ms_max": (live[-1] if live else 0.0),
            # For a group COMP this is the honest cost of the group: everything
            # inside it, summed. Zero for a plain operator.
            "inner_med": (deep[len(deep) // 2] if deep else 0.0),
            "n": len(live),
        }

    out = {"frames": span_frames, "samples": len(samples),
           "seq_moved": moved, "seq_distinct": len(set(seqs)),
           "fps": fps, "elapsed_s": elapsed, "ops": rows}
    try:
        with open(REPORT_PATH, "w") as handle:
            json.dump(out, handle, indent=1)
    except Exception as exc:
        print("[profile] could not write %%s: %%r" %% (REPORT_PATH, exc))

    if not moved:
        print("[profile] DISCARD: `seq` never changed over %%d frames, so nothing "
              "was arriving." %% span_frames)
        print("[profile] Every cookTime below would be the last value from "
              "whenever the stream stopped.")
    print("[profile] %%d samples over %%d frames at %%.1f fps, seq moved: %%s"
          %% (len(samples), span_frames, fps, moved))
    if fps < 45.0:
        print("[profile] SLOW: %%.1f fps. Every duration below is wall-clock, so "
              "they are all inflated." %% fps)
        print("[profile] Check what else is using the machine before comparing "
              "these to anything.")
    # A DAT that COMPILED during the window reports the compile as its cookTime,
    # with a cook count of one against everything else's hundred. Summing it into a
    # group total is how this tool nearly reported a 3x win as a 74%% loss.
    busiest = max((row["cooks"] for row in rows.values()), default=0)
    oneshots = sorted((path for path, row in rows.items()
                       if 0 < row["cooks"] <= max(1, busiest // 10)
                       and row["ms_med"] > 0.05), key=lambda p: p or "")
    if oneshots:
        print("[profile] ONE-OFF, do not sum into a group: %%s"
              %% ", ".join(oneshots[:5]))
        print("[profile] These cooked once or twice while others cooked %%d times - "
              "a DAT compiling looks exactly like this." %% busiest)
    ranked = sorted(rows.items(),
                    key=lambda kv: -max(kv[1]["ms_med"], kv[1]["inner_med"]))
    for path, row in ranked[:14]:
        print("   %%-34s %%4d cooks  self %%7.4f  inside %%7.4f ms"
              %% (path or "<COMP>", row["cooks"], row["ms_med"],
                  row["inner_med"]))
    print("[profile] full table in %%s" %% REPORT_PATH)
    return out
'''


def main():
    import td

    master = op(MASTER_PATH)
    if master is None:
        print("FAIL no COMP at %s" % MASTER_PATH)
        return

    dat = master.op(DAT_NAME) or master.create(td.textDAT, DAT_NAME)
    dat.nodeX, dat.nodeY = -1150, 700
    dat.text = PROFILER_SOURCE % {
        "master": MASTER_PATH, "report": REPORT_PATH,
        "dat": master.path + "/" + DAT_NAME}
    # Touching `.module` compiles the DAT, so a syntax error surfaces HERE rather
    # than three frames later inside a scheduled callback, where an exception is
    # printed to a textport nobody is reading.
    dat.module.start(DEFAULT_FRAMES)
    print("[profile] sampling %d frames; the report prints itself, and lands in %s"
          % (DEFAULT_FRAMES, REPORT_PATH))


main()
