#!/usr/bin/env python
"""Paste-into-TouchDesigner setup for the OSC (sidecar) route.

    HOW TO USE
      1. Start the sidecar in a terminal:
             ~/.venvs/visionhands/bin/python -m visionhands.sidecar
      2. In TouchDesigner, create a Text DAT, paste this whole file in,
         right-click > "Run Script".
      3. Watch the Textport. It creates the OSC In CHOP and reports the channel
         count once landmarks arrive.

    OPTIONAL: set LAUNCH_SIDECAR = True below and this will start the sidecar
    itself as a child process, and stop it when the project exits.

WHY THIS IS SO MUCH SMALLER THAN tools/td_setup_snippet.py. That one wires a
Script CHOP that runs our Python inside TouchDesigner, and MEASURED (DESIGN.md
2.8) a Python background thread in TD's process is starved by 28x - delivery fell
to 13 fps with 200 ms gaps. Moving the camera and Vision into their own process
put it back to 30 fps with 7.7 ms of jitter, and reduced the TouchDesigner side
to a single built-in operator with NO Python in it at all.

So there is no Script CHOP here, no callbacks DAT, and nothing of ours running
in a cook.

    THE CHANNELS. All 137, exactly as DESIGN.md 6.2 specifies, and identical to
    what the in-process Script CHOP produced - the contract did not change, only
    its transport.

    LIVENESS, and this is the one thing the sidecar route costs you. An OSC In
    CHOP holds its last received value forever, so a dead sidecar looks like a
    still hand rather than an error. Two native signals, no Python needed:
        slope of `seq`     == 0  ->  the CAMERA has stopped
        slope of `age_ms`  == 0  ->  the SIDECAR has stopped
    A Slope CHOP on either, into a Logic CHOP, gives you a usable alarm.

Built against TouchDesigner 099 / Python 3.11.15 on macOS.
"""

import os

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
PARENT_PATH = "/project1"
OSC_CHOP_NAME = "visionhands_osc"
OSC_PORT = 10000

# Set True to have TouchDesigner start and stop the sidecar itself.
#
# The trade: convenient, but it hides the sidecar's log where you cannot see it.
# While developing, leave this False and run the sidecar in a terminal - its
# status line reports camera fps, age and any engine errors every two seconds,
# and that is the first place to look when something is wrong.
LAUNCH_SIDECAR = False

REPO_ROOT = os.path.expanduser("~/Documents/GitHub/visionhands-touchdesigner")
SIDECAR_PYTHON = os.path.expanduser("~/.venvs/visionhands/bin/python")

# The Execute DAT that owns the child process, if LAUNCH_SIDECAR is on. It stops
# the sidecar on project exit - and the sidecar ALSO watches this process's pid
# and exits on its own if TouchDesigner dies without running onExit. Both, because
# an orphan holding the camera means the next launch fights it for the device.
LAUNCHER_DAT_NAME = "visionhands_sidecar_launcher"
LAUNCHER_SOURCE = '''# Generated by tools/td_setup_osc.py
#
# Owns the sidecar child process. onExit stops it politely; the sidecar also
# watches our pid and exits by itself if TouchDesigner dies without getting here.
import os
import subprocess

SIDECAR_PYTHON = %(python)r
REPO_ROOT = %(repo)r
PORT = %(port)d

_process = None


def start():
    global _process
    stop()
    _process = subprocess.Popen(
        [SIDECAR_PYTHON, "-m", "visionhands.sidecar",
         "--port", str(PORT), "--parent-pid", str(os.getpid())],
        cwd=REPO_ROOT,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("[visionhands] sidecar started, pid %%d" %% _process.pid)


def stop():
    global _process
    if _process is None:
        return
    proc, _process = _process, None
    proc.terminate()
    try:
        proc.wait(timeout=3.0)
    except subprocess.TimeoutExpired:
        proc.kill()
    print("[visionhands] sidecar stopped")


def onStart():
    start()


def onExit():
    stop()
'''


def main():
    print("=" * 68)
    print("visionhands: OSC route setup")
    print("=" * 68)

    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s - edit PARENT_PATH" % PARENT_PATH)
        return

    import td

    osc = parent.op(OSC_CHOP_NAME)
    if osc is None:
        osc = parent.create(td.oscinCHOP, OSC_CHOP_NAME)
        print("1. created OSC In CHOP %s" % osc.path)
    else:
        print("1. reusing OSC In CHOP %s" % osc.path)
    osc.par.port = OSC_PORT
    osc.par.active = True
    osc.nodeX, osc.nodeY = 0, 0
    print("   listening on port %d" % OSC_PORT)

    if LAUNCH_SIDECAR:
        if not os.path.isfile(SIDECAR_PYTHON):
            print("FAIL no interpreter at %s" % SIDECAR_PYTHON)
            return
        launcher = parent.op(LAUNCHER_DAT_NAME)
        if launcher is None:
            launcher = parent.create(td.executeDAT, LAUNCHER_DAT_NAME)
            print("2. created launcher %s" % launcher.path)
        else:
            print("2. reusing launcher %s" % launcher.path)
        launcher.text = LAUNCHER_SOURCE % {
            "python": SIDECAR_PYTHON, "repo": REPO_ROOT, "port": OSC_PORT}
        launcher.par.active = True
        launcher.par.start = True
        launcher.par.exit = True
        launcher.nodeX, launcher.nodeY = 0, 150
        # onStart only fires on project load, so kick it once now.
        launcher.module.start()
    else:
        print("2. LAUNCH_SIDECAR is off - start it yourself:")
        print("   %s -m visionhands.sidecar" % SIDECAR_PYTHON)

    print()
    print("3. %s has %d channels" % (osc.path, osc.numChans))
    if osc.numChans == 0:
        print("   (zero until the first bundle arrives - start the sidecar and")
        print("    re-run this, or just watch the operator)")
    elif osc.numChans in (137, 141):
        # 137 hand channels, plus the four `sc_*` sidecar status channels that
        # ride the base port (DESIGN.md 6.4). 137 alone means the sender predates
        # those - tools/send_synthetic.py sends the hands contract only.
        print("   OK all 137 hand channels present%s. Wave at the camera and"
              % (" (+4 sidecar status)" if osc.numChans == 141 else ""))
        print("   watch h0_conf_median. Gate downstream work on that, NEVER on")
        print("   h0_score - that channel is a measured constant 1.0.")
    else:
        print("   UNEXPECTED - expected 137, or 141 with the sidecar's status")
        print("   channels. Is another sender on port %d?" % OSC_PORT)
    print()
    print("LIVENESS: a dead sidecar leaves these channels frozen, not zeroed.")
    print("  Slope CHOP on 'seq'    -> 0 means the camera stopped")
    print("  Slope CHOP on 'age_ms' -> 0 means the sidecar stopped")
    print("=" * 68)


main()
