#!/usr/bin/env python
"""Paste-into-TouchDesigner setup for the visionhands Script CHOP.

    HOW TO USE
      1. In TouchDesigner, create a Text DAT and paste this whole file in.
      2. Right-click the DAT > "Run Script". Watch the Textport (Alt+T).
      3. It creates the Script CHOP and its callbacks DAT for you, starts the
         camera, and prints what it did.

    To stop the camera (and you MUST, before closing or reloading the project):
        from visionhands.td import bootstrap
        bootstrap.stop()

    To check on it at any time:
        from visionhands.td import bootstrap
        print(bootstrap.status())

WHY THIS FILE EXISTS RATHER THAN A LIST OF INSTRUCTIONS. Wiring a Script CHOP by
hand means creating two operators, setting a parameter to point one at the other,
and getting an import path right - four chances to make a mistake that presents
as an empty CHOP with no error. This does all of it and reports each step, so a
failure says which step failed.

It is idempotent: run it as often as you like. Existing operators are reused and
the camera is restarted rather than doubled, because two capture sessions
fighting over one device is the failure DESIGN.md 8 names.

Built against TouchDesigner 099 / Python 3.11.15 on macOS.
"""

import os
import sys

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# The repo, so `import visionhands` works. APPENDED, never inserted - see
# bootstrap.add_venv_to_path for why that ordering is load-bearing.
REPO_ROOT = os.path.expanduser("~/Documents/GitHub/visionhands-touchdesigner")

# Where to build the operators. "/project1" is TD's default container.
PARENT_PATH = "/project1"
CHOP_NAME = "visionhands_landmarks"
CALLBACKS_DAT_NAME = "visionhands_callbacks"

# What goes in the callbacks DAT. Importing the callbacks by name is all TD
# needs - it looks up onCook and onGetCookLevel in the DAT's namespace.
CALLBACKS_SOURCE = '''# Generated by tools/td_setup_snippet.py - safe to edit.
#
# TouchDesigner looks up onCook and onGetCookLevel in this DAT's namespace, so
# importing them by name is the whole wiring. The implementation lives in the
# repo, where it is version-controlled and tested.
from visionhands.td.hands_chop import onCook, onGetCookLevel  # noqa: F401
'''


def main():
    print("=" * 68)
    print("visionhands: TouchDesigner setup")
    print("=" * 68)

    # -- step 1: make the package importable --------------------------------
    if not os.path.isdir(REPO_ROOT):
        print("FAIL repo not found at %s - edit REPO_ROOT at the top of this DAT"
              % REPO_ROOT)
        return
    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)          # append, never insert
        print("1. sys.path += %s" % REPO_ROOT)
    else:
        print("1. sys.path already contains %s" % REPO_ROOT)

    # -- step 2: start the camera ------------------------------------------
    # Imported after the path is set, and re-imported fresh each run so an edit
    # to the repo takes effect without restarting TouchDesigner. bootstrap and
    # its dependencies are pure Python at module scope, so this is cheap.
    for module in [m for m in list(sys.modules) if m.startswith("visionhands")]:
        del sys.modules[module]
    from visionhands.td import bootstrap

    try:
        bootstrap.start()
        print("2. camera started")
    except Exception as exc:            # noqa: BLE001 - a setup script reports, see below
        # Not swallowed: printed and then returned on. Every likely cause here -
        # no camera permission for TouchDesigner.app, no matching device, a
        # missing venv - is something only a human can fix, and the message says
        # which.
        print("FAIL could not start the camera: %s" % exc)
        return

    # -- step 3: build the operators ---------------------------------------
    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s - edit PARENT_PATH" % PARENT_PATH)
        bootstrap.stop()
        return

    callbacks = parent.op(CALLBACKS_DAT_NAME)
    if callbacks is None:
        callbacks = parent.create(textDAT, CALLBACKS_DAT_NAME)
        print("3. created Text DAT %s" % callbacks.path)
    else:
        print("3. reusing Text DAT %s" % callbacks.path)
    callbacks.text = CALLBACKS_SOURCE

    chop = parent.op(CHOP_NAME)
    if chop is None:
        chop = parent.create(scriptCHOP, CHOP_NAME)
        print("4. created Script CHOP %s" % chop.path)
    else:
        print("4. reusing Script CHOP %s" % chop.path)
    # Point the CHOP at its callbacks. This is the wiring that is easy to get
    # wrong by hand and presents as an empty CHOP with no error at all.
    chop.par.callbacks = callbacks.path

    # Lay them out so they are findable rather than stacked on the origin.
    callbacks.nodeX, callbacks.nodeY = 0, 0
    chop.nodeX, chop.nodeY = 200, 0

    # -- step 4: report ----------------------------------------------------
    chop.cook(force=True)
    print()
    print("5. %s now has %d channels (expected 137)" % (chop.path, chop.numChans))
    print("   %s" % bootstrap.status())
    print()
    if chop.numChans == 137:
        print("OK  Wave at the camera and watch h0_found and h0_conf_median.")
        print("    Gate downstream work on h0_conf_median, NEVER on h0_score -")
        print("    that channel is a measured constant 1.0 (DESIGN.md 2.6).")
    else:
        print("UNEXPECTED channel count. Check the Textport for errors from the")
        print("callbacks DAT, and run bootstrap.status() for the engine's view.")
    print()
    print("REMEMBER: run bootstrap.stop() before closing or reloading this")
    print("project. A Vision call landing on a torn-down session is a native")
    print("crash that takes TouchDesigner with it (DESIGN.md 8).")
    print("=" * 68)


main()
