#!/usr/bin/env python
"""Paste-into-TouchDesigner setup for the appletd Script CHOP.

    HOW TO USE
      1. In TouchDesigner, create a Text DAT and paste this whole file in.
      2. Right-click the DAT > "Run Script". Watch the Textport (Alt+T).
      3. It creates the Script CHOP and its callbacks DAT for you, starts the
         camera, and prints what it did.

    To stop the camera (and you MUST, before closing or reloading the project):
        from appletd.td import bootstrap
        bootstrap.stop()

    To check on it at any time:
        from appletd.td import bootstrap
        print(bootstrap.status())

WHY THIS FILE EXISTS RATHER THAN A LIST OF INSTRUCTIONS. Wiring a Script CHOP by
hand means creating two operators, setting a parameter to point one at the other,
and getting an import path right - four chances to make a mistake that presents
as an empty CHOP with no error. This does all of it and reports each step, so a
failure says which step failed.

It is idempotent: run it as often as you like. Existing operators are reused and
the camera is restarted rather than doubled, because two capture sessions
fighting over one device is the failure DESIGN.md 8 names.

Built against TouchDesigner 099 / Python 3.11.15 on macOS.
"""

import os
import sys

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# The repo, so `import appletd` works. APPENDED, never inserted - see
# bootstrap.add_venv_to_path for why that ordering is load-bearing.
REPO_ROOT = os.path.expanduser("~/Documents/GitHub/appletd")

# Where to build the operators. "/project1" is TD's default container.
PARENT_PATH = "/project1"
CHOP_NAME = "appletd_landmarks"
CALLBACKS_DAT_NAME = "appletd_callbacks"

# What goes in the callbacks DAT. Importing the callbacks by name is all TD
# needs - it looks up onCook and onGetCookLevel in the DAT's namespace.
CALLBACKS_SOURCE = '''# Generated by tools/td_setup_snippet.py - safe to edit.
#
# onCook comes from the repo, where it is version-controlled and tested.
#
# onGetCookLevel is defined HERE and cannot be imported. VERIFIED LIVE against a
# running TouchDesigner: `CookLevel` is injected into a DAT's globals only - it
# is absent from `builtins` and missing from the `td` module. A function in an
# imported module therefore cannot see it, returns None, and TD falls back to
# AUTOMATIC: with no inputs to change, this CHOP then cooks exactly once and
# serves a frozen frame forever while the camera runs perfectly (measured:
# totalCooks = 1).
from appletd.td.hands_chop import cook_level, onCook  # noqa: F401


def onGetCookLevel(scriptOp):
    return cook_level(CookLevel)  # noqa: F821 - CookLevel is a DAT global
'''


def main():
    print("=" * 68)
    print("appletd: TouchDesigner setup")
    print("=" * 68)

    # -- step 1: make the package importable --------------------------------
    if not os.path.isdir(REPO_ROOT):
        print("FAIL repo not found at %s - edit REPO_ROOT at the top of this DAT"
              % REPO_ROOT)
        return
    if REPO_ROOT not in sys.path:
        sys.path.append(REPO_ROOT)          # append, never insert
        print("1. sys.path += %s" % REPO_ROOT)
    else:
        print("1. sys.path already contains %s" % REPO_ROOT)

    # -- step 2: start the camera ------------------------------------------
    #
    # NOTE what this deliberately does NOT do: flush `appletd` out of
    # sys.modules to pick up repo edits. An earlier version did, and it was
    # wrong twice over (both confirmed by running it):
    #
    #   * `engine.py` registers an Objective-C class at module scope, and
    #     re-importing raises `objc.error: _CaptureDelegate is overriding
    #     existing Objective-C class`. So it worked once and failed every run
    #     after.
    #   * Worse, the flush orphans `bootstrap._source` - the new module object
    #     has its own `_source = None`, so start()'s stop-first logic finds
    #     nothing to stop while the previous camera session is still running.
    #     That is precisely the two-sessions-fighting-over-one-camera failure
    #     DESIGN.md 8 names, caused by the very code meant to be convenient.
    #
    # To pick up an edit to the repo, RESTART TOUCHDESIGNER. Python module
    # caching plus Objective-C class registration means there is no safe
    # in-process reload, and pretending otherwise costs a camera session.
    from appletd.td import bootstrap

    try:
        # start() stops any existing source first, so re-running this DAT
        # restarts the camera rather than adding a second session.
        bootstrap.start()
        print("2. camera started (any previous session was stopped first)")
    except Exception as exc:            # noqa: BLE001 - a setup script reports, see below
        # Not swallowed: printed and then returned on. Every likely cause here -
        # no camera permission for TouchDesigner.app, no matching device, a
        # missing venv - is something only a human can fix, and the message says
        # which.
        print("FAIL could not start the camera: %s" % exc)
        return

    # -- step 3: build the operators ---------------------------------------
    parent = op(PARENT_PATH)
    if parent is None:
        print("FAIL no operator at %s - edit PARENT_PATH" % PARENT_PATH)
        bootstrap.stop()
        return

    callbacks = parent.op(CALLBACKS_DAT_NAME)
    if callbacks is None:
        callbacks = parent.create(textDAT, CALLBACKS_DAT_NAME)
        print("3. created Text DAT %s" % callbacks.path)
    else:
        print("3. reusing Text DAT %s" % callbacks.path)
    callbacks.text = CALLBACKS_SOURCE

    chop = parent.op(CHOP_NAME)
    if chop is None:
        chop = parent.create(scriptCHOP, CHOP_NAME)
        print("4. created Script CHOP %s" % chop.path)
    else:
        print("4. reusing Script CHOP %s" % chop.path)
    # Point the CHOP at its callbacks. This is the wiring that is easy to get
    # wrong by hand and presents as an empty CHOP with no error at all.
    chop.par.callbacks = callbacks.path

    # Lay them out so they are findable rather than stacked on the origin.
    callbacks.nodeX, callbacks.nodeY = 0, 0
    chop.nodeX, chop.nodeY = 200, 0

    # -- step 4: report ----------------------------------------------------
    chop.cook(force=True)
    print()
    print("5. %s now has %d channels (expected 137)" % (chop.path, chop.numChans))
    print("   %s" % bootstrap.status())
    print()
    if chop.numChans == 137:
        print("OK  Wave at the camera and watch h0_found and h0_conf_median.")
        print("    Gate downstream work on h0_conf_median, NEVER on h0_score -")
        print("    that channel is a measured constant 1.0 (DESIGN.md 2.6).")
    else:
        print("UNEXPECTED channel count. Check the Textport for errors from the")
        print("callbacks DAT, and run bootstrap.status() for the engine's view.")
    print()
    print("REMEMBER: run bootstrap.stop() before closing or reloading this")
    print("project. A Vision call landing on a torn-down session is a native")
    print("crash that takes TouchDesigner with it (DESIGN.md 8).")
    print("=" * 68)


main()
